DAOS-11386 pool: fix assertion when upgrade pool 1 to 2
daos-stack/daos pull request #10030
Opened 2022-08-18 15:05 UTC by wangshilong

Since Pool layout version 1, global version property will exist.
daos_prop_is_set() will return true, only assert for pool version 0.

Required-githooks: true

Signed-off-by: Wang Shilong <shilong.wang@intel.com>

2022-08-18 15:07 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-18 15:35 UTC, kccain requested changes

2022-08-18 15:35 UTC, kccain commented on src/container/srv_container.c
> +	entry = daos_prop_entry_get(prop, DAOS_PROP_CO_GLOBAL_VERSION);
I think this block needs to follow the cont_prop_read() call since prop is NULL here.

2022-08-19 01:13 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-19 01:37 UTC, liw approved these changes

2022-08-19 10:37 UTC, kccain approved these changes

2022-08-20 18:20 UTC, merged