DAOS-8012 tests: allow test_daos_server_dump_basic to run in CI (#9219)
daos-stack/daos pull request #10131
Opened 2022-08-29 09:25 UTC by bfaccini

Now that test_daos_server_dump_basic intermittent/timing
issue has been fixed by PR-7768, allow it to be run by
CI.

Signed-off-by: Bruno Faccini <bruno.faccini@intel.com>

2022-08-31 16:12 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/server/daos_server_dump.py:37](https://github.com/daos-stack/daos/blob/244c39625864db8c6a6b0984273110321819d8fb/src/tests/ftest/server/daos_server_dump.py#L37):
(pylint-attribute-defined-outside-init) Attribute '_Test__status' defined outside __init__

[src/tests/ftest/server/daos_server_dump.py:50](https://github.com/daos-stack/daos/blob/244c39625864db8c6a6b0984273110321819d8fb/src/tests/ftest/server/daos_server_dump.py#L50):
(pylint-attribute-defined-outside-init) Attribute '_Test__status' defined outside __init__

2022-09-08 06:27 UTC, bfaccini commented
@sylviachanoiyee and @phender any chance to review this ?? Or may be there is no plan for a 2.2 back-port so I may just close this PR and remove its branch ??

2022-09-08 08:13 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/server/daos_server_dump.py:37](https://github.com/daos-stack/daos/blob/7dbe2263b7122b9380e0db856fd6b281004e10fa/src/tests/ftest/server/daos_server_dump.py#L37):
(pylint-attribute-defined-outside-init) Attribute '_Test__status' defined outside __init__

[src/tests/ftest/server/daos_server_dump.py:50](https://github.com/daos-stack/daos/blob/7dbe2263b7122b9380e0db856fd6b281004e10fa/src/tests/ftest/server/daos_server_dump.py#L50):
(pylint-attribute-defined-outside-init) Attribute '_Test__status' defined outside __init__

2022-09-12 15:49 UTC, sylviachanoiyee approved these changes

2022-09-12 16:04 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/server/daos_server_dump.py:37](https://github.com/daos-stack/daos/blob/460723e67c5fbb2c85017028523c2d5e2ff14e01/src/tests/ftest/server/daos_server_dump.py#L37):
(pylint-attribute-defined-outside-init) Attribute '_Test__status' defined outside __init__

[src/tests/ftest/server/daos_server_dump.py:50](https://github.com/daos-stack/daos/blob/460723e67c5fbb2c85017028523c2d5e2ff14e01/src/tests/ftest/server/daos_server_dump.py#L50):
(pylint-attribute-defined-outside-init) Attribute '_Test__status' defined outside __init__

2022-09-14 18:32 UTC, phender requested changes
The test changes look fine, but because this test is currently skipped due to ticket DAOS-8012 the each commit message must begin with `DAOS-8012 ` in order for the skip to be overridden.

2022-09-15 08:32 UTC, bfaccini commented
> The test changes look fine, but because this test was skipped in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-10131/3/artifact/Functional%20on%20EL%208/server/daos_server_dump.py/results.html due to ticket DAOS-8012 the each commit message must begin with `DAOS-8012 ` in order for the skip to be overridden.

Ah yes, not only we need to forward the Test-tags from commit to commit, but there is also the need to have ticket name in first place of commit message... this is how our DevOps glue help us in our day to day work and to save time 👎

2022-09-19 15:44 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/server/daos_server_dump.py:37](https://github.com/daos-stack/daos/blob/944ce77ef278c9c98e6f5d7db755cbc11aea9a4c/src/tests/ftest/server/daos_server_dump.py#L37):
(pylint-attribute-defined-outside-init) Attribute '_Test__status' defined outside __init__

[src/tests/ftest/server/daos_server_dump.py:50](https://github.com/daos-stack/daos/blob/944ce77ef278c9c98e6f5d7db755cbc11aea9a4c/src/tests/ftest/server/daos_server_dump.py#L50):
(pylint-attribute-defined-outside-init) Attribute '_Test__status' defined outside __init__

2022-09-20 19:36 UTC, merged