DAOS-8648 tests: Re-enable skipped tests
daos-stack/daos pull request #10275
Opened 2022-09-12 20:51 UTC by phender

Removing skipForTicket decorator for tests being skipped by resolved tickets.

Quick-functional: true
Test-tags: nvme_pool_extend test_osa_offline_extend_oclass test_osa_offline_extend_during_aggregation test_osa_offline_parallel_test_with_aggregation online_extend test_osa_online_reintegration_server_stop

Required-githooks: true

Signed-off-by: Phil Henderson <phillip.henderson@intel.com>

2022-09-13 01:47 UTC, rpadma2 approved these changes

2022-09-13 10:22 UTC, shimizukko submitted a review, later dismissed

2022-09-13 12:10 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10275/1/execution/node/648/log

2022-09-13 15:29 UTC, daltonbohning requested changes
-1 just for the introduced pylint warning

2022-09-13 22:49 UTC, phender commented on src/tests/ftest/osa/offline_parallel_test.py
Fixed

2022-09-13 22:57 UTC, daltonbohning submitted a review, later dismissed

2022-09-14 09:14 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10275/2/execution/node/562/log

2022-09-19 19:10 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10275/3/execution/node/511/log

2022-09-19 19:42 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10275/3/execution/node/527/log

2022-09-20 03:21 UTC, phender commented
In https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-10275/3 the OSAOfflineExtend, OSAOfflineParallelTest, and OSAOnlineReintegration tests passed.  The NvmePoolExtend and OSAOnlineExtend tests failed.

2022-09-22 12:02 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10275/4/execution/node/593/log

2022-10-05 20:44 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-10-06 00:31 UTC, rpadma2 submitted a review, later dismissed

2022-10-06 01:53 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-10-06 10:54 UTC, shimizukko approved these changes

2022-10-06 14:46 UTC, daltonbohning approved these changes
LGTM - minor comments

2022-10-06 14:46 UTC, daltonbohning commented on src/tests/ftest/nvme/pool_extend.py
> +            # pools[-1].set_property("reclaim", "disabled")
Remove the comment?

2022-10-06 14:46 UTC, daltonbohning commented on src/tests/ftest/util/test_utils_pool.py
> +            ranks (list): a list daos server ranks (int) to exclude
```suggestion
            ranks (list): a list of daos server ranks (int) to exclude
```

2022-10-06 14:46 UTC, daltonbohning commented on src/tests/ftest/util/test_utils_pool.py
> +        return self.dmg.pool_extend(self.identifier, ranks)
`Returns` docstring?

2022-10-06 23:50 UTC, phender commented
All tests passed in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-10275/6/testReport/

2022-10-07 22:22 UTC, merged