DAOS-10301 test: pass dmg command line with mmap()
daos-stack/daos pull request #10394
Opened 2022-09-26 11:19 UTC by bfaccini

It seems possible that the buffer where dmg command line is being constructed, to be passed to system() call, can be in a page that had been registered for RDMA, which can cause a SEGV in fork()'ed child upon access for parsing.

So, to ensure allocating buffer in a brand new page, using mmap() to avoid this.

Signed-off-by: Bruno Faccini <bruno.faccini@intel.com>

2022-09-26 11:20 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-10394/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-09-26 11:20 UTC, daosbuild1 commented on src/common/tests_dmg_helpers.c
> +	void 		*addr;
(style)  please, no space before tabs

2022-09-26 11:20 UTC, daosbuild1 commented on src/common/tests_dmg_helpers.c
> +	void 		*addr;
```suggestion
	void		*addr;
```

2022-09-26 11:20 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10394/1/execution/node/145/log

2022-09-26 11:23 UTC, daosbuild1 commented
Test stage Build on Leap 15 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10394/1/execution/node/369/log

2022-09-26 11:29 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10394/1/execution/node/341/log

2022-10-03 11:36 UTC, knard-intel commented
From my side, do not understand how page allocated through malloc could be shared with memory mapped page ?
I am clearly not an expert in this area, but I was naively thinking that such situation could not happen: I was expecting that some kind of memory protection existing to prevent this.
Otherwise, your patch LGTM.

2022-10-03 17:35 UTC, daltonbohning reviewed
ftest LGTM

2022-10-04 07:15 UTC, knard-intel reviewed
LGTM thanks to @bfaccini explanation.

2022-10-04 07:16 UTC, knard-intel submitted a review, later dismissed

2022-10-04 08:13 UTC, bfaccini commented
> ftest LGTM

Hello @daltonbohning , I am not sure to understand the meaning of your comment/review ?! What do you mean by "ftest" and also why don't you review with a +1 if this PR looks good to you ?

2022-10-04 08:20 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-10-04 08:21 UTC, bfaccini commented
> > ftest LGTM
> 
> Hello @daltonbohning , I am not sure to understand the meaning of your comment/review ?! What do you mean by "ftest" and also why don't you review with a +1 if this PR looks good to you ?

Hmm, more thinking about it, may be you were asking that the full CI pipeline/stages must have run before to declare this PR is ok ?!  So I have pushed a new commit without any commit-tag now to have a full CI testing session to occur for this PR !

2022-10-04 08:45 UTC, daosbuild1 commented
Test stage Build on Leap 15 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10394/10/execution/node/449/log

2022-10-04 17:08 UTC, kjacque requested changes

2022-10-04 17:08 UTC, kjacque commented on src/tests/ftest/daos_test/suite.yaml
> +    test_daos_pool: -u6,7,9,13
Oops, this should be removed

2022-10-05 07:29 UTC, bfaccini commented on src/tests/ftest/daos_test/suite.yaml
> +    test_daos_pool: -u6,7,9,13
Oulah, right, I forgot this !

2022-10-05 07:41 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-10-06 06:42 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10394/11/execution/node/1177/log

2022-10-06 14:41 UTC, bfaccini commented
hmmm, the only 2 Existing failures : 

1)Test Hardware / Functional Hardware Large / 08-./daos_test/dfs.py – FTEST_launch.daos_test-dfs
2)Test Hardware / Functional Hardware Large / 10-./daos_racer/simple.py – FTEST_launch.daos_racer-simple

that have been triggered during last full CI session definitely look respectively related to both DAOS-11763/DAOS-11762 !!
Since associated patch/PR-10479 has has just landed to master, should I need to rebase and rerun CI again ???

2022-10-10 11:35 UTC, knard-intel approved these changes
OK from my side as it is just a merge with master.

2022-10-11 22:20 UTC, merged