DAOS-11608 cart: Add multisend test
daos-stack/daos pull request #10420
Opened 2022-09-27 20:33 UTC by frostedcmos

- Add multisend client/server test to test multi-chunk bulk
    transfers in various modes

Signed-off-by: Alexander A Oganezov <alexander.a.oganezov@intel.com>

2022-09-27 20:35 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-10420/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-09-27 20:35 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_client.c
> +	p_blk = (crt_bulk_t*)info->cci_arg;
(style)  "(foo*)" should be "(foo *)"

2022-09-27 20:35 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_client.c
> +
(style)  trailing whitespace

2022-09-27 20:35 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_client.c
> +
(style)  trailing whitespace

2022-09-27 20:35 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_client.c
> +
(style)  trailing whitespace

2022-09-27 20:35 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_client.c
> +	time_delta = (tv_end.tv_sec - tv_start.tv_sec) * 1000000 + (tv_end.tv_usec - tv_start.tv_usec);
(style)  line over 100 characters

2022-09-27 20:35 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_client.c
> +	p_blk = (crt_bulk_t*)info->cci_arg;
```suggestion
	p_blk = (crt_bulk_t *)info->cci_arg;
```

2022-09-27 20:35 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_client.c
> +
```suggestion

```

2022-09-27 20:35 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_client.c
> +
```suggestion

```

2022-09-27 20:35 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_client.c
> +		test.tg_test_mode == 1 ? "Synchronous" : "Asynchronous",
```suggestion
		  test.tg_test_mode == 1 ? "Synchronous" : "Asynchronous",
```

2022-09-27 20:35 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_common.h
> +#define RPC_DECLARE(name)					\
(style)  Macros with complex values should be enclosed in parentheses

2022-09-27 20:35 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_common.h
> +#define CRT_ISEQ_RPC_PING	/* input fields */		 \
(style)  Macros with complex values should be enclosed in parentheses

2022-09-27 20:35 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_server.c
> +static void
```suggestion
}

```

2022-09-27 20:35 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10420/1/execution/node/145/log

2022-09-27 20:40 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-10420/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-09-27 20:40 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_common.h
> +#define RPC_DECLARE(name)					\
(style)  Macros with complex values should be enclosed in parentheses

2022-09-27 20:40 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10420/2/execution/node/145/log

2022-09-28 00:37 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10420/2/execution/node/887/log

2022-09-28 04:53 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-10420/2/testReport/(root)/

2022-09-28 20:36 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-10420/3/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-09-28 20:36 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_common.h
> +#define RPC_DECLARE(name)					\
(style)  Macros with complex values should be enclosed in parentheses

2022-09-28 20:36 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_common.h
> +#define CRT_ISEQ_RPC_PING	/* input fields */		 \
(style)  Macros with complex values should be enclosed in parentheses

2022-09-28 20:36 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10420/3/execution/node/174/log

2022-09-28 23:05 UTC, jolivier23 requested changes
I think you need to address the pylint stuff but otherwise, LGTM

2022-09-28 23:05 UTC, jolivier23 commented on src/tests/ftest/cart/rpc/multisend_one_node.py
> +    """Run multisend test that launches 16 servers and splits bulk
Can't add spelling errors.  So either you need to figure out a spelling that it won't complain about.  Or add pylint disable line for this warning.  My guess is multi-send would be ok.

2022-09-28 23:05 UTC, jolivier23 commented on src/tests/ftest/cart/rpc/multisend_one_node.py
> +            self.print("Exception in launching server : {}".format(e))
this one is simply a matter of using a longer name

2022-09-29 14:25 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-10420/3/testReport/(root)/

2022-10-03 16:24 UTC, jgmoore-or submitted a review, later dismissed

2022-10-05 00:00 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-10420/4/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-10-05 00:00 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10420/4/execution/node/145/log

2022-10-05 21:32 UTC, jgmoore-or approved these changes

2022-10-06 02:21 UTC, jolivier23 approved these changes

2022-10-06 03:43 UTC, soumagne approved these changes

2022-10-06 03:47 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10420/4/execution/node/1177/log

2022-10-07 05:21 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-10420/5/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-10-07 05:21 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_common.h
> +#define RPC_DECLARE(name)					\
(style)  Macros with complex values should be enclosed in parentheses

2022-10-07 05:21 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_common.h
> +#define CRT_ISEQ_RPC_PING	/* input fields */		 \
(style)  Macros with complex values should be enclosed in parentheses

2022-10-07 05:21 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10420/5/execution/node/145/log

2022-10-08 07:40 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10420/5/execution/node/1137/log

2022-10-10 17:19 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-10420/6/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-10-10 17:19 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_common.h
> +#define RPC_DECLARE(name)					\
(style)  Macros with complex values should be enclosed in parentheses

2022-10-10 17:19 UTC, daosbuild1 commented on src/tests/ftest/cart/test_multisend_common.h
> +#define CRT_ISEQ_RPC_PING	/* input fields */		 \
(style)  Macros with complex values should be enclosed in parentheses

2022-10-10 17:19 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10420/6/execution/node/145/log

2022-10-11 18:08 UTC, soumagne approved these changes

2022-10-11 18:48 UTC, jgmoore-or approved these changes

2022-10-11 22:22 UTC, merged