DAOS-11043 umem: Blob backed Memory(BMEM) interface for umem
daos-stack/daos pull request #10514
Opened 2022-10-07 07:16 UTC by sherintg

This commit contains a new allocator which is a modified version of pmemobj. The new allocator operates on volatile memory and provides transaction functionality similar to that of pmemobj.

The BMEM interfaces internally use the new allocator functionalties to implement the required backend for hosting metadata on volatile memory backed by blob.

Note: The current commit default to BMEM instead of PMDK. One can override this by setting DAOS_USE_PMDK=1 in the server config file.

Allow-unstable-test: true

Signed-off-by: sherintg <sherin-t.george@hpe.com>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it
      should be force landed and forced-landing tag is set.
* [ ] Commit messages follows the guidelines outlined
      [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code.
* [ ] Any appropriate watchers have had a chance to review the PR.
* [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested
      changes.
* [ ] Githooks were used. If not, there is a sufficient reason to move forward.  Check copyrights
      if githooks were not used.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future
      PRs.
* [ ] All builds have passed.  Check non-required builds to ensure they don't indicate any problem
      such as a compiler warning on extraneous platforms.
* [ ] No new NLT or valgrind warnings.  Check the classic view. This step should only matter if
      the build requires force landing.
* [ ] Ensure sufficent testing is done.   Check feature pragmas and test tags. Check that tests
      skipped for the ticket are run and now pass with the changes.
* [ ] Quick-build or Quick-functional is not used.
* [ ] Pay attention to PRs that may affect compatibility between versions and ensure it has been
      addressed.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If
      it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Check the commit message when landing. Check the standard
      [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit
      it to create a single commit. If necessary, ask submitter for a new summary.

2022-10-07 19:03 UTC, jolivier23 requested changes
Looks like you hit the naming convention problem with your branch.  The test looks for a / so if you just change your branch from sherintg_DAOS11043 to sherintg/DAOS11043, that will fix it.   Alternatively, we could fix the check so it accepts an _ as well.  But regardless, testing, will not run without that change.

2022-10-10 07:38 UTC, closed without merging

2022-10-10 07:50 UTC, sherintg commented on src/common/mem.c
> +	dav_obj_t *pop;
Addressed this in mem.c. The files in dav directory are not always strictly following the above convention. The number of files to be modified  high. Will take it up as part of further cleanup.

2022-10-10 07:51 UTC, sherintg commented on src/common/dav/memops.c
> +		D_CRIT("Zalloc!\n");
Changed alloc.h to reflect the same. Also removed alloc.c from the build. Now Malloc, Zalloc, Realloc and Free point to the DAOS macros.

2022-10-10 07:51 UTC, sherintg commented
Will be creating a new PR with the right branch name shortly.