DAOS-11587 vos: standalone vos support for metadata on ssd
daos-stack/daos pull request #10587
Opened 2022-10-17 06:44 UTC by wangshilong

1. extend to support stand vos support for metadata on ssd
2. integration WAL parts with bio: 2.1: format meta header after blobs creation. 2.2: load meta head before open wal and data blob to check if data blobstore is associated and wal blobid.

Required-githooks: true
Signed-off-by: Wang Shilong <shilong.wang@intel.com>

2022-10-17 06:46 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-10-17 08:21 UTC, NiuYawei commented on src/bio/bio_xstream.c
> +		/* Data blobstore could be only setup after smd prepared */
I think the special check for sys xstream and standalone VOS are done in the find_xs_bio_dev() already, right?

2022-10-17 12:35 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10587/1/execution/node/1130/log

2022-10-17 14:01 UTC, wangshilong commented on src/bio/bio_xstream.c
> +	    (tgt_id == BIO_STAND_ALONE_ID && st == SMD_DEV_TYPE_DATA)) {
yes.

2022-10-17 14:02 UTC, wangshilong commented on src/bio/bio_context.c
> +	}
uuid_clear

2022-10-17 14:59 UTC, wangshilong commented on src/bio/bio_context.c
> +	flags |= BIO_MC_FL_NO_CHECKMETA;
OK

2022-10-17 15:19 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-10-17 20:40 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10587/2/execution/node/1130/log

2022-10-17 21:11 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10587/2/execution/node/1017/log

2022-10-18 01:21 UTC, NiuYawei requested changes

2022-10-18 01:21 UTC, NiuYawei commented on src/bio/bio_context.c
> +		wal_close(bio_mc);
wal_close() requires io context, it needs be called before closing wal io context. The closing order should be: wal_close(), meta_close(), wal & meta io context close.

2022-10-18 07:58 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10587/3/execution/node/311/log

2022-10-18 08:48 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-10-18 17:35 UTC, jolivier23 commented on src/bio/bio_context.c
> +		D_FREE(mc);
D_FREE does this check

2022-10-18 17:35 UTC, jolivier23 commented on src/bio/bio_context.c
> +	if (fi)
same

2022-10-18 22:24 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10587/4/execution/node/1130/log

2022-10-18 23:15 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10587/4/execution/node/1083/log

2022-10-19 00:16 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-10-19 02:38 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-10-19 02:44 UTC, NiuYawei approved these changes

2022-10-19 17:45 UTC, jolivier23 approved these changes

2022-10-19 20:35 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10587/6/execution/node/1084/log

2022-10-20 13:23 UTC, merged