DAOS-11634 doc: misc doc improvements
daos-stack/daos pull request #10585
Opened 2022-10-15 22:32 UTC by Michael-Hennecke

misc doc improvements

Doc-only: true
Signed-off-by: Michael Hennecke <michael.hennecke@intel.com>

2022-10-17 13:10 UTC, kccain requested changes

2022-10-17 15:45 UTC, Michael-Hennecke commented on docs/QSG/tour.md
> +	$ dmg pool create --size 10G Pool2
lets defer this to a separate PR

2022-10-17 15:45 UTC, Michael-Hennecke commented on docs/QSG/tour.md
> -	$ dmg pool query Pool1
lets defer this to a separate PR

2022-10-17 15:57 UTC, Michael-Hennecke commented on docs/QSG/tour.md
> +	$ dmg pool create --size 10G Pool2
renamed to Cont2 to avoid that ambiguity

2022-10-17 15:57 UTC, saurabhtandan commented on docs/QSG/tour.md
> +	$ dmg pool create --size 10G Pool2
+1

2022-10-17 17:44 UTC, kccain commented on docs/QSG/tour.md
> -	$ dmg pool query Pool1
Yes I think that makes sense.

2022-10-17 17:44 UTC, kccain commented on docs/QSG/tour.md
> +	$ dmg pool create --size 10G Pool2
Sure, sounds good.

2022-10-18 09:47 UTC, johannlombardi approved these changes

2022-10-18 09:48 UTC, merged