DAOS-11928 test: Update number of objects per test
daos-stack/daos pull request #10759
Opened 2022-11-03 15:37 UTC by mjean308

Quick-Functional: true
Test-tag: test_cascading_failures test_sequential_failures test_simultaneous_failures

Required-githooks: true

Signed-off-by: Maureen Jean <maureen.jean@intel.com>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficent testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2022-11-03 16:06 UTC, daltonbohning approved these changes

2022-11-07 18:13 UTC, phender requested changes
Shouldn't this PR also be updating the rebuild/container_rf.yaml file with similar changes?  I would also recommend running with a limited Test-tag set an enabling test repeat.

2022-11-07 21:24 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-11-07 22:49 UTC, phender approved these changes

2022-11-07 22:50 UTC, dinghwah approved these changes

2022-11-07 22:57 UTC, daltonbohning approved these changes

2022-11-09 21:19 UTC, merged