DAOS-12013 test: Update telemetry test for I/O DTX committed values
daos-stack/daos pull request #10890
Opened 2022-11-22 18:43 UTC by sydneyvanda

Change object class from SX to RP_2GX
Remove TODO for verifying I/O DTX committable metrics (no longer needed).

Quick-Functional: true
Skip-func-hw-test-large: true
Test-tag: test_io_latency_telemetry test_ior_latency_telemetry test_ior_dtx_telemetry offline_extend_oclass

Signed-off-by: Sydney Vanda <sydney.m.vanda@intel.com>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2022-11-22 19:32 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-10890/1/testReport/(root)/

2022-11-22 20:25 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-10890/2/testReport/(root)/

2022-11-28 18:41 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-10890/3/testReport/(root)/

2022-12-01 15:48 UTC, kjacque commented on src/tests/ftest/control/dmg_telemetry_io_latency.py
> +        num_operations *= 2
Instead of hard-coding the number of replicas, could we import the number of servers from the yaml file?

2022-12-01 20:44 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-02 02:10 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10890/6/execution/node/879/log

2022-12-02 19:05 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10890/6/execution/node/1080/log

2022-12-06 05:02 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10890/7/execution/node/464/log

2022-12-12 13:43 UTC, Nasf-Fan commented
I am thinking that whether it is worth for us to spend time on maintaining the test to verify the count of committed DTX entries. This time, it is because we changed DTX commit logic that does not generate committed DTX entry for single replicated object, then this test got failure. But in the future, we may change related DTX logic again, that may break the test at other point.

On the other hand, even if there is potential bug that may cause committed DTX entry is not generated, it also needs some completed IO mode/race, but current test IO mode is too simple, that almost cannot trigger related corner cases; otherwise, our other tests (with similar IO mode) have already hit test failures.

In the real world, a DTX entry can be removed by DTX aggregation at any time. The count of committed DTX entries cannot stand for related transactions count. It is not a hard standard for the user/application except DTX aggregation. But DTX aggregation is not the verified purpose of the test.

Sorry, my suggestion maybe some late. But it is better than still waste time on the maintaining...

2022-12-12 19:24 UTC, sydneyvanda commented
> I am thinking that whether it is worth for us to spend time on maintaining the test to verify the count of committed DTX entries. This time, it is because we changed DTX commit logic that does not generate committed DTX entry for single replicated object, then this test got failure. But in the future, we may change related DTX logic again, that may break the test at other point.
> 
> On the other hand, even if there is potential bug that may cause committed DTX entry is not generated, it also needs some completed IO mode/race, but current test IO mode is too simple, that almost cannot trigger related corner cases; otherwise, our other tests (with similar IO mode) have already hit test failures.
> 
> In the real world, a DTX entry can be removed by DTX aggregation at any time. The count of committed DTX entries cannot stand for related transactions count. It is not a hard standard for the user/application except DTX aggregation. But DTX aggregation is not the verified purpose of the test.
> 
> Sorry, my suggestion is some late. But it may be better than still waste time on the maintaining... please consider.

Understandable, maybe we should just remove test altogether then instead of worrying about constantly maintaining it? I will post your comment in ticket to get others opinion/approval.

2023-01-04 03:48 UTC, Nasf-Fan commented on src/tests/ftest/control/dmg_telemetry_io_latency.py
> +        num_operations *= test_servers
This caused the CI test failure:
05:02:17 ERROR| TypeError: can't multiply sequence by non-int of type 'float'

2023-01-30 17:53 UTC, phender requested changes

2023-01-30 17:53 UTC, phender commented on src/tests/ftest/control/dmg_telemetry_io_latency.py
> +        num_operations *= test_servers
The better way to get the number of server hosts is to use the class that manages starting the servers, but I suspect you want engine count here:
```suggestion
        num_operations *= self.server_managers[0].engines
```
Instead, if you do really need the number of hosts:
```
        num_operations *= len(self.server_managers[0].hosts)
```

2025-09-15 17:29 UTC, daltonbohning commented
Superseded by #11451

2025-09-15 17:29 UTC, closed without merging