DAOS-11048 bio: monitor WAL and Meta SSDs
daos-stack/daos pull request #10901
Opened 2022-11-24 04:51 UTC by wangshilong

Currently only data SSDs monitoring is supported, this patch tries enable monitoring for WAL and Meta SSDs as well.

Required-githooks: true

Signed-off-by: Wang Shilong <shilong.wang@intel.com>

2022-11-24 04:53 UTC, daosbuild1 requested changes

2022-11-24 04:53 UTC, daosbuild1 commented on src/bio/bio_monitor.c
> +	struct bio_xs_context	*ctxt = gsca->ctxt;
```suggestion
	struct bio_xs_context	*ctxt = gsca->ctxt;

```

2022-11-24 04:53 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10901/1/execution/node/145/log

2022-11-24 05:22 UTC, daosbuild1 requested changes

2022-11-24 05:22 UTC, daosbuild1 commented on src/bio/bio_monitor.c
> +	struct bio_xs_context	*ctxt = gsca->ctxt;
```suggestion
	struct bio_xs_context	*ctxt = gsca->ctxt;

```

2022-11-24 05:22 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10901/2/execution/node/146/log

2022-11-24 05:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-11-24 07:03 UTC, NiuYawei requested changes

2022-11-24 07:03 UTC, NiuYawei commented on src/bio/bio_monitor.c
> +		D_ALLOC_PTR(gsca);
Instead of allocating and freeing a 'gsca', can't we just pass '&xs_ctxt->bxc_xs_blobstore[st]" as argument for completion callback?

2022-11-24 07:03 UTC, NiuYawei commented on src/bio/bio_monitor.c
> +	bxb = bio_xs_context2xs_blobstore(ctxt, gsca->st);
bio_xs_context2bx_blobstore() should be used in this case. And I think we pass the address of bxc_xs_blobstore[st] as completion argument, we could just check if (*arg == NULL) here to tell if bio_xsctxt_free() is underway, right?

2022-11-24 11:39 UTC, wangshilong commented on src/bio/bio_xstream.c
> +			bio_bs_monitor(ctxt, st, now);
You are right, just tried to enable for monitoring metrics works, we disabled fault detection and device state transition for WAL/Meta, need enable them too, also fault detection and device state transition won't work for sys device.

2022-11-24 13:20 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-11-25 01:35 UTC, NiuYawei approved these changes

2022-11-28 18:09 UTC, jolivier23 approved these changes

2022-11-28 18:16 UTC, merged