DAOS0-12210 mercury: Update mercury version to 2.2.0-5 for source bui…
daos-stack/daos pull request #10982
Opened 2022-12-06 14:53 UTC by jgmoore-or

…lds.

Required-githooks: true

Signed-off-by: Joseph Moore <joseph.moore@intel.com>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2022-12-06 15:04 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-06 17:17 UTC, frostedcmos submitted a review, later dismissed

2022-12-06 19:18 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-06 20:34 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-06 22:42 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/5/execution/node/802/log

2022-12-07 18:37 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-08 04:15 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-12 17:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-12 18:41 UTC, brianjmurrell requested changes

2022-12-12 18:41 UTC, brianjmurrell commented on utils/rpms/daos.spec
> +* Tue Dec 06 2022 Joseph G. Moore <joseph.moore@intel.com> 2.1.101-5
You need to update `Release:` on line 18 to match this update.

2022-12-13 01:33 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-10982/8/testReport/(root)/

2022-12-14 18:29 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-14 18:35 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15.4 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/9/execution/node/313/log

2022-12-14 18:36 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/9/execution/node/335/log

2022-12-14 18:39 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/9/execution/node/340/log

2022-12-14 21:56 UTC, brianjmurrell approved these changes

2022-12-21 15:16 UTC, frostedcmos approved these changes

2022-12-21 15:38 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15.4 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/10/execution/node/296/log

2022-12-21 15:40 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/10/execution/node/340/log

2022-12-21 15:43 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/10/execution/node/331/log

2022-12-21 15:48 UTC, daosbuild1 commented
Test stage Build on Leap 15.4 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/10/execution/node/479/log

2022-12-21 19:49 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-21 19:55 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15.4 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/11/execution/node/334/log

2022-12-21 19:57 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/11/execution/node/342/log

2022-12-21 20:00 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/11/execution/node/339/log

2022-12-21 23:08 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-21 23:14 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15.4 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/12/execution/node/308/log

2022-12-21 23:17 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/12/execution/node/357/log

2022-12-21 23:20 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/12/execution/node/315/log

2022-12-21 23:24 UTC, jolivier23 approved these changes

2022-12-21 23:27 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-21 23:33 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15.4 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/13/execution/node/318/log

2022-12-21 23:35 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/13/execution/node/372/log

2022-12-21 23:38 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/13/execution/node/321/log

2022-12-22 19:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-22 19:31 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15.4 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/14/execution/node/299/log

2022-12-22 19:33 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/14/execution/node/365/log

2022-12-22 19:36 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/14/execution/node/302/log

2022-12-23 20:29 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-24 04:31 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/15/execution/node/1084/log

2022-12-27 23:31 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-27 23:35 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-28 05:49 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/17/execution/node/1064/log

2022-12-29 19:32 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-30 00:23 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/18/execution/node/1084/log

2022-12-30 15:28 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-12-30 20:54 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-10982/19/execution/node/1146/log

2023-01-03 18:07 UTC, brianjmurrell approved these changes
The changes LGTM.  I am assuming the [test failures](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-10982/19/tests) will be triaged and understood and/or fixed before this is landed by a @daos-stack/daos-gatekeeper.

2023-01-03 22:30 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-01-03 22:32 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-01-04 11:11 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-10982/21/testReport/(root)/

2023-01-04 14:09 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-01-05 04:45 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-10982/22/testReport/(root)/

2023-01-09 15:32 UTC, jolivier23 approved these changes

2023-01-09 15:35 UTC, frostedcmos approved these changes

2023-01-10 17:47 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-01-11 15:06 UTC, merged