DAOS-12121 test: Bullseye backports from master branch to rel_2.2
daos-stack/daos pull request #11069
Opened 2022-12-16 22:07 UTC by dinghwah

Skip-fnbullseye: false
Skip-bullseye: false
Skip-python-bandit: true
Skip-build-leap15-rpm: true
Skip-build-ubuntu20-rpm: true
Allow-unstable-test: true
Doc-only: false
Test-tag: pr daily_regression
Required-githooks: true
Signed-off-by: Ding Ho ding-hwa.ho@intel.com

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2022-12-16 22:10 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/2bd3bab9b0702bef952e63c7635ee8b2f1e130ca/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:273](https://github.com/daos-stack/daos/blob/2bd3bab9b0702bef952e63c7635ee8b2f1e130ca/src/tests/ftest/util/ior_utils.py#L273):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/2bd3bab9b0702bef952e63c7635ee8b2f1e130ca/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/2bd3bab9b0702bef952e63c7635ee8b2f1e130ca/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:914](https://github.com/daos-stack/daos/blob/2bd3bab9b0702bef952e63c7635ee8b2f1e130ca/src/tests/ftest/util/server_utils.py#L914):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-16 22:55 UTC, daosbuild1 commented
Test stage Unit Test Bullseye on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-11069/1/display/redirect

2022-12-16 23:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/c76bc3b0ab59020dc4c7973509d0055cb93e622a/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:273](https://github.com/daos-stack/daos/blob/c76bc3b0ab59020dc4c7973509d0055cb93e622a/src/tests/ftest/util/ior_utils.py#L273):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/c76bc3b0ab59020dc4c7973509d0055cb93e622a/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/c76bc3b0ab59020dc4c7973509d0055cb93e622a/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:914](https://github.com/daos-stack/daos/blob/c76bc3b0ab59020dc4c7973509d0055cb93e622a/src/tests/ftest/util/server_utils.py#L914):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-18 07:53 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-11069/2/testReport/(root)/

2022-12-18 08:05 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11069/2/execution/node/813/log

2022-12-18 19:51 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/808a09ef341da66cd49cbe5ffa9572d6f5a48074/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:273](https://github.com/daos-stack/daos/blob/808a09ef341da66cd49cbe5ffa9572d6f5a48074/src/tests/ftest/util/ior_utils.py#L273):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/808a09ef341da66cd49cbe5ffa9572d6f5a48074/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/808a09ef341da66cd49cbe5ffa9572d6f5a48074/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:914](https://github.com/daos-stack/daos/blob/808a09ef341da66cd49cbe5ffa9572d6f5a48074/src/tests/ftest/util/server_utils.py#L914):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-18 20:42 UTC, daosbuild1 commented
Test stage Unit Test Bullseye on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-11069/3/display/redirect

2022-12-19 18:39 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/c7d902cb534856ec19a4066468c83cbe5da5fa53/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:273](https://github.com/daos-stack/daos/blob/c7d902cb534856ec19a4066468c83cbe5da5fa53/src/tests/ftest/util/ior_utils.py#L273):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/c7d902cb534856ec19a4066468c83cbe5da5fa53/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/c7d902cb534856ec19a4066468c83cbe5da5fa53/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:914](https://github.com/daos-stack/daos/blob/c7d902cb534856ec19a4066468c83cbe5da5fa53/src/tests/ftest/util/server_utils.py#L914):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-20 03:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/9c43f016df847503a60170a3ce1d6369b6d79eaa/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:270](https://github.com/daos-stack/daos/blob/9c43f016df847503a60170a3ce1d6369b6d79eaa/src/tests/ftest/util/ior_utils.py#L270):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/9c43f016df847503a60170a3ce1d6369b6d79eaa/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/9c43f016df847503a60170a3ce1d6369b6d79eaa/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:941](https://github.com/daos-stack/daos/blob/9c43f016df847503a60170a3ce1d6369b6d79eaa/src/tests/ftest/util/server_utils.py#L941):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-20 04:02 UTC, daosbuild1 commented
Test stage Unit Test Bullseye on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-11069/5/display/redirect

2022-12-20 18:45 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/b7689c085af210c1768e93b3fc198e3bc2830dff/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:270](https://github.com/daos-stack/daos/blob/b7689c085af210c1768e93b3fc198e3bc2830dff/src/tests/ftest/util/ior_utils.py#L270):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/b7689c085af210c1768e93b3fc198e3bc2830dff/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/b7689c085af210c1768e93b3fc198e3bc2830dff/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:941](https://github.com/daos-stack/daos/blob/b7689c085af210c1768e93b3fc198e3bc2830dff/src/tests/ftest/util/server_utils.py#L941):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-20 18:56 UTC, daosbuild1 commented
Test stage Build on Leap 15 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11069/6/execution/node/289/log

2022-12-20 18:57 UTC, daosbuild1 commented
Test stage Build RPM on EL 8.5 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11069/6/execution/node/211/log

2022-12-20 19:27 UTC, daosbuild1 commented
Test stage Build on Leap 15 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11069/7/execution/node/268/log

2022-12-20 19:28 UTC, daosbuild1 commented
Test stage Build RPM on EL 8.5 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11069/7/execution/node/190/log

2022-12-20 20:57 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/9590b51c4139b2ac77a6d0b63e4f4a11613a873e/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:270](https://github.com/daos-stack/daos/blob/9590b51c4139b2ac77a6d0b63e4f4a11613a873e/src/tests/ftest/util/ior_utils.py#L270):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/9590b51c4139b2ac77a6d0b63e4f4a11613a873e/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/9590b51c4139b2ac77a6d0b63e4f4a11613a873e/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:941](https://github.com/daos-stack/daos/blob/9590b51c4139b2ac77a6d0b63e4f4a11613a873e/src/tests/ftest/util/server_utils.py#L941):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-20 21:06 UTC, daosbuild1 commented
Test stage Build on Leap 15 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11069/8/execution/node/289/log

2022-12-20 21:07 UTC, daosbuild1 commented
Test stage Build RPM on EL 8.5 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11069/8/execution/node/220/log

2022-12-20 21:23 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/25145981da46103f250215f15defe1909bcb3dae/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:270](https://github.com/daos-stack/daos/blob/25145981da46103f250215f15defe1909bcb3dae/src/tests/ftest/util/ior_utils.py#L270):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/25145981da46103f250215f15defe1909bcb3dae/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/25145981da46103f250215f15defe1909bcb3dae/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:941](https://github.com/daos-stack/daos/blob/25145981da46103f250215f15defe1909bcb3dae/src/tests/ftest/util/server_utils.py#L941):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-20 21:32 UTC, daosbuild1 commented
Test stage Build on Leap 15 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11069/9/execution/node/289/log

2022-12-20 21:33 UTC, daosbuild1 commented
Test stage Build RPM on EL 8.5 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11069/9/execution/node/211/log

2022-12-21 01:11 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/567a60f79944afcb7623fea7637a18b0ee49aaff/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:270](https://github.com/daos-stack/daos/blob/567a60f79944afcb7623fea7637a18b0ee49aaff/src/tests/ftest/util/ior_utils.py#L270):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/567a60f79944afcb7623fea7637a18b0ee49aaff/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/567a60f79944afcb7623fea7637a18b0ee49aaff/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:941](https://github.com/daos-stack/daos/blob/567a60f79944afcb7623fea7637a18b0ee49aaff/src/tests/ftest/util/server_utils.py#L941):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-21 01:48 UTC, daosbuild1 commented
Test stage Unit Test Bullseye on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-11069/10/display/redirect

2022-12-22 19:51 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/0b9e1c2b9955fc510a121c1cc800c14da6984e7e/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:270](https://github.com/daos-stack/daos/blob/0b9e1c2b9955fc510a121c1cc800c14da6984e7e/src/tests/ftest/util/ior_utils.py#L270):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/0b9e1c2b9955fc510a121c1cc800c14da6984e7e/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/0b9e1c2b9955fc510a121c1cc800c14da6984e7e/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:941](https://github.com/daos-stack/daos/blob/0b9e1c2b9955fc510a121c1cc800c14da6984e7e/src/tests/ftest/util/server_utils.py#L941):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-22 20:33 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/980e36e81e9847393733ec52139da33457d813ad/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:270](https://github.com/daos-stack/daos/blob/980e36e81e9847393733ec52139da33457d813ad/src/tests/ftest/util/ior_utils.py#L270):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/980e36e81e9847393733ec52139da33457d813ad/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/980e36e81e9847393733ec52139da33457d813ad/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:941](https://github.com/daos-stack/daos/blob/980e36e81e9847393733ec52139da33457d813ad/src/tests/ftest/util/server_utils.py#L941):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-22 21:08 UTC, daosbuild1 commented
Test stage Unit Test Bullseye on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-11069/12/display/redirect

2022-12-22 21:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/3617a144d54a193a5a59cfe479ca22ce2bfdaa52/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:270](https://github.com/daos-stack/daos/blob/3617a144d54a193a5a59cfe479ca22ce2bfdaa52/src/tests/ftest/util/ior_utils.py#L270):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/3617a144d54a193a5a59cfe479ca22ce2bfdaa52/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/3617a144d54a193a5a59cfe479ca22ce2bfdaa52/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:941](https://github.com/daos-stack/daos/blob/3617a144d54a193a5a59cfe479ca22ce2bfdaa52/src/tests/ftest/util/server_utils.py#L941):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-23 04:35 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/1a149dd13cf39c0b861686c6529d6bcc4c9c6902/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:270](https://github.com/daos-stack/daos/blob/1a149dd13cf39c0b861686c6529d6bcc4c9c6902/src/tests/ftest/util/ior_utils.py#L270):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/1a149dd13cf39c0b861686c6529d6bcc4c9c6902/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/1a149dd13cf39c0b861686c6529d6bcc4c9c6902/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:941](https://github.com/daos-stack/daos/blob/1a149dd13cf39c0b861686c6529d6bcc4c9c6902/src/tests/ftest/util/server_utils.py#L941):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-23 13:14 UTC, brianjmurrell requested changes

2022-12-23 13:14 UTC, brianjmurrell commented on Jenkinsfile
> +                            (key, value) = line.split(':', 2)
This is obsolete now.  You need to replace the entire block: https://github.com/daos-stack/daos/blob/1a149dd13cf39c0b861686c6529d6bcc4c9c6902/Jenkinsfile#L260-L279 with simply:

```
                pragmasToEnv()
```

2022-12-23 16:05 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-11069/14/testReport/(root)/

2022-12-23 18:08 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/76b9426b0ff1951141b869bed364c8b844b97e17/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:270](https://github.com/daos-stack/daos/blob/76b9426b0ff1951141b869bed364c8b844b97e17/src/tests/ftest/util/ior_utils.py#L270):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/76b9426b0ff1951141b869bed364c8b844b97e17/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/76b9426b0ff1951141b869bed364c8b844b97e17/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:941](https://github.com/daos-stack/daos/blob/76b9426b0ff1951141b869bed364c8b844b97e17/src/tests/ftest/util/server_utils.py#L941):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-23 18:30 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/b0e71d89bb6a49c509d2ff5774c80b73671a14fc/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:270](https://github.com/daos-stack/daos/blob/b0e71d89bb6a49c509d2ff5774c80b73671a14fc/src/tests/ftest/util/ior_utils.py#L270):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/b0e71d89bb6a49c509d2ff5774c80b73671a14fc/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/b0e71d89bb6a49c509d2ff5774c80b73671a14fc/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:941](https://github.com/daos-stack/daos/blob/b0e71d89bb6a49c509d2ff5774c80b73671a14fc/src/tests/ftest/util/server_utils.py#L941):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-24 05:17 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-11069/16/testReport/(root)/

2022-12-25 14:15 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11069/16/execution/node/968/log

2022-12-25 16:45 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11069/16/execution/node/1101/log

2022-12-27 00:54 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/a7aa18b3b3d2fc6661506965443d5ae2214fd261/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:270](https://github.com/daos-stack/daos/blob/a7aa18b3b3d2fc6661506965443d5ae2214fd261/src/tests/ftest/util/ior_utils.py#L270):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/a7aa18b3b3d2fc6661506965443d5ae2214fd261/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/a7aa18b3b3d2fc6661506965443d5ae2214fd261/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:941](https://github.com/daos-stack/daos/blob/a7aa18b3b3d2fc6661506965443d5ae2214fd261/src/tests/ftest/util/server_utils.py#L941):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-12-28 05:22 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11069/18/execution/node/1113/log

2022-12-28 10:00 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11069/18/execution/node/1207/log

2023-01-03 15:32 UTC, brianjmurrell requested changes
The CI parts LGTM.  I cannot comment on the remaining python changes.

This cannot land however, until https://github.com/daos-stack/spdk/pull/56 lands and that PR's latest test run hit a [lot of failures](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-spdk-PR-56-master/4/tests/) on daos master that will need to be understood (i.e. are they known test failures on daos master?) before it can be landed.

2023-01-03 15:52 UTC, dinghwah commented
Python scripts change and test-logs are consistent with Master branch.

2023-01-03 16:01 UTC, daltonbohning approved these changes

2023-01-05 16:35 UTC, brianjmurrell requested changes
-1 until https://github.com/daos-stack/spdk/pull/56 lands which has been hitting various issues in it's testing.

2023-01-05 20:53 UTC, shimizukko approved these changes

2023-01-10 21:53 UTC, brianjmurrell commented
> brianjmurrell requested a review from shimizukko now

Apologies.  Requesting another review form @shimizukko was a mis-click on my part.  Slow GUI update meant I clicked somewhere I didn't think I was clicking.  Could you please put your +1 back @shimizukko.  Thanks!

2023-01-10 21:55 UTC, brianjmurrell approved these changes
https://github.com/daos-stack/spdk/pull/56 has landed.  It will take some time for it to be built and uploaded to Artifactory, but in a while you should be able to remove the `PR-repos:` from this PR and get the new spdk @dinghwah.

2023-01-11 01:11 UTC, shimizukko approved these changes

2023-01-11 16:20 UTC, brianjmurrell commented
@dinghwah Your most recent commit on this PR still has a `PR-repos` commit pragma in it.  @daos-stack/daos-gatekeeper should not land PRs with such a commit pragma in their last commit and they don't know if this will cause breakage when they remove it on landing.

Please remove the pragma in a new commit so that this runs without the need for an spdk PR.

2023-01-11 16:31 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/11440ab4af7829216ef8a3d82dc4463c1ee23cf7/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:270](https://github.com/daos-stack/daos/blob/11440ab4af7829216ef8a3d82dc4463c1ee23cf7/src/tests/ftest/util/ior_utils.py#L270):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/11440ab4af7829216ef8a3d82dc4463c1ee23cf7/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/11440ab4af7829216ef8a3d82dc4463c1ee23cf7/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:942](https://github.com/daos-stack/daos/blob/11440ab4af7829216ef8a3d82dc4463c1ee23cf7/src/tests/ftest/util/server_utils.py#L942):
(pylint-consider-using-dict-items) Consider iterating with .items()

2023-01-12 17:01 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11069/19/execution/node/1100/log

2023-01-12 18:26 UTC, dinghwah commented
2 failures are due to:
(1)DAOS-12292: HDF5 test timeout
(2)DAOS-12199: ior: dfs_open() of testfile.00000001 Failed

2023-01-12 20:10 UTC, merged

2023-01-12 20:13 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:212](https://github.com/daos-stack/daos/blob/11440ab4af7829216ef8a3d82dc4463c1ee23cf7/src/tests/ftest/util/command_utils.py#L212):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in constructor call

[src/tests/ftest/util/ior_utils.py:270](https://github.com/daos-stack/daos/blob/11440ab4af7829216ef8a3d82dc4463c1ee23cf7/src/tests/ftest/util/ior_utils.py#L270):
(pylint-used-before-assignment) Using variable 'replica_qty' before assignment

[src/tests/ftest/util/pool_security_test_base.py:39](https://github.com/daos-stack/daos/blob/11440ab4af7829216ef8a3d82dc4463c1ee23cf7/src/tests/ftest/util/pool_security_test_base.py#L39):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/pool_security_test_base.py:51](https://github.com/daos-stack/daos/blob/11440ab4af7829216ef8a3d82dc4463c1ee23cf7/src/tests/ftest/util/pool_security_test_base.py#L51):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/server_utils.py:942](https://github.com/daos-stack/daos/blob/11440ab4af7829216ef8a3d82dc4463c1ee23cf7/src/tests/ftest/util/server_utils.py#L942):
(pylint-consider-using-dict-items) Consider iterating with .items()