DAOS-12372 mgmt: fix dev query assertion with MD-ON-SSD enabled
daos-stack/daos pull request #11208
Opened 2023-01-12 03:25 UTC by wangshilong

Two fixes:
1. dev query ult should be run on the owner xstream, introduce a new api to return dev's owner xs target id.

2. SYS XS might be owner of device, fix to pass correct XS type when creating ults.

Required-githooks: true
Signed-off-by: Wang Shilong <shilong.wang@intel.com>

2023-01-12 03:27 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-01-12 22:50 UTC, daosbuild1 commented
Test stage Functional Hardware Medium UCX Provider completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-11208/1/testReport/(root)/

2023-01-13 02:57 UTC, NiuYawei requested changes
The meta & wal device query/monitor will be done in a separate PR?

2023-01-13 02:57 UTC, NiuYawei commented on src/engine/ult.c
> +	if (xs_type != DSS_XS_SYS)
either we revert this change and ensure caller always pass 0 tgt_id when the tgt_id is not used, or we change it to "if (xs_type == DSS_XS_VOS || xs_type == DSS_XS_OFFLOAD || xs_type == DSS_XS_IOFW)"

2023-01-13 02:57 UTC, NiuYawei commented on src/mgmt/srv_query.c
> +		tgt_id = bio_dev_owner_xs_id(bs_uuid);
The device list in nvme_glb.bd_bdevs is managed by init xstream, it's not thread safe, though the race window is small (the list is only changed on xstream start or hotplug), we just can iterate the list from other xstreams.

I know that there might be existing code having similar problems, maybe we'd use this opportunity to cleanup and fix all potential issues.

2023-01-13 02:57 UTC, NiuYawei commented on src/mgmt/srv_query.c
> +		bs_arg.bs_arg_type = SMD_DEV_TYPE_META;
What if SCM is configured (not md-on-ssd)? And I don't know why we need device type at all, since the device ID is already provided by user.

2023-01-13 02:57 UTC, NiuYawei commented on src/mgmt/srv_query.c
> +		mbh->mb_dev_type = SMD_DEV_TYPE_DATA;
Ditto, it seems to me the device type isn't useful when the device ID is known.

2023-01-13 02:57 UTC, NiuYawei commented on src/mgmt/srv_query.c
> +		faulty_info.bf_dev_type = SMD_DEV_TYPE_DATA;
Ditto.

2023-01-28 07:56 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-11208/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2023-01-28 07:56 UTC, daosbuild1 commented on src/bio/bio_context.c
> +	for (st = SMD_DEV_TYPE_DATA; st < SMD_DEV_TYPE_MAX; st++)
(style)  that open brace { should be on the previous line

2023-01-28 07:56 UTC, daosbuild1 commented on src/engine/ult.c
> +	if (xs_type == DSS_XS_VOS || xs_type == DSS_XS_OFFLOAD || xs_type == DSS_XS_IOFW)
(style)  suspect code indent for conditional statements (8, 24)

2023-01-28 07:56 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11208/2/execution/node/145/log

2023-01-28 08:05 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-01-30 03:16 UTC, NiuYawei approved these changes

2023-01-30 10:11 UTC, tanabarr approved these changes

2023-01-30 10:11 UTC, tanabarr commented on src/bio/bio_context.c
> +	for (st = SMD_DEV_TYPE_DATA; st < SMD_DEV_TYPE_MAX; st++) {
Very minor comment but I would prefer using 0 as a starting point is it doesn't use implicit knowledge that DATA is the first entry in the enum.

2023-01-30 23:46 UTC, merged