DAOS-10249 rdb: Fix raft RV assertion failures
daos-stack/daos pull request #11421
Opened 2023-02-09 15:06 UTC by liw

PR-repos: raft@PR-67
Signed-off-by: Li Wei <wei.g.li@intel.com>
Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2023-02-09 15:08 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-02-14 03:39 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-02-15 02:18 UTC, kccain submitted a review, later dismissed

2023-02-15 03:16 UTC, brianjmurrell requested changes

2023-02-15 03:16 UTC, brianjmurrell commented on debian/changelog
> + -- Li Wei <wei.g.li@intel.com>  Mon, 13 Apr 2023 10:36:00 +0800
```suggestion
 -- Li Wei <wei.g.li@intel.com>  Mon, 13 Feb 2023 10:36:00 +0800
```

2023-02-15 03:21 UTC, liw commented on debian/changelog
> + -- Li Wei <wei.g.li@intel.com>  Mon, 13 Apr 2023 10:36:00 +0800
Thanks. Fixed.

2023-02-15 03:22 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-02-15 13:42 UTC, kccain submitted a review, later dismissed

2023-02-15 16:03 UTC, brianjmurrell approved these changes

2023-02-16 00:15 UTC, liw commented
Merged master to fix a conflict.

2023-02-16 00:15 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-02-16 13:38 UTC, kccain approved these changes

2023-02-16 14:53 UTC, brianjmurrell approved these changes

2023-02-21 00:48 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-02-21 00:56 UTC, liw commented
Merged master to fix another conflict.

2023-02-21 14:10 UTC, kccain approved these changes

2023-02-22 13:07 UTC, liw commented
Merged master to fix yet another conflict.

2023-02-22 13:09 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-02-22 13:16 UTC, merged