DAOS-12646 test: use unique dfuse mount directory
daos-stack/daos pull request #11453
Opened 2023-02-14 16:45 UTC by daltonbohning

Test-tag: dfuse DmvrNegativeTest DmvrPosixMetaEntry DmvrPosixSymlinks DmvrPosixTypesTest DmvrSerialLargePosix DfuseSpaceCheck DaosVol DaosBuild DfuseEnospace FioSmall test_stat_parameters RootContainerTest PosixSimul SparseFile EcodFioRebuild test_ec_truncate EcodFaultInjection DfuseContainerCheck TestWithTelemetryIOBasic test_daos_vol_bigio DbenchTest BasicCheckout IoSysAdmin IoConsistency LargeFileCount MacsioTest ParallelIo SmallFileCount IorInterceptBasic IorInterceptMessages IorInterceptMultiClient IorSmall MdtestSmall IorEasy IorHard MdtestEasy test_telemetry_pool_metrics test_daos_dfuse_unit Skip-unit-tests: true
Skip-fault-injection-test: true

Remove mount_dir from tests and let dfuse_utils create a unique directory per test

Required-githooks: true

Signed-off-by: Dalton Bohning <dalton.bohning@intel.com>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2023-02-14 16:47 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-02-14 16:53 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-02-15 15:25 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11453/2/execution/node/1011/log

2023-02-15 16:31 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-02-16 18:48 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11453/3/execution/node/1011/log

2023-02-17 20:26 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11453/5/execution/node/722/log

2023-02-17 21:12 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-02-22 15:15 UTC, rpadma2 submitted a review, later dismissed
LGTM.

2023-02-24 16:49 UTC, mjean308 approved these changes

2023-02-24 17:05 UTC, daltonbohning commented
Had to resolve merge conflicts :(

2023-02-24 17:07 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-02-24 19:29 UTC, jamesanunez submitted a review, later dismissed

2023-02-25 18:52 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-11453/7/testReport/(root)/

2023-02-25 23:49 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11453/7/execution/node/1010/log

2023-02-27 15:54 UTC, daltonbohning commented
Existing failures in https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-11453/7/tests
- dfuse/daos_build.py - being fixed by #11534 
- FTEST_daos_test.DAOS_Rebuild_EC
  - https://daosio.atlassian.net/browse/DAOS-12709

2023-02-28 20:54 UTC, phender approved these changes

2023-02-28 21:15 UTC, phender requested changes

2023-02-28 21:15 UTC, phender commented on src/tests/ftest/interoperability/diff_versions.yaml
> -  mount_dir: "/tmp/daos_dfuse1/"
This will cause problems with the test as it does a `mount_dir = self.params.get("mount_dir", '/run/dfuse/*')`

2023-02-28 22:00 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-02-28 23:38 UTC, phender approved these changes

2023-03-01 15:57 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-11453/8/testReport/(root)/

2023-03-01 21:38 UTC, daltonbohning commented
Reverting changes to a manual and re-ran. Existing failures in https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-11453/8/tests
- FTEST_daos_test.DAOS_Rebuild_EC
  - https://daosio.atlassian.net/browse/DAOS-12709

2023-03-01 21:43 UTC, jamesanunez approved these changes

2023-03-02 18:53 UTC, merged