DAOS-11394 test: Save dmg log for daos_test suite
daos-stack/daos pull request #11783
Opened 2023-03-23 16:55 UTC by kjacque

Save dmg logs for all daos_test cases.

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [x] You are the appropriate gatekeeper to be landing the patch.
* [x] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [x] Githooks were used. If not, request that user install them and check copyright dates.
* [x] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [x] All builds have passed.  Check non-required builds for any new compiler warnings.
* [x] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [x] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [x] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2023-03-23 21:11 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11783/2/execution/node/1062/log

2023-03-24 08:05 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11783/2/execution/node/1177/log

2023-03-24 08:08 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-11783/2/execution/node/1239/log

2023-03-28 16:04 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-03-30 14:30 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-03-30 16:36 UTC, daltonbohning requested changes
This test also uses the shared code, and unfortunately is not tagged with `pr` or `daos_test`
```
Test-tag: CsumErrorLog
```
> Test tag daos_test is covered by the standard PR tests. I saw the dmg results collected for tag daos_test on its own, so I am re-running with the full PR suite now for landing purposes

That's not entirely true. There are tests using this shared code, and tagged with `daos_test`, but NOT tagged with `pr`.

To run `pr`, `daos_test`, and `CsumErrorLog` you can do:
```
Features: daos_test CsumErrorLog
```

2023-03-30 16:58 UTC, kjacque commented
@daltonbohning Good catches, thanks.

2023-03-30 19:22 UTC, kjacque commented on src/tests/ftest/util/daos_core_base.py
> +            print("unable to move dmg log:", error)
Good catch. I added a specific case for the FileNotFoundError as well. There seem to be a few tests where dmg isn't run by daos_test, so there isn't a log file.

2023-03-30 19:22 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-03-30 19:40 UTC, daltonbohning approved these changes
LGTM - thanks!

2023-03-31 19:18 UTC, phender approved these changes
As an improvement, it would be good to able to redefine the `/tmp/suite_dmg.log` to `os.path.join(self.outputdir, f"{self.subtest_name}_dmg.log")` prior to running the `daos_test` command to avoid the additional file moving code.  This would avoid potential problems with tests timeouts that prevent the file moving code from being executed or situations where the tests in run in a different environment where `/tmp` might not be an ideal location.

2023-03-31 19:20 UTC, merged