DAOS-13587 test: Re-enable skipped DAOS Seg Count test
daos-stack/daos pull request #12283
Opened 2023-06-06 18:05 UTC by arorasamarth

Updating test to enabling CI

Skip-unit-tests: true
Skip-fault-injection-test: true
Test-tag: test_segcount

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2023-06-06 18:07 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-12283/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2023-06-06 18:07 UTC, daosbuild1 commented on src/tests/ftest/io/seg_count.yaml
> +  size: 60gb
(style)  trailing whitespace

2023-06-06 18:07 UTC, daosbuild1 commented on src/tests/ftest/io/seg_count.yaml
> +  size: 60gb
```suggestion
  size: 60gb
```

2023-06-06 18:07 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-12283/1/execution/node/145/log

2023-06-06 18:16 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-06-07 15:59 UTC, daltonbohning commented
The test was skipped:
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-12283/2/tests

Because the skiplist has an entry against DAOS-7258. On `wolf`:
```
$ cat /scratch/CI-skip-list-master |grep seg
[['DAOS-7258', 'test_method_name', 'test_segcount']]
```


@arorasamarth The test will run if you push a commit where the title starts with DAOS-7258. I.e.
```
DAOS-7528 test: Re-enable skipped DAOS Seg Count test

Updating test to enabling CI

Skip-unit-tests: true
Skip-fault-injection-test: true
Test-tag: test_segcount
```

2023-06-07 18:35 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-06-08 15:03 UTC, phender requested changes
The `io/seq_count.py` test is employing an older technique for skipping tests and the https://github.com/daos-stack/daos/blob/master/src/tests/ftest/io/seg_count.py#L17 line needs to be removed along with https://github.com/daos-stack/daos/blob/master/src/tests/ftest/io/seg_count.py#L8.  Please implement this change and use the a commit message the starts with `DAOS-7258 test:` as there is still a skip-list entry for the test case as well.

2023-06-12 18:33 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-06-13 16:11 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-06-13 18:14 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-06-14 16:12 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-06-14 17:08 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-12283/7/execution/node/771/log

2023-06-14 17:13 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-06-14 22:19 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-12283/8/execution/node/771/log

2023-06-16 15:38 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-06-16 18:20 UTC, daltonbohning commented
You shouldn't request gatekeeper until after
1. The tests are passing
2. The PR is "Open" instead of Draft
3. You have two reviews

2023-06-19 05:31 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-12283/10/testReport/(root)/

2023-06-20 17:13 UTC, daltonbohning commented on src/tests/ftest/io/seg_count.yaml
> +  size: 60gb
To be generic, we can just use most available space
```suggestion
  size: 95%
```

2023-06-20 19:58 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-06-21 16:46 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-06-22 22:12 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-12283/12/testReport/

2023-06-23 18:04 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-06-26 01:09 UTC, arorasamarth commented
All tests have passed. Sending for a review.

2023-06-26 12:28 UTC, phender approved these changes

2023-06-26 14:17 UTC, mjean308 approved these changes

2023-06-26 15:13 UTC, merged