DAOS-13510 chk: Query output should include dry-run status
daos-stack/daos pull request #12294
Opened 2023-06-07 17:55 UTC by mjmac

If the checker is running in dry-run mode, notify the user.

Required-githooks: true

Signed-off-by: Michael MacDonald <mjmac.macdonald@intel.com>

2023-06-07 17:59 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-06-07 18:47 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-12294/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2023-06-07 18:47 UTC, daosbuild1 commented on src/chk/chk_leader.c
> +				   cru->cru_rank, cru->cru_target, cru->cru_pool, cru->cru_pool_label,
(style)  line over 100 characters

2023-06-07 18:47 UTC, daosbuild1 commented on src/chk/chk_leader.c
> +				   cru->cru_akey, cru->cru_msg, cru->cru_option_nr, cru->cru_options,
(style)  line over 100 characters

2023-06-07 18:47 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-12294/2/execution/node/146/log

2023-06-08 10:25 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-12294/2/execution/node/1237/log

2023-06-08 11:13 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-12294/2/execution/node/1284/log

2023-06-09 04:59 UTC, Nasf-Fan commented
> @Nasf-Fan: Please take a look to see if this is what you had in mind. The only issue that I can see is that there does not appear to be a way to get out of dry-run mode. If I run `dmg check start --dry-run`, then `dmg check start --reset`, the checker seems to stay in dry-run mode. I have also tried running `dmg check stop && dmg check start`, but the flag is persistent in the checker properties, it seems.
> 
> I think probably we need to clear the property flag if the user did not specify it with the start command. I tried to implement that, but ran into some trouble. Perhaps you can suggest a solution that I can include with this patch, thanks.

Does MS store the "dryrun" flag somewhere? If not, then when you start checker next time without "--dry-run", then the former "dryrun" will be automatically removed. If it does not work, then it is daos engine bug, and I need to fix it. Would you please to verify the "dryrun" behavior against the patch https://github.com/daos-stack/daos/pull/12242 ? In such patch, we start checker with "dryrun" firstly, and then without "dryrun" in subsequent "check start". According to the CI test result, it works.

2023-06-09 05:10 UTC, Nasf-Fan commented
As my understand, MS can have more simple way to know whether current check instance is running under "dryrun" mode or not. For example, when user input "dmg check query", then MS can handle that in two steps:
1. Firstly, trigger DRPC_METHOD_MGMT_CHK_PROP to DAOS engine, then it will get current checker start options, that includes the "dryrun" if have.
2. Then, trigger DRPC_METHOD_MGMT_CHK_QUERY to DAOS engine as you orignal "dmg check query" does.

With the firstly step checker property information, you can know whether current checker is running under dryrun mode or not. That will much simplify the patch. How do you think?

2023-10-02 16:01 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-11-01 16:36 UTC, tanabarr approved these changes

2023-11-13 07:13 UTC, Nasf-Fan requested changes
@kjacque, as my understand, MS can have more simple way to know whether current check instance is running under "dryrun" mode instead of changing the API just for the dryrun flag. For example, when user input "dmg check query", then MS can handle that in two steps:

Firstly, trigger DRPC_METHOD_MGMT_CHK_PROP to DAOS engine, then it will get current checker start options, that includes the "dryrun" flag if have.

Then, trigger DRPC_METHOD_MGMT_CHK_QUERY to DAOS engine as you orignal "dmg check query" does.

With the firstly step checker property information, you can know whether current checker is running under dryrun mode or not. That will much simplify current patch.

2024-05-01 21:05 UTC, closed without merging