DAOS-14072 test: Fix pool query test params
daos-stack/daos pull request #12810
Opened 2023-08-09 14:26 UTC by tanabarr

Test-tag: test_pool_query_basic
Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2023-08-09 14:29 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-08-09 14:35 UTC, phender requested changes

2023-08-09 14:35 UTC, phender commented on src/tests/ftest/util/apricot/apricot/test.py
> +        self.maxDiff = None
We will need the following as the definition of this name comes from avocado:
```suggestion
        self.maxDiff = None    # pylint: disable=invalid-name
```

2023-08-09 14:58 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-08-09 14:59 UTC, daltonbohning commented on src/tests/ftest/util/apricot/apricot/test.py
> +        self.maxDiff = None # pylint: disable=invalid-name
Inline comments need 2 spaces. I think pylint will complain about this
```suggestion
        self.maxDiff = None  # pylint: disable=invalid-name
```

2023-08-09 22:30 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-08-10 12:06 UTC, phender approved these changes

2023-08-11 14:45 UTC, daltonbohning approved these changes

2023-08-11 14:48 UTC, merged