DAOS-14139 test: Debug Unhandled exception for dfuse/caching_check.py
daos-stack/daos pull request #12842
Opened 2023-08-15 01:11 UTC by shimizukko

During the teardown of dfuse/caching_checking.py, Unhandled exception occurs when dmg pool destroy is called. The command itself works, but we can't tell where that exception is coming from, so use Exception in remove_pool() so that we can catch and investigate any kind of exception.

This issue is intermittent.

Skip-unit-tests: true
Skip-fault-injection-test: true
Test-tag: test_dfuse_caching_check
Test-repeat: 6
Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2023-08-15 01:13 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-08-16 14:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-08-16 16:21 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-12842/2/execution/node/785/log

2023-08-19 04:51 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-08-21 00:41 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-08-22 01:54 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-08-22 23:11 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-08-23 08:52 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-12842/6/execution/node/785/log

2023-08-23 14:10 UTC, phender requested changes

2023-08-23 14:10 UTC, phender commented on src/tests/ftest/util/apricot/apricot/test.py
> +                if str(Exception) == "Test interrupted by SIGTERM":
```suggestion
                if str(error) == "Test interrupted by SIGTERM":
```

2023-08-24 07:35 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-08-25 00:36 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-12842/7/execution/node/792/log

2023-08-25 15:24 UTC, phender requested changes
With the debug `sleep(120)` removed we shouldn't need to repeat the `dfuse/caching_check.py` test.

2023-08-25 15:24 UTC, phender commented on src/tests/ftest/util/test_utils_pool.py
> +
In https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-12842/7 this has proven that the changes in `src/tests/ftest/util/apricot/apricot/test.py` are working correctly, e.g.
```
2023-08-24 23:52:07,304 process          L0686 INFO | Command '/usr/bin/dmg -o /etc/daos/daos_control.yml -d -j server set-logmasks' finished with 0 after 0.12249326705932617s
2023-08-24 23:53:32,105 stacktrace       L0039 ERROR| 
2023-08-24 23:53:32,105 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/lib/python3.6/site-packages/avocado/core/test.py:793
2023-08-24 23:53:32,106 stacktrace       L0045 ERROR| Traceback (most recent call last):
2023-08-24 23:53:32,106 stacktrace       L0045 ERROR|   File "/usr/lib/daos/TESTING/ftest/util/apricot/apricot/test.py", line 1393, in tearDown
2023-08-24 23:53:32,106 stacktrace       L0045 ERROR|     self._teardown_errors.extend(self._cleanup())
2023-08-24 23:53:32,106 stacktrace       L0045 ERROR|   File "/usr/lib/daos/TESTING/ftest/util/apricot/apricot/test.py", line 413, in _cleanup
2023-08-24 23:53:32,106 stacktrace       L0045 ERROR|     raise error
2023-08-24 23:53:32,106 stacktrace       L0045 ERROR|   File "/usr/lib/daos/TESTING/ftest/util/apricot/apricot/test.py", line 409, in _cleanup
2023-08-24 23:53:32,106 stacktrace       L0045 ERROR|     errors.extend(cleanup["method"](**cleanup["kwargs"]))
2023-08-24 23:53:32,106 stacktrace       L0045 ERROR|   File "/usr/lib/daos/TESTING/ftest/util/test_utils_pool.py", line 93, in remove_pool
2023-08-24 23:53:32,106 stacktrace       L0045 ERROR|     sleep(120)
2023-08-24 23:53:32,106 stacktrace       L0045 ERROR|   File "/usr/lib/python3.6/site-packages/avocado/plugins/runner.py", line 77, in sigterm_handler
2023-08-24 23:53:32,106 stacktrace       L0045 ERROR|     raise RuntimeError("Test interrupted by SIGTERM")
2023-08-24 23:53:32,106 stacktrace       L0045 ERROR| RuntimeError: Test interrupted by SIGTERM
2023-08-24 23:53:32,106 stacktrace       L0046 ERROR| 
2023-08-24 23:53:32,106 test             L0206 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
2023-08-24 23:53:32,106 test             L0206 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
2023-08-24 23:53:32,106 test             L0206 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
2023-08-24 23:53:32,107 test             L0933 ERROR| ERROR 1-./dfuse/caching_check.py:DfuseCachingCheck.test_dfuse_caching_check;run-container-dfuse-hosts-ior-client_processes-pool-server_config-engines-0-storage-0-1-51d0 -> TestSetupFail: Test interrupted by SIGTERM
```
Let's now remove this in order to land the fix to `src/tests/ftest/util/apricot/apricot/test.py`.
```suggestion
```

2023-08-29 06:10 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-08-29 13:49 UTC, phender approved these changes

2023-08-29 14:04 UTC, daltonbohning approved these changes

2023-08-29 15:21 UTC, merged