DAOS-8331 client: Export client metrics via agent
daos-stack/daos pull request #13545
Opened 2023-12-28 19:23 UTC by mjmac

Adds a new agent config parameter and code to
optionally export client metrics in Prometheus
format.

Change-Id: I77864682cc19fa4c33f326d879e20704ef57a7ea
Required-githooks: true

Signed-off-by: Michael MacDonald <mjmac@google.com>

2024-01-05 18:29 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13545/6/display/redirect

2024-01-11 16:19 UTC, daltonbohning reviewed
Should there be new entries added to utils/config/daos_agent.yml?

Also, could I ask for this small change? It would allow functional tests - specifically, the performance tests - to set the config
https://github.com/daos-stack/daos/commit/578d9075c0e432c3121fade934ff8ced3eff24e7
And since it's unused, no special testing is needed

2024-01-11 17:22 UTC, mjmac commented
> Should there be new entries added to utils/config/daos_agent.yml?
> 
Yes, good catch. I forgot about those.

> Also, could I ask for this small change? It would allow functional tests - specifically, the performance tests - to set the config [578d907](https://github.com/daos-stack/daos/commit/578d9075c0e432c3121fade934ff8ced3eff24e7) And since it's unused, no special testing is needed
>
I'll merge that in, thanks. Actually, I may try to add a ftest for this work, so that change makes it even easier.

2024-01-31 18:37 UTC, daosbuild1 commented
Test stage Build on Leap 15.5 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-13545/10/execution/node/284/log

2024-01-31 18:40 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15.5 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-13545/10/execution/node/279/log

2024-01-31 18:41 UTC, daosbuild1 commented
Test stage Build RPM on EL 9 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-13545/10/execution/node/366/log

2024-01-31 18:42 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-13545/10/execution/node/361/log

2024-01-31 18:43 UTC, mjmac commented
> 
> I'll merge that in, thanks. Actually, I may try to add a ftest for this work, so that change makes it even easier.

Just refreshed this patch. I did add the `agent_utils_params.py` changes. I have not gotten to adding the ftest yet. As these metrics are still somewhat of a WIP, IMO it's premature to add tests that are expecting fixed sets of metrics while we're iterating. I agree with @wangdi1 that we should add the ftest later.

2024-01-31 18:44 UTC, daosbuild1 commented
Test stage Build on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-13545/10/execution/node/480/log

2024-01-31 18:44 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-13545/10/execution/node/347/log

2024-02-26 17:12 UTC, mjmac commented
Requesting early reviews while waiting for the base patch to land, TIA.

2024-02-27 16:03 UTC, tanabarr approved these changes
Not overly familiar with the telemetry code but these changes LGTM.

2024-02-27 18:04 UTC, mjmac commented on src/control/cmd/daos_agent/config.go
> +	if cfg.TelemetryRetain > 0 && cfg.TelemetryPort == 0 {
Hmm. I see where you're coming from on this suggestion, but IMO there's a subtle difference. It's true that the current implementation of `TelemetryEnabled()` just checks to see if `TelemetryPort` is greater than zero. If we change that logic to depend on other checks in order to determine if it's enabled, though, then we have to go back and change this line which is specifically about validating the configuration values.

2024-02-27 18:05 UTC, mjmac commented on src/control/lib/telemetry/promexp/engine.go
> +	_ = copy(sourceCopy, c.sources)
TBH, not sure why I added this placeholder assignment in the original method. I've removed it though, because it's distracting.

2024-03-05 20:55 UTC, daltonbohning reviewed
ftest code changes LGTM. Thanks for adding!

2024-03-06 00:28 UTC, kjacque requested changes

2024-03-06 00:28 UTC, kjacque commented on src/control/lib/telemetry/promexp/source.go
> +func (s *sourceMetricSchema) Prune() {
nit - needs documentation comment

2024-03-06 00:28 UTC, kjacque commented on src/control/lib/telemetry/promexp/source.go
> +	MetricSource struct {
nit - needs documentation comment

2024-03-06 00:28 UTC, kjacque commented on src/control/lib/telemetry/promexp/source.go
> +func (s *MetricSource) Collect(log logging.Logger, ch chan<- *sourceMetric) {
nit - needs documentation comment

2024-03-06 00:28 UTC, kjacque commented on src/control/lib/telemetry/promexp/source.go
> +func (s *MetricSource) PruneSegments(log logging.Logger, maxSegAge time.Duration) {
needs documentation comment

2024-03-06 00:28 UTC, kjacque commented on src/control/cmd/daos_agent/infocache.go
> +func (c *InfoCache) adjustAttachInfo(resp *control.GetAttachInfoResp) {
We make other modifications to the GetAttachInfoResp struct in mgmt_rpc.go before returning to the client. Infocache has been caching only what the server sends back. I'm not exactly opposed to doing it this way, but it feels a little odd making our client-side modifications in two different layers.

2024-03-24 14:45 UTC, closed without merging

2024-03-24 14:45 UTC, mjmac commented
Closed in favor of the approach in #14030.