DOS-14821 bio: introduce env var to ignore sys SSD fault
daos-stack/daos pull request #13611
Opened 2024-01-16 03:36 UTC by NiuYawei

Introduce env var to ignore sys SSD fault (sys SSD fault will result in the engine being killed), this env var will be used in tests.

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2024-01-16 10:24 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-13611/1/testReport/

2024-01-16 10:44 UTC, tanabarr reviewed
looks good but maybe we should include a reference to the environment variable in documentation somewhere, maybe one of the configs in utils/config or somewhere where engine environment variables are listed?

2024-01-16 12:49 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-13611/1/execution/node/1433/log

2024-01-17 01:12 UTC, wangshilong submitted a review, later dismissed

2024-01-17 02:10 UTC, NiuYawei commented
> looks good but maybe we should include a reference to the environment variable in documentation somewhere, maybe one of the configs in utils/config or somewhere where engine environment variables are listed?

Currently all the env vars for developers/testers are not documented. I agree with you that we need to document such env vars somewhere, will push a separate patch for this.

2024-01-17 19:15 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-13611/2/testReport/

2024-01-19 03:55 UTC, NiuYawei commented
On second thought, this workaround could cause the test failed on other places. Need to consider it more.

2024-01-31 10:11 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-13611/3/execution/node/1451/log

2024-02-06 05:17 UTC, NiuYawei commented
The rebuild hang issue in nvme recovery tests are due to https://daosio.atlassian.net/browse/DAOS-15145 , I'll refresh the PR once DAOS-15145 fixed.

2024-02-19 06:46 UTC, tanabarr approved these changes

2024-02-21 14:54 UTC, phender requested changes
I disagree with this approach.  We can update the tests to verify that the server has faulted when faulting an sys SSD instead of adding an env to disable this behavior.  I have changes implemented in a PR for https://daosio.atlassian.net/browse/DAOS-14782 that already has been proven to work.

2024-02-23 02:54 UTC, NiuYawei commented
> I disagree with this approach. We can update the tests to verify that the server has faulted when faulting an sys SSD instead of adding an env to disable this behavior. I have changes implemented in a PR for https://daosio.atlassian.net/browse/DAOS-14782?focusedCommentId=125079 that already has been proven to work.

I agree with you, let's close this one and update tests instead.

2024-02-23 02:54 UTC, closed without merging