DAOS-15116 test: to fix missing test.cov file on functional VM and HW tests
daos-stack/daos pull request #13725
Opened 2024-02-02 17:50 UTC by dinghwah

Description: update environment_utils.py with correct test.cov path

Skip-fnbullseye: false
Skip-bullseye: false
Skip-python-bandit: true
Skip-build-EL9-rpm: true
Allow-unstable-test: true
Doc-only: false
Test-tag: test_aggregation_single_pool test_basic_aggregation test_daos_management test_single_object_with_checksum
Required-githooks: true
Signed-off-by: Ding Ho ding-hwa.ho@intel.com

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2024-02-02 19:02 UTC, daltonbohning approved these changes

2024-02-05 21:58 UTC, phender requested changes
Changes look ok, but this needs to run with https://github.com/daos-stack/pipeline-lib/pull/420 changes, either after it has landed or by referencing the PR in the Jenkinsfile.

==>Thanks for the comment, this PR had rebased after pipeline-lib/pull/420 landed (on 02/05/2024).

2024-02-06 19:19 UTC, JohnMalmberg approved these changes

2024-02-06 19:30 UTC, daltonbohning approved these changes

2024-02-06 19:48 UTC, dinghwah commented
Please note: The error on stage Bullseye Report gen will be covered by DAOS-15150.

2024-02-06 20:27 UTC, phender commented
The `Bullseye Report on EL 8` stage failed in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13725/3/pipeline-console/?selected-node=1653:
```
[11](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13725/3/pipeline-console/?start-byte=0&selected-node=1692#log-11)
14:35:43  + java -jar bullshtml.jar test_coverage
[12](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13725/3/pipeline-console/?start-byte=0&selected-node=1692#log-12)
14:35:43  Error: A JNI error has occurred, please check your installation and try again
[13](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13725/3/pipeline-console/?start-byte=0&selected-node=1692#log-13)
14:35:43  Exception in thread "main" java.lang.UnsupportedClassVersionError: com/junoyoon/BullsHtml has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[14](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13725/3/pipeline-console/?start-byte=0&selected-node=1692#log-14)
14:35:43  	at java.lang.ClassLoader.defineClass1(Native Method)
[15](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13725/3/pipeline-console/?start-byte=0&selected-node=1692#log-15)
14:35:43  	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
```

2024-02-06 20:28 UTC, phender approved these changes

2024-02-06 20:30 UTC, merged