DAOS-14557 object: code clean for collective query
daos-stack/daos pull request #13733
Opened 2024-02-03 13:06 UTC by Nasf-Fan

Add prefix for the members of obj_tgt_query_args and obj_query_merge_args. Some other code style adjustment.

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2024-02-05 16:38 UTC, jolivier23 approved these changes, later dismissed

2024-02-07 20:42 UTC, mchaarawi requested changes
no request for changes really, but according to this PR:
https://github.com/daos-stack/daos/pull/13761
which reverts the original coll query patch, this feature introduced a massive amount of failures in EC testing. so we will either land the revert PR (in which this PR does not apply anymore), or a fix to those issues must be developed first.
either way, some action will be taken before the weekend testing. This issue is also blocking the delay rebuild PR.

2024-02-17 06:34 UTC, Nasf-Fan commented
Resolve merge conflict.

2024-02-19 02:04 UTC, Nasf-Fan commented
> no request for changes really, but according to this PR:
> #13761
> which reverts the original coll query patch, this feature introduced a massive amount of failures in EC testing. so we will either land the revert PR (in which this PR does not apply anymore), or a fix to those issues must be developed first.
> either way, some action will be taken before the weekend testing. This issue is also blocking the delay rebuild PR.

The test failures (DAOS-15127/15128) have been fixed via the patch https://github.com/daos-stack/daos/pull/13775. Please review this patch again. Thanks!

2024-02-20 03:11 UTC, liuxuezhao approved these changes

2024-02-20 13:32 UTC, mchaarawi approved these changes

2024-02-20 16:03 UTC, merged