DAOS-15198 test: Test DAOS_PROP_PO_SPACE_RB - Pool space reservation
daos-stack/daos pull request #13802
Opened 2024-02-14 00:16 UTC by shimizukko

Test steps:
1. Create pool with space_rb set to 50 and aggregation disabled.
2. Call dmg pool get-prop and verify that Rebuild space ratio (space_rb) is 50%.
3. Run IOR to fill 50% of SCM. Use small transfer size so that data are written to SCM. IOR should fail with DER_NOSPACE(-1007): 'No space left on device'
4. Create a new pool with space_rb set to 50 and aggregation enabled this time.
5. Call dmg pool get-prop and verify that Rebuild space ratio (space_rb) is 50%.
6. Run IOR to fill 50% of NVMe. Use large transfer size so that data are written to NVMe. IOR should fail with DER_NOSPACE(-1007): 'No space left on device'

Skip-unit-tests: true
Skip-fault-injection-test: true
Test-tag: test_space_rb

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2024-02-22 22:26 UTC, shimizukko commented on src/tests/ftest/aggregation/space_rb.py
> +        pool_1.create()
I didn't realize this. Thanks.

2024-02-24 07:36 UTC, shimizukko commented on src/tests/ftest/aggregation/space_rb.py
> +            pool=pool_1, container=container_1, job_num=1, block_size="2400M", transfer_size="2K",
Done. I use 32, so divided block_size by it.

2024-02-24 07:48 UTC, shimizukko commented on src/tests/ftest/aggregation/space_rb.py
> +        ior_cmd.transfer_size.update(value=transfer_size)
I moved the comment to the test yaml.

Thanks for the code. It looks good, but I'm not sure whether dynamically determining the block size adds any value. The pool size isn't the focus of this test. If we need to enhance this test to support different pool sizes and space_rb percentages, then this dynamic calculation would definitely help.

2024-02-28 01:08 UTC, daltonbohning approved these changes

2024-02-28 01:08 UTC, daltonbohning commented on src/tests/ftest/aggregation/space_rb.py
> +        ppn = self.params.get("ppn", '/run/ior/*')
This could come from the namespace too
```suggestion
        ppn = self.params.get("ppn", namespace)
```

2024-02-28 01:08 UTC, daltonbohning commented on src/tests/ftest/aggregation/space_rb.py
> +        ior_cmd.transfer_size.update(value=transfer_size)
That said, this dynamic code is easy enough to add later if we need to

2024-02-29 23:53 UTC, shimizukko commented on src/tests/ftest/aggregation/space_rb.py
> +        ppn = self.params.get("ppn", '/run/ior/*')
Done

2024-03-05 14:45 UTC, dinghwah approved these changes

2024-03-06 16:54 UTC, daltonbohning requested changes
Sorry, I didn't notice before. I think part of the process for adding a new test should include running with MD on SSD so we don't get surprise failures in weekly
```
Skip-func-hw-medium-md-on-ssd: false
```

2024-03-08 22:51 UTC, shimizukko commented
> Sorry, I didn't notice before. I think part of the process for adding a new test should include running with MD on SSD so we don't get surprise failures in weekly
> 
> ```
> Skip-func-hw-test-medium-md-on-ssd: false
> ```
I ran the test with MD-on-SSD and it passed.

2024-03-08 23:24 UTC, daltonbohning approved these changes

2024-03-08 23:25 UTC, merged