DAOS-15085 container: increase capa ULT stack size
daos-stack/daos pull request #13811
Opened 2024-02-15 15:49 UTC by wangdi1

Increase capa ULT stack sizeto avoid stack overflow.

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2024-02-15 15:53 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2024-02-17 00:55 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2024-02-17 20:25 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-13811/2/testReport/

2024-02-19 02:21 UTC, liuxuezhao approved these changes

2024-02-19 22:09 UTC, wangdi1 commented
failure due to DAOS-14353

2024-02-20 03:32 UTC, NiuYawei requested changes
Temporarily mark -1 until my concern is addressed.

2024-02-20 03:32 UTC, NiuYawei commented on src/container/container_iv.c
> +			    0, DSS_DEEP_STACK_SZ, NULL);
I think we'd investigate the IV operations deeper, and try to fix all the potential stack overrun issues together:

1. Do we know what are the major stack consumers for the IV operations? Are these functions from Cart or DAOS? If they are from Cart, the async IV operation in lazy mode should use deep stack size as well? See iv_op_async().
2. Should we use deep stack size for all container IV operations? See ds_cont_tgt_snapshots_refresh().
3. Should we use deep stack size for pool IV operations as well? See ds_pool_iv_svc_fetch().

2024-02-20 04:35 UTC, NiuYawei approved these changes

2024-02-20 04:35 UTC, NiuYawei commented on src/container/container_iv.c
> +			    0, DSS_DEEP_STACK_SZ, NULL);
I'm fine with landing it as-is if it's blocking 2.4.2. Let's address my concerns in master.

2024-02-21 20:03 UTC, merged