DAOS-15154 pool: ds_pool_child_lookup() could return NULL
daos-stack/daos pull request #13834
Opened 2024-02-20 01:32 UTC by wangshilong

When a faulty device is replaced with a new one using the “dmg storage replace nvme” command, the reintegration of affected pool targets is automatically triggered. The followings steps outline the device replacement process on the engine side:

1) Replace the old device with the new device in the SMD. 2) Setup all SPDK related stuff for the new device. 3) Start ds_pool_child

It is important to note that manual reintegration may be initiated before step 3, which trigger assertion.

For above case, return DER_AGAIN error, this patch also tries to fix another two places which forgot to check return of ds_pool_child_lookup().

Required-githooks: true

2024-02-20 02:04 UTC, tanabarr approved these changes, later dismissed

2024-02-20 11:24 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-13834/2/execution/node/1452/log

2024-02-20 11:46 UTC, NiuYawei requested changes

2024-02-20 11:46 UTC, NiuYawei commented on src/object/srv_obj_migrate.c
> +	pool_tls->mpt_pool = child;
ds_pool_child could leak when any of above operation fails. I think simpler change could be:

`
pool_tls->mpt_pool = ds_pool_child_lookup(arg->pool_uuid);
 if (pool_tls->mpt_pool == NULL)
    D_GOTO(out, rc = -DER_NO_HDL);
`

2024-02-20 12:37 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-13834/2/execution/node/1406/log

2024-02-21 02:48 UTC, NiuYawei submitted a review, later dismissed

2024-02-21 15:03 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-13834/3/execution/node/1497/log

2024-02-21 21:16 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-13834/3/execution/node/1405/log

2024-02-23 02:48 UTC, NiuYawei approved these changes

2024-02-25 00:43 UTC, jolivier23 approved these changes

2024-02-26 01:44 UTC, merged