DAOS-15136 client: Switch to using libfused
daos-stack/daos pull request #14077
Opened 2024-03-28 00:53 UTC by jolivier23

Switch to using libfused instead of libfuse3

PR-repos: fused@PR-1:25

Required-githooks: true

Change-Id: I382b96a17a8d503d6cf7321b57050e7ab0c187d4

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2024-03-28 00:57 UTC, daosbuild1 commented
Test stage Build RPM on EL 9 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/2/execution/node/354/log

2024-03-28 00:58 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/2/execution/node/327/log

2024-03-28 00:59 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15.5 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/2/execution/node/287/log

2024-03-28 01:04 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/2/execution/node/351/log

2024-03-28 01:33 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15.5 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/4/execution/node/349/log

2024-03-28 01:34 UTC, daosbuild1 commented
Test stage Build RPM on EL 9 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/4/execution/node/341/log

2024-03-28 01:37 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/4/execution/node/369/log

2024-03-28 01:37 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/4/execution/node/353/log

2024-03-28 02:18 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15.5 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/5/execution/node/270/log

2024-03-28 02:21 UTC, daosbuild1 commented
Test stage Build RPM on EL 9 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/5/execution/node/349/log

2024-03-28 02:23 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/5/execution/node/309/log

2024-03-28 02:27 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/5/execution/node/355/log

2024-03-28 03:01 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15.5 completed with status UNSTABLE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/6/execution/node/287/log

2024-03-28 03:02 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status UNSTABLE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/6/execution/node/364/log

2024-03-28 03:06 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status UNSTABLE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/6/execution/node/350/log

2024-03-28 16:19 UTC, daosbuild1 commented
Test stage Build RPM on EL 9 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/8/execution/node/326/log

2024-03-28 16:19 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/8/execution/node/345/log

2024-03-28 16:21 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15.5 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/8/execution/node/329/log

2024-03-28 16:21 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/8/execution/node/338/log

2024-04-25 18:09 UTC, ashleypittman commented on debian/changelog
> +>>>>>>> master
Bad merge here.

2024-04-26 18:04 UTC, ashleypittman commented on src/client/dfuse/SConscript
> +    src = """#include <fused/fuse_lowlevel.h>
This is for working with various fuse versions, we should replace this with a simple version check.

2024-06-05 19:06 UTC, brianjmurrell requested changes

2024-06-05 19:06 UTC, brianjmurrell commented on utils/rpms/daos.spec
>  %endif
The `>= 1` is redundant here as is the `%if` branch.

```suggestion
BuildRequires: fused-devel
```

(Sorry, GH is really mangling this suggestion due to the unchanged lines in it.)

2024-06-05 19:06 UTC, brianjmurrell commented on utils/rpms/daos.spec
> +Requires: fused >= 1
Not at all necessary.

```suggestion
```

2024-06-05 19:06 UTC, brianjmurrell commented on utils/rpms/daos.spec
> +Requires: fused >= 1
Ditto, if this really should be a change from `fused-devel` to `fused` but it's not clear why the `-devel` is not needed here now.

So either:

```suggestion
```

or

```suggestion
Requires: fused-devel
```

2024-06-05 19:06 UTC, brianjmurrell commented on utils/rpms/daos.spec
> +* Thu Apr 25 2024 Jeff Olivier <jeffolivier@google.com> 2.5.101-5
This datestamp could use an update.

2024-06-05 19:06 UTC, brianjmurrell commented on debian/changelog
> + -- Jeff Olivier <jeffolivier@google.com>  Thu, 25 Apr 2024 10:30:00 +0000
Worth bringing this timestamp up-to-date.

2024-12-20 04:11 UTC, jolivier23 commented
I started looking at static compilation and it wasn't trivial (no debian packages in daos-stack/fused, for example) so I thought I would try to finish this.

fused is currently in sync with libfuse head so need some validation but it has all of the patches.   I changed tactics to just do a few renames from fuse3 to fused which hopefully won't cause too many future conflicts when syncing.

2024-12-20 16:02 UTC, daosbuild1 commented
Test stage NLT on EL 8.8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/20/execution/node/817/log

2024-12-21 00:56 UTC, daosbuild1 commented
Test stage NLT on EL 8.8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-14077/21/testReport/

2024-12-21 06:03 UTC, daosbuild1 commented
Test stage NLT on EL 8.8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-14077/23/testReport/

2024-12-22 10:25 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/23/execution/node/1425/log

2024-12-27 15:57 UTC, jolivier23 commented
Looks like it hit this warning: https://daosio.atlassian.net/browse/DAOS-16869

2025-01-01 17:26 UTC, jolivier23 commented
https://github.com/daos-stack/daos/pull/15667 was created to test this

2025-01-08 00:19 UTC, johannlombardi submitted a review, later dismissed

2025-01-10 19:56 UTC, wangdi1 submitted a review, later dismissed

2025-01-10 19:58 UTC, jolivier23 commented
Copyright warnings are wrong because it's only been merged this year.

2025-01-10 20:20 UTC, mchaarawi commented
let's get a review from release team before landing this

2025-01-10 20:35 UTC, mchaarawi approved these changes

2025-01-13 07:24 UTC, daosbuild1 commented
Test stage NLT on EL 8.8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-14077/34/testReport/

2025-01-14 01:29 UTC, ryon-jensen approved these changes

2025-01-14 05:40 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14077/34/execution/node/1425/log

2025-01-16 05:40 UTC, wangdi1 approved these changes

2025-01-16 05:53 UTC, merged