DAOS-15748 dfuse: Have pre read work with out-of-order I/O
daos-stack/daos pull request #14248
Opened 2024-04-25 08:05 UTC by ashleypittman

Skip-unit-tests: true
Skip-fault-injection-test: true
Test-tag: test_dfuse_pre_read
Test-repeat: 10

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

2024-04-25 16:37 UTC, daltonbohning reviewed
ftest LGTM

2024-04-25 16:37 UTC, daltonbohning commented on src/tests/ftest/dfuse/read.py
> +        the first file leave the flag enabled.
```suggestion
        the first file leaves the flag enabled.
```

2024-04-25 21:41 UTC, jolivier23 approved these changes

2024-04-26 08:58 UTC, johannlombardi approved these changes

2024-04-27 21:54 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14248/6/execution/node/1452/log

2024-04-27 23:40 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14248/6/execution/node/1406/log

2024-04-28 17:38 UTC, mchaarawi commented
why did you restart testing on this? 
why are you pushing in the queue as high priority?

2024-04-28 18:04 UTC, mchaarawi requested changes
blocking landing because of failed dfuse tests with `Features: dfuse` here
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-14248/6/tests
and master merge commit does not have that features tag. sorry.
also this ticket is not marked as required for 2.6 so you should not rebuild with P2.

2024-04-28 18:22 UTC, ashleypittman commented
> blocking landing because of failed dfuse tests with `Features: dfuse` here https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-14248/6/tests and master merge commit does not have that features tag.

This is a bug-fix for one of three dfuse tests which are currently failing.  This is one is an intermittent failure, https://github.com/daos-stack/daos/pull/14262 is for something which is always failing and https://github.com/daos-stack/daos/pull/14256 is intermittently failing for everyone, even without the dfuse tag.  Until we can get these three landed then `Features: dfuse` will be not pass and is causing wasted CI cycles.

2024-04-28 18:25 UTC, mchaarawi commented
> > blocking landing because of failed dfuse tests with `Features: dfuse` here https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-14248/6/tests and master merge commit does not have that features tag.
> 
> This is a bug-fix for one of three dfuse tests which are currently failing. This is one is an intermittent failure, #14262 is for something which is always failing and #14256 is intermittently failing for everyone, even without the dfuse tag. Until we can get these three landed then `Features: dfuse` will be not pass and is causing wasted CI cycles.

i disagree. it is required unless all extra tests with the Features tag are failing. just because some tests are failing does not mean you should not be using the features tag.

2024-04-28 18:29 UTC, mchaarawi commented
> > blocking landing because of failed dfuse tests with `Features: dfuse` here https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-14248/6/tests and master merge commit does not have that features tag.
> 
> This is a bug-fix for one of three dfuse tests which are currently failing. This is one is an intermittent failure, #14262 is for something which is always failing and #14256 is intermittently failing for everyone, even without the dfuse tag. Until we can get these three landed then `Features: dfuse` will be not pass and is causing wasted CI cycles.

and again https://daosio.atlassian.net/browse/DAOS-15748 is not required for 2.6 (and it really shouldn't block 2.6). so please respect the order of the testing queue like everyone else.

2024-04-28 18:56 UTC, mchaarawi commented
> This is a bug-fix for one of three dfuse tests which are currently failing. This is one is an intermittent failure, #14262 is for something which is always failing and #14256 is intermittently failing for everyone, even without the dfuse tag. Until we can get these three landed then `Features: dfuse` will be not pass and is causing wasted CI cycles.

afaik there is also a way in the commit pragma to exclude running a test with a particular tag if that is known to be failing (using the minus sign i believe).

2024-04-28 19:29 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14248/8/execution/node/1448/log

2024-04-29 16:54 UTC, ashleypittman commented
Failures look to be DAOS-15124.  Failures in previous build which ran with `Features: dfuse` are DAOS-15662, DAOS-15745, DAOS-15616 and DAOS-15747

2024-04-29 16:59 UTC, ashleypittman commented
> > afaik there is also a way in the commit pragma to exclude running a test with a particular tag if that is known to be failing (using the minus sign i believe).
> 
> That would be
> 
> ```
> Features: dfuse,-test_that_is_failing
> ```

I'll make a note of that, thank you.

2024-04-29 17:27 UTC, mchaarawi commented
> Failures look to be DAOS-15124. Failures in previous build which ran with `Features: dfuse` are DAOS-15662, DAOS-15745, DAOS-15616 and DAOS-15747

this is a lot of failures.. you stopped the previous build before it has completed, so it did not run fully and we do not know if there are other issues. As for the issue you linked:
15662 is resolved and should pass with rebase.
15748 is resolved
15745 is close to land
15747 is resolved

so that leaves 15616. I would suggest you wait till 15745 is landed, then rebase and rerun with the Feature tag excluding only the test from 15616.
removing gatekeeper request as my concern with testing is not addressed.

2024-05-01 20:36 UTC, merged