DAOS-15884 cart: Cleanup
daos-stack/daos pull request #14417
Opened 2024-05-22 05:53 UTC by frostedcmos

crt_launch now correctly sets D_PORT instead of deprecated OFI_PORT self_test client:
 - For non-daos usage (no agent), use default 0:0 endpoint instead of 0:2, as cart-level sample engines might not have tag=2, but are guaranteed to have at least 1 context
 - Remove deprecated singleton and nopmix options

Other:
- Remove crt_phy_addr_t, replace with char*
- Remove CRT_PHY_ADDR_ENV, OFI_PORT, OFI_DOMAIN, OFI_INTERFACE
- Remove sep related stuff
- Remove unimplemented crt_group_info_set/get

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2024-05-22 05:56 UTC, daosbuild1 commented
Test stage Build on Leap 15.5 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14417/1/execution/node/371/log

2024-05-22 06:03 UTC, daosbuild1 commented
Test stage Build RPM on EL 9 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14417/1/execution/node/359/log

2024-05-22 06:06 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14417/1/execution/node/327/log

2024-05-22 06:06 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15.5 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14417/1/execution/node/360/log

2024-05-22 06:12 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14417/1/execution/node/367/log

2024-05-22 17:04 UTC, daltonbohning reviewed
ftest LGTM

2024-05-23 22:05 UTC, soumagne approved these changes

2024-05-23 22:06 UTC, soumagne requested changes
looks good to me but you should fix the clang format (from the env var list).

2024-05-23 22:53 UTC, frostedcmos commented
> looks good to me but you should fix the clang format (from the env var list).

tried few different formats, including local formatting suggested by clang itself, but each time it is unhappy. so not sure what format to change this to

2024-05-23 22:59 UTC, daosbuild1 commented
Test stage NLT on EL 8.8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-14417/6/display/redirect

2024-05-28 19:31 UTC, soumagne approved these changes

2024-05-29 15:08 UTC, mchaarawi approved these changes

2024-05-29 15:46 UTC, merged