DAOS-16333 test: Disable the debug mask during rebuild in soak testing
daos-stack/daos pull request #14913
Opened 2024-08-12 13:38 UTC by mjean308

Skip-unit-tests: true
Skip-fault-injection-test: true
Test-tag: soak_smoke

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2024-08-12 13:43 UTC, mjean308 commented
This ticket was a recommendation from DAOS-15979.  When debug mask is enabled during a rebuild it can cause some rebuilds to never complete.    That issue is being worked in DAOS-16255.   In the mean time the debug mask will be disabled in soak rebuilds unless needed

2024-08-12 15:15 UTC, daltonbohning commented on src/tests/ftest/util/soak_utils.py
> +        self.dmg_command.server_set_logmasks("DEBUG", raise_exception=False)
FYI there is already logic for this per-pool:

https://github.com/daos-stack/daos/blob/bf0bedbc4f1a75ec42c057d56418dbe826b818eb/src/tests/ftest/pool/create_capacity.yaml#L50

And then used like this
https://github.com/daos-stack/daos/blob/bf0bedbc4f1a75ec42c057d56418dbe826b818eb/src/tests/ftest/util/test_utils_pool.py#L421
Where `self` is the pool object.


Do you only need this disabled for rebuild, or should it be disabled for other pool operations too?

2024-08-13 00:25 UTC, shimizukko approved these changes

2024-08-19 18:39 UTC, dinghwah submitted a review, later dismissed

2024-08-19 18:44 UTC, rpadma2 approved these changes

2024-08-19 18:59 UTC, phender requested changes

2024-08-19 18:59 UTC, phender commented on src/tests/ftest/util/soak_utils.py
> +        self.dmg_command.server_set_logmasks(raise_exception=False)
To ensure we put this setting back if we hit a test timeout while waiting for rebuild:
```suggestion
    finally:
        if self.enable_rebuild_logmasks:
            self.dmg_command.server_set_logmasks(raise_exception=False)
```

2024-08-19 20:17 UTC, shimizukko approved these changes

2024-08-20 15:13 UTC, merged