DAOS-14408 common: ensure NDCTL not used for storage class `ram`
daos-stack/daos pull request #15203
Opened 2024-09-26 12:57 UTC by grom72

NDCTL features can not be used with no-DCPM PMem (simulated PMem) PMEMOBJ_CONF=sds.at_create=0 disables NDCTL features in PMDK

Ensure ABT_THREAD_STACKSIZE>=20480 for dcpm storage class

dcpm storage class with NDCTL enabled requires at least 20480 stack size for ULT.

PR-repos: pmdk@PR-38:11
Priority: 2
Cancel-prev-build: false

Skip-nlt: false
Skip-unit-tests: false
Skip-func-test-vm: false
Skip-test-rpms: false
Allow-unstable-test: true
Skip-func-hw-test-large: false
Skip-func-hw-test-medium: false
Skip-func-hw-test-medium-verbs-provider: false

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2024-09-26 13:44 UTC, daosbuild1 commented
Test stage NLT on EL 8.8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-15203/1/testReport/

2024-10-15 12:50 UTC, janekmi requested changes

2024-10-15 15:48 UTC, grom72 commented on utils/rpms/daos.spec
> +
Fixed

2024-10-15 15:57 UTC, tanabarr approved these changes

2024-10-15 19:08 UTC, janekmi approved these changes

2024-10-16 00:25 UTC, kjacque approved these changes

2024-10-16 00:48 UTC, merged