DAOS-13559 vos: MD-on-SSD phase2 landing
daos-stack/daos pull request #15429
Opened 2024-10-30 02:04 UTC by NiuYawei

Landing MD-on-SSD phase2 branch to master.

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>
Signed-off-by: Sherin T George <sherin-t.george@hpe.com>
Signed-off-by: Niu Yawei <yawei.niu@intel.com>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2024-10-30 02:51 UTC, daosbuild1 commented
Test stage NLT on EL 8.8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-15429/1/testReport/

2024-10-30 11:43 UTC, tanabarr approved these changes, later dismissed

2024-10-30 13:10 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-15429/1/testReport/

2024-10-30 15:05 UTC, NiuYawei commented
@tanabarr any thoughts on the test failures? The two NLT memcheck failures looks are related to Go, are they known issue? The other two list_verbose.py failures are related to the new 'mem_file_bytes', will you fix that after this landed?

2024-10-30 15:33 UTC, brianjmurrell requested changes

2024-10-30 17:48 UTC, tanabarr commented
> @tanabarr any thoughts on the test failures? The two NLT memcheck failures looks are related to Go, are they known issue? The other two list_verbose.py failures are related to the new 'mem_file_bytes', will you fix that after this landed?

https://github.com/daos-stack/daos/pull/15405 addresses the `list_verbose.py` failures so if we have to re-push let's include that otherwise it can land to master after. I'm looking into the memcheck failures.

2024-10-30 17:48 UTC, tanabarr commented on debian/changelog
"file file"? could you please elaborate

2024-10-30 19:04 UTC, brianjmurrell commented on debian/changelog
Comment updated.

2024-10-30 19:48 UTC, jolivier23 submitted a review, later dismissed

2024-10-30 19:51 UTC, jolivier23 commented
> @tanabarr any thoughts on the test failures? The two NLT memcheck failures looks are related to Go, are they known issue? The other two list_verbose.py failures are related to the new 'mem_file_bytes', will you fix that after this landed?

Do you have the memcheck suppressions from master branch?   The race_amd64.s usually are handled by adding a new suppression but I'm surprised it would be different or MD on SSD branch.

2024-10-31 13:56 UTC, NiuYawei commented on debian/changelog
Isn't the following entry sufficient? (see the "Add DAV v2 lib" below).

2024-10-31 15:24 UTC, brianjmurrell commented on utils/rpms/daos.spec
Yes, both `%changelog` and `debian/changelog` entries should be at the top and should bump the `Release:` value in the `daos.spec` and the respective _version-release_ in the `debian/changelog` to +1 from the previous entry.  The existing entry in both of those files in this PR is actually duplicating/conflicting with an already used _version-release_: `2.5.100-10`.

The _version-release_ that should be used for this PR is `2.7.100-10`.

2024-11-01 01:38 UTC, NiuYawei commented on utils/rpms/daos.spec
Thanks! changelogs are updated.

2024-11-01 01:39 UTC, NiuYawei commented
> > @tanabarr any thoughts on the test failures? The two NLT memcheck failures looks are related to Go, are they known issue? The other two list_verbose.py failures are related to the new 'mem_file_bytes', will you fix that after this landed?
> 
> #15405 addresses the `list_verbose.py` failures so if we have to re-push let's include that otherwise it can land to master after. I'm looking into the memcheck failures.

I included your fix from #15405. Thanks!

2024-11-01 01:40 UTC, NiuYawei commented
> > @tanabarr any thoughts on the test failures? The two NLT memcheck failures looks are related to Go, are they known issue? The other two list_verbose.py failures are related to the new 'mem_file_bytes', will you fix that after this landed?
> 
> Do you have the memcheck suppressions from master branch? The race_amd64.s usually are handled by adding a new suppression but I'm surprised it would be different or MD on SSD branch.

I didn't add suppression since I'm not quite sure if they are caused by the new changes in control plane. Maybe we can fix them after this landed.

2024-11-01 07:00 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15429/2/display/redirect

2024-11-01 07:01 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15429/2/display/redirect

2024-11-01 14:07 UTC, tanabarr approved these changes, later dismissed

2024-11-01 14:09 UTC, tanabarr commented
@brianjmurrell do the build related changes look okay?

2024-11-01 14:17 UTC, phender requested changes

2024-11-01 14:17 UTC, phender commented on debian/changelog
> +daos (2.5.100-11) unstable; urgency=medium
This should be reverted
```suggestion
daos (2.5.100-10) unstable; urgency=medium
```

2024-11-01 18:46 UTC, tanabarr commented
> > @tanabarr any thoughts on the test failures? The two NLT memcheck failures looks are related to Go, are they known issue? The other two list_verbose.py failures are related to the new 'mem_file_bytes', will you fix that after this landed?
> 
> Do you have the memcheck suppressions from master branch? The race_amd64.s usually are handled by adding a new suppression but I'm surprised it would be different or MD on SSD branch.

yes the suppression 's file seems to be the same on both branches

2024-11-01 19:52 UTC, tanabarr commented
@NiuYawei @gnailzenh I've pushed again with the following fixes because the previously CI run failed to run the hardware stages because of Jenkins issues.

- Fixed changelog merge mistake identified by @phender 
- Updated test tags to
   Test-tag: pr daily_regression hw,medium,ListVerboseTest
    Skip-func-hw-test-medium-md-on-ssd: false
    Skip-func-hw-test-large-md-on-ssd: false
    Allow-unstable-test: true
- Removed two unnecessary changes on feature branch

2024-11-01 19:56 UTC, phender approved these changes
Ftest changes look good.

2024-11-01 21:31 UTC, tanabarr approved these changes

2024-11-02 05:02 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15429/3/display/redirect

2024-11-02 05:03 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15429/3/display/redirect

2024-11-02 05:03 UTC, daosbuild1 commented
Test stage Functional Hardware Medium MD on SSD completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15429/3/display/redirect

2024-11-02 05:05 UTC, daosbuild1 commented
Test stage Functional Hardware Large MD on SSD completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15429/3/display/redirect

2024-11-02 05:42 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15429/3/display/redirect

2024-11-02 09:21 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15429/4/display/redirect

2024-11-02 09:22 UTC, daosbuild1 commented
Test stage Functional Hardware Medium MD on SSD completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15429/4/display/redirect

2024-11-02 09:23 UTC, daosbuild1 commented
Test stage Functional Hardware Large MD on SSD completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15429/4/display/redirect

2024-11-02 09:26 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15429/4/display/redirect

2024-11-02 19:43 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15429/4/execution/node/584/log

2024-11-03 16:14 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15429/5/display/redirect

2024-11-03 16:44 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15429/5/display/redirect

2024-11-04 03:08 UTC, daosbuild1 commented
Test stage Functional Hardware Medium MD on SSD completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15429/5/execution/node/1064/log

2024-11-04 10:00 UTC, tanabarr commented
@NiuYawei @gnailzenh @phender 
I've been trying to get coverage over the weekend by rerunning to avoid the intermittent issue that stopping tests from starting. https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-15429/

Following builds all on tip of PR branch without any code changes between.

Build 4:
- Functional Hardware Large DID NOT RUN
- Functional Hardware Large MD-on-SSD DID NOT RUN
- Functional Hardware Medium failed with a single known issue DAOS-16768
- Functional Hardware Medium MD-on-SSD DID NOT RUN
- Functional Hardware Verbs Provider DID NOT RUN

Build 5:
- Functional Hardware Large DID NOT RUN
- Functional Hardware Large MD-on-SSD PASSED
- Functional Hardware Medium MD-on-SSD failed because of faulty hardware in cluster on wolf-217
- Functional Hardware Verbs Provider DID NOT RUN

Build 7:
- Functional Hardware Large ???
- Functional Hardware Medium MD-on-SSD ???
- Functional Hardware Verbs Provider ??? 

Summary:
- Functional Hardware Large ???
- Functional Hardware Large MD-on-SSD PASSED
- Functional Hardware Medium ACCEPTABLE
- Functional Hardware Medium MD-on-SSD ???
- Functional Hardware Verbs Provider ???

I don't think there is huge value in waiting for the verbs provider test results but maybe the other two from build 7?

2024-11-04 10:00 UTC, tanabarr commented on debian/changelog
> +daos (2.5.100-11) unstable; urgency=medium
done

2024-11-04 12:10 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15429/7/display/redirect

2024-11-04 12:53 UTC, gnailzenh approved these changes

2024-11-04 13:02 UTC, merged