DAOS-16877 client: implement utilities for shared memory
daos-stack/daos pull request #15613
Opened 2024-12-13 17:39 UTC by wiliamhuang

Features: shm

1. use tlsf as memory allocator
2. shared memory create/destroy
3. robust mutex in shared memory
4. hash table in shared memory

Required-githooks: true
Skipped-githooks: codespell

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2024-12-13 22:33 UTC, daosbuild1 commented
Test stage Functional on EL 8.8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/1/execution/node/1210/log

2024-12-23 15:17 UTC, wiliamhuang commented
Some component (e.g., hash table record reference count) will be revised later when we add more use cases.

2024-12-23 15:18 UTC, wiliamhuang commented
Currently we use tlsf memory allocator. It will be replaced by our own allocator in future.

2025-01-02 14:21 UTC, phender requested changes

2025-01-02 14:21 UTC, phender commented on src/tests/ftest/daos_test/shm.yaml
> +  control_method: daos
This isn't used by the test.  A typical cmocka test would use the `pool` entry information, but only when the test is run via `DaosCoreBase.run_subtest()`:
- https://github.com/daos-stack/daos/blob/master/src/tests/ftest/util/daos_core_base.py#L68-L69
- https://github.com/daos-stack/daos/blob/master/src/tests/ftest/util/daos_core_base.py#L89-L90

2025-01-06 16:10 UTC, wiliamhuang commented on src/tests/ftest/daos_test/shm.py
> +        cmocka_utils.run_cmocka_test(self, job)
@phender Thank you very much! I wrote shm.py and shm.yaml with dfuse.py and dfuse.yaml as templates. "shm_test" does not need to configure dmg command. Additional environment variables might be in added in futures tests with "daos_test_env" here.
Thank you for your tip of using "faults-enabled:  false". I will use it in future. I used "Features: shm" previously to run the new test.

2025-01-06 16:15 UTC, wiliamhuang commented on src/tests/ftest/daos_test/shm.yaml
> +  control_method: daos
The new test "shm_test" does not need scm_size and nvme_size information.

2025-01-07 17:45 UTC, daltonbohning commented on src/tests/ftest/daos_test/shm.yaml
> +  control_method: daos
I think what @phender means is since this test does not use `DaosCoreBase.run_subtest()`, the entire `pool` and `container` keys here are not used and can be removed

2025-01-07 17:45 UTC, daltonbohning commented on src/tests/ftest/daos_test/shm.yaml
> +  control_method: daos
... or if we use `DaosCoreBase.run_subtest()` we can keep it

2025-01-07 17:48 UTC, wiliamhuang commented on src/tests/ftest/daos_test/shm.yaml
> +  control_method: daos
@daltonbohning @phender Thank you very much! I will try removing pool and container keys locally to make sure it works. I thought they are required.

2025-01-07 17:55 UTC, wiliamhuang commented on src/tests/ftest/daos_test/shm.yaml
> +  control_method: daos
@daltonbohning @phender You are right. We can remove pool and container keys in yaml file as you suggested. I will update it in next commit. Thank you!

2025-01-08 15:08 UTC, knard38 reviewed
I have not yet finish the review process, but I still have several concerns and questions regarding this PR.

2025-01-08 15:08 UTC, knard38 commented on src/gurt/shm_alloc.c
> +		munmap(d_shm_head, d_shm_head->size);
From my understanding, all the process should `unmap` and then `close` the file.
The shared mmaped file content should be keept until the `unlink()` and `shm_unlink()` will be called.
Thus, not unmapping for the process creating the shared memory file seems to be useless.
I am also concerned that it could be seen as memoy leak by valgrind or other memory checker tools.

2025-01-08 16:52 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +			goto create_shm;
You are right. I will create a function for shm creation. Thank you!

2025-01-08 16:55 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +			MAP_SHARED | MAP_FIXED, shm_ht_fd, 0);
I agree. Fixed memory location is a strong limitation. It comes from the memory allocator we use. We could eliminate this limitation later once we have our own memory allocator supporting shared memory management.

2025-01-08 16:59 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +	close(shm_ht_fd);
The fd is not needed any more after calling mmap() in my impression, so you can close fd and still access shared memory.

2025-01-08 17:01 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +	shm_ht_fd = shm_open(daos_shm_name_buf, O_RDWR | O_CREAT | O_EXCL, shmopen_perm);
You are right. I will fix it. Thank you!

2025-01-08 17:05 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +			goto err_unmap;
I think it is not needed to destroy mutexes in shared memory since shared memory is not set up successfully. They will not be used.

2025-01-08 17:06 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +		DS_ERROR(errno, "shm_mutex_init() failed");
Same here. It is not needed to destroy mutexes in shared memory since shared memory is not set up successfully. They will not be used.

2025-01-08 17:11 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +		tid  = syscall(SYS_gettid);
I never used "pthread_self" before.
https://man7.org/linux/man-pages/man3/pthread_self.3.html

**The thread ID returned by pthread_self() is not the same thing as
 the kernel thread ID returned by a call to gettid.**

This syscall will be called only once. I would not worry about the overhead.

2025-01-08 17:14 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +	unlink(daos_shm_file_name);
You are right. I will replace unlink() with shm_unlink(). Thank you!

2025-01-08 17:15 UTC, daltonbohning commented on src/tests/ftest/daos_test/shm.py
> +"""
In general, yes. If the same test can be ran as a unit test (low cost, quick) instead of a functional test (higher cost, slower) then we should run it as a unit test

2025-01-08 17:25 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +		munmap(d_shm_head, d_shm_head->size);
Considering the cache in kernel space, I thought we may want to keep our cache persistent too. Otherwise, shared memory needs to be initialized again and again. Ideally, the space for caching would be freed after the content expires. We need our own shared memory allocator to dynamically expand/shrink shared memory region. It would be a long way to get there.
Yes. I did have a little concern about whether valgrind can detect the memory leak in shared memory usage here. I could play with valgrind to find out with simple test.

2025-01-08 17:34 UTC, wiliamhuang commented on src/tests/ftest/daos_test/shm.py
> +"""
@knard38 @daltonbohning Thank you very much! I will look into running this test as a unit test.

2025-01-08 17:49 UTC, wiliamhuang commented on src/tests/ftest/daos_test/shm.py
> +"""
Yes. Current tests are simple. They could fit as a unit test. More complex tests will be added in future. We can add shared memory related ftest later when we need.

2025-01-08 17:52 UTC, wiliamhuang commented on src/tests/ftest/daos_test/shm.py
> +"""
> @wiliamhuang , If it can help, I recently added some unit tests in the following PR: https://github.com/daos-stack/daos/pull/14713/files#diff-294ea4ccb7880cabe2a9a4ffadd3c709916da304a39a819c82f23bfe06197a61

@knard38 Thank you very much! It's very helpful.

2025-01-08 17:56 UTC, knard38 commented on src/gurt/shm_alloc.c
> +		shm_size = shm_pool_size * N_SHM_POOL + sizeof(struct d_shm_hdr);
In fact my remarks on aligning the `struct d_shm_addr` was to have a sizeof struct which will be a multiple of the `PAGE_SIZE` otherwise `shm_size` could be not a multiple of `PAGE_SIZE` from my understanding. Then the shared pools (following the header), could be not aligned on PAGE_SIZE (from my understanding).
However, I have not check that the align attribute will properly change the sizeof. I will check this asap.

2025-01-08 18:02 UTC, mchaarawi reviewed
just some quick comments.
still need to review more closely. will do that soon

2025-01-08 18:02 UTC, mchaarawi commented on src/tests/suite/SConscript
> +
i don't think you need a DAOS server to run those tests, right?
so probably adding those as unit tests in gurt will be more appropriate

2025-01-08 18:02 UTC, mchaarawi commented on src/include/gurt/shm_alloc.h
> +#include <stdint.h>
it's probably better to create 1 header for this rather than multiple public headers that users of this module need to always include.

2025-01-08 18:09 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +		shm_size = shm_pool_size * N_SHM_POOL + sizeof(struct d_shm_hdr);
"shm_size" does not have be a multiple of PAGE_SIZE. mmap() does not require size to be a multiple of PAGE_SIZE. The memory allocator will use some space in the pool too. I am not sure making shm_size a multiple of PAGE_SIZE will bring noticeable benefit. Maybe some performance tests could help to clarify later.

2025-01-08 18:24 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +open_rw:
I used "O_CREAT | O_EXCL" to make sure only one process will initialize shared memory. Without "O_EXCL" would allow more than one concurrent processes to initialize shared memory.

2025-01-08 18:39 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +			MAP_SHARED | MAP_FIXED, shm_ht_fd, 0);
You are right.
The requirement of using fix same address across processes is due to memory allocator we use. This is a quick and dirty way to allow us to use existing memory allocator for now. In future we need to implement our own memory allocator to natively support shared memory management, then the limitation could be removed.

2025-01-08 18:43 UTC, wiliamhuang commented on src/tests/suite/SConscript
> +
Right. Current tests are quite simple. DAOS server is not needed. I will change the tests as unit tests. We will add ftest later when necessary. Thank you!

2025-01-09 07:14 UTC, daosbuild1 commented
Test stage Unit Test with memcheck on EL 8.8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-15613/6/testReport/

2025-01-10 16:40 UTC, wiliamhuang commented on src/include/gurt/shm_alloc.h
> +#include <stdint.h>
Thank you very much! Just fixed it. Now only necessary APIs are exposed in this header file.

2025-01-14 17:32 UTC, daosbuild1 commented
Test stage Unit Test with memcheck on EL 8.8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-15613/14/testReport/

2025-01-15 09:55 UTC, knard38 commented on src/gurt/shm_alloc.c
> +			goto err_unmap;
Fair enough

2025-01-15 09:56 UTC, knard38 commented on src/gurt/shm_alloc.c
> +		DS_ERROR(errno, "shm_mutex_init() failed");
Fair enough

2025-01-15 14:59 UTC, knard38 commented on src/gurt/shm_alloc.c
> +		tid  = syscall(SYS_gettid);
Not fully agree with you on this, this function should be called for each memory allocation and thus its performance have some impact.  However, this point is not a blocker for me.

2025-01-15 15:09 UTC, knard38 commented on src/gurt/shm_alloc.c
> +		munmap(d_shm_head, d_shm_head->size);
Not sure that it will change something for the kernel cache to keep a dangling pointer when the process will die.
From my understanding what will make the difference is to unlink the file.
@mchaarawi do you have an opinion on this ?

2025-01-15 15:17 UTC, knard38 commented on src/gurt/shm_alloc.c
> +		shm_size = shm_pool_size * N_SHM_POOL + sizeof(struct d_shm_hdr);
From what I know it is indeed always better to have aligned memory for performance.
Moreover, from what I understand, the size really allocated by `mmap()` will be the same.
The only difference is that the padding will be added at the end of allocated memory instead of being between the `struct d_shm_hdr` and the first shm_pool.
In any case, this is not a blocker from my side.

2025-01-15 15:44 UTC, knard38 commented on src/include/gurt/shm_internal.h
From what I understand of the best DAOS practice, the internal header should not be located in the `src/include directory` to not be visible by the end user.  But I could be wrong on this point.

2025-01-15 15:44 UTC, knard38 commented on src/include/gurt/shm_internal.h
> +	/* array of pointors to memory allocators */
NIT
```suggestion
	/* array of pointers to memory allocators */
```

2025-01-15 15:44 UTC, knard38 commented on src/gurt/shm_dict.c
Instead of creating a new hash map, could it not be possible to update the current DAOS htable implementation with your shared memory new features ?

2025-01-15 15:53 UTC, wiliamhuang commented on src/gurt/shm_dict.c
I agree. I inclined to take current DAOS htable implementation and modify it to fit shared memory at the beginning. I decided to implement hash table in shared memory from scratch after I realized many parts are not compatible.

2025-01-15 16:05 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +		tid  = syscall(SYS_gettid);
I tested pthread_self() and syscall(SYS_gettid).

Hello from thread 1! tid_pthread_self = 140335788001024 SYS_gettid = 3023160
Hello from thread 2! tid_pthread_self = 140335779608320 SYS_gettid = 3023161
Hello from thread 3! tid_pthread_self = 140335771215616 SYS_gettid = 3023162
Hello from thread 4! tid_pthread_self = 140335762822912 SYS_gettid = 3023163

It looks like all tid_pthread_self are even number here. They are not evenly distributed to me. syscall(SYS_gettid) is only called once per thread instead of every memory allocation.

2025-01-15 16:10 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +		munmap(d_shm_head, d_shm_head->size);
One extreme case, the caching does not have any benefit at all if a user runs job serially in case we destruct caching once application ends.

2025-01-15 16:17 UTC, wiliamhuang commented on src/include/gurt/shm_internal.h
ok. I will move it to src/gurt. Thank you!

2025-01-15 16:18 UTC, wiliamhuang commented on src/include/gurt/shm_internal.h
> +	/* array of pointors to memory allocators */
A good catch. Thank you! Will fix it.

2025-01-17 13:04 UTC, knard38 commented on src/gurt/shm_dict.c
Fair enough, I will thus have a more in depth look to this file.

2025-01-17 13:09 UTC, knard38 commented on src/gurt/shm_alloc.c
> +		munmap(d_shm_head, d_shm_head->size);
Maybe, I am missing something, but if you remove the shared file then keeping a dangling pointer will not help if you have unlink the file.  On the other hand, if you do not unlink the file, the cache will still be available even if you do not have a dangling pointer at the end your applications.
However, it is perfectly that I am missing something.

2025-01-21 16:58 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +		munmap(d_shm_head, d_shm_head->size);
shm_destroy() is not called by regular applications. It was called only in the shm_test. The file associated with shared memory will not be unlinked.
I talked to Mohamad recently. He suggested daos_agent will initialize and destruct shared memory region. We will update it later.

2025-02-04 18:50 UTC, mchaarawi commented on src/gurt/shm_alloc.c
> +	/* map the shared memory at a fixed address for now. We will remove this limit later. */
can we add some more details for this in the comment as to why FIXED is needed for the allocator.

2025-02-04 18:50 UTC, mchaarawi commented on src/gurt/shm_alloc.c
> +			DS_ERROR(errno, "unexpected error shm_open()");
im curious why the need for retry in this case?
also this should be a warn not an error in this case.

2025-02-04 18:50 UTC, mchaarawi commented on src/gurt/shm_alloc.c
> +			MAP_SHARED | MAP_FIXED, shm_ht_fd, 0);
i am wondering if we should block on this before landing. im worried about this limitation and what issues can arise because of that.

2025-02-04 18:50 UTC, mchaarawi commented on src/gurt/shm_alloc.c
> +	close(shm_ht_fd);
if the descriptor is not needed after the mmap call, there is no need to keep it open. it's best close it to avoid leaks.

2025-02-04 18:50 UTC, mchaarawi commented on src/gurt/shm_alloc.c
> +		munmap(d_shm_head, d_shm_head->size);
not sure i quite understood the discussion. the cache needs to be persistent beyond one process lifetime and can be destroyed when the agent is killed.
but as i understand each procecss needs to call shm_open(), mmap(), close(), munmap() on the shared memory region, and only the agent calls shm_unlink().
the agent part can be done later.

2025-02-04 18:50 UTC, mchaarawi commented on src/gurt/shm_dict.c
i did attempt to do that myself too and got the same conclusion as Lei before.

2025-02-04 20:49 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +	/* map the shared memory at a fixed address for now. We will remove this limit later. */
ok. I will add more details as suggested. Thank you!

2025-02-04 21:24 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +			DS_ERROR(errno, "unexpected error shm_open()");
I thought retry might make the code more robust.
I just went through all possible errno returned by shm_open(). Retry should be not needed. I will change DS_ERROR to DS_WARN. Thank you!

2025-02-04 21:42 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +			MAP_SHARED | MAP_FIXED, shm_ht_fd, 0);
I agree that this fixed mapping address limit should be removed before landing to master. Maybe ok for feature branch? This would allow us to work on caching while we implement our own memory allocator.

2025-02-05 05:32 UTC, daosbuild1 commented
Test stage Build RPM on EL 9 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/17/execution/node/356/log

2025-02-05 05:33 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/17/execution/node/334/log

2025-02-05 05:34 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15.5 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/17/execution/node/357/log

2025-02-05 05:37 UTC, daosbuild1 commented
Test stage Build on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/17/execution/node/453/log

2025-02-05 05:47 UTC, daosbuild1 commented
Test stage Build on Leap 15.5 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/17/execution/node/519/log

2025-02-05 14:34 UTC, daosbuild1 commented
Test stage NLT on EL 8.8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-15613/19/testReport/

2025-02-05 16:08 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +			DS_ERROR(errno, "unexpected error shm_open()");
The retry code was removed. DS_ERROR is kept to log the error of shm_open().

2025-02-05 16:13 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +	unlink(daos_shm_file_name);
Fixed as suggested. Thank you!

2025-02-05 16:14 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +	shm_ht_fd = shm_open(daos_shm_name_buf, O_RDWR | O_CREAT | O_EXCL, shmopen_perm);
This is fixed. Thank you!

2025-02-05 16:15 UTC, wiliamhuang commented on src/include/gurt/shm_internal.h
Fixed as suggested. Thank you!

2025-02-05 16:15 UTC, wiliamhuang commented on src/include/gurt/shm_internal.h
> +	/* array of pointors to memory allocators */
This is fixed. Thank you!

2025-02-10 21:50 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15613/19/display/redirect

2025-02-12 08:44 UTC, knard38 commented on src/gurt/shm_dict.c
> +	ht_head_loc->n_bucket = n_bucket;
At least we should check if `n_bucket` is greater or equal than `n_lock`.
We could also check if `n_bucket % n_lock == 0` as it will ensure an even number of buckets per lock and also not need to use float to find the lock index.

2025-02-12 08:44 UTC, knard38 commented on src/gurt/shm_dict.c
> +	p_off_list = (long int *)((char *)p_ht_lock + sizeof(d_shm_mutex_t) * ht_head->n_lock);
seems to have concurrency issue with `shm_ht_destroy()` function.
The same apply for most of the other functions working on records and `get_shm_ht_with_name()` functions.

2025-02-18 17:45 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +		munmap(d_shm_head, d_shm_head->size);
Thank you!
To be clear, line 209,
"close(shm_ht_fd);"
It only frees the file descriptor.

2025-02-19 14:41 UTC, daosbuild1 commented
Test stage Build on Leap 15.5 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/20/execution/node/571/log

2025-02-19 16:02 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +	return 0;
Thank you! Now fd is closed here. After creating shared memory region, it returns immediately instead of calling munmap and mmap.

2025-02-19 16:03 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +	d_shm_head->magic         = DSM_MAGIC;
Thank you! This is fixed as you suggested.

2025-02-19 16:05 UTC, wiliamhuang commented on src/gurt/shm_dict.c
> +	*ht_head = shm_alloc(sizeof(struct d_shm_ht_head) + (sizeof(d_shm_mutex_t) * n_lock) +
Now error (EINVAL) is returned if hash table exists but with different parameters. Thank you!

2025-02-19 17:16 UTC, daosbuild1 commented
Test stage Build on Leap 15.5 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/21/execution/node/571/log

2025-02-21 07:00 UTC, daosbuild1 commented
Test stage Build on Leap 15.5 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/22/execution/node/571/log

2025-02-21 14:43 UTC, wiliamhuang commented on src/gurt/shm_dict.c
> +	p_off_list = (long int *)((char *)p_ht_lock + sizeof(d_shm_mutex_t) * ht_head->n_lock);
Thank you very much! I just made some improvements about possible issue of accessing hash table head.  I am working on mitigating the concurrency of hash table record. I will push my commit soon.

2025-02-28 06:49 UTC, daosbuild1 commented
Test stage Build on Leap 15.5 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/23/execution/node/571/log

2025-02-28 14:34 UTC, daosbuild1 commented
Test stage Build on Leap 15.5 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/24/execution/node/570/log

2025-02-28 15:09 UTC, daosbuild1 commented
Test stage Build on Leap 15.5 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/25/execution/node/385/log

2025-02-28 15:14 UTC, daosbuild1 commented
Test stage Build RPM on EL 9 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/25/execution/node/347/log

2025-02-28 15:15 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/25/execution/node/365/log

2025-02-28 15:16 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15.5 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/25/execution/node/354/log

2025-02-28 15:20 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15613/25/execution/node/353/log

2025-02-28 16:20 UTC, daosbuild1 commented
Test stage Unit Test on EL 8.8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-15613/27/testReport/

2025-02-28 16:58 UTC, daosbuild1 commented
Test stage Unit Test with memcheck on EL 8.8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-15613/27/testReport/

2025-03-01 06:36 UTC, daosbuild1 commented
Test stage Unit Test with memcheck on EL 8.8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-15613/28/testReport/

2025-03-05 13:43 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +	/* map the shared memory at a fixed address for now. We will remove this limit later. */
Fixed mapping address is not needed with updated tlsf memory alllocator.

2025-03-05 13:44 UTC, wiliamhuang commented on src/gurt/shm_dict.c
> +	ht_head_loc->n_bucket = n_bucket;
This is fixed as suggested. Thank you!

2025-03-05 13:46 UTC, wiliamhuang commented on src/gurt/shm_dict.c
> +	p_off_list = (long int *)((char *)p_ht_lock + sizeof(d_shm_mutex_t) * ht_head->n_lock);
Could you please review again? Thank you very much!
Now the memory of hash table head and records are not freed as long as the reference count is not zero.

2025-03-12 15:03 UTC, knard38 reviewed
The overall PR is OK for me.  The only blocker from my side is to check if the maximal value of the htable reference counter is acceptable for our use case.

2025-03-12 17:03 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +	d_shm_head->magic = 0;
Now memset() is used to zero the whole mapped region as you suggested. Thank you!

2025-03-12 17:04 UTC, wiliamhuang commented on src/gurt/shm_dict.c
> +		new_nref_htid = 0;
Fixed as you suggested. Thank you!

2025-03-12 17:04 UTC, wiliamhuang commented on src/gurt/shm_dict.c
> +	if (old_nref <= 0 && change < 0) {
Fixed as you suggested. Thank you!

2025-03-12 17:04 UTC, wiliamhuang commented on src/gurt/shm_dict.c
> +				if (old_nref <= 0 && change < 0) {
Fixed as you suggested. Thank you!

2025-03-12 17:19 UTC, knard38 commented on src/gurt/shm_alloc.c
> +	d_shm_head->magic = 0;
In fact, it was an error from my side as I was expecting `mmap` to fill the mapped memory with zero.
After more investigation , it appears that it is done only with the `MAP_ANONYMOUS` flag which is not compatible with using a file descriptor.
At the end, using `memset()` or your assignment is OK for me.
However, to avoid some race conditions I will switch the lines 85 and 86:
```c
	memset(shm_addr, 0, shm_size);
	d_shm_head = (struct d_shm_hdr *)shm_addr;
```

2025-03-12 17:53 UTC, wiliamhuang commented on src/gurt/shm_alloc.c
> +	d_shm_head->magic = 0;
Thank you very much! These lines are reordered.

2025-03-12 17:56 UTC, wiliamhuang commented on src/gurt/shm_dict.c
> +#define NREF_MASK     (0xFFFF000000000000L)
Now the lower 40 bits are allocated for ht id and 24 bits are for reference count.

2025-03-13 08:08 UTC, knard38 approved these changes
LGTM

2025-03-13 12:12 UTC, mchaarawi approved these changes
looks good to me overall. 1 thing i still like to see done, perhaps in a follow on PR, is move all the shm headers in gurt to 1 directory to not have 4 shm* headers in the gurt main dir. so i would suggest either:
1) 1 header in gurt
2) 1 dir in gurt called shm/; with all the headers in there (similar for the utilities implementation in the .c files).

2025-03-13 12:23 UTC, wiliamhuang commented
> looks good to me overall. 1 thing i still like to see done, perhaps in a follow on PR, is move all the shm headers in gurt to 1 directory to not have 4 shm* headers in the gurt main dir. so i would suggest either:
> 
> 1. 1 header in gurt
> 2. 1 dir in gurt called shm/; with all the headers in there (similar for the utiliti

Thank you! I will do this in the robust readers-writer lock PR.

2025-03-13 12:27 UTC, mchaarawi commented
even though this is to a feature branch, the PR must be green (all linting and builds, tests passing).

2025-03-13 12:28 UTC, mchaarawi commented
> even though this is to a feature branch, the PR must be green (all linting and builds, tests passing).

we know there is an issue with GHA arm builds since there are no runners, but others should be pass i believe.

2025-03-13 12:49 UTC, mjmac reviewed
Is there any plan to unify this work with the shm management in the telemetry library? https://github.com/daos-stack/daos/blob/master/src/gurt/telemetry.c

Not suggesting that should be a hard requirement, but it seems like it would be a miss to wind up with two completely separate designs and implementations in the codebase.

cc @kjacque

2025-03-13 13:32 UTC, mchaarawi commented
> > > even though this is to a feature branch, the PR must be green (all linting and builds, tests passing).
> > 
> > 
> > we know there is an issue with GHA arm builds since there are no runners, but others should be pass i believe.
> 
> codespell check: the issues reported are not from this PR. copyright check: The major code of src/gurt/shm_tlsf.c and src/include/gurt/shm_tlsf.h are from https://github.com/mattconte/tlsf, so I did not add the HPE copyright. Clang format check: Most of them seems not necessary.

ok for the first 2. Clang is required on all PRs, so unfortunately you have to fix it.
note that if you think a code block looks bad with clang formatting you can add the clang format off / on around the code block to disable clang checks. but it has to pass on the PR.

2025-03-13 13:38 UTC, wiliamhuang commented
> ok for the first 2. Clang is required on all PRs, so unfortunately you have to fix it. note that if you think a code block looks bad with clang formatting you can add the clang format off / on around the code block to disable clang checks. but it has to pass on the PR.

ok. I will fix the clang format issues. Thank you!

2025-03-14 05:32 UTC, wiliamhuang commented
Pushed two commits to fix clang format issues. Now clang format is green.

2025-03-14 20:42 UTC, johannlombardi approved these changes
lgtm

2025-03-17 11:46 UTC, merged