DAOS-16630 control: improve dmg pool exclude
daos-stack/daos pull request #15668
Opened 2024-12-28 08:57 UTC by wangshilong

When invoking “dmg pool exclude”, an administrator may not be aware of whether this will break the pool-wise RF or not. If this breaks the pool-wise RF, there may be data loss. Hence, we should perform the pool-wise RF check (i.e., the pw_rf check in pool_svc_update_map_internal) before changing the pool map.

On the other hand, the administrator may also want to exclude rank/targets even if there may be data loss. We should introduce a new, explicit option for the administrator to say that she’s aware of the danger and would like to bypass the pool-wise RF check.

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2024-12-28 23:51 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15668/1/display/redirect

2024-12-30 09:16 UTC, daosbuild1 commented
Test stage Unit Test on EL 8.8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-15668/2/testReport/

2024-12-30 20:47 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15668/2/execution/node/1559/log

2025-01-06 04:55 UTC, liw commented on src/pool/srv_pool.c
> +	if (opc == MAP_EXCLUDE && (src == MUS_SWIM || !skip_rf_check)) {
[Question] IIRC, `src` was introduced for the `dmg pool exclude` case. Could we remove `src`, `MUS_DMG`, and `MUS_SWIM` now that we have `skip_rf_check`?

2025-01-06 04:55 UTC, liw commented on src/pool/srv_pool.c
> +			       DP_UUID(svc->ps_uuid), tgt_addrs->pta_number, failed_cnt);
Should we remove "SWIM" from the log message instead? For instance, "exclude %d ranks: %d failed nodes\n".

2025-01-06 16:13 UTC, daltonbohning requested changes
I think we need a test to verify the new behavior. Also, copyrights need updating
If you merge latest master and install the githooks, it should handle the copyright now
https://github.com/daos-stack/daos/tree/master/utils/githooks#readme
I.e.
> git config core.hookspath utils/githooks

2025-01-06 16:13 UTC, daltonbohning commented on src/tests/ftest/util/dmg_utils.py
> +            force (bool): force exclusion regardless of data loss
nit - we usually put the default value in the docstring as well
```suggestion
            force (bool, optional): force exclusion regardless of data loss. Defaults to False
```

2025-01-06 16:13 UTC, daltonbohning commented on src/tests/ftest/util/test_utils_pool.py
> +        return self.dmg.pool_exclude(self.identifier, ranks, tgt_idx, force=True)
This maintains previous behavior, but we should have some test to verify force=False behaves as expected

2025-01-06 16:13 UTC, daltonbohning commented on src/control/cmd/dmg/pool_test.go
> +			"pool exclude -f 031bcaf8-f0f5-42ef-b3c5-ee048676dceb --rank 0 --target-idx 1,2,3",
This maintains previous behavior, but we should have some test to verify force=False behaves as expected

2025-01-07 01:55 UTC, wangshilong commented on src/pool/rpc.h
> +	((uint32_t)			(pti_flags)		CRT_VAR)
We've already bumped it for 2.8..so we won't bump It again. It looks this PR could not be added to 2.6.

2025-01-07 01:56 UTC, wangshilong commented on src/pool/srv_pool.c
> +	if (opc == MAP_EXCLUDE && (src == MUS_SWIM || !skip_rf_check)) {
Indeed, I'll try to remove src.

2025-01-07 01:59 UTC, wangshilong commented on src/pool/cli.c
> +				    POOL_TGT_UPDATE_SKIP_RF_CHECK);
In some cases eg Nvme-faulty case, server will try to call pool exclude, in this case now we always try to skip RF check.

2025-01-07 10:11 UTC, tanabarr submitted a review, later dismissed
LGTM, notwithstanding existing requests for change

2025-01-09 00:53 UTC, kjacque reviewed
Go side LGTM

2025-01-09 13:57 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15668/6/execution/node/1514/log

2025-01-09 15:55 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15668/6/execution/node/1451/log

2025-01-09 21:19 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15668/6/execution/node/1467/log

2025-01-16 07:11 UTC, liw approved these changes

2025-01-16 07:11 UTC, liw commented on src/pool/rpc.h
> +	((uint32_t)			(pti_flags)		CRT_VAR)
Thanks for checking.

2025-01-16 07:11 UTC, liw commented on src/pool/cli.c
> +				    POOL_TGT_UPDATE_SKIP_RF_CHECK);
Looks okay for now...

2025-01-16 07:55 UTC, liuxuezhao requested changes

2025-01-16 07:55 UTC, liuxuezhao commented on src/pool/rpc.h
> -
sorry did not check it intime.
But why you remove this? this is I added that try to leave for future usage for rebuild's error handling to differentiate the source of trigger the rebuild.

2025-01-16 07:58 UTC, liuxuezhao commented on src/pool/rpc.h
> -
Current rebuild err handling need some refining, for example ds_pool_tgt_revert_rebuild() cannot do it for some cases, so I added the source to try to provide some more info to make it possible to refine the err handling in future.

2025-01-16 08:10 UTC, wangshilong commented on src/pool/rpc.h
> -
I was not aware of that, i thought it is not used anymore, let's add it back.

2025-01-16 08:10 UTC, liuxuezhao commented on src/pool/srv_pool.c
> -	if (src == MUS_SWIM && opc == MAP_EXCLUDE) {
the original intention of adding src is not only for this usage.
Will pass that info to rebuild to differenciate err handling. One example is current ds_pool_tgt_revert_rebuild() is incorrect if the rebuild is triggered by CSUM scrubber.

2025-01-16 08:15 UTC, liw commented on src/pool/srv_pool.c
> -	if (src == MUS_SWIM && opc == MAP_EXCLUDE) {
@wangshilong, sorry, I didn't know `src` will be used for other purposes, and was only thinking that having both `src` and `skip_rf_check` would create 4 different cases instead of the 2 we currently need. My apologies.

2025-01-16 08:17 UTC, wangshilong commented on src/pool/srv_pool.c
> -	if (src == MUS_SWIM && opc == MAP_EXCLUDE) {
No problem, let me add this parameter back for future usage.

2025-01-16 08:26 UTC, liuxuezhao approved these changes
nevermind, for the src it is not difficult to add it later when needed.

2025-01-16 08:27 UTC, liuxuezhao commented on src/pool/srv_pool.c
> -	if (src == MUS_SWIM && opc == MAP_EXCLUDE) {
No problem, looks fine to keep it as it now. I can add it back later when needed, to save retest time.

2025-01-16 09:05 UTC, wangshilong commented
> nevermind, for the src it is not difficult to add it later when needed.

I was aware new added test cases was not tested with flag, refresh to fix copyright and address this too.

2025-01-16 09:19 UTC, liuxuezhao commented on src/pool/srv_pool_scrub_ult.c
> + * (C) Copyright 2021-2022 Intel Corporation.
may need minor fix if you refresh it later.

2025-01-16 09:19 UTC, liuxuezhao commented on src/pool/srv_pool.c
> +	if (!skip_rf_check) {
this block of code seems only need to execute if "opc == MAP_EXCLUDE"?

2025-01-16 09:26 UTC, liuxuezhao commented on src/pool/srv_pool.c
> +				&out->peo_op.po_map_version, &out->peo_op.po_hint, MUS_DMG, false);
POOL_EXTEND seems will never cause RF broken so last parameter can be true.
If you check opc == EXCLUDE inside pool_svc_update_map_internal then either is fine.

2025-01-16 09:56 UTC, wangshilong commented on src/pool/srv_pool.c
> +	if (!skip_rf_check) {
No, admin could force to skip this check...that is what this PR intent to do.

2025-01-16 11:57 UTC, wangshilong commented on src/pool/srv_pool.c
> +				&out->peo_op.po_map_version, &out->peo_op.po_hint, MUS_DMG, false);
A second think...It might be ok to proceed, in the broken case, rebuild might hang until restarting dead engines..Let me change it to true always.

2025-01-16 13:24 UTC, liuxuezhao commented on src/pool/srv_pool.c
> +	if (!skip_rf_check) {
the "--force" option is added to "dmg pool exclued" right? so it is still only for opc == MAP_EXCLUDE, I mean "if (!skip_rf_check && opc == MAP_EXCLUDE)", for other operation like EXTEND/REINT/DRAIN all need not to execute the code block?

2025-01-16 13:33 UTC, liuxuezhao approved these changes

2025-01-16 14:07 UTC, wangshilong commented on src/pool/srv_pool.c
> +	if (!skip_rf_check) {
Fixed.

2025-01-16 14:12 UTC, liuxuezhao commented on src/pool/srv_pool.c
> +	if (!skip_rf_check) {
Thx, not really a problem, I checked the code you added explicit flag parameter and set it as false for DRAIN/REINT/EXTEND. But not harmful to add the opc check.

2025-01-16 14:12 UTC, liuxuezhao submitted a review, later dismissed

2025-01-16 17:10 UTC, daltonbohning reviewed
Thanks for adding a test. Just some minor ftest changes. I also pushed a commit with my ftest suggestions for convenience
https://github.com/daos-stack/daos/commit/1c69dbc2555394755cd0142d4d4d672c6577bc6e

2025-01-16 17:10 UTC, daltonbohning commented on src/tests/ftest/util/test_utils_pool.py
> +        return self.dmg.pool_exclude(self.identifier, ranks, tgt_idx, force=True)
Can we pass this argument through the function please? I.e.
`def exclude(self, ranks, tgt_idx=None, force=True):`
Not that we need to handle on this PR, but ideally tests should only use force if needed, so adding the argument means new tests can choose

2025-01-16 23:41 UTC, wangshilong commented
> Thanks for adding a test. Just some minor ftest changes. I also pushed a commit with my ftest suggestions for convenience [368a1c5](https://github.com/daos-stack/daos/commit/368a1c5b227d6c32bac88a5c8edb343936d91ec7)

Thanks @daltonbohning , I pulled your commit with extra tags in the commit to make sure test run.

2025-01-16 23:44 UTC, daltonbohning reviewed
ftest LGTM. thanks!

2025-01-17 00:33 UTC, daosbuild1 commented
Test stage NLT on EL 8.8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-15668/13/testReport/

2025-01-17 06:20 UTC, liw approved these changes

2025-01-20 14:51 UTC, liuxuezhao approved these changes

2025-01-21 09:24 UTC, tanabarr approved these changes
Go changes LGTM

2025-01-22 07:11 UTC, merged