DAOS-16766 container: don't create for cont lookup
daos-stack/daos pull request #15670
Opened 2024-12-31 01:33 UTC by wangshilong

If container is not found from LRU, that means it was evicted from cache. This should only happens on container stopped or destroyed. don't create it again to avoid any race.

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2025-01-07 01:38 UTC, NiuYawei requested changes

2025-01-07 01:38 UTC, NiuYawei commented on src/container/srv_target.c
> +			       ds_cont);
The comment & code in cont_child_stop() will be incorrect due to this change, please modify cont_child_stop() accordingly.

2025-01-14 08:44 UTC, Nasf-Fan commented on src/container/srv_target.c
> -	if (cont_child_started(cont_child)) {
Consider `ds_cont_local_open()` for rebuild, the cleanup logic may call `cont_child_stop()` with `cont_child_started()` as false. So here, removing the condition check maybe unsafe?

2025-01-17 07:26 UTC, NiuYawei approved these changes

2025-01-17 07:26 UTC, NiuYawei commented on src/container/srv_target.c
> -	if (cont_child_started(cont_child)) {
As long as cont_child_stop() is always called for an started cont, and cont_child_stop() won't be called twice for an started cont, I think we should be fine.

@Nasf-Fan , does your example break above two consumptions?

2025-01-20 14:09 UTC, Nasf-Fan approved these changes

2025-01-20 14:09 UTC, Nasf-Fan commented on src/container/srv_target.c
> -	if (cont_child_started(cont_child)) {
> As long as cont_child_stop() is always called for an started cont,
Here, we removed the condition check, then it is the caller to guarantee that.

2025-01-22 07:08 UTC, merged