DAOS-14011 rebuild: incremental reintegrate patch sets
daos-stack/daos pull request #15671
Opened 2024-12-31 07:23 UTC by liuxuezhao

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

2025-01-08 10:00 UTC, daosbuild1 commented
Test stage Build on Leap 15.5 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15671/2/execution/node/559/log

2025-01-12 11:21 UTC, liuxuezhao commented
the 1st commit is from @Nasf-Fan 's PR https://github.com/daos-stack/daos/pull/15605 
other commits is incremental reint code
will rebase after fanyong's PR landed later.

2025-01-13 10:14 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15671/5/execution/node/1342/log

2025-01-13 17:06 UTC, daltonbohning commented
> removed request for https://github.com/orgs/daos-stack/teams/ftest-watchers, https://github.com/orgs/daos-stack/teams/ftest-owners, https://github.com/orgs/daos-stack/teams/object-owners and https://github.com/orgs/daos-stack/teams/object-watchers

Why are you manually removing review requests from codeowners? The whole point is to make sure there are reviews for each area of code

2025-01-13 17:10 UTC, daltonbohning commented on src/tests/ftest/util/server_utils_params.py
> +            "DAOS_VOS_AGG_GAP=25",
We need to consider whether this actually belongs in test code because it means we will not be testing what is used in production

2025-01-13 22:53 UTC, liuxuezhao commented
> > removed request for https://github.com/orgs/daos-stack/teams/ftest-watchers, https://github.com/orgs/daos-stack/teams/ftest-owners, https://github.com/orgs/daos-stack/teams/object-owners and https://github.com/orgs/daos-stack/teams/object-watchers
> 
> Why are you manually removing review requests from codeowners? The whole point is to make sure there are reviews for each area of code

the test code was added by Fanyong's PR, this PR just add it temporally and will rebase it lafter after this PR landed. 
My PR did not add such code. it was explained above.

2025-01-13 23:03 UTC, daltonbohning commented
> > > removed request for https://github.com/orgs/daos-stack/teams/ftest-watchers, https://github.com/orgs/daos-stack/teams/ftest-owners, https://github.com/orgs/daos-stack/teams/object-owners and https://github.com/orgs/daos-stack/teams/object-watchers
> > 
> > 
> > Why are you manually removing review requests from codeowners? The whole point is to make sure there are reviews for each area of code
> 
> the test code was added by Fanyong's PR, this PR just add it temporally and will rebase it lafter after this PR landed. My PR did not add such code. it was explained above.

Sorry for missing that - and I didn't mean to sound so harsh, now that I reread it...

2025-01-15 06:36 UTC, Nasf-Fan requested changes

2025-01-15 06:36 UTC, Nasf-Fan commented on src/container/srv_container.c
> +	/* Only should update local stable epoch if the target is in UPIN status */
For the target with `PO_COMP_ST_UP` status, should we consider its local stable epoch?

2025-01-15 06:36 UTC, Nasf-Fan commented on src/container/srv_container.c
> +			ds_pool_put(pool);
`pool` is NULL here.

2025-01-15 06:36 UTC, Nasf-Fan commented on src/container/srv_container.c
> +			new_eph = d_hlc2sec(min_ec_agg_eph);
Does it only affect ec_agg_epoch or also stable_epoch?

2025-01-15 06:36 UTC, Nasf-Fan commented on src/container/srv_target.c
> +	rc = dss_ult_create(cont_tgt_track_eph_init_ult, cont_child, DSS_XS_SELF,
cont_tgt_track_eph_init_ult() will create another ULT cont_track_eph_init_ult(), why need two ULTs for that?

2025-01-15 06:36 UTC, Nasf-Fan commented on src/container/srv_target.c
> +				    min_stable_eph <= ec_eph->cte_last_stable_epoch)
Why EC_agg_epoch/stable_epoch cannot keep unchanged between two cycle checks? I think that is normal instead or ERROR().

2025-01-15 06:36 UTC, Nasf-Fan commented on src/container/srv_target.c
> +		sched_req_sleep(pool->sp_ec_ephs_req, EC_TGT_EPH_QUERY_INTV);
That means per-5 seconds, current engine will report its local stable epoch (per-ppol) to the leader, right?

2025-01-15 06:36 UTC, Nasf-Fan commented on src/vos/vos_container.c
> +	}
That seems unnecessary since for old pool either `cont_ext` is NULL or `cont_ext->ced_global_stable_epoch` is not set by default.

2025-01-15 07:45 UTC, liuxuezhao reviewed
thanks for review @Nasf-Fan , will rebase later after your patch landed.

2025-01-15 07:45 UTC, liuxuezhao commented on src/container/srv_container.c
> +	/* Only should update local stable epoch if the target is in UPIN status */
here it is setting local's persistent global stable epoch, only UPIN node can set it. 
For reint it should rebuild from the local stored stable epoch before exclude it (still be UPIN).

The UP tgt reports its local epoch by query vos_cont_get_local_stable_epoch() in cont_aggregate_interval().

2025-01-15 07:45 UTC, liuxuezhao commented on src/container/srv_container.c
> +			ds_pool_put(pool);
maybe an issue when rebase, will fix it soon, thx

2025-01-15 07:45 UTC, liuxuezhao commented on src/container/srv_container.c
> +			new_eph = d_hlc2sec(min_ec_agg_eph);
this is to throw a warning if the EC agg epoch boundary is updated too slow (> 600S).

Both ec_agg_epoch and stable_epoch are considered by other code in this func

2025-01-15 07:45 UTC, liuxuezhao commented on src/container/srv_target.c
> +	rc = dss_ult_create(cont_tgt_track_eph_init_ult, cont_child, DSS_XS_SELF,
cont_tgt_track_eph_init_ult() execute on vos tgt main XS, it will execute cont_track_eph_init_ult on XS0. The pool->sp_ec_ephs_list only maintained (insert/lookup) on XS0

2025-01-15 07:45 UTC, liuxuezhao commented on src/container/srv_target.c
> +				    min_stable_eph <= ec_eph->cte_last_stable_epoch)
The D_ERROR() is just kept from original code, commonly should not get smaller epoch,  but better to change the <= to < same as before.

2025-01-15 07:45 UTC, liuxuezhao commented on src/container/srv_target.c
> +		sched_req_sleep(pool->sp_ec_ephs_req, EC_TGT_EPH_QUERY_INTV);
yes, reports each container's local stable epoch and ec agg epoch to leader per container.

2025-01-15 07:45 UTC, liuxuezhao commented on src/vos/vos_container.c
> +	}
that need some knowledge for example suing umem_zalloc() to allocate the vos_cont_ext_df. adding such explicit code looks harmless?

2025-01-15 08:11 UTC, Nasf-Fan commented on src/object/srv_obj_migrate.c
> +		ABT_rwlock_rdlock(pool->sp_lock);
Is it possible during current ULT being blocked on the lock, another ULT do the same check `if (!tls->mpt_reintegrating_check)` ?

2025-01-15 08:11 UTC, Nasf-Fan commented on src/object/srv_obj_migrate.c
> +				rc = vos_dtx_cmt_reindex(cont_child->sc_hdl);
It is unnecessary to reindex DTX if the opening container only for get the global stable epoch. On the other hand, since the global stable epoch is (at least) per-container, then we can pass it as one of the parameters for `migrate_obj_ult()` instead of loading it from VOS for every object again and again.

2025-01-15 08:11 UTC, Nasf-Fan commented on src/object/srv_obj_migrate.c
> +		} else {
unnecessary `else` since above `continue`.

2025-01-15 08:36 UTC, liuxuezhao commented on src/object/srv_obj_migrate.c
> +				rc = vos_dtx_cmt_reindex(cont_child->sc_hdl);
seems you are checking an older version, the call to vos_dtx_cmt_reindex removed already.
migrate_get_cont_child() is the original code maybe useful to detect if the cont destroy during rebuild WIP.

2025-01-15 08:37 UTC, liuxuezhao commented on src/object/srv_obj_migrate.c
> +		} else {
right, it can be removed.

2025-01-15 10:29 UTC, Nasf-Fan commented on src/object/srv_obj_migrate.c
> +		goto out;
How to handle the following case: a 2-way object, related servers on which the two shards reside are both offline for some reason almost at the same time, then nobody update such object after that, and then when we reint the two servers, we should keep such 2-way object, right? Does current logic support that? Here, we need to discard such object, right?

2025-01-15 13:55 UTC, liuxuezhao commented on src/object/srv_obj_migrate.c
> +		goto out;
right, this is a known issue to me. I wanted to discuss with you at weekly meeting but did not get time.
One explanation is with RP2 obj then RF <= 1, then losing 2 engines cannot ensure no data lose. But we should try the best to not lost data.
Anyway, we cannot handle everything in one patch, let's discuss and resolve it in following PR.

2025-01-17 03:16 UTC, daosbuild1 commented
Test stage NLT on EL 8.8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-15671/10/testReport/

2025-01-17 08:05 UTC, NiuYawei commented on src/object/srv_obj_migrate.c
> +	rc = vos_cont_open(iter_param->ip_hdl, entry->ie_couuid, &coh);
Here we intentionally call VOS interface to open the container? I think the ds_cont_child in container level should be in started state? Why don't we just lookup & use  ds_cont_child directly?

2025-01-17 08:48 UTC, liuxuezhao commented on src/container/srv_container.c
> +	/* Only should update local stable epoch if the target is in UPIN status */
yes, there is a time window between excluding and every tgt server get the new pool map.
But as long as this tgt is still UPIN in current poolmap, it will report its local stable epoch and on PS leader will ensure the global stable epoch will not exceed every UPIN tgt.
So here even in the time window that this engine with stable pool map still safe to update its local stored global stable epoch, right?

2025-01-17 08:48 UTC, liuxuezhao commented on src/container/srv_container.c
> +			rc = 0;
the refresh callback returned err code seems will cause some trouble at IV path.
the vos_cont_set_global_stable_epoch()'s err cases are -
1) -DER_NOTSUPPORTED on old pool, this can be ignored as will not change anyghing.
2) -DER_NO_PERM for invalid epoch for very cornel case, also can be ignored with err/warn log
3) umm tx fail, that will not change persistent value, seems err/warn log enough?
these cases seems adding log is enough, I don't want cart IV path ivo_on_refresh()'s failure case affect too much to whole IV path's handling.

2025-01-17 08:48 UTC, liuxuezhao commented on src/container/srv_container.c
> +			DP_UUID(pool_uuid), rc);
ok, will change to err

2025-01-17 08:48 UTC, liuxuezhao commented on src/container/srv_target.c
> +	rc = dss_ult_create(cont_tgt_track_eph_init_ult, cont_child, DSS_XS_SELF,
the pool->sp_ec_ephs_list only maintained on XS0, so create ULT and execute on XS0 need not take lock.
hmm, maybe need not create cont_tgt_track_eph_init_ult, just create cont_track_eph_init_ult on XS0, is this what you prefer?

2025-01-17 08:48 UTC, liuxuezhao commented on src/object/srv_obj_migrate.c
> +	rc = vos_cont_open(iter_param->ip_hdl, entry->ie_couuid, &coh);
I'll see if the ds_cont_child can be used, thx

2025-01-17 09:37 UTC, NiuYawei commented on src/container/srv_container.c
> +	/* Only should update local stable epoch if the target is in UPIN status */
hmm, on leader side, if a rank is DOWN, I think it'll be ignored when leader finding out the lowest stable epoch, right?

2025-01-17 09:37 UTC, NiuYawei commented on src/container/srv_target.c
> +	rc = dss_ult_create(cont_tgt_track_eph_init_ult, cont_child, DSS_XS_SELF,
Yes, I just don't see why we need to create a ULT for creating a ULT on sys xstream. This dss_ult_create() looks not necessary to me, it also makes cont_track_eph_insert() not being executed before cont_tgt_track_eph_init() returns, that looks not quite right to me.

2025-01-17 10:36 UTC, liuxuezhao commented on src/container/srv_container.c
> +	/* Only should update local stable epoch if the target is in UPIN status */
right, that case is - leader with latest pool map that tgt A is DOWN, will ignore its reports then global stable epoch can exceed A's local stable epoch.
But A itself with stable poolmap still think itself is UPIN.
But when leader try to refresh the stable epoch by cont_iv_track_eph_refresh(), the IV msg propogate will find group version mismatch and return -DER_GRPVER, and will retry the IV OP until grp ver matched on all nodes.
So far looks fine?

2025-01-17 10:36 UTC, liuxuezhao commented on src/container/srv_target.c
> +	rc = dss_ult_create(cont_tgt_track_eph_init_ult, cont_child, DSS_XS_SELF,
OK, i see, will change it. thx

2025-01-20 01:30 UTC, kccain reviewed
This patch will take some time to fully review. Got through the container/ code and some other files. Not so much the object/ code yet. I will take a look at the rest of the patch in a second chunk of work. For now, some preliminary comments since they may be helpful sooner as the patch may be revised soon.

2025-01-20 01:30 UTC, kccain commented on src/container/srv_target.c
> +						", "DF_X64"/"DF_X64", "DF_UUID"\n",
suggest output of the log message includes description of what the values are, such as "Skip ec_agg_eph " for the first two, and then "stable_eph" for the second two values

2025-01-20 02:27 UTC, NiuYawei commented on src/container/srv_container.c
> +	/* Only should update local stable epoch if the target is in UPIN status */
I see, I think we are good as long as the IV request with different pool map version can be rejected, thanks for the explanation.

2025-01-20 04:26 UTC, liuxuezhao commented on src/container/srv_target.c
> +	daos_epoch_t	*cte_stable_ephs;
ok

2025-01-20 04:26 UTC, liuxuezhao commented on src/container/srv_target.c
> +cont_track_eph_insert(struct ds_pool *pool, uuid_t cont_uuid, int tgt_idx,
the leader side was named as cont_track_eph_leader_alloc()/cont_track_eph_leader_lookup()/cont_track_eph_leader_delete() to differenciate.

2025-01-20 04:26 UTC, liuxuezhao commented on src/container/srv_target.c
> +cont_track_eph_fini_ult(void *data)
no "_leader_" in func name means tgt

2025-01-20 04:26 UTC, liuxuezhao commented on src/container/srv_target.c
> +cont_tgt_track_eph_fini(struct ds_cont_child *cont_child)
ditto

2025-01-20 04:26 UTC, liuxuezhao commented on src/container/srv_target.c
> +						", "DF_X64"/"DF_X64", "DF_UUID"\n",
sure

2025-01-20 04:26 UTC, liuxuezhao commented on src/include/daos_srv/container.h
> +	uint64_t		sc_stable_epoch;
sure

2025-01-20 04:26 UTC, liuxuezhao commented on src/pool/srv.c
> +	daos_incr_reint_enabled = false;
in cont_svc_eph_track_leader_start(), the ec_agg_disabled checked looks can be removed.
and I am going to remove DAOS_INCR_REINT_ENABLE and replace it by pool property

2025-01-20 04:30 UTC, liuxuezhao commented on src/vos/vos_container.c
> +	 * in the calculating new globle stable epoch. Then do not allow to set globle stable epoch.
fixed

2025-01-20 04:34 UTC, liuxuezhao commented on src/vos/vos_container.c
> +		D_WARN("Invalid global stable epoch: " DF_X64" vs " DF_X64 " for container "
ok

2025-01-20 09:43 UTC, liuxuezhao commented
comments from @Nasf-Fan , @NiuYawei and @kccain should all have been addressed, thx
the last commit is for adding a pool property to enable incr reint (the ENV removed).

2025-01-20 10:22 UTC, daosbuild1 commented
Test stage Unit Test on EL 8.8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-15671/13/testReport/

2025-01-21 02:48 UTC, Nasf-Fan approved these changes, later dismissed

2025-01-21 02:48 UTC, Nasf-Fan commented on src/vos/vos_container.c
> +	}
It is harmless but redundant, not fatal.

2025-01-21 09:20 UTC, tanabarr submitted a review, later dismissed
Go changes LGTM

2025-01-21 13:03 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15671/14/execution/node/1510/log

2025-01-21 18:32 UTC, kccain commented on src/container/srv_target.c
> +cont_track_eph_insert(struct ds_pool *pool, uuid_t cont_uuid, int tgt_idx,
OK I guess the code can remain this way. Based on the below analysis(which I did again now to make sure I have it right), it is why I had suggested a renaming of the insert/delete functions, but I guess it is OK.

- ds_cont_track_eph_free() is actually operating at the levbel of a pool (iterate over a list of containers, each represented by a struct cont_track_eph). But naming the function to begin with ds_pool might seem strange in this file.
- cont_track_eph_alloc() and cont_track_eph_destroy() seem pretty straightforward naming and operate at a container level for this engine. They create or destroy a struct cont_track_eph (this is at the level of the container in this engine).
- cont_track_eph_insert() is not straightfoward. It refers to both the whole struct cont_track_eph (a container in this engine), and also a specific target index within the engine. It might alloc/create a whole struct cont_track_eph, increments a cte_ref count for the struct (that was looked up or created), and returns pointers to ec_agg_eph and stable_eph values for a specific target index.
- cont_track_eph_delete() also not totally straightforward. It refers to a particular target index, but only manipulates struct cont_track_eph.cte_ref count at the container/engine level.

2025-01-21 18:36 UTC, kccain commented on src/container/srv_target.c
> +cont_track_eph_fini_ult(void *data)
The reason for the suggestion is that the ULT is executing for a specific target index. The concern was not about leader vs. other engine. Instead, the concern is distinguishing between whole engine and a specific target.

The function that creates this ULT has "tgt" in its name, so it probably makes sense for this function to have "tgt" too.

2025-01-22 00:42 UTC, kccain commented on src/container/srv_target.c
> +cont_track_eph_fini_ult(void *data)
oh but it's running on system XS, that's why tgt is not in the function name.

2025-01-22 01:23 UTC, kjacque reviewed
I only inspected the Go changes -- LGTM.

Leaving it to reviewers of the C code to officially approve.

2025-01-22 01:57 UTC, liuxuezhao commented
the codespell warning is all not related with this PR
Error: ./src/dtx/tests/dts_local_rdb.c:48: re-using ==> reusing
Error: ./src/control/server/mgmt_system.go:634: synthesise ==> synthesize
Error: ./src/gurt/examples/telem_producer_example.c:14: incremements ==> increments
Error: ./src/vea/vea_internal.h:189: aggergate ==> aggregate

2025-01-22 08:45 UTC, NiuYawei submitted a review, later dismissed

2025-01-22 10:56 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15671/21/execution/node/1447/log

2025-01-22 11:29 UTC, daosbuild1 commented
Test stage Functional Hardware Medium Verbs Provider completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-15671/21/execution/node/1476/log

2025-01-22 14:01 UTC, Nasf-Fan submitted a review, later dismissed

2025-01-23 06:30 UTC, NiuYawei approved these changes

2025-01-23 09:12 UTC, wangshilong approved these changes

2025-01-23 09:24 UTC, liuxuezhao commented
the "Linting / Codespell " check failed, but it is totally unrelated with my PR.
So may need force landing @gnailzenh @daos-stack/daos-gatekeeper

2025-01-23 16:43 UTC, gnailzenh approved these changes

2025-01-23 16:48 UTC, merged

2025-01-23 16:49 UTC, daltonbohning commented
> the "Linting / Codespell " check failed, but it is totally unrelated with my PR. So may need force landing @gnailzenh @daos-stack/daos-gatekeeper

Yep. Those snuck in somehow on files that haven't even changed. It's fixed now in master and 2.6