DAOS-5598: Add conditional fetch testing for MVCC
daos-stack/daos pull request #3386
Opened 2020-09-03 21:25 UTC by marcelarosalesj

Signed-off-by: Marcela Rosales <marcela.a.rosales.jimenez@intel.com>

2020-09-03 21:34 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3386/1/execution/node/60/log

2020-09-09 18:19 UTC, jolivier23 approved these changes

2020-09-09 18:34 UTC, jolivier23 requested changes

2020-09-09 18:34 UTC, jolivier23 commented on src/vos/tests/vts_mvcc.c
> +	{"fetch_dne",	T_R,	L_A,	L_NIL,	R_NE,	W_NIL,	fetch_dne_f},
this should be L_D

2020-09-09 19:09 UTC, marcelarosalesj commented on src/vos/tests/vts_mvcc.c
> +	{"fetch_dne",	T_R,	L_A,	L_NIL,	R_NE,	W_NIL,	fetch_dne_f},
right, good catch, I'll send the fix

2020-09-09 19:20 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3386/2/execution/node/60/log

2020-09-09 21:20 UTC, jolivier23 submitted a review, later dismissed

2020-09-10 14:20 UTC, jolivier23 commented on src/vos/tests/vts_mvcc.c
> +	{"fetch_dne",	T_R,	L_D,	L_NIL,	R_NE,	W_NIL,	fetch_dne_f},
Ok, @marcelarosalesj my bad.   Change it back to L_A since it does a read of the akey and with current logic it suffices.

2020-09-10 16:14 UTC, marcelarosalesj commented on src/vos/tests/vts_mvcc.c
> +	{"fetch_dne",	T_R,	L_D,	L_NIL,	R_NE,	W_NIL,	fetch_dne_f},
okay, I'll send the patch

2020-09-10 16:24 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3386/3/execution/node/60/log

2020-09-10 22:35 UTC, jolivier23 commented
Can you merge latest master to get checkpatch fix?

2020-09-11 07:12 UTC, liw approved these changes

2020-09-11 15:11 UTC, jolivier23 approved these changes

2020-09-11 17:14 UTC, merged