Fix an issue with reintegration.   The same target can have
daos-stack/daos pull request #3455
Opened 2020-09-15 22:28 UTC by jolivier23

multiple vos operations when a node is reintegrated.

Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>

2020-09-15 22:46 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-09-15 23:47 UTC, daosbuild1 commented
Test stage Functional on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3455/2/display/redirect

2020-09-16 01:13 UTC, daosbuild1 commented
Test stage Functional_Hardware_Small completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3455/2/display/redirect

2020-09-16 01:19 UTC, daosbuild1 commented
Test stage Functional_Hardware_Large completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3455/2/display/redirect

2020-09-16 01:20 UTC, daosbuild1 commented
Test stage Functional_Hardware_Medium completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3455/2/display/redirect

2020-09-22 20:15 UTC, jolivier23 commented
@Nasf-Fan I don't think this is the right fix given our discussions about the issue with multiple updates in same dtx to different shards.   Should I close it?   It did enable Byron's demo to be a bit more stable but probably not the right solution.

2020-09-23 03:59 UTC, Nasf-Fan requested changes

2020-09-23 03:59 UTC, Nasf-Fan commented on src/dtx/dtx_rpc.c
> +	if (drr->drr_count == drr->drr_max) {
If more than one shards locate on the same vos target, then we only need one DTX entry for that, so any time when we call dtx_cf_rec_update(), we can check whether current DTX ID is the same as "drr->drr_dti[drr->drr_count]", if yes, just skip current update.

I have made a patch for that:
https://github.com/daos-stack/daos/pull/3506

2020-09-28 19:09 UTC, closed without merging