DAOS-5579 doc: removed warning on parallel libdfs use
daos-stack/daos pull request #3465
Opened 2020-09-17 08:20 UTC by Michael-Hennecke

The POSIX section of the User Guide contained a warning to
not used libdfs from multiple nodes/processes. Removed this
warning, and now state that parallel usage is possible.
Listed some of the remaining corner cases as limitations.

Signed-off-by: Michael Hennecke <mhennecke@lenovo.com>

2020-09-17 09:16 UTC, bfaccini submitted a review, later dismissed

2020-09-17 13:52 UTC, mchaarawi submitted a review, later dismissed

2020-09-17 16:38 UTC, jolivier23 requested changes
Needs a conflict resolution

2020-09-18 13:41 UTC, mchaarawi approved these changes

2020-09-18 19:51 UTC, jolivier23 approved these changes

2020-09-18 19:51 UTC, merged