DAOS-5435: weekly-testing: IorIntercept: test_ior_intercept: IOR command issued warnings
daos-stack/daos pull request #3570
Opened 2020-09-30 18:42 UTC by cibervicho

DAOS-5435: weekly-testing: IorIntercept: test_ior_intercept: IOR command issued warnings

'ior' command uses the -D optional argument to specify the number of seconds
before stopping a read or write phase. If for some reason the data written or read
takes longer than the seconds allowed by this parameter the test logs WARNING
messages and finally fails the test.

Being exposed that, an optional boolean parameter named 'fail_on_warning' was introduced
in the run_ior_with_pool() function to control whether the test should fail or not.
In order to test the correct behavior of this parameter, the test 'ior_fail_on_warning.py'
was added too.

Test-tag: iorfailonwarning
Test-tag-hw-small: iorfailonwarning

Signed-off-by: David Maldonado Moreno <david.maldonado.moreno@intel.com>

2020-09-30 19:00 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3570/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/882cd41ecfec0a434ea75698e1d148785728ba1c/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-09-30 19:00 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/1/execution/node/60/log

2020-09-30 20:33 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3570/1/display/redirect

2020-09-30 22:23 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3570/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/882cd41ecfec0a434ea75698e1d148785728ba1c/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-09-30 22:23 UTC, daosbuild1 commented on src/tests/ftest/io/ior_fail_on_warning.py
> +
(style)  trailing whitespace

2020-09-30 22:23 UTC, daosbuild1 commented on src/tests/ftest/io/ior_fail_on_warning.py
> +        except:
(pylint-bare-except) No exception type(s) specified

2020-09-30 22:23 UTC, daosbuild1 commented on src/tests/ftest/io/ior_fail_on_warning.py
> +
```suggestion

```

2020-09-30 22:23 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/2/execution/node/60/log

2020-10-01 16:59 UTC, cibervicho commented on src/tests/ftest/io/ior_fail_on_warning.py
> +
Done

2020-10-01 16:59 UTC, cibervicho commented on src/tests/ftest/io/ior_fail_on_warning.py
> +
Done

2020-10-01 17:47 UTC, cibervicho commented on src/tests/ftest/io/ior_fail_on_warning.py
> +        except:
Done.

2020-10-01 18:08 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3570/3/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/6b85df7f3bddf7987bdf2b92abb13314e268c349/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-01 18:08 UTC, daosbuild1 commented on src/tests/ftest/io/ior_fail_on_warning.py
> +from ior_utils import IorCommand
(pylint-unused-import) Unused IorCommand imported from ior_utils

2020-10-01 18:08 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/3/execution/node/61/log

2020-10-01 19:44 UTC, cibervicho commented on src/tests/ftest/io/ior_fail_on_warning.py
> +from ior_utils import IorCommand
Done

2020-10-01 20:04 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/6731e092468701e90b2a03f6af853d16b27aea8b/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-01 22:04 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/083bbc42a0527c723cda6ed1118129010e1785a9/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-02 00:50 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/5/execution/node/867/log

2020-10-02 18:14 UTC, daosbuild1 commented
Test stage Functional_Hardware_Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/5/execution/node/1001/log

2020-10-05 14:08 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/4c160cf0f5c036cf899066d6ef0cf30de7df8806/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-05 16:10 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/6/execution/node/895/log

2020-10-05 16:53 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/89545ab36f29cd1bd2daaf39b9c4e068c1d8ac9e/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-05 20:23 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3570/7/display/redirect

2020-10-05 20:23 UTC, daosbuild1 commented
Test stage Functional on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3570/7/display/redirect

2020-10-05 22:06 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/d4ba6353e3c2747c85c9f352f9d3245c30bcba90/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-06 01:06 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/8/execution/node/866/log

2020-10-06 05:31 UTC, daosbuild1 commented
Test stage Functional_Hardware_Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/8/execution/node/985/log

2020-10-06 19:51 UTC, saurabhtandan requested changes
As per our conversation on MS Teams, we can do without this added test, as the changes made as part of this PR will be tested in ior_intercept_basic (the original failure).
In your next push, can you please add the following line to the final commit message to make sure ior_intercept_basic is run to verify the original bug is fixed.
`Test-tag-hw-small: pr,hw,small iorinterceptbasic`

2020-10-06 20:30 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3570/10/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/b89b60269388ba54ca0d779618ff6ebc14f9b880/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-06 20:30 UTC, daosbuild1 commented on src/tests/ftest/io/ior_intercept_basic.py
> +
(style)  trailing whitespace

2020-10-06 20:30 UTC, daosbuild1 commented on src/tests/ftest/io/ior_intercept_basic.py
> +
```suggestion

```

2020-10-06 20:31 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/10/execution/node/61/log

2020-10-07 04:21 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/10/execution/node/867/log

2020-10-07 12:51 UTC, daosbuild1 commented
Test stage Functional_Hardware_Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/10/execution/node/986/log

2020-10-07 16:03 UTC, cibervicho commented on src/tests/ftest/io/ior_intercept_basic.py
> +
Done

2020-10-07 16:24 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/6c8acc0f08bb295ec7c1b9efa2ac027ba40ad87b/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-07 18:35 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/11/execution/node/866/log

2020-10-08 04:48 UTC, daosbuild1 commented
Test stage Functional_Hardware_Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/11/execution/node/985/log

2020-10-08 17:55 UTC, shimizukko approved these changes
LGTM

2020-10-08 20:40 UTC, saurabhtandan commented
The test impacted by this PR is failing in CI.

2020-10-09 17:06 UTC, cibervicho commented
> The test impacted by this PR is failing in CI.

PR #3405 merged. I'm re-trying with this patch to see if there is an improvement

2020-10-09 17:23 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/cbe50a909d59aa39588684bb26c555bd3be61344/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-09 20:30 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/13/execution/node/867/log

2020-10-09 22:49 UTC, daosbuild1 commented
Test stage Functional_Hardware_Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/13/execution/node/986/log

2020-10-09 23:29 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3570/14/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/4d5d635ba855483b6c45490e736bb25977559343/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-09 23:29 UTC, daosbuild1 commented on src/tests/ftest/io/ior_intercept_basic.py
> +                write_x = self.params.get("write_x", "/run/ior/iorflags/ssf/*", 1)
(pylint-line-too-long) Line too long (82/80)

2020-10-09 23:29 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/14/execution/node/61/log

2020-10-10 04:01 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/14/execution/node/867/log

2020-10-13 14:46 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3570/15/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/65266f0dc1704608fef74f88d669478c9c59b4bb/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-13 14:46 UTC, daosbuild1 commented on src/tests/ftest/io/ior_intercept_basic.py
> +                    "/run/ior/iorflags/ssf/*", 1)
(pylint-bad-continuation) Wrong continued indentation (add 22 spaces).

2020-10-13 14:46 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/15/execution/node/60/log

2020-10-13 16:44 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/15/execution/node/866/log

2020-10-13 23:50 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3570/16/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/64602dc64442a1258fac60fa728b3b07cdfc1285/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-13 23:50 UTC, daosbuild1 commented on src/tests/ftest/io/ior_intercept_basic.py
> +                read_x = self.params.get("read_x",
(style)  trailing whitespace

2020-10-13 23:50 UTC, daosbuild1 commented on src/tests/ftest/io/ior_intercept_basic.py
> +                                          "/run/ior/iorflags/ssf/*", 1)
(pylint-bad-continuation) Wrong continued indentation (remove 1 space).

2020-10-13 23:50 UTC, daosbuild1 commented on src/tests/ftest/io/ior_intercept_basic.py
> +                read_x = self.params.get("read_x",
```suggestion
                read_x = self.params.get("read_x",
```

2020-10-13 23:50 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/16/execution/node/60/log

2020-10-14 06:47 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/16/execution/node/866/log

2020-10-14 20:21 UTC, cibervicho commented
Added the "fail_on_warning" flag as requested. This flag is working as expected when WARNING messages are shown in log, however the test now fails with an assertion when comparing **POSIX read** vs **POSIX + IL read**.

When discussing this with Saurabh he suggested, after talking with Mohamad, to include a DFS run to the test to get some baseline numbers because the performance numbers with IL should be similar or closer to the numbers if we use DFS api.

I got the results here:
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3570/16/testReport/junit/(root)/IorIntercept/Test___Functional_Hardware_Small___1___io_ior_intercept_basic_py_IorIntercept_test_ior_intercept_container_dfuse_hosts_np_16_oclass_SX_1M_pool_servers_ca08/

`
==== DFS ====
write   2629.70 MiB/sec
read    2795.45 MiB/sec

==== POSIX ====
without IL: write   329.81 MiB/sec
without IL: read    1383.25 MiB/sec
with IL:    write   2418.37 MiB/sec
with IL:    read    1339.22 MiB/sec
`

**DFS read > (POSIX + IL read = POSIX read)**

It seems to be a problem with the Intercept Library.

2020-10-14 23:27 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/051275f6a852a702eae0805fbf8e9a9e84652ab8/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-15 03:19 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/17/execution/node/866/log

2020-10-15 22:05 UTC, cibervicho commented
Opened the following ticket to address the IL bug: https://jira.hpdd.intel.com/browse/DAOS-5857

2020-10-15 22:15 UTC, saurabhtandan approved these changes
LGTM

2020-10-15 22:29 UTC, shimizukko approved these changes
LGTM

2020-10-15 22:36 UTC, mchaarawi requested changes
What are the warning messages that ior prints here? is it just the stat size warning?
what if there are other warnings?

I don't think you really need to do stonewalling here (-D 300). i would just remove that, and use a smaller block size, something like 4G and that should run in a reasonable amount of time. then you should not expect any warnings.

It would also be good to keep the DFS run before the runs over fuse to always have the comparison here.

2020-10-15 22:53 UTC, saurabhtandan commented
> What are the warning messages that ior prints here? is it just the stat size warning?
> what if there are other warnings?
> 
> I don't think you really need to do stonewalling here (-D 300). i would just remove that, and use a smaller block size, something like 4G and that should run in a reasonable amount of time. then you should not expect any warnings.
> 
> It would also be good to keep the DFS run before the runs over fuse to always have the comparison here.

Yeah the warning here is due to stat size. If you want '-D' option to be removed for this test, i think it shouldn't be a problem.
But there are other tests which require ior to be run with '-D' option and are failing too in weekly run. They will need this option to avoid fail on warning. Without this option we cannot run ior with -D option in CI right now.

2020-10-16 03:16 UTC, mchaarawi approved these changes

2020-10-16 03:16 UTC, mchaarawi commented
> > What are the warning messages that ior prints here? is it just the stat size warning?
> > what if there are other warnings?
> > I don't think you really need to do stonewalling here (-D 300). i would just remove that, and use a smaller block size, something like 4G and that should run in a reasonable amount of time. then you should not expect any warnings.
> > It would also be good to keep the DFS run before the runs over fuse to always have the comparison here.
> 
> Yeah the warning here is due to stat size. If you want '-D' option to be removed for this test, i think it shouldn't be a problem.
> But there are other tests which require ior to be run with '-D' option and are failing too in weekly run. They will need this option to avoid fail on warning. Without this option we cannot run ior with -D option in CI right now.

Ok I see. Thanks for the explanation. I’ll approve then if there are other requirements where stonewalling is needed.
But as I mentioned it would be good to add the DFS test here for comparison since I see it was added then reverted in the pr. It’s fine to do it in this or a separate pr.

2020-10-16 03:23 UTC, sylviachanoiyee commented
Do you know why the iorintercept test failed in Jenkins?

2020-10-16 14:14 UTC, saurabhtandan commented
> Do you know why the iorintercept test failed in Jenkins?

There is a parallel ticket opened for that issue.
https://jira.hpdd.intel.com/browse/DAOS-5857

2020-10-16 14:24 UTC, sylviachanoiyee commented
@saurabhtandan , thanks.
@cibervicho , is the issue intermittent or consistent?
If it is consistently failing, please do the following:
1. add skipForTicket in this PR to skip the test for DAOS-5857). I will land it.
2. create a ticket in JIRA to re-enable this test and set it as blocking DAOS-5857.

Thanks!

2020-10-16 17:57 UTC, saurabhtandan submitted a review, later dismissed
LGTM

2020-10-16 17:57 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3570/18/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/f737e8ea69191c876287d931dc3721de7f8b3502/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-16 17:57 UTC, daosbuild1 commented on src/tests/ftest/io/ior_intercept_basic.py
> +    @skipForTicket("DAOS-5857")
(pylint-undefined-variable) Undefined variable 'skipForTicket'

2020-10-16 17:58 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/18/execution/node/60/log

2020-10-16 18:12 UTC, cibervicho commented on src/tests/ftest/io/ior_intercept_basic.py
> +    @skipForTicket("DAOS-5857")
Fixed.

2020-10-16 18:15 UTC, shimizukko submitted a review, later dismissed
LGTM

2020-10-16 18:45 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:263](https://github.com/daos-stack/daos/blob/8a5bdc2df5c121839d2fd1056944c11885078d74/src/tests/ftest/util/ior_test_base.py#L263):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-16 19:44 UTC, ashleypittman commented
The -D option was to give us a vaguely consistent run-time but if our CI is stable now and running on consistent hardware we could probably remove it at the risks of tests taking longer.

The abort_on_warnings issue is something that I'd forgotten about, we really should land https://github.com/daos-stack/ior-hpc/commit/4ec2bebc33900c2712f21852eff685828d05f4c6 into IOR and then we wouldn't need this hack.

2020-10-16 20:44 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/20/execution/node/867/log

2020-10-16 21:02 UTC, saurabhtandan commented
> The -D option was to give us a vaguely consistent run-time but if our CI is stable now and running on consistent hardware we could probably remove it at the risks of tests taking longer.
> 
> The abort_on_warnings issue is something that I'd forgotten about, we really should land [daos-stack/ior-hpc@4ec2beb](https://github.com/daos-stack/ior-hpc/commit/4ec2bebc33900c2712f21852eff685828d05f4c6) into IOR and then we wouldn't need this hack.

stonewalling is a handy option I think. Otherwise we will be playing a guessing game with time limits everything in test side. Anyways, that's great if the above PR will take care of this issue. Until it is merged, it will be nice to go ahead with this hack. The PR seems almost ready, given the current run goes through fine.

2020-10-19 13:56 UTC, cibervicho commented
> @saurabhtandan , thanks.
> @cibervicho , is the issue intermittent or consistent?
> If it is consistently failing, please do the following:
> 
> 1. add skipForTicket in this PR to skip the test for DAOS-5857). I will land it.
> 2. create a ticket in JIRA to re-enable this test and set it as blocking DAOS-5857.
> 
> Thanks!

@sylviachanoiyee I completed step1 above. The test was skipped in CI.

2020-10-19 16:36 UTC, shimizukko approved these changes
LGTM

2020-10-20 17:38 UTC, cibervicho commented
> > Do you know why the iorintercept test failed in Jenkins?
> 
> There is a parallel ticket opened for that issue.
> https://jira.hpdd.intel.com/browse/DAOS-5857

Will merge with master and send a new patch to double check the fix.

2020-10-20 18:15 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:234](https://github.com/daos-stack/daos/blob/681aa7c88bf6bccfcb9b9c590779c7863e777e8a/src/tests/ftest/util/ior_test_base.py#L234):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-21 06:44 UTC, daosbuild1 commented
Test stage Functional_Hardware_Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/21/execution/node/983/log

2020-10-21 07:03 UTC, daosbuild1 commented
Test stage Functional_Hardware_Small completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3570/21/execution/node/940/log

2020-10-21 14:13 UTC, cibervicho commented
> > > Do you know why the iorintercept test failed in Jenkins?
> > 
> > 
> > There is a parallel ticket opened for that issue.
> > https://jira.hpdd.intel.com/browse/DAOS-5857
> 
> Will merge with master and send a new patch to double check the fix.

These are the results of last night's CI run (ior_intercept_basic.py):

==== DFS ====
without IL: write   2765.40 MiB/sec
without IL: read    2691.96 MiB/sec

==== POSIX ====
without IL: write   317.69 MiB/sec
without IL: read    1387.19 MiB/sec
with IL:    write   2465.06
with IL:    read    1350.48

The test also failed with the "AssertionError: False is not true" error:

06:34:15 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:596
06:34:15 ERROR| Traceback (most recent call last):
06:34:15 ERROR|   File "/usr/lib/daos/TESTING/ftest/io/ior_intercept_basic.py", line 87, in test_ior_intercept
06:34:15 ERROR|     read_x * float(without_intercept[1][max_mib]))
06:34:15 ERROR|   File "/usr/lib64/python2.7/unittest/case.py", line 462, in assertTrue
06:34:15 ERROR|     raise self.failureException(msg)
06:34:15 ERROR| AssertionError: False is not true

https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3570/21/testReport/(root)/IorIntercept/Test___Functional_Hardware_Small___1___io_ior_intercept_basic_py_IorIntercept_test_ior_intercept_container_dfuse_hosts_np_16_oclass_SX_1M_pool_servers_74f0/

I'm readding the skipForTicket decorator to the test and re-submitting to CI.

2020-10-21 14:40 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:234](https://github.com/daos-stack/daos/blob/85a84ed3503d740121c65d7b72335f11dab273ee/src/tests/ftest/util/ior_test_base.py#L234):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-22 13:17 UTC, cibervicho commented
All CI checks passed.

2020-10-22 13:46 UTC, saurabhtandan approved these changes
LGTM

2020-10-22 13:51 UTC, sylviachanoiyee approved these changes

2020-10-22 13:52 UTC, sylviachanoiyee commented
@cibervicho , please create a JIRA ticket to re-enable this test and set it to block DAOS-5857. thanks!

2020-10-22 13:53 UTC, merged