DAOS-5803 example: add simple example for different object APIs
daos-stack/daos pull request #3619
Opened 2020-10-08 00:17 UTC by mchaarawi

Skip-func-test-vm: true
Skip-func-hw-test-small: true
Skip-func-hw-test-medium: true
Skip-func-hw-test-large: true

Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>

2020-10-08 00:27 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3619/2/execution/node/61/log

2020-10-08 17:05 UTC, jolivier23 submitted a review, later dismissed
should we actually run the example ?  I've done example code in the past for other projects and found it gets stale pretty fast.

2020-10-08 17:10 UTC, mchaarawi commented
> should we actually run the example ? I've done example code in the past for other projects and found it gets stale pretty fast.

agreed, but i just wanted something to share with others for now.

2020-10-08 17:26 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3619/3/execution/node/60/log

2020-10-08 17:54 UTC, jolivier23 approved these changes

2020-10-08 17:56 UTC, jolivier23 requested changes

2020-10-08 17:56 UTC, jolivier23 commented on src/tests/simple_obj.c
> +	 * type of the value under tha akey will be a single value of size
11:19:09  src/tests/simple_obj.c:355: tha ==> than, that, the

This is what is causing checkpatch to fail

2020-10-08 17:56 UTC, jolivier23 commented on src/tests/simple_obj.c
> +	 * type of the value under tha akey will be a single value of size
There is an open bug on this but it happens when the suggestion is more than one word

2020-10-08 18:20 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3619/4/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2020-10-08 18:20 UTC, daosbuild1 commented on src/tests/simple_obj.c
> +        HANDLE_POOL,
(style)  code indent should use tabs where possible

2020-10-08 18:20 UTC, daosbuild1 commented on src/tests/simple_obj.c
> +        HANDLE_CO,
(style)  code indent should use tabs where possible

2020-10-08 18:20 UTC, daosbuild1 commented on src/tests/simple_obj.c
> +	 * choose max striping with no data prorection - OC_SX. */
(style)  Block comments use a trailing */ on a separate line

2020-10-08 18:20 UTC, daosbuild1 commented on src/tests/simple_obj.c
> +		/*
(style)  trailing whitespace

2020-10-08 18:20 UTC, daosbuild1 commented on src/tests/simple_obj.c
> +		 * writes 1k extent contiguously: 0: 0, 1:1024, 2:2048, etc. */
(style)  Block comments use a trailing */ on a separate line

2020-10-08 18:20 UTC, daosbuild1 commented on src/tests/simple_obj.c
> +		iod.iod_type	= DAOS_IOD_ARRAY; /** the value type of the akey */
(style)  line over 80 characters

2020-10-08 18:20 UTC, daosbuild1 commented on src/tests/simple_obj.c
> +		iod.iod_type	= DAOS_IOD_ARRAY; /** the value type of the akey */
(style)  line over 80 characters

2020-10-08 18:20 UTC, daosbuild1 commented on src/tests/simple_obj.c
> +		iod.iod_type	= DAOS_IOD_SINGLE; /** the value type of the akey */
(style)  line over 80 characters

2020-10-08 18:20 UTC, daosbuild1 commented on src/tests/simple_obj.c
> +		rc = daos_array_create(coh, oid, DAOS_TX_NONE, 1, 1048576, &oh, NULL);
(style)  line over 80 characters

2020-10-08 18:20 UTC, daosbuild1 commented on src/tests/simple_obj.c
> +
(style)  trailing whitespace

2020-10-08 18:20 UTC, daosbuild1 commented on src/tests/simple_obj.c
> +        HANDLE_CO,
```suggestion
	HANDLE_POOL,
	HANDLE_CO,
```

2020-10-08 18:20 UTC, daosbuild1 commented on src/tests/simple_obj.c
> +		 * memory. in this case it's a single contigous buffer, but this
```suggestion
		/*
		 * init scatter/gather. this describes that data in your
		 * memory. in this case it's a single contiguous buffer, but this
```

2020-10-08 18:20 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3619/4/execution/node/61/log

2020-10-08 19:13 UTC, daosbuild1 submitted a review, later dismissed

2020-10-08 19:13 UTC, daosbuild1 commented on src/tests/simple_obj.c
> +		 * memory. in this case it's a single contigous buffer, but this
```suggestion
		 * memory. in this case it's a single contiguous buffer, but this
```

2020-10-08 19:13 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3619/5/execution/node/61/log

2020-10-08 19:36 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3619/6/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2020-10-08 19:36 UTC, daosbuild1 commented on src/tests/simple_obj.c
> +		 * memory. in this case it's a single contiguous buffer, but this
(style)  line over 80 characters

2020-10-08 19:36 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3619/6/execution/node/61/log

2020-10-08 19:56 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-10-09 01:09 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3619/7/execution/node/867/log

2020-10-09 08:09 UTC, daosbuild1 commented
Test stage Functional_Hardware_Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3619/7/execution/node/986/log

2020-10-09 20:56 UTC, jolivier23 approved these changes

2020-10-12 20:54 UTC, johannlombardi approved these changes

2020-10-12 20:55 UTC, merged