DAOS-5887 iosrv: check ABT_mutex_create return value
daos-stack/daos pull request #3703
Opened 2020-10-21 00:08 UTC by wangdi1

Check ABT_mutex_create return value.

Signed-off-by: Di Wang <di.wang@intel.com>

2020-10-21 00:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-10-21 03:12 UTC, NiuYawei approved these changes

2020-10-21 03:12 UTC, NiuYawei commented on src/iosrv/server_iv.c
> +		return -DER_NOMEM;
dss_abterr2der(rc).

2020-10-21 15:55 UTC, jolivier23 requested changes
fix Niu's comment.  Just clearing my inbox of ones that need more work.  Otherwise, looks fine

2020-10-21 16:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-10-22 03:50 UTC, NiuYawei approved these changes

2020-10-22 09:08 UTC, daosbuild1 commented
Test stage Functional_Hardware_Small completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3703/2/execution/node/941/log

2020-10-23 23:37 UTC, jolivier23 approved these changes

2020-10-23 23:37 UTC, merged