DAOS-4326 api: daos_pool_get_vos_state()
daos-stack/daos pull request #3717
Opened 2020-10-23 02:59 UTC by sydneyvanda

A DAOS mgmt/pool C API to query the VOS target state
is required for daos_test validation of DAOS NVMe recovery
tests (and can later be applied to rebuild tests).

Add capabilty to check the VOS target state before, during,
and after rebuild have completed (ie NEW/UP/UPIN/DOWN/DOWNOUT/DRAIN).
This is accomplished using the daos_pool_get_vos_state() C API,
which will return the VOS target state for a given pool uuid, rank,
and target idx. Not currently exported via dmg command for admin use.

Test-tag-hw-medium: daos_test_nvme_recovery

Signed-off-by: Sydney Vanda <sydney.m.vanda@intel.com>

2020-10-23 03:18 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3717/1/execution/node/60/log

2020-10-24 00:46 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3717/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/mgmt/SConscript:14](https://github.com/daos-stack/daos/blob/e3f5e82eaabf1b65fa26fb9b15c2bc86b8486160/src/mgmt/SConscript#L14):
(pylint-invalid-name) Invalid variable name "pb"

2020-10-24 00:46 UTC, daosbuild1 commented on src/common/tests_dmg_helpers.c
> +				json_object_object_foreach(smd_pool, key2, val2) {
(style)  line over 80 characters

2020-10-24 00:46 UTC, daosbuild1 commented on src/common/tests_dmg_helpers.c
> +					D_DEBUG(DB_TEST, "pool:\"%s\",val=%s\n", key2,
(style)  line over 80 characters

2020-10-24 00:46 UTC, daosbuild1 commented on src/common/tests_dmg_helpers.c
> +						json_object_to_json_string(val2));
(style)  line over 80 characters

2020-10-24 00:46 UTC, daosbuild1 commented on src/common/tests_dmg_helpers.c
> +					rc = parse_pooltable_info(smd_pool, pools,
(style)  line over 80 characters

2020-10-24 00:46 UTC, daosbuild1 commented on src/common/tests_dmg_helpers.c
> +								  host, pool_length,
(style)  line over 80 characters

2020-10-24 00:46 UTC, daosbuild1 commented on src/include/daos/tests_lib.h
> +typedef struct {
(style)  do not add new typedefs

2020-10-24 00:46 UTC, daosbuild1 commented on src/include/daos/tests_lib.h
> + *  					NULL is permitted in which case only the
(style)  please, no space before tabs

2020-10-24 00:46 UTC, daosbuild1 commented on src/include/daos/tests_lib.h
> + *  					number of pool will be returned in
(style)  please, no space before tabs

2020-10-24 00:46 UTC, daosbuild1 commented on src/include/daos/tests_lib.h
> + *  					\a npools.
(style)  please, no space before tabs

2020-10-24 00:46 UTC, daosbuild1 commented on src/include/daos/tests_lib.h
> +const char * vos_state_enum_to_str(int state);
(style)  "foo * bar" should be "foo *bar"

2020-10-24 00:46 UTC, daosbuild1 commented on src/include/daos/tests_lib.h
> + *  					\a npools.
```suggestion
 *					NULL is permitted in which case only the
 *					number of pool will be returned in
 *					\a npools.
```

2020-10-24 00:46 UTC, daosbuild1 commented on src/include/daos/tests_lib.h
> +const char * vos_state_enum_to_str(int state);
```suggestion
const char *vos_state_enum_to_str(int state);
```

2020-10-24 00:46 UTC, daosbuild1 commented on src/include/daos_mgmt.h
> + * 				ie DOWN/DOWNOUT/UP/UPIN/NEW/DRAIN
(style)  please, no space before tabs

2020-10-24 00:46 UTC, daosbuild1 commented on src/include/daos_mgmt.h
> + * 				The function will run in blocking mode
(style)  please, no space before tabs

2020-10-24 00:46 UTC, daosbuild1 commented on src/include/daos_mgmt.h
> + * 				if \a ev is NULL.
(style)  please, no space before tabs

2020-10-24 00:46 UTC, daosbuild1 commented on src/include/daos_mgmt.h
> + * 				if \a ev is NULL.
```suggestion
 *				ie DOWN/DOWNOUT/UP/UPIN/NEW/DRAIN
 * \param ev		  [IN]  Completion event. Optional and can be NULL.
 *				The function will run in blocking mode
 *				if \a ev is NULL.
```

2020-10-24 00:46 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2020-10-24 00:46 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2020-10-24 00:46 UTC, daosbuild1 commented on src/include/daos_task.h
> +	/** UUID of the of the pool that the target resides */
(style)  trailing whitespace

2020-10-24 00:46 UTC, daosbuild1 commented on src/include/daos_task.h
> +	/** UUID of the of the pool that the target resides */
```suggestion
	/** UUID of the of the pool that the target resides */
```

2020-10-24 00:46 UTC, daosbuild1 commented on src/mgmt/rpc.h
> +#define DAOS_OSEQ_MGMT_GET_BS_STATE /* output fields */		 \
(style)  Macros with complex values should be enclosed in parentheses

2020-10-24 00:46 UTC, daosbuild1 commented on src/mgmt/rpc.h
> +#define DAOS_ISEQ_MGMT_GET_VOS_STATE /* input fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2020-10-24 00:46 UTC, daosbuild1 commented on src/mgmt/rpc.h
> +#define DAOS_OSEQ_MGMT_GET_VOS_STATE /* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2020-10-24 00:46 UTC, daosbuild1 commented on src/tests/suite/daos_test.h
> +			      int rank, char *expected_state, const char *group);
(style)  line over 80 characters

2020-10-24 00:46 UTC, daosbuild1 commented on src/mgmt/rpc.c
> +		DAOS_OSEQ_MGMT_GET_VOS_STATE)
```suggestion
	       DAOS_OSEQ_MGMT_GET_VOS_STATE)
```

2020-10-24 00:46 UTC, daosbuild1 commented on src/tests/suite/daos_nvme_recovery.c
> +						arg->pool.pool_uuid,
```suggestion
					      pools[i].rank[j], pools[i].tgts[k]);
				/* get VOS tgt state for rank/tgtidx */
				rc = daos_pool_get_vos_state(arg->group,
							     arg->pool.pool_uuid,
```

2020-10-24 00:46 UTC, daosbuild1 commented on src/tests/suite/daos_nvme_recovery.c
> +						arg->pool.pool_uuid,
```suggestion
							     arg->pool.pool_uuid,
```

2020-10-24 00:46 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3717/2/execution/node/60/log

2020-10-24 00:48 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3717/2/execution/node/267/log

2020-10-26 19:11 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3717/3/execution/node/60/log

2020-10-27 03:57 UTC, NiuYawei requested changes

2020-10-27 03:57 UTC, NiuYawei commented on src/include/daos/tests_lib.h
> +
According to our discussion, we can easily know the total node count and total target count from pool query, then we can calculate the per node target count by (total target count / total node count). This data structure won't be necessary anymore?

2020-10-27 03:57 UTC, NiuYawei commented on src/include/daos_mgmt.h
> +			d_rank_t rank, int *state, daos_event_t *ev);
As I mentioned above, it's could be done in daos_pool_target_query(), and it should be a pool API instead of mgmt API.

2020-10-27 03:57 UTC, NiuYawei commented on src/mgmt/cli_query.c
> +dc_pool_get_vos_state(tse_task_t *task)
Let's move this implementation to dc_pool_query_target() in src/pool/cli.c, and get pool target state only for this moment. Let's improve it later to add per target space usage information.

2020-10-27 03:57 UTC, NiuYawei commented on src/common/tests_dmg_helpers.c
> +		      pool_table_list *pools)
As we discussed, this API looks not necessary.

2020-10-27 03:57 UTC, NiuYawei commented on src/mgmt/rpc.h
> +		ds_mgmt_hdlr_get_vos_state, NULL)
Move to src/pool/rpc.h

2020-10-27 03:57 UTC, NiuYawei commented on src/mgmt/srv_target.c
> +ds_mgmt_hdlr_get_vos_state(crt_rpc_t *rpc_req)
Move to src/pool/srv_pool.c and rename as ds_pool_query_target_handler().

2020-10-27 03:57 UTC, NiuYawei commented on src/mgmt/srv_target.c
> +	pool = ds_pool_lookup(vs_in->vs_pool_uuid);
Get pool svc by pool_svc_lookup_leader(), and use the svc->ps_pool instead.

2020-10-27 03:57 UTC, NiuYawei commented on src/mgmt/srv_target.c
> +				   &vs_state);
Instead of calling another function to lookup ds_pool again, get the target state from pool map directly here?

2020-10-27 03:57 UTC, NiuYawei commented on src/mgmt/srv_target.c
> +
In the future, we can send pool target query RPC here to get space usage for the specified target here.

2020-10-31 04:11 UTC, sydneyvanda commented
Revised in #3772

2020-10-31 04:11 UTC, closed without merging