DAOS-5751 test: Remove deprecated control_method=API
daos-stack/daos pull request #3720
Opened 2020-10-23 04:23 UTC by berserk-fury

Signed-off-by: Jonathan Martinez Montes <jonathan.martinez.montes@intel.com>

2020-10-23 04:42 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-10-23 04:50 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3720/1/execution/node/235/log

2020-10-23 05:41 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-10-23 05:43 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3720/2/execution/node/260/log

2020-10-23 13:05 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-10-26 03:41 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/pool/bad_connect.py:30](https://github.com/daos-stack/daos/blob/08c4c6db2e0c715d205548032b6b358149e098d3/src/tests/ftest/pool/bad_connect.py#L30):
(pylint-unused-import) Unused skipForTicket imported from apricot

[src/tests/ftest/util/daos_io_conf.py:28](https://github.com/daos-stack/daos/blob/08c4c6db2e0c715d205548032b6b358149e098d3/src/tests/ftest/util/daos_io_conf.py#L28):
(pylint-unused-import) Unused CommandFailure imported from command_utils_base

[src/tests/ftest/util/ior_test_base.py:243](https://github.com/daos-stack/daos/blob/08c4c6db2e0c715d205548032b6b358149e098d3/src/tests/ftest/util/ior_test_base.py#L243):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2020-10-26 04:17 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-10-27 14:59 UTC, shimizukko approved these changes
LGTM

2020-10-27 18:01 UTC, phender requested changes

2020-10-27 18:01 UTC, phender commented on src/tests/ftest/pool/rebuild_with_io.py
> +        pool = TestPool(self.context, self.get_dmg_command(), log=self.log)
The `log` argument is defunct for TestPool.create():
```suggestion
        pool = TestPool(self.context, self.get_dmg_command())
```

2020-10-27 18:01 UTC, phender commented on src/tests/ftest/pool/rebuild_tests.py
> +                                  log=self.log))
The `log` argument is defunct for TestPool.create():
```suggestion
            pools.append(TestPool(self.context, self.get_dmg_command()))
```

2020-10-27 18:01 UTC, phender commented on src/tests/ftest/pool/rebuild_no_cap.py
> +                             log=self.log)
The `log` argument is defunct for TestPool.create():
```suggestion
        self.pool = TestPool(self.context, self.get_dmg_command())
```

2020-10-27 18:01 UTC, phender commented on src/tests/ftest/pool/info_tests.py
> +                             log=self.log)
The `log` argument is defunct for TestPool.create():
```suggestion
        self.pool = TestPool(self.context, self.get_dmg_command())
```

2020-10-27 18:01 UTC, phender commented on src/tests/ftest/pool/evict_test.py
> +        pool = TestPool(self.context, self.get_dmg_command(), log=self.log)
The `log` argument is defunct for TestPool.create():
```suggestion
        pool = TestPool(self.context, self.get_dmg_command())
```

2020-10-27 18:01 UTC, phender commented on src/tests/ftest/pool/destroy_rebuild.py
> +        self.pool = TestPool(self.context, self.get_dmg_command(), log=self.log)
The `log` argument is defunct for TestPool.create():
```suggestion
        self.pool = TestPool(self.context, self.get_dmg_command())
```

2020-10-27 18:10 UTC, cibervicho submitted a review, later dismissed

2020-10-28 23:02 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-10-29 22:34 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-10-30 15:01 UTC, sylviachanoiyee commented
@berserk-fury , can you leave a comment in this PR with JIRA tickets to the failures in Jenkins? thanks!!

2020-10-31 15:33 UTC, merged