DAOS-6000: fix memory leak in vos key_punch for akey case
daos-stack/daos pull request #3851
Opened 2020-11-11 21:20 UTC by marcelarosalesj

Signed-off-by: Marcela Rosales <marcela.a.rosales.jimenez@intel.com>

2020-11-11 21:39 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3851/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2020-11-11 21:39 UTC, daosbuild1 commented on src/vos/vos_obj.c
> +	daos_handle_t		 toh = DAOS_HDL_INVAL ;
(style)  space prohibited before semicolon

2020-11-11 21:39 UTC, daosbuild1 commented on src/vos/vos_obj.c
> +	daos_handle_t		 toh = DAOS_HDL_INVAL ;
```suggestion
	daos_handle_t		 toh = DAOS_HDL_INVAL;
```

2020-11-11 21:39 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3851/1/execution/node/57/log

2020-11-11 21:42 UTC, jolivier23 requested changes
just fix the checkpatch issue, otherwise, looks good to me

2020-11-11 21:42 UTC, jolivier23 commented on src/vos/vos_obj.c
> +	daos_handle_t		 toh = DAOS_HDL_INVAL ;
this one should be fixed.

2020-11-12 02:18 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-11-12 02:34 UTC, NiuYawei approved these changes

2020-11-12 03:00 UTC, Nasf-Fan approved these changes

2020-11-12 15:01 UTC, jolivier23 approved these changes

2020-11-12 16:25 UTC, ashleypittman commented
I just want to add that it's great to see issues like that that we're working through the memcheck errors and using it to fix real issues.

2020-11-12 18:11 UTC, ryon-jensen approved these changes

2020-11-12 18:21 UTC, jolivier23 commented
> I just want to add that it's great to see issues like that that we're working through the memcheck errors and using it to fix real issues.

yeah, this is the first real issue we've fixed so far.   I'm happy to have memcheck running and also to get rid of some of the suppressions that may mask any new issues.

2020-11-12 19:33 UTC, merged