DAOS-6135 [java] refactor DaosFsClient to move common logic to DaosClient
daos-stack/daos pull request #3946
Opened 2020-11-25 01:40 UTC by zjf2012

To support DAOS Object API, we can reuse some common logic, like daos_init, pool/container connection, in DaosFsClient. So we need to move these common logic to new class DaosClient and refactor DaosFsClient to reference DaosClient.

2020-11-25 02:00 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3946/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> + * 		JNI_ERR or non-zeor rc code of daos_init() for any error. In
(style)  please, no space before tabs

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> + * 		this case, JVM throws JNI error.
(style)  please, no space before tabs

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +	if(new_exception_msg == NULL){
(style)  space required before the open brace '{'
(style)  space required before the open parenthesis '('

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +	if(new_exception_cause == NULL){
(style)  space required before the open brace '{'
(style)  space required before the open parenthesis '('

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +	if(new_exception_msg_code_msg == NULL){
(style)  space required before the open brace '{'
(style)  space required before the open parenthesis '('

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +	if(new_exception_msg_code_cause == NULL){
(style)  space required before the open brace '{'
(style)  space required before the open parenthesis '('

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +        printf("Failed daos_eq_lib_init: %d\n", rc);
(style)  code indent should use tabs where possible

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +        return rc;
(style)  code indent should use tabs where possible

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +		const char* temp = posix_error ?
(style)  "foo* bar" should be "foo *bar"

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +JNI_OnUnload(JavaVM* vm, void *reserved)
(style)  "foo* bar" should be "foo *bar"

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> + * 		this case, JVM throws JNI error.
```suggestion
 *		JNI_ERR or non-zeor rc code of daos_init() for any error. In
 *		this case, JVM throws JNI error.
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +	if(new_exception_msg == NULL){
```suggestion
	if (new_exception_msg == NULL) {
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +	if(new_exception_cause == NULL){
```suggestion
	if (new_exception_cause == NULL) {
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +	if(new_exception_msg_code_msg == NULL){
```suggestion
	if (new_exception_msg_code_msg == NULL) {
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +	if(new_exception_msg_code_cause == NULL){
```suggestion
	if (new_exception_msg_code_cause == NULL) {
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +        return rc;
```suggestion
	printf("Failed daos_eq_lib_init: %d\n", rc);
	return rc;
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +			int release_msg, int posix_error)
```suggestion
		     int release_msg, int posix_error)
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +		const char* temp = posix_error ?
```suggestion
		const char *temp = posix_error ?
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +JNI_OnUnload(JavaVM* vm, void *reserved)
```suggestion
JNI_OnUnload(JavaVM *vm, void *reserved)
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/include/daos_jni_common.h
> + * 				customized error code
(style)  please, no space before tabs

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/include/daos_jni_common.h
> + * 				1 for true, 0 for false
(style)  please, no space before tabs

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/include/daos_jni_common.h
> + * 				1 for true, 0 for false
```suggestion
 *				customized error code
 * \param[in]	release_msg	is \a msg needed to be released, (0 or 1)
 * \param[in]	posix_error	is \a error_code posix error,
 *				1 for true, 0 for false
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/include/daos_jni_common.h
> +			int release_msg, int posix_error);
```suggestion
		     int release_msg, int posix_error);
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +	uuid_parse(pool_str, pool_uuid);
(style)  Missing a blank line after declarations

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		char *tmp = "Invalid pool service rank list (%s) when open " \
(style)  Avoid unnecessary line continuations

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		rc = daos_pool_connect(pool_uuid, server_group, svcl,
(style)  Missing a blank line after declarations

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +	uuid_parse(cont_str, cont_uuid);
(style)  Missing a blank line after declarations

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +	if (rc) {
(style)  Missing a blank line after declarations

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jstring poolId, jstring serverGroup,
```suggestion
Java_io_daos_DaosClient_daosOpenPool(JNIEnv * env,
				     jclass clientClass, jstring poolId, jstring serverGroup,
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +	uuid_parse(pool_str, pool_uuid);
```suggestion
	uuid_t pool_uuid;

```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +			&poh /* returned pool handle */,
```suggestion
		int rc;

		rc = daos_pool_connect(pool_uuid, server_group, svcl,
				       flags,
```

2020-11-25 02:00 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3946/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> + * 		JNI_ERR or non-zeor rc code of daos_init() for any error. In
(style)  please, no space before tabs

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> + * 		this case, JVM throws JNI error.
(style)  please, no space before tabs

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +	if(new_exception_msg == NULL){
(style)  space required before the open brace '{'
(style)  space required before the open parenthesis '('

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +	if(new_exception_cause == NULL){
(style)  space required before the open brace '{'
(style)  space required before the open parenthesis '('

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +	if(new_exception_msg_code_msg == NULL){
(style)  space required before the open brace '{'
(style)  space required before the open parenthesis '('

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +	if(new_exception_msg_code_cause == NULL){
(style)  space required before the open brace '{'
(style)  space required before the open parenthesis '('

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +		const char* temp = posix_error ?
(style)  "foo* bar" should be "foo *bar"

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> + * 		this case, JVM throws JNI error.
```suggestion
 *		JNI_ERR or non-zeor rc code of daos_init() for any error. In
 *		this case, JVM throws JNI error.
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +	if(new_exception_msg == NULL){
```suggestion
	if (new_exception_msg == NULL) {
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +	if(new_exception_msg_code_msg == NULL){
```suggestion
	if (new_exception_msg_code_msg == NULL) {
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +	if(new_exception_msg_code_cause == NULL){
```suggestion
	if (new_exception_msg_code_cause == NULL) {
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +        return rc;
```suggestion
	printf("Failed daos_eq_lib_init: %d\n", rc);
	return rc;
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +			int release_msg, int posix_error)
```suggestion
		     int release_msg, int posix_error)
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +		const char* temp = posix_error ?
```suggestion
		const char *temp = posix_error ?
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +JNI_OnUnload(JavaVM* vm, void *reserved)
```suggestion
JNI_OnUnload(JavaVM *vm, void *reserved)
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/include/daos_jni_common.h
> + * 				customized error code
(style)  please, no space before tabs

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/include/daos_jni_common.h
> + * 				1 for true, 0 for false
(style)  please, no space before tabs

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/include/daos_jni_common.h
> + * 				1 for true, 0 for false
```suggestion
 *				customized error code
 * \param[in]	release_msg	is \a msg needed to be released, (0 or 1)
 * \param[in]	posix_error	is \a error_code posix error,
 *				1 for true, 0 for false
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/include/daos_jni_common.h
> +			int release_msg, int posix_error);
```suggestion
		     int release_msg, int posix_error);
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +	uuid_parse(pool_str, pool_uuid);
(style)  Missing a blank line after declarations

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		char *tmp = "Invalid pool service rank list (%s) when open " \
(style)  Avoid unnecessary line continuations

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		rc = daos_pool_connect(pool_uuid, server_group, svcl,
(style)  Missing a blank line after declarations

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +	uuid_parse(cont_str, cont_uuid);
(style)  Missing a blank line after declarations

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +	if (rc) {
(style)  Missing a blank line after declarations

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jstring poolId, jstring serverGroup,
```suggestion
Java_io_daos_DaosClient_daosOpenPool(JNIEnv * env,
				     jclass clientClass, jstring poolId, jstring serverGroup,
```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +	uuid_parse(pool_str, pool_uuid);
```suggestion
	uuid_t pool_uuid;

```

2020-11-25 02:00 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +			&poh /* returned pool handle */,
```suggestion
		int rc;

		rc = daos_pool_connect(pool_uuid, server_group, svcl,
				       flags,
```

2020-11-25 02:00 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3946/1/execution/node/57/log

2020-11-25 02:45 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3946/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +	uuid_parse(pool_str, pool_uuid);
(style)  Missing a blank line after declarations

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		char *tmp = "Invalid pool service rank list (%s) when open pool (%s)";
(style)  line over 80 characters

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jstring poolId, jstring serverGroup,
```suggestion
Java_io_daos_DaosClient_daosOpenPool(JNIEnv * env,
				     jclass clientClass, jstring poolId, jstring serverGroup,
```

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +	uuid_parse(pool_str, pool_uuid);
```suggestion
	uuid_t pool_uuid;

```

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +			flags,
```suggestion
				       flags,
```

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jlong poolHandle)
```suggestion
				      jclass clientClass, jlong poolHandle)
```

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jlong poolHandle, jstring contUuid,
```suggestion
				     jclass clientClass, jlong poolHandle, jstring contUuid,
```

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jlong contHandle)
```suggestion
					   jclass clientClass, jlong contHandle)
```

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass)
```suggestion
				     jclass clientClass)
```

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/java/io/daos/DaosContainer.java
> +public class DaosContainer extends Sharable implements Closeable {
```suggestion
public class DaosContainer extends Shareable implements Closeable {
```

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/java/io/daos/DaosPool.java
> +public class DaosPool extends Sharable implements Closeable {
```suggestion
public class DaosPool extends Shareable implements Closeable {
```

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/java/io/daos/Sharable.java
> +public abstract class Sharable {
```suggestion
public abstract class Shareable {
```

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/java/io/daos/SharableClient.java
> +public abstract class SharableClient extends Sharable implements ForceCloseable {
```suggestion
public abstract class SharableClient extends Shareable implements ForceCloseable {
```

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/java/io/daos/dfs/DaosFsClient.java
> + * A sharable Java DAOS DFS client to wrap all DFS related operations, including
```suggestion
 * A shareable Java DAOS DFS client to wrap all DFS related operations, including
```

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +			int release_msg, int posix_error)
```suggestion
		     int release_msg, int posix_error)
```

2020-11-25 02:45 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/include/daos_jni_common.h
> +		int release_msg, int posix_error);
```suggestion
		     int release_msg, int posix_error);
```

2020-11-25 02:45 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3946/2/execution/node/58/log

2020-11-25 03:36 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3946/6/execution/node/58/log

2020-11-25 06:41 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3946/7/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2020-11-25 06:41 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		            "open pool (%s)";
(style)  code indent should use tabs where possible

2020-11-25 06:41 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jstring poolId, jstring serverGroup,
```suggestion
Java_io_daos_DaosClient_daosOpenPool(JNIEnv * env,
				     jclass clientClass, jstring poolId, jstring serverGroup,
```

2020-11-25 06:41 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		            "open pool (%s)";
```suggestion
			    "open pool (%s)";
```

2020-11-25 06:41 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +			flags,
```suggestion
				       flags,
```

2020-11-25 06:41 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jlong poolHandle)
```suggestion
				      jclass clientClass, jlong poolHandle)
```

2020-11-25 06:41 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jlong poolHandle, jstring contUuid,
```suggestion
				     jclass clientClass, jlong poolHandle, jstring contUuid,
```

2020-11-25 06:41 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jlong contHandle)
```suggestion
					   jclass clientClass, jlong contHandle)
```

2020-11-25 06:41 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass)
```suggestion
				     jclass clientClass)
```

2020-11-25 06:41 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +		int release_msg, int posix_error)
```suggestion
		     int release_msg, int posix_error)
```

2020-11-25 06:41 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/include/daos_jni_common.h
> +		int release_msg, int posix_error);
```suggestion
		     int release_msg, int posix_error);
```

2020-11-25 06:41 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3946/7/execution/node/58/log

2020-11-25 07:06 UTC, daosbuild1 submitted a review, later dismissed

2020-11-25 07:06 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +		int release_msg, int posix_error)
```suggestion
		     int release_msg, int posix_error)
```

2020-11-25 07:06 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/include/daos_jni_common.h
> +		int release_msg, int posix_error);
```suggestion
		     int release_msg, int posix_error);
```

2020-11-25 07:06 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jstring poolId, jstring serverGroup,
```suggestion
Java_io_daos_DaosClient_daosOpenPool(JNIEnv * env,
				     jclass clientClass, jstring poolId, jstring serverGroup,
```

2020-11-25 07:06 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +			flags,
```suggestion
				       flags,
```

2020-11-25 07:06 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jlong poolHandle)
```suggestion
				      jclass clientClass, jlong poolHandle)
```

2020-11-25 07:06 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jlong poolHandle, jstring contUuid,
```suggestion
				     jclass clientClass, jlong poolHandle, jstring contUuid,
```

2020-11-25 07:06 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jlong contHandle)
```suggestion
					   jclass clientClass, jlong contHandle)
```

2020-11-25 07:06 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass)
```suggestion
				     jclass clientClass)
```

2020-11-25 07:06 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3946/8/execution/node/58/log

2020-11-25 10:04 UTC, daosbuild1 commented
Test stage Functional_Hardware_Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3946/8/execution/node/994/log

2020-11-26 02:35 UTC, daosbuild1 commented
Test stage Functional_Hardware_Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3946/8/execution/node/1172/log

2020-12-08 05:45 UTC, zjf2012 commented
@carsonwang @johannlombardi , please help review. thanks.

2020-12-26 17:47 UTC, johannlombardi commented
Please merge master and address the conflict.

2020-12-26 18:07 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3946/9/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2020-12-26 18:07 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/DunsAttribute.pb-c.c
> +static const ProtobufCFieldDescriptor uns__duns_attribute__field_descriptors[9] =
(style)  line over 80 characters

2020-12-26 18:07 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/DunsAttribute.pb-c.c
> +    0,NULL,NULL    /* reserved1,reserved2, etc */
(style)  space required after that ',' (ctx:VxV)
(style)  space required after that ',' (ctx:VxV)

2020-12-26 18:07 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/DunsAttribute.pb-c.c
> +    0,NULL,NULL    /* reserved1,reserved2, etc */
(style)  space required after that ',' (ctx:VxV)
(style)  space required after that ',' (ctx:VxV)

2020-12-26 18:07 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/include/DunsAttribute.pb-c.h
> +    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, UNS__LAYOUT__UNKNOWN, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0, NULL, 0 }
(style)  line over 80 characters

2020-12-26 18:07 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_dfs_DaosFsClient.c
> +    attr.da_no_prefix = !has_prefix;
(style)  Missing a blank line after declarations

2020-12-26 18:07 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_dfs_DaosFsClient.c
> +	if (attr.da_rel_path) {
(style)  suspect code indent for conditional statements (8, 12)

2020-12-26 18:07 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_dfs_DaosFsClient.c
> +    attr.da_no_prefix = !has_prefix;
```suggestion
    bool has_prefix = strncmp(prefix, path, strlen(prefix)) == 0;

```

2020-12-26 18:07 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/daos_jni_common.c
> +		int release_msg, int posix_error)
```suggestion
		     int release_msg, int posix_error)
```

2020-12-26 18:07 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/include/daos_jni_common.h
> +		int release_msg, int posix_error);
```suggestion
		     int release_msg, int posix_error);
```

2020-12-26 18:07 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jstring poolId, jstring serverGroup,
```suggestion
Java_io_daos_DaosClient_daosOpenPool(JNIEnv * env,
				     jclass clientClass, jstring poolId, jstring serverGroup,
```

2020-12-26 18:07 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +			flags,
```suggestion
				       flags,
```

2020-12-26 18:07 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jlong poolHandle)
```suggestion
				      jclass clientClass, jlong poolHandle)
```

2020-12-26 18:07 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jlong poolHandle, jstring contUuid,
```suggestion
				     jclass clientClass, jlong poolHandle, jstring contUuid,
```

2020-12-26 18:07 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass, jlong contHandle)
```suggestion
					   jclass clientClass, jlong contHandle)
```

2020-12-26 18:07 UTC, daosbuild1 commented on src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
> +		jclass clientClass)
```suggestion
				     jclass clientClass)
```

2020-12-26 18:07 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3946/9/execution/node/57/log

2020-12-26 21:42 UTC, daosbuild1 commented
Test stage Functional_Hardware_Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3946/9/execution/node/1043/log

2020-12-27 00:32 UTC, daosbuild1 commented
Test stage Functional_Hardware_Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3946/9/execution/node/1184/log

2020-12-27 10:48 UTC, johannlombardi requested changes
It sounds like there is still a merge conflict with master. Please also address the relevant checkpatch errors.

2020-12-29 02:07 UTC, closed without merging