Added posix_stat.py to verify metadata of a file created in a container
daos-stack/daos pull request #3960
Opened 2020-11-28 20:41 UTC by shimizukko

Requirement: SRS-10-0303
DFS stat call reports meaningful information (i.e. valid file size, correct
block size, ...).

Test Steps:
Create files of different size (block size) in a mounted POSIX container and
verify the size with stat command. Also verify the creation time with date
command.

Test-tag: stat_parameters
Skip-func-hw-test: true
Skip-unit-test: true
Skip-func-test-leap15: true
Signed-off-by: Makito Kano <makito.kano@intel.com>

2020-11-28 20:58 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3960/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2020-11-28 20:58 UTC, daosbuild1 commented on src/tests/ftest/io/posix_stat.py
> +class POSIXStatTest(IorTestBase):
(pylint-too-many-ancestors) Too many ancestors (9/7)

2020-11-28 20:58 UTC, daosbuild1 commented on src/tests/ftest/io/posix_stat.py
> +            unit = block_size[-1]
(pylint-unused-variable) Unused variable 'unit'

2020-11-28 20:59 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3960/1/execution/node/57/log

2020-11-28 21:18 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3960/2/execution/node/58/log

2020-12-04 21:17 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-12-04 22:13 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3960/3/execution/node/59/log

2020-12-06 00:32 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3960/4/execution/node/59/log

2021-07-12 19:34 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3960/14/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-12 19:34 UTC, daosbuild1 commented on src/tests/ftest/io/posix_stat.py
> +from avocado.core.exceptions import TestFail
(pylint-unused-import) Unused TestFail imported from avocado.core.exceptions

2021-07-12 19:34 UTC, daosbuild1 commented on src/tests/ftest/io/posix_stat.py
> +from ior_test_base import IorTestBase
(pylint-unused-import) Unused IorTestBase imported from ior_test_base

2021-07-12 19:34 UTC, daosbuild1 commented on src/tests/ftest/io/posix_stat.py
> +from general_utils import get_remote_file_size, run_task
(pylint-unused-import) Unused get_remote_file_size imported from general_utils
(pylint-unused-import) Unused run_task imported from general_utils

2021-07-12 19:34 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3960/14/execution/node/100/log

2021-07-12 19:37 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-19 19:51 UTC, phender requested changes

2021-07-19 19:51 UTC, phender commented on src/tests/ftest/io/posix_stat.yaml
> +  scm_size: 1073741824
We don't need `mode:` anymore and we should use human-readable sizes:
```suggestion
  name: daos_server
  scm_size: 1G
```

2021-07-19 19:51 UTC, phender commented on src/tests/ftest/io/posix_stat.py
> +            current_epoch = cmd_output.split()[-1]
I'd suggest replacing this with the `general_utils.py` `run_pcmd()` method

2021-07-19 19:51 UTC, phender commented on src/tests/ftest/io/posix_stat.py
> +                self.hostlist_clients, "stat -c%Z {}".format(testfile_path))
The `self.run_ior_with_pool()` method updates the `self.ior_cmd.test_file` property with the `self.dfuse.mount_dir.value` + `"testfile"` as part of it's execution, so this method does not need to track/create it:
```suggestion
            task = run_task(
                self.hostlist_clients, "stat -c%Z {}".format(self.ior_cmd.test_file.value))
```

2021-07-19 19:51 UTC, phender commented on src/tests/ftest/io/posix_stat.py
> +        testfile_path_base = "/tmp/daos_dfuse/testfile"
The `self.run_ior_with_pool()` method updates the `self.ior_cmd.test_file` property with the `self.dfuse.mount_dir.value` + `"testfile"` as part of it's execution, so this method does not need to define it:
```suggestion
```

2021-07-19 19:51 UTC, phender commented on src/tests/ftest/io/posix_stat.py
> +                    [line.decode("utf-8") for line in output])
I'd suggest replacing this with the general_utils.py run_pcmd() method

2021-07-19 19:51 UTC, phender commented on src/tests/ftest/io/posix_stat.py
> +                self.hostlist_clients[0], testfile_path)
```suggestion
                self.hostlist_clients[0], self.ior_cmd.test_file.value)
```

2021-07-19 19:51 UTC, phender commented on src/tests/ftest/io/posix_stat.py
> +        self.stop_dfuse()
This can be removed as stopping dfuse is performed as part of `tearDown()` through the `DfuseTestBase.stop_job_managers()` method.

2021-07-20 13:25 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3960/25/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-20 13:25 UTC, daosbuild1 commented on src/tests/ftest/io/posix_stat.py
> +            self.log.info("date stdout = {}".format(stdout))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-07-20 13:25 UTC, daosbuild1 commented on src/tests/ftest/io/posix_stat.py
> +            self.log.info("stat stdout = {}".format(stdout))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-07-20 13:25 UTC, daosbuild1 commented on src/tests/ftest/io/posix_stat.py
> +            cmd_output = ""
(pylint-unused-variable) Unused variable 'cmd_output'

2021-07-20 13:25 UTC, daosbuild1 commented on src/tests/ftest/io/posix_stat.py
> +from apricot import TestWithServers
(pylint-unused-import) Unused TestWithServers imported from apricot

2021-07-20 13:25 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3960/25/execution/node/99/log

2021-07-20 14:36 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3960/26/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-20 14:36 UTC, daosbuild1 commented on src/tests/ftest/io/posix_stat.py
> +            self.log.info("date stdout = %s".format(stdout))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions
(pylint-too-many-format-args) Too many arguments for format string

2021-07-20 14:36 UTC, daosbuild1 commented on src/tests/ftest/io/posix_stat.py
> +            self.log.info("stat stdout = %s".format(stdout))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions
(pylint-too-many-format-args) Too many arguments for format string

2021-07-20 14:36 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3960/26/execution/node/88/log

2021-07-20 14:42 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-20 17:54 UTC, phender approved these changes

2021-07-21 13:24 UTC, dinghwah approved these changes
LGTM.

2021-07-22 05:22 UTC, sylviachanoiyee commented
Could you document the test steps here? Thanks!
https://wiki.hpdd.intel.com/display/DAOS/IO+Test+Plan

2021-07-27 18:49 UTC, merged