simple program to demo TX restarts.
daos-stack/daos pull request #3987
Opened 2020-12-02 00:04 UTC by mchaarawi

Skip-checkpatch: true
Skip-build: true
Skip-unit-tests: true
Skip-test: true

Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>

2020-12-07 19:41 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3987/7/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2020-12-07 19:41 UTC, daosbuild1 commented on src/client/array/dc_array.c
> +		D_DEBUG(DB_IO, "DKEY IOD "DF_U64": idx = "DF_U64"\t num_records = %zu"
(style)  line over 80 characters

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +		//rc = daos_obj_punch_dkeys(oh, th, 0, 1, &dkey, NULL);
(style)  do not use C99 // comments

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +		//ASSERT(rc == 0, "object punch failed with %d", rc);
(style)  do not use C99 // comments

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +			printf("Commit on rank %d failed with %s\n", rank, d_errstr(rc));
(style)  line over 80 characters

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +			ASSERT(rc == -DER_TX_RESTART, "invalid error from commit");
(style)  line over 80 characters

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +		ASSERT(rc == 0, "daos_tx_close() failed with %d\n", rc);
(style)  trailing whitespace

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +			printf("Rank 0 insert same Key with different value.\n");
(style)  line over 80 characters

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +			rc = daos_kv_put(oh, th, 0, "KeyA", sizeof(int), &val, NULL);
(style)  line over 80 characters

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +			/** this gets delayed now for some reason (simulate with barrier) */
(style)  line over 80 characters

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +			printf("Commit on rank %d failed with %s\n", rank, d_errstr(rc));
(style)  line over 80 characters

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +			ASSERT(rc == -DER_TX_RESTART, "invalid error from commit");
(style)  line over 80 characters

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +		ASSERT(rc == 0, "daos_tx_close() failed with %d\n", rc);
(style)  trailing whitespace

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +
(style)  trailing whitespace

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +		//ASSERT(rc == 0, "object punch failed with %d", rc);
```suggestion
		/* rc = daos_obj_punch_dkeys(oh, th, 0, 1, &dkey, NULL); */
		/* ASSERT(rc == 0, "object punch failed with %d", rc); */
```

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +		ASSERT(rc == 0, "daos_tx_close() failed with %d\n", rc);
```suggestion
		ASSERT(rc == 0, "daos_tx_close() failed with %d\n", rc);
```

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +		ASSERT(rc == 0, "daos_tx_close() failed with %d\n", rc);
```suggestion
		ASSERT(rc == 0, "daos_tx_close() failed with %d\n", rc);
```

2020-12-07 19:41 UTC, daosbuild1 commented on src/tests/dtx_demo.c
> +
```suggestion

```

2020-12-07 19:41 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-3987/7/execution/node/59/log

2021-01-06 19:51 UTC, jolivier23 requested changes
Do you intend to update this and land it or is it just for reference?

2021-01-06 19:54 UTC, mchaarawi commented
> Do you intend to update this and land it or is it just for reference?

no this was just for the demo, closing

2021-01-06 19:54 UTC, closed without merging