dfuse: Enable writeback caching in kernel.
daos-stack/daos pull request #3992
Opened 2020-12-02 12:51 UTC by ashleypittman

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

2020-12-02 13:09 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-01-15 14:15 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-03-26 17:19 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-03-26 21:11 UTC, johannlombardi requested changes
Need some changes with on the timestamp management:

tar: daos/debian/daos-client.dirs: Cannot utime: Operation not supported

We should land this patch, even if it is enabled only when mounting a single container.

2021-04-19 10:55 UTC, ashleypittman commented
Included in https://github.com/daos-stack/daos/pull/4540

2021-04-19 10:55 UTC, closed without merging