DAOS-5479 dmg/vmd: Set FAULT state on VMD LED when device is evicted
daos-stack/daos pull request #4000
Opened 2020-12-03 00:06 UTC by sydneyvanda

Add transport address param to the dmg storage set nvme-faulty command.
$dmg storage set nvme-faulty --uuid=DEV_UUID --traddr=TRADDR

When a device is manually evicted via the command above, also set the
LED device state to a FAULTY ("on") state if the device is a VMD
supported device. If the device is just a regular NVMe deivce, then
the device will just be evicted.

Signed-off-by: Sydney Vanda <sydney.m.vanda@intel.com>

2020-12-03 00:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-12-03 00:33 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4000/1/execution/node/285/log

2020-12-03 00:34 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4000/1/execution/node/224/log

2020-12-03 00:38 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4000/1/execution/node/291/log

2020-12-03 01:11 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4000/1/execution/node/625/log

2020-12-03 06:45 UTC, NiuYawei requested changes
Get rid of the 'traddr' option can save lot of changes in control plane.

2020-12-04 21:00 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4000/2/execution/node/59/log

2020-12-05 02:50 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4000/3/execution/node/59/log

2020-12-07 06:14 UTC, NiuYawei approved these changes

2020-12-07 14:25 UTC, tanabarr approved these changes

2020-12-08 00:13 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-12-08 02:14 UTC, NiuYawei approved these changes

2020-12-08 09:13 UTC, tanabarr approved these changes

2020-12-08 09:16 UTC, tanabarr commented
I%s this intentionally a very small PR or did some of the commits get lost somewhere?
Also with regard to the to do to check if the device is VMD, was that removed because it's no longer necessary?

2020-12-08 15:28 UTC, sydneyvanda commented
> I%s this intentionally a very small PR or did some of the commits get lost somewhere?
> Also with regard to the to do to check if the device is VMD, was that removed because it's no longer necessary?

@tanabarr yes this was a small PR (it was just on top of #3950). and they check for VMD was removed because it is done later in BIO code. we can think about moving this into the control plane at some point when refactoring and adding unit tests to the VMD LED commands, which I filed a ticket for (DAOS-6236).

2020-12-09 13:25 UTC, merged