DAOS-6172 test:allow hugepages to be set in yaml
daos-stack/daos pull request #4079
Opened 2020-12-10 23:10 UTC by mjean308

Test-tag-hw-large: pr,hw,large soak_smoke

Signed-off-by: Maureen Jean <maureen.jean@intel.com>

2020-12-10 23:31 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-12-11 13:02 UTC, mjean308 commented
Verified that nr_hugepages is set correctly
  /usr/bin/daos_server storage prepare --force --hugepages=8192 --target-user=root

2020-12-11 15:55 UTC, phender requested changes

2020-12-11 15:55 UTC, phender commented on src/tests/ftest/util/server_utils.py
> +            hugepages = self.manager.job.yaml.get_value("nr_hugepages")
The safer method to perform the same action - https://github.com/daos-stack/daos/blob/master/src/tests/ftest/util/command_utils.py#L949:
```suggestion
            hugepages = self.get_config_value("nr_hugepages")
```

2020-12-12 16:50 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-12-14 22:36 UTC, saurabhtandan approved these changes
LGTM

2020-12-16 18:10 UTC, phender approved these changes

2020-12-16 18:13 UTC, merged