DAOS-5999 tests: re-enable OID subtest 3
daos-stack/daos pull request #4120
Opened 2020-12-16 00:05 UTC by wangdi1

Since DAOS-6187 has been fixed, let's re-enable OID
subtest 3.

Signed-off-by: Di Wang <di.wang@intel.com>

2020-12-16 00:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2020-12-16 00:36 UTC, jolivier23 approved these changes

2020-12-16 14:00 UTC, mchaarawi approved these changes

2020-12-16 14:39 UTC, phender requested changes
Blocking this as the OID test didn't pass: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4120/1/artifact/Functional/job-2020-12-16T12.02-9e4964b-daos_test-daos_core_test/job.log:
```
2020-12-16 12:40:44,638 test             L0179 INFO | *** TEARDOWN called due to TIMEOUT: 320 second timeout exceeded ***
```

Is the [timeout](https://github.com/daos-stack/daos/blob/master/src/tests/ftest/daos_test/daos_core_test.yaml#L135) reasonable for this variant?

2020-12-16 14:49 UTC, wangdi1 commented
> Blocking this as the OID test didn't pass: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4120/1/artifact/Functional/job-2020-12-16T12.02-9e4964b-daos_test-daos_core_test/job.log:
> 
> ```
> 2020-12-16 12:40:44,638 test             L0179 INFO | *** TEARDOWN called due to TIMEOUT: 320 second timeout exceeded ***
> ```
> 
> Is the [timeout](https://github.com/daos-stack/daos/blob/master/src/tests/ftest/daos_test/daos_core_test.yaml#L135) reasonable for this variant?

Hmm, it looks like rebuild is finished, and it still hangs during psr look up.  I am not sure if the timeout is enough for PSR lookup to recover. Probably we need some further work on DAOS-6187. I will check. Thanks.

2021-01-13 17:40 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-01-15 18:53 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-01-19 20:34 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-01-22 06:55 UTC, wangdi1 commented
OID rebuild test has been passed on current master after PR-2854 is landed. https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4120/4/artifact/Functional/job-2021-01-20T02.06-e72d2dc-daos_test-daos_core_test/test-results/19-._daos_test_daos_core_test.py%3ADaosCoreTest.test_subtest%3Btransport_config-test_O-num_clients-transport_config-hosts-pool-0-1-transport_config-32f7/debug.log

2021-01-25 13:59 UTC, mchaarawi approved these changes

2021-01-28 15:05 UTC, jolivier23 approved these changes

2021-01-28 15:06 UTC, merged