DAOS-6264: cart_logparse.py", line 127, in __init__: KeyError: 'DAOS[2502/2502]'
daos-stack/daos pull request #4206
Opened 2021-01-06 20:15 UTC by mallove79

CaRT might print a malformed line to the log file, e.g., here CaRT process 1071
appears to exit while printing to the log file:

  ...
  12/09-01:15:24.00 wolf-106vm2 DAOS[1071/1071] server INFO src/iosrv/module.c:335 dss_module_cleanup_all() Module cont: no sm_cleanup func
  12/09-01:15:24.00 wolf-106vm2 DAOS[1071/12/09-01:15:37.72 wolf-106vm2 DAOS[2502/2502] fi   INFO src/gurt/fault_inject.c:489 d_fault_inject_init() No config file, fault injection is OFF.
  ...

See https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/3296/artifact/Functional/job-2020-12-09T01.14-ce44a76-security-cont_delete_acl/daos_logs/daos_server.wolf-106vm2.cart_logtest.log

Warn user of malformed logline, but report on the lines which are not malformed.

Skip-build-leap15-rpm: true
Skip-build-ubuntu-clang: true
Skip-build-leap15-icc: true
Skip-coverity-test: true
Skip-checkpatch: true
Quick-build: true
Test-tag: dont-run-anything
Skip-func-test-leap15: true
Skip-func-hw-test-small: true
Skip-func-hw-test-medium: true
Skip-func-hw-test-large: true

Signed-off-by: Ethan Mallove <ethanx.a.mallove@intel.com>

2021-01-06 20:59 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4206/1/execution/node/400/log

2021-01-06 21:40 UTC, daosbuild1 commented
Test stage NLT completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4206/1/execution/node/507/log

2021-01-07 13:42 UTC, ashleypittman requested changes
I'm against this, as it'll mean that we only log, not fail on corrupt log files so we won't detect regressions.

The bug is that the log is corrupt, so we should fix the bug, not ignore the problem when it happens.

2021-01-08 00:30 UTC, mallove79 commented
> I'm against this, as it'll mean that we only log, not fail on corrupt log files so we won't detect regressions.
> 
> The bug is that the log is corrupt, so we should fix the bug, not ignore the problem when it happens.

Hi @ashleypittman , thank you for reviewing this.

The original bug report points to a [passing test](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/3296/testReport/(root)/DeleteContainerACLTest) (since the exit status of the test is as expected?) Does something turn red on a `cart_logparse` falilure?  `avocado` returns an [error result](https://avocado-framework.readthedocs.io/en/52.0/api/test/avocado.html#avocado.Test.error) instead of a [failure result](https://avocado-framework.readthedocs.io/en/52.0/api/test/avocado.html#avocado.Test.fail) on the python exception. Closing this PR, as we prefer a python stacktrace on a bad log line, instead of parsed cart log with log parse warning:

```
Pid 2502, 42 lines total, 0 trace (0.00%)
Parsed 127 lines of logs
Most common logging locations
Logging used 16 times at src/iosrv/drpc_progress.c:295 (12.6%)
Logging used 16 times at src/iosrv/drpc_progress.c:409 (12.6%)
Most common facilities
server: 42 (33.1%)
daos: 32 (25.2%)
mgmt: 15 (11.8%)
Most common levels
INFO: 97 (76.4%)
WARN: 27 (21.3%)
```

2021-01-08 00:30 UTC, closed without merging

2021-01-08 07:56 UTC, ashleypittman commented
> > I'm against this, as it'll mean that we only log, not fail on corrupt log files so we won't detect regressions.
> > The bug is that the log is corrupt, so we should fix the bug, not ignore the problem when it happens.
> 
> Hi @ashleypittman , thank you for reviewing this.
> 
> The original bug report points to a [passing test](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/3296/testReport/(root)/DeleteContainerACLTest) (since the exit status of the test is as expected?) Does something turn red on a `cart_logparse` falilure? `avocado` returns an [error result](https://avocado-framework.readthedocs.io/en/52.0/api/test/avocado.html#avocado.Test.error) instead of a [failure result](https://avocado-framework.readthedocs.io/en/52.0/api/test/avocado.html#avocado.Test.fail) on the python exception. Closing this PR, as we prefer a python stacktrace on a bad log line, instead of parsed cart log with log parse warning:

The log parsing happens in post-processing, so outside the test.  I believe there is work afoot to create a extra "test" for the log parsing of each test to improve reporting.  Failure of logparse itself, or detection of errors will result in job failure which prevents landing but is difficult to debug.

Printing warning messages from logparse is not checked, simply the exit code.  Specifically on log parsing only some areas will fail, it would be quite possible for lines to be spliced in a way that they appear correct, we only spotted it this time because it affected the preamble at the start of the line, so there's possibly a 30% chance of us hitting this.  Log splicing could also mean that for example D_ALLOC() or D_FREE() lines were missed, which would lead to log parsing reporting errors, however very few if any tests run with this much debugging enabled.