DAOS-6184: daos_core_base.py overrides timeout values w/o logging
daos-stack/daos pull request #4217
Opened 2021-01-07 17:48 UTC by omar-ocampo

Added a logging message to let tester know the timeout
    has been updated based on the test yaml test_timeout value.

Signed-off-by: Omar Ocampo <omar.ocampo.coronado@intel.com>

2021-01-07 17:49 UTC, omar-ocampo commented
One of the ideas discussed to centralize all timeout-related functions was to move test_timeout variable to apricot test class however, it implies also move self.TEST_PATH from daos_core_base.py, to apricot and it does not make much sense to do as it is only for daos_core related tests. A better approach would be to modify all the yaml files to use a single timeout style, although I believe that is out of the scope of this ticket.

2021-01-07 17:59 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4217/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-01-07 17:59 UTC, daosbuild1 commented on src/tests/ftest/util/daos_core_base.py
> +            self.log.info("Test timeout updated to {timeout}".format(
(pylint-logging-format-interpolation) Use % formatting in logging functions and pass the % parameters as arguments

2021-01-07 18:00 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4217/1/execution/node/60/log

2021-01-07 19:28 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-01-15 14:09 UTC, phender requested changes

2021-01-15 14:09 UTC, phender commented on src/tests/ftest/util/daos_core_base.py
> +            self.log.info("Test timeout updated to %s", test_timeout)
Please review https://jira.hpdd.intel.com/browse/DAOS-6184?focusedCommentId=254614&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-254614 and let me know your thoughts.  I think we should still be able to implement what we discussed in apricot Test.

2021-01-19 22:09 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-17 17:46 UTC, closed without merging