DAOS-6443 test: Expand cancel for ticket
daos-stack/daos pull request #4256
Opened 2021-01-12 14:58 UTC by mjean308

Test-tag-hw-large: pr,hw,large soak_smoke

This ticket will add code to test.py to support
Cancel for ticket for specified parameters/conditions
in single variant, multiple parameter type testcases
like soak and iorsmall

Signed-off-by: Maureen Jean <maureen.jean@intel.com>

2021-01-12 15:10 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_utils.py:583](https://github.com/daos-stack/daos/blob/140a52cd15524d0bab267d39fd11a5c9c2f3833b/src/tests/ftest/soak/soak_utils.py#L583):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2021-01-12 16:48 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_utils.py:585](https://github.com/daos-stack/daos/blob/f74220d6a411c31d05d0e36b0251c5961cfcaac2/src/tests/ftest/soak/soak_utils.py#L585):
(pylint-too-many-nested-blocks) Too many nested blocks (6/5)

2021-01-12 22:48 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_test_base.py:42](https://github.com/daos-stack/daos/blob/4edc689133108599dd404f5bc261f3f67d589506/src/tests/ftest/soak/soak_test_base.py#L42):
(pylint-too-many-instance-attributes) Too many instance attributes (31/30)

[src/tests/ftest/soak/soak_test_base.py:197](https://github.com/daos-stack/daos/blob/4edc689133108599dd404f5bc261f3f67d589506/src/tests/ftest/soak/soak_test_base.py#L197):
(pylint-redefined-variable-type) Redefinition of job type from threading.Thread to multiprocessing.context.Process

2021-01-12 23:05 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4256/3/execution/node/264/log

2021-01-12 23:21 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_test_base.py:42](https://github.com/daos-stack/daos/blob/412e283e700f758ec535f19497f5943a0a0f5574/src/tests/ftest/soak/soak_test_base.py#L42):
(pylint-too-many-instance-attributes) Too many instance attributes (31/30)

[src/tests/ftest/soak/soak_test_base.py:197](https://github.com/daos-stack/daos/blob/412e283e700f758ec535f19497f5943a0a0f5574/src/tests/ftest/soak/soak_test_base.py#L197):
(pylint-redefined-variable-type) Redefinition of job type from threading.Thread to multiprocessing.context.Process

2021-01-13 00:20 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_test_base.py:42](https://github.com/daos-stack/daos/blob/d8a76ada49f2668b362c56670c03d86c255e74e3/src/tests/ftest/soak/soak_test_base.py#L42):
(pylint-too-many-instance-attributes) Too many instance attributes (31/30)

[src/tests/ftest/soak/soak_test_base.py:197](https://github.com/daos-stack/daos/blob/d8a76ada49f2668b362c56670c03d86c255e74e3/src/tests/ftest/soak/soak_test_base.py#L197):
(pylint-redefined-variable-type) Redefinition of job type from threading.Thread to multiprocessing.context.Process

2021-01-13 15:59 UTC, phender requested changes
Minor fixes if you need to make other changes.

2021-01-13 15:59 UTC, phender commented on src/tests/ftest/soak/soak_utils.py
> +                            o_type in ["RP_2G1", 'RP_2GX']):
Optional: PEP8 suggests something like this (https://www.python.org/dev/peps/pep-0008/#indentation):
```suggestion
                    if (api in ["HDF5-VOL", "HDF5", "POSIX"]
                            and t_size == "4k"
                            and o_type in ["RP_2G1", 'RP_2GX']):
```

2021-01-13 15:59 UTC, phender commented on src/tests/ftest/util/apricot/apricot/test.py
> +            ticket (object): the ticket (str) or group of tickets (list)
```suggestion
            ticket (object): the ticket (str) or group of tickets (set)
```

2021-01-13 15:59 UTC, phender commented on src/tests/ftest/util/apricot/apricot/test.py
> +                that cause this test case to be cancelled.
```suggestion
            ticket (str): the ticket (str) used to cancel the test
```

2021-01-13 15:59 UTC, phender commented on src/tests/ftest/util/apricot/apricot/test.py
> +        self._teardown_cancel = set()
I wonder if we should add a comment here:
```
        # When cancelling within a test variant, use 'add_cancel_ticket(<ticket>)' to add to this set.
```

2021-01-13 18:17 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4256/7/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_test_base.py:42](https://github.com/daos-stack/daos/blob/43c66521962009df5ef6480f955018c6dc64149c/src/tests/ftest/soak/soak_test_base.py#L42):
(pylint-too-many-instance-attributes) Too many instance attributes (31/30)

[src/tests/ftest/soak/soak_test_base.py:197](https://github.com/daos-stack/daos/blob/43c66521962009df5ef6480f955018c6dc64149c/src/tests/ftest/soak/soak_test_base.py#L197):
(pylint-redefined-variable-type) Redefinition of job type from threading.Thread to multiprocessing.context.Process

2021-01-13 18:17 UTC, daosbuild1 commented on src/tests/ftest/util/apricot/apricot/test.py
> +        # When cancelling within a test variant,
```suggestion
        # When canceling within a test variant,
```

2021-01-13 18:17 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4256/7/execution/node/67/log

2021-01-13 22:43 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4256/8/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_test_base.py:36](https://github.com/daos-stack/daos/blob/4ba1f1157ce1b0c569b365f61fc55922a877f0cd/src/tests/ftest/soak/soak_test_base.py#L36):
(pylint-import-error) Unable to import 'soak_utils'

[src/tests/ftest/soak/soak_test_base.py:42](https://github.com/daos-stack/daos/blob/4ba1f1157ce1b0c569b365f61fc55922a877f0cd/src/tests/ftest/soak/soak_test_base.py#L42):
(pylint-too-many-instance-attributes) Too many instance attributes (31/30)

[src/tests/ftest/soak/soak_test_base.py:197](https://github.com/daos-stack/daos/blob/4ba1f1157ce1b0c569b365f61fc55922a877f0cd/src/tests/ftest/soak/soak_test_base.py#L197):
(pylint-redefined-variable-type) Redefinition of job type from threading.Thread to multiprocessing.context.Process

2021-01-13 22:43 UTC, daosbuild1 commented on src/tests/ftest/util/apricot/apricot/test.py
> +        # When cancelling within a test variant,
```suggestion
        # When canceling within a test variant,
```

2021-01-13 22:43 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4256/8/execution/node/66/log

2021-01-14 00:02 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_test_base.py:36](https://github.com/daos-stack/daos/blob/c19749984acd1a438e352153bf3e9d1f077ccc8e/src/tests/ftest/soak/soak_test_base.py#L36):
(pylint-import-error) Unable to import 'soak_utils'

[src/tests/ftest/soak/soak_test_base.py:42](https://github.com/daos-stack/daos/blob/c19749984acd1a438e352153bf3e9d1f077ccc8e/src/tests/ftest/soak/soak_test_base.py#L42):
(pylint-too-many-instance-attributes) Too many instance attributes (31/30)

[src/tests/ftest/soak/soak_test_base.py:197](https://github.com/daos-stack/daos/blob/c19749984acd1a438e352153bf3e9d1f077ccc8e/src/tests/ftest/soak/soak_test_base.py#L197):
(pylint-redefined-variable-type) Redefinition of job type from threading.Thread to multiprocessing.context.Process

2021-01-14 09:37 UTC, shimizukko submitted a review, later dismissed
LGTM

2021-01-14 12:52 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_test_base.py:36](https://github.com/daos-stack/daos/blob/e6c4ff275baf422ff21e982e9a96fdc008e5636e/src/tests/ftest/soak/soak_test_base.py#L36):
(pylint-import-error) Unable to import 'soak_utils'

[src/tests/ftest/soak/soak_test_base.py:42](https://github.com/daos-stack/daos/blob/e6c4ff275baf422ff21e982e9a96fdc008e5636e/src/tests/ftest/soak/soak_test_base.py#L42):
(pylint-too-many-instance-attributes) Too many instance attributes (31/30)

[src/tests/ftest/soak/soak_test_base.py:197](https://github.com/daos-stack/daos/blob/e6c4ff275baf422ff21e982e9a96fdc008e5636e/src/tests/ftest/soak/soak_test_base.py#L197):
(pylint-redefined-variable-type) Redefinition of job type from threading.Thread to multiprocessing.context.Process

2021-01-14 16:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_test_base.py:36](https://github.com/daos-stack/daos/blob/3b99dd3ef16e5a1705d93b08f42b0671809857a5/src/tests/ftest/soak/soak_test_base.py#L36):
(pylint-import-error) Unable to import 'soak_utils'

[src/tests/ftest/soak/soak_test_base.py:42](https://github.com/daos-stack/daos/blob/3b99dd3ef16e5a1705d93b08f42b0671809857a5/src/tests/ftest/soak/soak_test_base.py#L42):
(pylint-too-many-instance-attributes) Too many instance attributes (31/30)

[src/tests/ftest/soak/soak_test_base.py:197](https://github.com/daos-stack/daos/blob/3b99dd3ef16e5a1705d93b08f42b0671809857a5/src/tests/ftest/soak/soak_test_base.py#L197):
(pylint-redefined-variable-type) Redefinition of job type from threading.Thread to multiprocessing.context.Process

2021-01-14 19:38 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_test_base.py:36](https://github.com/daos-stack/daos/blob/ee665cf35ac5b527e468745e275416f39cce17df/src/tests/ftest/soak/soak_test_base.py#L36):
(pylint-import-error) Unable to import 'soak_utils'

[src/tests/ftest/soak/soak_test_base.py:42](https://github.com/daos-stack/daos/blob/ee665cf35ac5b527e468745e275416f39cce17df/src/tests/ftest/soak/soak_test_base.py#L42):
(pylint-too-many-instance-attributes) Too many instance attributes (31/30)

[src/tests/ftest/soak/soak_test_base.py:197](https://github.com/daos-stack/daos/blob/ee665cf35ac5b527e468745e275416f39cce17df/src/tests/ftest/soak/soak_test_base.py#L197):
(pylint-redefined-variable-type) Redefinition of job type from threading.Thread to multiprocessing.context.Process

2021-01-15 13:20 UTC, shimizukko approved these changes
LGTM

2021-01-15 17:43 UTC, saurabhtandan approved these changes
LGTM

2021-01-20 16:24 UTC, phender approved these changes

2021-01-20 16:26 UTC, merged