DAOS-6452 test: Disable Dmg pool query basic test
daos-stack/daos pull request #4260
Opened 2021-01-12 20:40 UTC by sylviachanoiyee

Disabling cmd pool query basic test for DAOS-6452

2021-01-12 20:42 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4260/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-01-12 20:42 UTC, daosbuild1 commented on src/tests/ftest/control/dmg_pool_query_test.py
> +    @skipForTicket("DAOS-6452")
(pylint-undefined-variable) Undefined variable 'skipForTicket'

2021-01-12 20:42 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4260/1/execution/node/60/log

2021-01-12 21:24 UTC, brianjmurrell requested changes

2021-01-12 21:24 UTC, brianjmurrell commented on src/tests/ftest/control/dmg_pool_query_test.py
> +    @skipForTicket("DAOS-6452")
You need to import this to use it.

2021-01-12 21:55 UTC, jolivier23 approved these changes

2021-01-12 21:56 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-01-13 14:42 UTC, brianjmurrell approved these changes

2021-01-13 15:07 UTC, merged