DAOS-6045 Agent: Data race in agent attachInfoCache
daos-stack/daos pull request #4294
Opened 2021-01-14 22:41 UTC by jbrosenz

Reworked access to aic.defaultNumaNode so that it now
    has mutex protection to avoid a data race between the
    initResponseCache() that initializes it, and the
    handleGetAttachInfo() that reads it.

Signed-off-by: Joel Rosenzweig <joel.b.rosenzweig@intel.com>

2021-01-14 22:43 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-01-15 18:24 UTC, mjmac requested changes

2021-01-15 18:24 UTC, mjmac commented on src/control/cmd/daos_agent/mgmt_rpc.go
>  		numaNode, err = netdetect.GetNUMASocketIDForPid(mod.netCtx, pid)
There is still an unsynchronized write here. I think you'll need to move the lock up to protect it.

2021-01-15 18:43 UTC, mjmac approved these changes

2021-01-15 19:03 UTC, kjacque approved these changes

2021-01-15 20:53 UTC, jbrosenz commented
The NLT failure is unrelated to this PR.  Still waiting on Functional Hardware Large results.

2021-01-15 21:17 UTC, tanabarr approved these changes

2021-01-15 22:25 UTC, jbrosenz commented
All tests passing, excluding the erroneous NLT which does not relate to this PR.

2021-01-19 17:42 UTC, merged