CART=89 mercury: Update to mercury v2.0.1rc1
daos-stack/daos pull request #4375
Opened 2021-01-22 06:32 UTC by frostedcmos

- Update to mercury v2.0.1rc1
- Modify memcheck suppresion file to include broader code path
- Mercury for now will be built with build of testing being disabled

Test-tag-vm: pr,-hw daily_regression,-hw
Test-tag-hw-small: pr,hw,small daily_regression,hw,small
Test-tag-hw-medium: pr,hw,medium,ib2 daily_regression,hw,medium,ib2
Test-tag-hw-large: pr,hw,large daily_regression,hw,large

Signed-off-by: Alexander Oganezov <alexander.a.oganezov@intel.com>

2021-01-22 06:34 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-01-22 20:18 UTC, frostedcmos commented
The 1 failure is due to https://jira.hpdd.intel.com/browse/DAOS-6588

2021-01-22 21:05 UTC, brianjmurrell requested changes

2021-01-22 21:05 UTC, brianjmurrell commented on utils/rpms/daos.spec
>  %endif
I don't think we need this branch any more:
```suggestion
%global mercury_version 2.0.1~rc1-1%{?dist}
￼```

2021-01-22 23:12 UTC, jolivier23 submitted a review, later dismissed

2021-01-22 23:38 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-01-23 00:17 UTC, jolivier23 submitted a review, later dismissed

2021-01-24 07:30 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-01-24 21:12 UTC, jolivier23 approved these changes

2021-01-25 17:54 UTC, brianjmurrell approved these changes

2021-01-25 21:19 UTC, merged