CORCI-1042 test: Reenable hdf5/vol unit tests
daos-stack/daos pull request #4427
Opened 2021-01-27 01:39 UTC by mjean308

PR-repo: hdf5@PR-20 hdf5-vol-daos@PR-10 ior-hpc@PR13 MACSio@PR-7
Skip-unit-tests: true
Skip-func-hw-test-medium: true
Test-tag-hw-large: macsio_daos_vol iorsmall saok_smoke macsio_daos vol hdf5

Signed-off-by: Maureen Jean <maureen.jean@intel.com>

2021-01-27 01:41 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-01-27 12:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-01-27 15:18 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-01-27 18:00 UTC, brianjmurrell commented
Please retry this with `ior-hpc@PR-13 MACSio@PR-7` removed from `PR-repos:`.  Those should not need a rebuild.  Shared libraries take care of this for us.

And note that your commit message had a typo in that pragma.  It had: `PR-repo:`.

2021-01-28 06:15 UTC, daosbuild1 commented
Test stage Functional_Hardware_Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4427/3/execution/node/1113/log

2021-01-29 06:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-01-29 06:29 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4427/4/execution/node/314/log

2021-01-29 06:33 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4427/4/execution/node/259/log

2021-01-29 06:36 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4427/4/execution/node/317/log

2021-01-29 12:55 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4427/5/execution/node/238/log

2021-01-29 13:00 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4427/5/execution/node/210/log

2021-01-29 13:02 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4427/5/execution/node/235/log

2021-01-29 14:55 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4427/6/execution/node/241/log

2021-01-29 15:00 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4427/6/execution/node/235/log

2021-01-29 15:08 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4427/6/execution/node/238/log

2021-01-29 16:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-01-29 16:30 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4427/7/execution/node/342/log

2021-01-29 16:34 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4427/7/execution/node/288/log

2021-01-29 16:37 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4427/7/execution/node/338/log

2021-01-29 21:04 UTC, daosbuild1 commented
Test stage Functional_Hardware_Large completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4427/8/display/redirect

2021-01-29 21:08 UTC, daosbuild1 commented
Test stage Functional_Hardware_Small completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4427/8/display/redirect

2021-01-30 12:55 UTC, shimizukko approved these changes
LGTM

2021-01-31 23:53 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4427/16/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-01-31 23:53 UTC, daosbuild1 commented on src/tests/ftest/io/daos_vol_bigio.py
> +            daos vol connector and mpich. Testing various I/O functions
(style)  trailing whitespace

2021-01-31 23:53 UTC, daosbuild1 commented on src/tests/ftest/io/daos_vol_bigio.py
> +
(style)  trailing whitespace

2021-01-31 23:53 UTC, daosbuild1 commented on src/tests/ftest/io/daos_vol_bigio.py
> +            daos vol connector and mpich. Testing various I/O functions
```suggestion
            daos vol connector and mpich. Testing various I/O functions
```

2021-01-31 23:53 UTC, daosbuild1 commented on src/tests/ftest/io/daos_vol_bigio.py
> +
```suggestion

```

2021-01-31 23:53 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4427/16/execution/node/68/log

2021-02-01 03:04 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:104](https://github.com/daos-stack/daos/blob/60c070af3ac0e4e3f4f2c5db1482233f86a24880/src/tests/ftest/util/ior_test_base.py#L104):
(pylint-too-many-arguments) Too many arguments (11/10)

2021-02-01 21:52 UTC, saurabhtandan submitted a review, later dismissed
LGTM

2021-02-01 23:09 UTC, phender requested changes

2021-02-01 23:09 UTC, phender commented on src/tests/ftest/io/ior_small.py
> +                        self.ior_cmd.flags.update(flags.append("-k"))
```suggestion
                        flags_w_k = " ".join([flags[0]] + ["-k"])
                        self.ior_cmd.flags.update(flags_w_k)
```

2021-02-01 23:09 UTC, phender commented on src/tests/ftest/io/ior_small.py
> +                        dfuse_mount_dir = "/".join(["/tmp/daos_dfuse", sub_dir])
```suggestion
                        mount_dir = self.params.get("mount_dir", "/run/dfuse/*")
                        dfuse_mount_dir = os.path.join(mount_dir, sub_dir)
```

2021-02-01 23:40 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:104](https://github.com/daos-stack/daos/blob/23dd4f06f30b8e9515d6959ce1b6adc5d5e80fd6/src/tests/ftest/util/ior_test_base.py#L104):
(pylint-too-many-arguments) Too many arguments (11/10)

2021-02-02 00:01 UTC, phender approved these changes

2021-02-02 00:23 UTC, saurabhtandan approved these changes
LGTM

2021-02-02 12:06 UTC, shimizukko approved these changes
LGTM

2021-02-02 13:01 UTC, mjean308 commented
The single failure is due to a timeout in daos_core_test Epoch Recovery Test 15.   

This is a known failure - DAOS-6590.    However DAOS-6590  was duped to DAOS-6544 which only disabled daos_test -m, not test 15 so this test continues to run in CI.   It appears to be intermittent.

2021-02-02 14:37 UTC, merged