DAOS-6554 vos: return error when key larger than anchor
daos-stack/daos pull request #4514
Opened 2021-02-03 03:37 UTC by NiuYawei

Return error when key is larger than anchor, instead of asserting
key is always smaller than anchor.

Signed-off-by: Niu Yawei <yawei.niu@intel.com>

2021-02-03 03:39 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-03 12:57 UTC, jolivier23 requested changes
I think we should keep the asserts in encode/decode but add an error on insert if a direct key exceeds the limit.  Aggregation will have to iterate them even if the user doesn't so we can't really support them properly unless we fix the anchor protocol

2021-02-04 04:00 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-04 04:52 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4514/2/execution/node/755/log

2021-02-04 04:54 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4514/2/execution/node/758/log

2021-02-04 15:21 UTC, jolivier23 submitted a review, later dismissed

2021-02-04 16:20 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-04 17:26 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4514/3/execution/node/708/log

2021-02-04 17:31 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4514/3/execution/node/722/log

2021-02-05 01:51 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-07 04:31 UTC, NiuYawei commented
All CI tests passed, but daos_vol tests definitely insert long dkeys.

Server log from daos_vol test:
``
02/05-04:31:45.42 wolf-135 DAOS[45492/45765] tree ERR  src/common/btree.c:483 btr_rec_alloc() Key size (66560) > Anchor size (100)
02/05-04:31:45.42 wolf-135 DAOS[45492/45765] vos  ERR  src/vos/vos_tree.c:1062 key_tree_prepare() Failed to upsert: DER_MISC(-1025): 'Miscellaneous error'
02/05-04:31:45.42 wolf-135 DAOS[45492/45765] vos  ERR  src/vos/vos_io.c:1604 dkey_update() Error preparing dkey tree: rc=DER_MISC(-1025): 'Miscellaneous error'
02/05-04:31:45.42 wolf-135 DAOS[45492/45765] vos  ERR  src/vos/vos_io.c:2072 vos_update_end() Failed to update tree index: DER_MISC(-1025): 'Miscellaneous error'
``

Client test log from daos_vol test:
``
2021-02-05 04:31:45,634 process          L0479 DEBUG| [stdout] Testing soft link creation with a long name                           *FAILED*
2021-02-05 04:31:45,634 process          L0479 DEBUG| [stderr]   #000: /builddir/build/BUILD/vol-daos-1.1.0rc2/src/daos_vol_link.c line 2348 in H5_daos_link_create(): link creation failed in task "link write": miscellaneous error (DER_MISC)
2021-02-05 04:31:45,634 process          L0479 DEBUG| [stdout]     couldn't create soft link with a long name
2021-02-05 04:31:45,634 process          L0479 DEBUG| [stderr]     major: Links
2021-02-05 04:31:45,635 process          L0479 DEBUG| [stderr]     minor: Can't operate on object
2021-02-05 04:31:45,635 process          L0479 DEBUG| [stderr]   #001: /builddir/build/BUILD/vol-daos-1.1.0rc2/src/daos_vol.c line 3287 in H5_daos_h5op_finalize(): operation "soft link create" failed in task "link write": miscellaneous error (DER_MISC)
``

But the daos_vol was reported as PASS despite of all these failures.

I think we'd land this fix to avoid long direct dkey inserted, otherwise, it could trigger the assert on client enumeration or server aggregation.

2021-02-07 18:52 UTC, jolivier23 submitted a review, later dismissed

2021-02-08 15:23 UTC, mchaarawi commented
this is weird, because on my side i haven't seen those tests failing before.
in latest master run, they work fine:
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/3781/artifact/Functional/job-2021-02-08T06.32-fe676d5-io-daos_vol/job.log

aren't they supposed to cause server assertion or fail??
i don't think we should land this PR TBH before we understand and fix the issue.

2021-02-09 02:57 UTC, NiuYawei commented
> this is weird, because on my side i haven't seen those tests failing before.
> in latest master run, they work fine:
> https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/3781/artifact/Functional/job-2021-02-08T06.32-fe676d5-io-daos_vol/job.log
> 
> aren't they supposed to cause server assertion or fail??
> i don't think we should land this PR TBH before we understand and fix the issue.

@mchaarawi , in latest master, we don't reject long direct key, so you won't see test failures, and the daos_vol test always finish quickly (container is destroyed) before aggregation is triggered, so we don't observe the server assertion as well (it happens on VOS tree iteration only, like aggregation or processing enumeration request from client)

In one of my PR I hit the server assertion quite often, because there was a defect in my PR caused delay on container close, so the aggregation was triggered in daos_vol test and assertion was triggered.

2021-02-09 13:28 UTC, mchaarawi commented
> > this is weird, because on my side i haven't seen those tests failing before.
> > in latest master run, they work fine:
> > https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/3781/artifact/Functional/job-2021-02-08T06.32-fe676d5-io-daos_vol/job.log
> > aren't they supposed to cause server assertion or fail??
> > i don't think we should land this PR TBH before we understand and fix the issue.
> 
> @mchaarawi , in latest master, we don't reject long direct key, so you won't see test failures, and the daos_vol test always finish quickly (container is destroyed) before aggregation is triggered, so we don't observe the server assertion as well (it happens on VOS tree iteration only, like aggregation or processing enumeration request from client)
> 
> In one of my PR I hit the server assertion quite often, because there was a defect in my PR caused delay on container close, so the aggregation was triggered in daos_vol test and assertion was triggered.

yes I had a short chat with Jeff yesterday to explain this issue. i think we need to modify the VOL tests to shorten this key entry they write and rebuild the RPMs for that before we can land this patch though.

2021-02-10 02:20 UTC, NiuYawei commented
> > > this is weird, because on my side i haven't seen those tests failing before.
> > > in latest master run, they work fine:
> > > https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/3781/artifact/Functional/job-2021-02-08T06.32-fe676d5-io-daos_vol/job.log
> > > aren't they supposed to cause server assertion or fail??
> > > i don't think we should land this PR TBH before we understand and fix the issue.
> > 
> > 
> > @mchaarawi , in latest master, we don't reject long direct key, so you won't see test failures, and the daos_vol test always finish quickly (container is destroyed) before aggregation is triggered, so we don't observe the server assertion as well (it happens on VOS tree iteration only, like aggregation or processing enumeration request from client)
> > In one of my PR I hit the server assertion quite often, because there was a defect in my PR caused delay on container close, so the aggregation was triggered in daos_vol test and assertion was triggered.
> 
> yes I had a short chat with Jeff yesterday to explain this issue. i think we need to modify the VOL tests to shorten this key entry they write and rebuild the RPMs for that before we can land this patch though.

I didn't find the daos_vol test code, these tests are maintained by us or other groups?

2021-02-18 12:35 UTC, gnailzenh approved these changes

2021-02-19 02:15 UTC, NiuYawei commented on src/common/btree.c
> +			return DER_KEY2BIG;
indeed.

2021-02-19 02:15 UTC, NiuYawei commented on src/common/btree.c
> +		if (key->iov_len > EMBEDDED_KEY_MAX) {
ok

2021-02-19 02:21 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-20 04:56 UTC, jolivier23 approved these changes

2021-04-21 02:30 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-05-27 19:36 UTC, johannlombardi approved these changes

2021-05-27 19:37 UTC, merged