DAOS-5157 mgmt: report -DER_PROTO when getattachinfo from new server
daos-stack/daos pull request #4556
Opened 2021-02-05 11:04 UTC by Nasf-Fan

When 1.1.x client tries to getattachinfo from 1.2 server, the server
will not reply related ranks information. Currently, client reports
"Miscellaneous error (-1025)" under such case. That is some confused.
The patch changes it as "Incompatible protocol (-1014)".

Signed-off-by: Fan Yong <fan.yong@intel.com>

2021-02-05 11:24 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4556/1/execution/node/66/log

2021-02-05 12:46 UTC, daosbuild1 commented
Test stage Functional_Hardware_Small completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4556/1/display/redirect

2021-02-05 13:08 UTC, daosbuild1 commented
Test stage Functional_Hardware_Medium completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4556/1/display/redirect

2021-02-05 20:32 UTC, daosbuild1 commented
Test stage Functional_Hardware_Large completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4556/1/display/redirect

2021-02-05 21:10 UTC, johannlombardi approved these changes

2021-02-08 07:53 UTC, Nasf-Fan commented
The patch is only for old client, not for master.

2021-02-09 17:39 UTC, jolivier23 requested changes
Needs a merge.   But it sounds like this is for tag release? Or is it for 1.0?  I don't think we are making anymore changes there.

2021-02-18 04:48 UTC, Nasf-Fan commented
Not need it any longer.

2021-02-18 04:48 UTC, closed without merging