DAOS-5434: weekly-test: ObjOpenBadParam: test_invalid_handle and test_closed_container_handle: Test died without reporting the status
daos-stack/daos pull request #4586
Opened 2021-02-09 01:15 UTC by cibervicho

Tests 'test_invalid_container_handle' and 'test_closed_container_handle' were
failing not reporting the expected status because in the obj_layout_create()
function in object/cli_obj.c L308, when trying to get the pool from an
incorrect container handler, the test was aborting as soon as it noticed
that pool==NULL.
In order to fix this the D_ASSERT call was replaced with a D_GOTO call
instead, passing the expected '-DER_NO_HDL' return code. With this, the
'open()' function of the DaosObj class can raise the DaosApiError to the
test itself.

Test-tag: pr,-hw object

Signed-off-by: David Maldonado Moreno <david.maldonado.moreno@intel.com>

2021-02-09 01:17 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4586/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-02-09 01:17 UTC, daosbuild1 commented on src/object/cli_obj.c
> +        if(pool == NULL) {
(style)  code indent should use tabs where possible
(style)  suspect code indent for conditional statements (8, 12)
(style)  space required before the open parenthesis '('

2021-02-09 01:17 UTC, daosbuild1 commented on src/object/cli_obj.c
> +            D_DEBUG(DB_PL, "Cannot find valid pool\n");
(style)  code indent should use tabs where possible

2021-02-09 01:17 UTC, daosbuild1 commented on src/object/cli_obj.c
> +            D_GOTO(out, rc = -DER_NO_HDL);
(style)  code indent should use tabs where possible

2021-02-09 01:17 UTC, daosbuild1 commented on src/object/cli_obj.c
> +        }
(style)  code indent should use tabs where possible

2021-02-09 01:17 UTC, daosbuild1 commented on src/object/cli_obj.c
> +        }
```suggestion
	if (pool == NULL) {
	    D_DEBUG(DB_PL, "Cannot find valid pool\n");
	    D_GOTO(out, rc = -DER_NO_HDL);
	}
```

2021-02-09 01:17 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4586/1/execution/node/68/log

2021-02-09 01:27 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4586/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-02-09 01:27 UTC, daosbuild1 commented on src/object/cli_obj.c
> +	if (pool == NULL) {
(style)  suspect code indent for conditional statements (8, 12)

2021-02-09 01:27 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4586/2/execution/node/69/log

2021-02-09 01:44 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4586/3/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-02-09 01:44 UTC, daosbuild1 commented on src/object/cli_obj.c
> +        if(pool == NULL) {
(style)  code indent should use tabs where possible
(style)  suspect code indent for conditional statements (8, 12)
(style)  space required before the open parenthesis '('

2021-02-09 01:44 UTC, daosbuild1 commented on src/object/cli_obj.c
> +            D_DEBUG(DB_PL, "Cannot find valid pool\n");
(style)  code indent should use tabs where possible

2021-02-09 01:44 UTC, daosbuild1 commented on src/object/cli_obj.c
> +            D_GOTO(out, rc = -DER_NO_HDL);
(style)  code indent should use tabs where possible

2021-02-09 01:44 UTC, daosbuild1 commented on src/object/cli_obj.c
> +        }
(style)  code indent should use tabs where possible

2021-02-09 01:44 UTC, daosbuild1 commented on src/object/cli_obj.c
> +        }
```suggestion
	if (pool == NULL) {
	    D_DEBUG(DB_PL, "Cannot find valid pool\n");
	    D_GOTO(out, rc = -DER_NO_HDL);
	}
```

2021-02-09 01:44 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4586/3/execution/node/69/log

2021-02-09 16:13 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4586/4/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-02-09 16:13 UTC, daosbuild1 commented on src/object/cli_obj.c
> +	if(pool == NULL) {
(style)  space required before the open parenthesis '('

2021-02-09 16:13 UTC, daosbuild1 commented on src/object/cli_obj.c
> +	if(pool == NULL) {
```suggestion
	if (pool == NULL) {
```

2021-02-09 16:13 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4586/4/execution/node/68/log

2021-02-09 16:14 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4586/4/display/redirect

2021-02-09 16:14 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4586/4/display/redirect

2021-02-09 16:14 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4586/4/display/redirect

2021-02-09 16:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-09 16:45 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-09 23:25 UTC, cibervicho commented
The test obj_open_bad_param passed successfully now:

2021-02-09 14:34:05,006 test             L0139 INFO | *** SETUP running on <LinuxDistro: name=centos, version=7, release=9, arch=x86_64> ***
2021-02-09 14:34:37,954 test             L0779 INFO | PASS 1-./object/obj_open_bad_param.py:ObjOpenBadParam.test_bad_obj_handle;hosts-pool-server_config-bc1b
2021-02-09 14:34:50,730 test             L0779 INFO | PASS 2-./object/obj_open_bad_param.py:ObjOpenBadParam.test_invalid_container_handle;hosts-pool-server_config-bc1b
2021-02-09 14:35:03,334 test             L0779 INFO | PASS 3-./object/obj_open_bad_param.py:ObjOpenBadParam.test_closed_container_handle;hosts-pool-server_config-bc1b
2021-02-09 14:35:15,802 test             L0779 INFO | PASS 4-./object/obj_open_bad_param.py:ObjOpenBadParam.test_pool_handle_as_obj_handle;hosts-pool-server_config-bc1b
2021-02-09 14:35:28,612 test             L0779 INFO | PASS 5-./object/obj_open_bad_param.py:ObjOpenBadParam.test_null_ranklist;hosts-pool-server_config-bc1b
2021-02-09 14:35:41,413 test             L0779 INFO | PASS 6-./object/obj_open_bad_param.py:ObjOpenBadParam.test_null_oid;hosts-pool-server_config-bc1b
2021-02-09 14:35:54,746 test             L0779 INFO | PASS 7-./object/obj_open_bad_param.py:ObjOpenBadParam.test_null_tgts;hosts-pool-server_config-bc1b
2021-02-09 14:36:07,706 test             L0779 INFO | PASS 8-./object/obj_open_bad_param.py:ObjOpenBadParam.test_null_attrs;hosts-pool-server_config-bc1b

2021-02-09 14:34:59,260 test             L0139 INFO | *** SETUP running on <LinuxDistro: name=SuSE, version=15, release=2, arch=x86_64> ***
2021-02-09 14:35:36,560 test             L0779 INFO | PASS 1-./object/obj_open_bad_param.py:ObjOpenBadParam.test_bad_obj_handle;hosts-pool-server_config-c281
2021-02-09 14:35:56,799 test             L0779 INFO | PASS 2-./object/obj_open_bad_param.py:ObjOpenBadParam.test_invalid_container_handle;hosts-pool-server_config-c281
2021-02-09 14:36:11,983 test             L0779 INFO | PASS 3-./object/obj_open_bad_param.py:ObjOpenBadParam.test_closed_container_handle;hosts-pool-server_config-c281
2021-02-09 14:36:26,924 test             L0779 INFO | PASS 4-./object/obj_open_bad_param.py:ObjOpenBadParam.test_pool_handle_as_obj_handle;hosts-pool-server_config-c281
2021-02-09 14:36:51,651 test             L0779 INFO | PASS 5-./object/obj_open_bad_param.py:ObjOpenBadParam.test_null_ranklist;hosts-pool-server_config-c281
2021-02-09 14:37:06,491 test             L0779 INFO | PASS 6-./object/obj_open_bad_param.py:ObjOpenBadParam.test_null_oid;hosts-pool-server_config-c281
2021-02-09 14:37:21,343 test             L0779 INFO | PASS 7-./object/obj_open_bad_param.py:ObjOpenBadParam.test_null_tgts;hosts-pool-server_config-c281
2021-02-09 14:37:36,420 test             L0779 INFO | PASS 8-./object/obj_open_bad_param.py:ObjOpenBadParam.test_null_attrs;hosts-pool-server_config-c281

2021-02-10 15:38 UTC, cibervicho commented
The build errors shown as failing in this PR were a transient network issue. I re-ran the Build phase from BO and all passed: https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-4586/6/pipeline

2021-02-10 17:34 UTC, berserk-fury commented on src/object/cli_obj.c
> +		D_DEBUG(DB_PL, "Cannot find valid pool\n");
Perhaps D_WARN ?

2021-02-10 21:10 UTC, jolivier23 approved these changes

2021-02-10 21:17 UTC, berserk-fury approved these changes

2021-02-10 22:57 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-11 13:59 UTC, cibervicho commented
Tests passed CI checks:

2021-02-11 03:23:52,450 test             L0139 INFO | *** SETUP running on <LinuxDistro: name=centos, version=7, release=9, arch=x86_64> ***
2021-02-11 03:23:52,238 test             L0779 INFO | PASS 1-./object/obj_open_bad_param.py:ObjOpenBadParam.test_invalid_container_handle;hosts-pool-server_config-07d4
2021-02-11 03:24:05,062 test             L0779 INFO | PASS 2-./object/obj_open_bad_param.py:ObjOpenBadParam.test_closed_container_handle;hosts-pool-server_config-07d4

2021-02-11 03:24:29,228 test             L0139 INFO | *** SETUP running on <LinuxDistro: name=SuSE, version=15, release=2, arch=x86_64> ***
2021-02-11 03:25:06,548 test             L0779 INFO | PASS 1-./object/obj_open_bad_param.py:ObjOpenBadParam.test_invalid_container_handle;hosts-pool-server_config-0d9b
2021-02-11 03:25:21,138 test             L0779 INFO | PASS 2-./object/obj_open_bad_param.py:ObjOpenBadParam.test_closed_container_handle;hosts-pool-server_config-0d9b

2021-02-11 15:33 UTC, sylviachanoiyee requested changes
David, this change is in a common file used by a lot of tests, Could you rerun all test stages with no pragma filter? Thanks!

2021-02-11 16:11 UTC, cibervicho commented
> David, this change is in a common file used by a lot of tests, Could you rerun all test stages with no pragma filter? Thanks!

Sure, doing it right now. Thank you.

2021-02-11 16:14 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-11 19:17 UTC, cibervicho commented
CI checks just finished without errors reported

2021-02-12 08:12 UTC, merged