DAOS-5579 doc: clarifiy container type and IOR backends
daos-stack/daos pull request #4602
Opened 2021-02-09 22:16 UTC by Michael-Hennecke

remove references to container type MPI-IO (MPI-IO uses POSIX containers)
clarify IOR usage in performance_tuning.md

Signed-off-by: Michael Hennecke <mhennecke@lenovo.com>

2021-02-09 22:23 UTC, jolivier23 requested changes
You'll need to fix the spelling error.   That will affect future PRs if landed.

2021-02-09 23:01 UTC, jolivier23 approved these changes

2021-02-10 08:28 UTC, bfaccini approved these changes

2021-02-10 08:36 UTC, bfaccini commented
Since you may want to push a new commit to fix the spelling error in commit message's previous one, and as these are pure documentation changes, you may specify "Skip-test: true" commit pragma in order to skip all testing stages.

2021-02-12 07:53 UTC, johannlombardi approved these changes

2021-02-12 07:54 UTC, merged