DAOS-6766 log: increase default log size
daos-stack/daos pull request #4613
Opened 2021-02-10 19:36 UTC by wangdi1

1. Increase default log size to 2G.
2. Disable unnecessary iv ns trace log in CI tests.

Signed-off-by: Di Wang <di.wang@intel.com>

2021-02-10 19:43 UTC, sylviachanoiyee submitted a review, later dismissed

2021-02-10 20:51 UTC, jolivier23 requested changes

2021-02-10 20:51 UTC, jolivier23 commented on src/gurt/dlog.c
> +	LOG_SIZE_DEF	= (1ULL << 31),
should update the comment to 2GB ?

2021-02-10 21:15 UTC, wangdi1 commented on src/gurt/dlog.c
> +	LOG_SIZE_DEF	= (1ULL << 31),
ah, miss that, thanks

2021-02-10 21:41 UTC, jolivier23 approved these changes

2021-02-11 03:39 UTC, sylviachanoiyee approved these changes

2021-02-12 20:10 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-16 19:33 UTC, sylviachanoiyee commented
@wangdi1 , I think this PR needs a rebase/merge with master

2021-03-21 04:24 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-03-24 04:43 UTC, merged