DAOS-6803 ofi: Update OFI to v1.12.0rc1
daos-stack/daos pull request #4666
Opened 2021-02-16 21:44 UTC by frostedcmos

PR-repos: libfabric@PR-34

Signed-off-by: Alexander Oganezov <alexander.a.oganezov@intel.com>

2021-02-16 21:46 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-16 23:49 UTC, daosbuild1 commented
Test stage Scan CentOS 7 RPMs completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4666/1/execution/node/1039/log

2021-02-16 23:50 UTC, daosbuild1 commented
Test stage Test CentOS 7 RPMs completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4666/1/execution/node/1064/log

2021-02-17 02:40 UTC, daosbuild1 commented
Test stage Functional_Hardware_Medium completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4666/1/display/redirect

2021-02-17 02:41 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-17 02:45 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4666/2/execution/node/321/log

2021-02-17 02:48 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4666/2/execution/node/337/log

2021-02-17 02:48 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-4666/2/execution/node/340/log

2021-02-17 02:52 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-17 17:50 UTC, frostedcmos commented
Failures reported in this are the same as the master against which it was based:
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/3872/

2021-02-17 19:44 UTC, brianjmurrell requested changes

2021-02-17 19:44 UTC, brianjmurrell commented on utils/rpms/daos.spec
> +%global libfabric_version 1.12.0~rc1-1
Need to update https://github.com/daos-stack/daos/blob/15fe4f8b7a22168afa319ab5a36605fd00105e09/debian/control#L8 similarly.

2021-02-17 20:13 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-17 20:20 UTC, brianjmurrell approved these changes

2021-02-17 22:43 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-02-17 23:12 UTC, jolivier23 approved these changes

2021-02-18 20:51 UTC, brianjmurrell approved these changes

2021-02-19 21:07 UTC, merged