CaRT-955 Selftest: Fix memory leak
daos-stack/daos pull request #4969
Opened 2021-03-11 19:06 UTC by SABollinger

Signed-off-by: Steven Bollinger <stevenx.bollinger@intel.com>

2021-03-11 19:08 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-03-12 20:37 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-03-15 19:16 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-03-17 20:36 UTC, sylviachanoiyee approved these changes

2021-03-18 20:20 UTC, frostedcmos approved these changes

2021-03-18 20:21 UTC, frostedcmos requested changes
Actually we want to change those to use D_FREE()

2021-03-19 11:15 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-03-19 16:08 UTC, frostedcmos approved these changes

2021-03-22 03:30 UTC, sylviachanoiyee approved these changes

2021-03-22 03:32 UTC, merged