DAOS-6848
daos-stack/daos pull request #5117
Opened 2021-03-22 17:32 UTC by omar-ocampo

Added a timeout of 5m to yum install comands to avoid
    functional tests to hang indefinitely.

    Test-tag: test_core_files

Signed-off-by: Omar Ocampo <omar.ocampo.coronado@intel.com>

2021-03-22 17:34 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/launch.py:38](https://github.com/daos-stack/daos/blob/bdc2e840993d69ad3d4c41dedb54ddd18166e156/src/tests/ftest/launch.py#L38):
(pylint-useless-object-inheritance) Class 'TemporaryDirectory' inherits from object, can be safely removed from bases in python3

[src/tests/ftest/launch.py:375](https://github.com/daos-stack/daos/blob/bdc2e840993d69ad3d4c41dedb54ddd18166e156/src/tests/ftest/launch.py#L375):
(pylint-unnecessary-comprehension) Unnecessary use of a comprehension

2021-03-22 21:42 UTC, brianjmurrell commented
What ticket is this for?  [DAOS-6848](https://jira.hpdd.intel.com/browse/DAOS-6848) is already _Resolved_.

Also please put more descriptive text in the title of your commit messages.  They are supposed to be of the format: _ticket-number: area: description_.  Please search our wiki for commit message format if you require more information.

2021-03-22 22:28 UTC, daosbuild1 commented
Test stage Functional on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5117/1/display/redirect

2021-03-22 22:47 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5117/1/display/redirect

2021-03-23 02:47 UTC, brianjmurrell requested changes
This isn't really the way to fix this.  It was going to be fixed in #4615 however it seems that a subsequent merge commit in 7a4067bcab024628ef1e97db4f6ae8897d29608e wiped it out.

Resurrecting (i.e. reverting the above commit) is the path forward on this issue.

2021-03-23 16:07 UTC, omar-ocampo commented
Fixed ticket number typo, added area and ticket title.

2021-03-23 16:19 UTC, omar-ocampo commented
> This isn't really the way to fix this. It was going to be fixed in #4615 however it seems that a subsequent merge commit in [7a4067b](https://github.com/daos-stack/daos/commit/7a4067bcab024628ef1e97db4f6ae8897d29608e) wiped it out.
> 
> Resurrecting (i.e. reverting the above commit) is the path forward on this issue.

Are you suggesting to use dnf instead of yum? That can be done

2021-03-23 16:39 UTC, omar-ocampo commented
Going to drop this PR to correct the branch name in github

2021-03-23 16:39 UTC, closed without merging

2021-03-23 16:48 UTC, brianjmurrell commented
> Are you suggesting to use dnf instead of yum? That can be done

Yes.  YUM is a dead tool.  DNF is the future.  You can probably use that PR and merge commit I referenced above as a starting point.