daos-7022 documentation: Update docs and github.io site
daos-stack/daos pull request #5164
Opened 2021-03-25 00:57 UTC by cdurf1

Skip-build: true
Skip-test: true

Signed-off-by: craig <craig.durfey@intel.com>

2021-03-25 00:58 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5164/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-03-25 00:58 UTC, daosbuild1 commented on doc/admin/hardware.md
> +for Ethernet/sockets, InfiniBand/verbs, and RoCE.
(style)  trailing whitespace

2021-03-25 00:58 UTC, daosbuild1 commented on doc/user/container.md
> +
(style)  trailing whitespace

2021-03-25 00:58 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5164/1/execution/node/72/log

2021-03-25 21:49 UTC, tanabarr requested changes
I'm a bit confused as to why there are references to local user paths in C:/ home drives in this PR, wouldn't expect any user specific references in a DAOS PR

2021-03-26 08:02 UTC, johannlombardi commented
Yeah, the doxyfile is something that only Craig is able to use .... that's indeed a bummer.

2021-03-26 10:37 UTC, tanabarr approved these changes

2021-04-01 06:16 UTC, johannlombardi commented on mkdocs.yml
> +    - Issue tracker: 'https://jira.hpdd.intel.com/projects/DAOS'
Please use doc/mkdocks.yml instead.

2021-04-01 06:16 UTC, johannlombardi commented on Doxyfile
> +                         daos_cdurf/src/include/daos_mgmt.h
should not include daos_cdurf since INPUT above does not.

2021-04-01 06:16 UTC, johannlombardi commented on debug.log
> +[0324/173242.135:ERROR:registration_protocol_win.cc(130)] TransactNamedPipe: The pipe has been ended. (0x6D)
Debug logs should not be checked in.

2021-04-01 06:17 UTC, johannlombardi requested changes
Still not ready.

2021-09-27 16:47 UTC, closed without merging