DAOS-7111 test: Cleanup python2.7 references
daos-stack/daos pull request #5206
Opened 2021-03-26 21:24 UTC by mjean308

Test-tag-vm: pr,-hw daily_regression,-hw
Test-tag-hw-small: pr,hw,small daily_regression,hw,small
Test-tag-hw-medium: pr,hw,medium,ib2 daily_regression,hw,medium,ib2
Test-tag-hw-large: pr,hw,large daily_regression,hw,large soak_smoke

Signed-off-by: Maureen Jean <maureen.jean@intel.com>

2021-03-26 21:26 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5206/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/__init__.py:27](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/__init__.py#L27):
(pylint-super-init-not-called) __init__ method from base class 'Exception' is not called

[src/client/pydaos/__init__.py:64](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/__init__.py#L64):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:68](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/__init__.py#L68):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:76](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/__init__.py#L76):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:87](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/__init__.py#L87):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package
(pylint-wildcard-import) Wildcard import pydaos_core

[src/client/pydaos/__init__.py:89](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/__init__.py#L89):
(pylint-undefined-all-variable) Undefined variable name 'pydaos_core' in __all__

[src/client/pydaos/__init__.py:9](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/__init__.py#L9):
(pylint-unused-import) Unused import sys

[src/client/pydaos/pydaos_core.py:18](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/pydaos_core.py#L18):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:19](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/pydaos_core.py#L19):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:20](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/pydaos_core.py#L20):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:103](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/pydaos_core.py#L103):
(pylint-singleton-comparison) Comparison to None should be 'expr is not None'

[src/client/pydaos/pydaos_core.py:254](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/pydaos_core.py#L254):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/pydaos_core.py:12](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/pydaos_core.py#L12):
(pylint-unused-import) Unused import sys

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2269/1000)

[src/client/pydaos/raw/daos_api.py:1389](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L1389):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:18](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L18):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:19](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L19):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:20](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L20):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:81](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L81):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:104](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L104):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:140](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L140):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:288](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L288):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:322](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L322):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:582](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L582):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:901](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L901):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1429](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L1429):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1337](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L1337):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1466](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L1466):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1503](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L1503):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1533](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L1533):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1557](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L1557):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1838](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L1838):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:2251](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/pydaos/raw/daos_api.py#L2251):
(pylint-protected-access) Access to a protected member _getframe of a client class

[src/client/setup.py:1](https://github.com/daos-stack/daos/blob/e2d3ce1d8a5a2fcdd54d0e18ac1f490b55ac7427/src/client/setup.py#L1):
(pylint-missing-module-docstring) Missing module docstring

[src/client/setup.py: [...]

2021-03-26 21:26 UTC, daosbuild1 commented on src/client/pydaos/pydaos_core.py
> +from . import pydaos_shim_3 as pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-26 21:26 UTC, daosbuild1 commented on src/client/pydaos/raw/daos_api.py
> +from .. import pydaos_shim_3 as pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-26 21:26 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5206/1/execution/node/73/log

2021-03-26 21:43 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5206/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/__init__.py:27](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/__init__.py#L27):
(pylint-super-init-not-called) __init__ method from base class 'Exception' is not called

[src/client/pydaos/__init__.py:65](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/__init__.py#L65):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:69](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/__init__.py#L69):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:77](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/__init__.py#L77):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:90](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/__init__.py#L90):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package
(pylint-wildcard-import) Wildcard import pydaos_core

[src/client/pydaos/__init__.py:92](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/__init__.py#L92):
(pylint-undefined-all-variable) Undefined variable name 'pydaos_core' in __all__

[src/client/pydaos/__init__.py:9](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/__init__.py#L9):
(pylint-unused-import) Unused import sys

[src/client/pydaos/pydaos_core.py:18](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/pydaos_core.py#L18):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:19](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/pydaos_core.py#L19):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:20](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/pydaos_core.py#L20):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:106](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/pydaos_core.py#L106):
(pylint-singleton-comparison) Comparison to None should be 'expr is not None'

[src/client/pydaos/pydaos_core.py:259](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/pydaos_core.py#L259):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/pydaos_core.py:12](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/pydaos_core.py#L12):
(pylint-unused-import) Unused import sys

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2273/1000)

[src/client/pydaos/raw/daos_api.py:1392](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1392):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:21](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L21):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:22](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L22):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:23](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L23):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:82](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L82):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:105](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L105):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:141](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L141):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:289](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L289):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:323](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L323):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:583](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L583):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:902](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L902):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1432](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1432):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1340](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1340):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1469](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1469):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1506](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1506):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1536](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1536):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1560](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1560):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1841](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1841):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:2255](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L2255):
(pylint-protected-access) Access to a protected member _getframe of a client class

[src/client/setup.py:1](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/setup.py#L1):
(pylint-missing-module-docstring) Missing module docstring

[src/client/setup.py: [...]

2021-03-26 21:43 UTC, daosbuild1 commented on src/client/pydaos/pydaos_core.py
> +from . import pydaos_shim_3 as pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-26 21:43 UTC, daosbuild1 commented on src/client/pydaos/raw/daos_api.py
> +from .. import pydaos_shim_3 as pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-26 21:43 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5206/2/execution/node/74/log

2021-03-26 21:44 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5206/3/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/__init__.py:27](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/__init__.py#L27):
(pylint-super-init-not-called) __init__ method from base class 'Exception' is not called

[src/client/pydaos/__init__.py:65](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/__init__.py#L65):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:69](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/__init__.py#L69):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:77](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/__init__.py#L77):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:90](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/__init__.py#L90):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package
(pylint-wildcard-import) Wildcard import pydaos_core

[src/client/pydaos/__init__.py:92](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/__init__.py#L92):
(pylint-undefined-all-variable) Undefined variable name 'pydaos_core' in __all__

[src/client/pydaos/__init__.py:9](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/__init__.py#L9):
(pylint-unused-import) Unused import sys

[src/client/pydaos/pydaos_core.py:18](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/pydaos_core.py#L18):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:19](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/pydaos_core.py#L19):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:20](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/pydaos_core.py#L20):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:106](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/pydaos_core.py#L106):
(pylint-singleton-comparison) Comparison to None should be 'expr is not None'

[src/client/pydaos/pydaos_core.py:259](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/pydaos_core.py#L259):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/pydaos_core.py:12](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/pydaos_core.py#L12):
(pylint-unused-import) Unused import sys

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2273/1000)

[src/client/pydaos/raw/daos_api.py:1392](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1392):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:21](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L21):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:22](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L22):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:23](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L23):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:82](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L82):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:105](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L105):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:141](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L141):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:289](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L289):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:323](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L323):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:583](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L583):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:902](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L902):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1432](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1432):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1340](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1340):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1469](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1469):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1506](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1506):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1536](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1536):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1560](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1560):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1841](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L1841):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:2255](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/pydaos/raw/daos_api.py#L2255):
(pylint-protected-access) Access to a protected member _getframe of a client class

[src/client/setup.py:1](https://github.com/daos-stack/daos/blob/05cbb1358e58cf4dd135fa7d69c01cfdff56abc3/src/client/setup.py#L1):
(pylint-missing-module-docstring) Missing module docstring

[src/client/setup.py: [...]

2021-03-26 21:44 UTC, daosbuild1 commented on src/client/pydaos/pydaos_core.py
> +from . import pydaos_shim_3 as pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-26 21:44 UTC, daosbuild1 commented on src/client/pydaos/raw/daos_api.py
> +from .. import pydaos_shim_3 as pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-26 21:44 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5206/3/execution/node/74/log

2021-03-26 22:30 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5206/3/execution/node/874/log

2021-03-26 22:52 UTC, daosbuild1 commented
Test stage NLT completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5206/3/execution/node/974/log

2021-03-27 00:17 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5206/5/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/__init__.py:27](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/__init__.py#L27):
(pylint-super-init-not-called) __init__ method from base class 'Exception' is not called

[src/client/pydaos/__init__.py:65](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/__init__.py#L65):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:69](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/__init__.py#L69):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:77](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/__init__.py#L77):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:90](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/__init__.py#L90):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package
(pylint-wildcard-import) Wildcard import pydaos_core

[src/client/pydaos/__init__.py:92](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/__init__.py#L92):
(pylint-undefined-all-variable) Undefined variable name 'pydaos_core' in __all__

[src/client/pydaos/__init__.py:9](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/__init__.py#L9):
(pylint-unused-import) Unused import sys

[src/client/pydaos/pydaos_core.py:18](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/pydaos_core.py#L18):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:19](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/pydaos_core.py#L19):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:20](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/pydaos_core.py#L20):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:106](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/pydaos_core.py#L106):
(pylint-singleton-comparison) Comparison to None should be 'expr is not None'

[src/client/pydaos/pydaos_core.py:259](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/pydaos_core.py#L259):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/pydaos_core.py:12](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/pydaos_core.py#L12):
(pylint-unused-import) Unused import sys

[src/client/pydaos/raw/daos_api.py:1392](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L1392):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2273/1000)

[src/client/pydaos/raw/daos_api.py:21](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L21):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:22](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L22):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:23](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L23):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:82](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L82):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:105](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L105):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:141](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L141):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:289](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L289):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:323](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L323):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:583](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L583):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:902](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L902):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1432](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L1432):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1340](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L1340):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1469](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L1469):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1506](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L1506):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1536](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L1536):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1560](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L1560):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1841](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L1841):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:2255](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/pydaos/raw/daos_api.py#L2255):
(pylint-protected-access) Access to a protected member _getframe of a client class

[src/client/setup.py:1](https://github.com/daos-stack/daos/blob/3ae3a0def5e9137646578c6c71c675aedfb03c83/src/client/setup.py#L1):
(pylint-missing-module-docstring) Missing module docstring

[src/client/setup.py: [...]

2021-03-27 00:17 UTC, daosbuild1 commented on src/client/pydaos/pydaos_core.py
> +from . import pydaos_shim_3 as pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-27 00:17 UTC, daosbuild1 commented on src/client/pydaos/raw/daos_api.py
> +from .. import pydaos_shim_3 as pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-27 00:17 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5206/5/execution/node/74/log

2021-03-27 14:44 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5206/7/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/__init__.py:27](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/__init__.py#L27):
(pylint-super-init-not-called) __init__ method from base class 'Exception' is not called

[src/client/pydaos/__init__.py:65](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/__init__.py#L65):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:69](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/__init__.py#L69):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:77](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/__init__.py#L77):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:90](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/__init__.py#L90):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package
(pylint-wildcard-import) Wildcard import pydaos_core

[src/client/pydaos/__init__.py:92](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/__init__.py#L92):
(pylint-undefined-all-variable) Undefined variable name 'pydaos_core' in __all__

[src/client/pydaos/__init__.py:9](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/__init__.py#L9):
(pylint-unused-import) Unused import sys

[src/client/pydaos/pydaos_core.py:18](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/pydaos_core.py#L18):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:19](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/pydaos_core.py#L19):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:20](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/pydaos_core.py#L20):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:106](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/pydaos_core.py#L106):
(pylint-singleton-comparison) Comparison to None should be 'expr is not None'

[src/client/pydaos/pydaos_core.py:259](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/pydaos_core.py#L259):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/pydaos_core.py:12](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/pydaos_core.py#L12):
(pylint-unused-import) Unused import sys

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2273/1000)

[src/client/pydaos/raw/daos_api.py:1392](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L1392):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:21](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L21):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:22](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L22):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:23](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L23):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:82](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L82):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:105](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L105):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:141](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L141):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:289](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L289):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:323](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L323):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:583](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L583):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:902](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L902):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1432](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L1432):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1340](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L1340):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1469](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L1469):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1506](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L1506):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1536](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L1536):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1560](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L1560):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1841](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L1841):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:2255](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/pydaos/raw/daos_api.py#L2255):
(pylint-protected-access) Access to a protected member _getframe of a client class

[src/client/setup.py:1](https://github.com/daos-stack/daos/blob/0418dc6017846c4d909a08dfbc06407ebca62def/src/client/setup.py#L1):
(pylint-missing-module-docstring) Missing module docstring

[src/client/setup.py: [...]

2021-03-27 14:44 UTC, daosbuild1 commented on src/client/pydaos/__init__.py
> +from . import pydaos_shim_3 as pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-27 14:44 UTC, daosbuild1 commented on src/client/pydaos/pydaos_core.py
> +from . import pydaos_shim_3 as pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-27 14:44 UTC, daosbuild1 commented on src/client/pydaos/raw/daos_api.py
> +from .. import pydaos_shim_3 as pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-27 14:44 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5206/7/execution/node/74/log

2021-03-29 15:30 UTC, mjean308 commented
The 64 failures are the same failures that are being seen on master daily regression and are all known issues
DAOS-7114 - pool connect
DAOS-7115 - simple rebuild
DAOS-6944 - pool svc

2021-03-29 19:40 UTC, jolivier23 approved these changes

2021-03-30 14:40 UTC, dpquigl commented on src/client/pydaos/__init__.py
> +from . import pydaos_shim_3 as pydaos_shim
Is there anyway to rename pydaos_shim_3 to just pydaos_shim since there is no longer a python 2 shim?

2021-03-30 14:40 UTC, dpquigl commented on src/client/pydaos/pydaos_core.py
> +from . import pydaos_shim_3 as pydaos_shim
Same as above and probably applies to all lines like this.

2021-03-30 14:40 UTC, dpquigl commented on src/client/pydaos/__init__.py
> +
I notice a lot of additional new lines. Is this a change in the python coding style?

2021-03-30 14:40 UTC, dpquigl commented on src/client/pydaos/pydaos_shim.c
> +
Should probably remove this newline. I'm not sure why the checkpatch stage didn't check this as it normally would complain about a new line after a function declaration.

2021-03-30 14:40 UTC, dpquigl commented on src/client/setup.py
> +shim_name = 'pydaos_shim_3'
You can probably get rid of the shim_name variable and just use the string directly in the module1 = line below.

2021-03-30 15:03 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5206/9/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/SConscript:58](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/SConscript#L58):
(pylint-import-outside-toplevel) Import outside toplevel (prereq_tools.PreReqComponent)

[src/client/pydaos/SConscript:61](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/SConscript#L61):
(pylint-unused-variable) Unused variable 'prereqs'

[src/client/pydaos/__init__.py:27](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/__init__.py#L27):
(pylint-super-init-not-called) __init__ method from base class 'Exception' is not called

[src/client/pydaos/__init__.py:65](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/__init__.py#L65):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:69](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/__init__.py#L69):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:77](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/__init__.py#L77):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:90](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/__init__.py#L90):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package
(pylint-wildcard-import) Wildcard import pydaos_core

[src/client/pydaos/__init__.py:92](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/__init__.py#L92):
(pylint-undefined-all-variable) Undefined variable name 'pydaos_core' in __all__

[src/client/pydaos/__init__.py:9](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/__init__.py#L9):
(pylint-unused-import) Unused import sys

[src/client/pydaos/pydaos_core.py:18](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/pydaos_core.py#L18):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:19](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/pydaos_core.py#L19):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:20](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/pydaos_core.py#L20):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:106](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/pydaos_core.py#L106):
(pylint-singleton-comparison) Comparison to None should be 'expr is not None'

[src/client/pydaos/pydaos_core.py:259](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/pydaos_core.py#L259):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/pydaos_core.py:12](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/pydaos_core.py#L12):
(pylint-unused-import) Unused import sys

[src/client/pydaos/raw/daos_api.py:1392](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L1392):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2273/1000)

[src/client/pydaos/raw/daos_api.py:21](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L21):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:22](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L22):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:23](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L23):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:82](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L82):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:105](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L105):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:141](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L141):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:289](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L289):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:323](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L323):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:583](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L583):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:902](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L902):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1432](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L1432):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1340](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L1340):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1469](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L1469):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1506](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L1506):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1536](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L1536):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1560](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L1560):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1841](https://github.com/daos-stack/daos/blob/f65e12ddae5d30d5fbf17edb9fc05eeb34e9413a/src/client/pydaos/raw/daos_api.py#L1841):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos [...]

2021-03-30 15:03 UTC, daosbuild1 commented on src/client/pydaos/__init__.py
> +from . import pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-30 15:03 UTC, daosbuild1 commented on src/client/pydaos/pydaos_core.py
> +from . import pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-30 15:03 UTC, daosbuild1 commented on src/client/pydaos/raw/daos_api.py
> +from .. import pydaos_shim as pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package
(pylint-useless-import-alias) Import alias does not rename original package

2021-03-30 15:04 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5206/9/execution/node/74/log

2021-03-30 19:35 UTC, dpquigl approved these changes

2021-03-30 19:56 UTC, mjean308 commented
The 58 failures are the same failures that are being seen on master daily regression and are all known issues
DAOS-7115 - simple rebuild
DAOS-6944 - pool svc

2021-03-30 20:03 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5206/10/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/SConscript:58](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/SConscript#L58):
(pylint-import-outside-toplevel) Import outside toplevel (prereq_tools.PreReqComponent)

[src/client/pydaos/SConscript:61](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/SConscript#L61):
(pylint-unused-variable) Unused variable 'prereqs'

[src/client/pydaos/__init__.py:27](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/__init__.py#L27):
(pylint-super-init-not-called) __init__ method from base class 'Exception' is not called

[src/client/pydaos/__init__.py:65](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/__init__.py#L65):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:69](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/__init__.py#L69):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:77](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/__init__.py#L77):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:90](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/__init__.py#L90):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package
(pylint-wildcard-import) Wildcard import pydaos_core

[src/client/pydaos/__init__.py:92](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/__init__.py#L92):
(pylint-undefined-all-variable) Undefined variable name 'pydaos_core' in __all__

[src/client/pydaos/__init__.py:9](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/__init__.py#L9):
(pylint-unused-import) Unused import sys

[src/client/pydaos/pydaos_core.py:18](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/pydaos_core.py#L18):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:19](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/pydaos_core.py#L19):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:20](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/pydaos_core.py#L20):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:106](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/pydaos_core.py#L106):
(pylint-singleton-comparison) Comparison to None should be 'expr is not None'

[src/client/pydaos/pydaos_core.py:259](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/pydaos_core.py#L259):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/pydaos_core.py:12](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/pydaos_core.py#L12):
(pylint-unused-import) Unused import sys

[src/client/pydaos/raw/daos_api.py:1392](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1392):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2273/1000)

[src/client/pydaos/raw/daos_api.py:21](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L21):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:22](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L22):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:23](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L23):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:82](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L82):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:105](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L105):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:141](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L141):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:289](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L289):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:323](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L323):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:583](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L583):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:902](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L902):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1432](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1432):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1340](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1340):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1469](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1469):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1506](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1506):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1536](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1536):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1560](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1560):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1841](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1841):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydao [...]

2021-03-30 20:03 UTC, daosbuild1 commented on src/client/pydaos/__init__.py
> +from . import pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-30 20:03 UTC, daosbuild1 commented on src/client/pydaos/pydaos_core.py
> +from . import pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-30 20:03 UTC, daosbuild1 commented on src/client/pydaos/raw/daos_api.py
> +from .. import pydaos_shim as pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package
(pylint-useless-import-alias) Import alias does not rename original package

2021-03-30 20:05 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5206/11/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/SConscript:58](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/SConscript#L58):
(pylint-import-outside-toplevel) Import outside toplevel (prereq_tools.PreReqComponent)

[src/client/pydaos/SConscript:61](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/SConscript#L61):
(pylint-unused-variable) Unused variable 'prereqs'

[src/client/pydaos/__init__.py:27](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/__init__.py#L27):
(pylint-super-init-not-called) __init__ method from base class 'Exception' is not called

[src/client/pydaos/__init__.py:65](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/__init__.py#L65):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:69](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/__init__.py#L69):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:77](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/__init__.py#L77):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:90](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/__init__.py#L90):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package
(pylint-wildcard-import) Wildcard import pydaos_core

[src/client/pydaos/__init__.py:92](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/__init__.py#L92):
(pylint-undefined-all-variable) Undefined variable name 'pydaos_core' in __all__

[src/client/pydaos/__init__.py:9](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/__init__.py#L9):
(pylint-unused-import) Unused import sys

[src/client/pydaos/pydaos_core.py:18](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/pydaos_core.py#L18):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:19](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/pydaos_core.py#L19):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:20](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/pydaos_core.py#L20):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:106](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/pydaos_core.py#L106):
(pylint-singleton-comparison) Comparison to None should be 'expr is not None'

[src/client/pydaos/pydaos_core.py:259](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/pydaos_core.py#L259):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/pydaos_core.py:12](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/pydaos_core.py#L12):
(pylint-unused-import) Unused import sys

[src/client/pydaos/raw/daos_api.py:1392](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1392):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2273/1000)

[src/client/pydaos/raw/daos_api.py:21](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L21):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:22](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L22):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:23](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L23):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:82](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L82):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:105](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L105):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:141](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L141):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:289](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L289):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:323](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L323):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:583](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L583):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:902](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L902):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1432](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1432):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1340](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1340):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1469](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1469):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1506](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1506):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1536](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1536):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1560](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1560):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1841](https://github.com/daos-stack/daos/blob/cf151e9d05303e182e882ee63cca6c45a90be05d/src/client/pydaos/raw/daos_api.py#L1841):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydao [...]

2021-03-30 20:05 UTC, daosbuild1 commented on src/client/pydaos/__init__.py
> +from . import pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-30 20:05 UTC, daosbuild1 commented on src/client/pydaos/pydaos_core.py
> +from . import pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

2021-03-30 20:05 UTC, daosbuild1 commented on src/client/pydaos/raw/daos_api.py
> +from .. import pydaos_shim as pydaos_shim
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package
(pylint-useless-import-alias) Import alias does not rename original package

2021-03-30 20:05 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5206/11/execution/node/74/log

2021-03-30 20:22 UTC, dpquigl approved these changes

2021-03-30 21:05 UTC, jolivier23 requested changes

2021-03-30 21:05 UTC, jolivier23 commented on src/client/pydaos/pydaos_core.py
> +from . import pydaos_shim
Can this just be 

import pydaos_shim

2021-03-30 21:05 UTC, jolivier23 commented on src/client/pydaos/raw/daos_api.py
> +from .. import pydaos_shim as pydaos_shim
same comment here but also we don't need the "as" since it's the same name

2021-03-30 21:58 UTC, daosbuild1 commented
Test stage Functional on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5206/11/display/redirect

2021-03-30 22:58 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/SConscript:58](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/SConscript#L58):
(pylint-import-outside-toplevel) Import outside toplevel (prereq_tools.PreReqComponent)

[src/client/pydaos/SConscript:61](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/SConscript#L61):
(pylint-unused-variable) Unused variable 'prereqs'

[src/client/pydaos/__init__.py:27](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/__init__.py#L27):
(pylint-super-init-not-called) __init__ method from base class 'Exception' is not called

[src/client/pydaos/__init__.py:65](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/__init__.py#L65):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:69](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/__init__.py#L69):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:77](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/__init__.py#L77):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:90](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/__init__.py#L90):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package
(pylint-wildcard-import) Wildcard import pydaos_core

[src/client/pydaos/__init__.py:92](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/__init__.py#L92):
(pylint-undefined-all-variable) Undefined variable name 'pydaos_core' in __all__

[src/client/pydaos/__init__.py:9](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/__init__.py#L9):
(pylint-unused-import) Unused import sys

[src/client/pydaos/pydaos_core.py:18](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/pydaos_core.py#L18):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:19](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/pydaos_core.py#L19):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:20](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/pydaos_core.py#L20):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:106](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/pydaos_core.py#L106):
(pylint-singleton-comparison) Comparison to None should be 'expr is not None'

[src/client/pydaos/pydaos_core.py:259](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/pydaos_core.py#L259):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/pydaos_core.py:12](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/pydaos_core.py#L12):
(pylint-unused-import) Unused import sys

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2273/1000)

[src/client/pydaos/raw/daos_api.py:1392](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L1392):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:21](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L21):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:22](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L22):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:23](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L23):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:82](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L82):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:105](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L105):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:141](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L141):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:289](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L289):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:323](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L323):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:583](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L583):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:902](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L902):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1432](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L1432):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1340](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L1340):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1469](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L1469):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1506](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L1506):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1536](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L1536):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1560](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L1560):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1841](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos/raw/daos_api.py#L1841):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:2255](https://github.com/daos-stack/daos/blob/f4ac7b6dda0f22d6ecaf799a84619ae8c980fe63/src/client/pydaos [...]

2021-03-31 14:40 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/SConscript:58](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/SConscript#L58):
(pylint-import-outside-toplevel) Import outside toplevel (prereq_tools.PreReqComponent)

[src/client/pydaos/SConscript:61](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/SConscript#L61):
(pylint-unused-variable) Unused variable 'prereqs'

[src/client/pydaos/__init__.py:27](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/__init__.py#L27):
(pylint-super-init-not-called) __init__ method from base class 'Exception' is not called

[src/client/pydaos/__init__.py:65](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/__init__.py#L65):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:69](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/__init__.py#L69):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:77](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/__init__.py#L77):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:90](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/__init__.py#L90):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package
(pylint-wildcard-import) Wildcard import pydaos_core

[src/client/pydaos/__init__.py:92](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/__init__.py#L92):
(pylint-undefined-all-variable) Undefined variable name 'pydaos_core' in __all__

[src/client/pydaos/__init__.py:9](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/__init__.py#L9):
(pylint-unused-import) Unused import sys

[src/client/pydaos/pydaos_core.py:18](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/pydaos_core.py#L18):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:19](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/pydaos_core.py#L19):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:20](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/pydaos_core.py#L20):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:106](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/pydaos_core.py#L106):
(pylint-singleton-comparison) Comparison to None should be 'expr is not None'

[src/client/pydaos/pydaos_core.py:259](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/pydaos_core.py#L259):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/pydaos_core.py:12](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/pydaos_core.py#L12):
(pylint-unused-import) Unused import sys

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2273/1000)

[src/client/pydaos/raw/daos_api.py:1392](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L1392):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:21](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L21):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:22](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L22):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:23](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L23):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:82](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L82):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:105](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L105):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:141](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L141):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:289](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L289):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:323](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L323):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:583](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L583):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:902](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L902):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1432](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L1432):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1340](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L1340):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1469](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L1469):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1506](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L1506):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1536](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L1536):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1560](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L1560):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1841](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos/raw/daos_api.py#L1841):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:2255](https://github.com/daos-stack/daos/blob/4fffd7e265eebd5642e4c3a82b168f4a824ff09b/src/client/pydaos [...]

2021-03-31 18:45 UTC, jolivier23 approved these changes

2021-03-31 23:56 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/SConscript:58](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/SConscript#L58):
(pylint-import-outside-toplevel) Import outside toplevel (prereq_tools.PreReqComponent)

[src/client/pydaos/SConscript:61](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/SConscript#L61):
(pylint-unused-variable) Unused variable 'prereqs'

[src/client/pydaos/__init__.py:27](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/__init__.py#L27):
(pylint-super-init-not-called) __init__ method from base class 'Exception' is not called

[src/client/pydaos/__init__.py:65](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/__init__.py#L65):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:69](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/__init__.py#L69):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:77](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/__init__.py#L77):
(pylint-attribute-defined-outside-init) Attribute 'connected' defined outside __init__

[src/client/pydaos/__init__.py:90](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/__init__.py#L90):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package
(pylint-wildcard-import) Wildcard import pydaos_core

[src/client/pydaos/__init__.py:92](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/__init__.py#L92):
(pylint-undefined-all-variable) Undefined variable name 'pydaos_core' in __all__

[src/client/pydaos/__init__.py:9](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/__init__.py#L9):
(pylint-unused-import) Unused import sys

[src/client/pydaos/pydaos_core.py:18](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/pydaos_core.py#L18):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:19](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/pydaos_core.py#L19):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:20](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/pydaos_core.py#L20):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/pydaos_core.py:106](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/pydaos_core.py#L106):
(pylint-singleton-comparison) Comparison to None should be 'expr is not None'

[src/client/pydaos/pydaos_core.py:259](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/pydaos_core.py#L259):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/pydaos_core.py:12](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/pydaos_core.py#L12):
(pylint-unused-import) Unused import sys

[src/client/pydaos/raw/daos_api.py:1392](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L1392):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2273/1000)

[src/client/pydaos/raw/daos_api.py:21](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L21):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:22](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L22):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:23](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L23):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:82](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L82):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:105](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L105):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:141](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L141):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:289](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L289):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:323](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L323):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:583](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L583):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:902](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L902):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1432](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L1432):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1340](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L1340):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1469](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L1469):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1506](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L1506):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1536](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L1536):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1560](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L1560):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1841](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos/raw/daos_api.py#L1841):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:2255](https://github.com/daos-stack/daos/blob/e037ec6593a2981cdc83ced2f0c7ccf9fd67f29e/src/client/pydaos [...]

2021-04-01 13:24 UTC, mjean308 commented
Latest failures are due to:
DAOS-7073 - daos core test rebuild 25 timeout

2021-04-01 14:15 UTC, dpquigl approved these changes

2021-04-01 17:33 UTC, johannlombardi approved these changes

2021-04-01 17:34 UTC, merged

2021-04-01 18:32 UTC, brianjmurrell commented
This PR needed to update `debian/changelog` also.  Just like touching `daos.spec` requires a Version/Release/%changelog update, any change in `debian/` requires a `debian/changelog` update/entry.