DAOS-7113: Fix rebuild/delete_objects.py variant 3 - Error data mismatch
daos-stack/daos pull request #5285
Opened 2021-04-01 14:26 UTC by dinghwah

clean up read_array.py and cascading_failures.py cancel for tickets.
modified:   cascading_failures.py
modified:   delete_objects.py
modified:   read_array.py
modified:   ../util/test_utils_container.py

Skip-unit-tests: true
Skip-nlt: true
Quick-Functional: true
Test-tag: rebuild_tests
Signed-off-by: Ding Ho <ding-hwa.ho@intel.com>

2021-04-01 15:40 UTC, shimizukko approved these changes

2021-04-01 17:47 UTC, dinghwah commented
There are failures on unrelated to this rebuild delete_object tests, isolating the issue with different PR.

2021-04-01 17:54 UTC, dinghwah commented
There are failures on cascading test, due to an existing JIRA bug, isolate the PR to individual rebuild tests.

2021-04-01 18:58 UTC, dinghwah commented
Due to CentOS7 build rpm failed

2021-04-01 20:00 UTC, shimizukko submitted a review, later dismissed

2021-04-02 00:02 UTC, saurabhtandan commented on src/tests/ftest/rebuild/delete_objects.py
> +        :avocado: tags=pool,rebuild_tests,rebuilddeleteobject
can you please change `rebuild_tests` to `deleteobjects` as something similar is already being used under rebuild/rebuild_tests.py

2021-04-02 00:02 UTC, saurabhtandan commented on src/tests/ftest/rebuild/delete_objects.py
> +        :avocado: tags=pool,rebuild_tests,rebuilddeletrecord
Same as above.

2021-04-02 00:05 UTC, saurabhtandan requested changes
After the change you will need to run the PR with `deleteobjects` tag along with all other pr tests as this PR makes changes to utils file.

2021-04-02 10:11 UTC, shimizukko submitted a review, later dismissed

2021-04-02 15:26 UTC, dinghwah commented
All test passed on the testcases on test-Tag.

2021-04-02 15:59 UTC, ravalsam reviewed
This code is updating container utility so to land this patch need to run all standard CI tests, isn't it?

2021-04-02 15:59 UTC, ravalsam commented on src/tests/ftest/rebuild/delete_objects.py
> +        :avocado: tags=vm,large
large tag is needed?

2021-04-02 17:36 UTC, dinghwah reviewed
Thanks for the comment.
I have updated the test-tag after discussed team.
Also added entire rebuild testcases into the the is PR.
Please see next commit.

2021-04-02 18:59 UTC, shimizukko approved these changes

2021-04-03 00:09 UTC, dinghwah commented
Resubmitted PR with all the rebuild tests.
3 tests failed are due to known issue DAOS-7169.
All rest tests on the rebuild are passed.

2021-04-03 00:12 UTC, ravalsam approved these changes

2021-04-03 12:34 UTC, mjean308 approved these changes
lgtm

2021-04-03 13:10 UTC, shimizukko approved these changes

2021-04-05 20:57 UTC, sylviachanoiyee commented
Can you run all the functional tests? There is change to the utils file. Thanks!

2021-04-06 17:07 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-06 21:29 UTC, dinghwah commented
Fix has been merge with PR# 5171, Close this PR to avoid conflict.

2021-04-08 19:42 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-08 19:43 UTC, closed without merging