DAOS-4757-test: remove skipForTicket rebuild read_array.py
daos-stack/daos pull request #5293
Opened 2021-04-01 18:21 UTC by dinghwah

modified:   read_array.py
modified:   read_array.yaml
Skip-unit-tests: true
Skip-nlt: true
Quick-Functional: true
Test-tag: rebuildreadarray
Signed-off-by: Ding Ho ding-hwa.ho@intel.com

2021-04-01 23:09 UTC, dinghwah commented
All tests on the Test-tag are passed.

2021-04-01 23:18 UTC, saurabhtandan commented on src/tests/ftest/rebuild/cascading_failures.py
> +    CANCEL_FOR_TICKET = [["DAOS-6728"]]
Don't think this is the correct way of using `CANCEL_FOR_TICKET` option. The ticket id should be accompanied with some condition from yaml file or the test case.

2021-04-01 23:20 UTC, saurabhtandan requested changes
Also, can you please update the tags of cascading_failures.py to have common tag for the whole test as well. And run this PR with that tag even if other tests are supposed to be skipped. I think because the PR was run with just 'cascading' tag, the issue of `CANCEL_FOR_TICKET` mentioned below might not have been picked up.

==>Done.

2021-04-02 10:10 UTC, shimizukko approved these changes

2021-04-02 15:45 UTC, dinghwah commented
All tests passed from the testcases on the test-Tag.

2021-04-02 16:00 UTC, ravalsam approved these changes

2021-04-02 18:24 UTC, saurabhtandan requested changes
Results of Build 3 of this pr seem to indicate 2 cascading tests actually passed. But later all the tests are being skipped. Can we unsnap that test please.

2021-04-02 19:26 UTC, merged