DAOS-6794 CLient: Remove pool APIs from src/include/daos_mgmt.h
daos-stack/daos pull request #5295
Opened 2021-04-01 18:31 UTC by cibervicho

Removing these 4 APIs from this file
daos_pool_drain_tgt
daos_pool_tgt_exclude_out
daos_pool_tgt_exclude
daos_pool_reint_tgt

PR-repos: hdf5-vol-daos@PR-16

2021-04-01 18:33 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-01 18:37 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/1/execution/node/409/log

2021-04-01 18:41 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/1/execution/node/325/log

2021-04-01 18:52 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/1/execution/node/406/log

2021-04-02 03:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-02 03:30 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/2/execution/node/374/log

2021-04-02 03:34 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/2/execution/node/322/log

2021-04-02 03:45 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/2/execution/node/356/log

2021-04-02 14:44 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-02 17:01 UTC, cibervicho commented
"container/simple_create_delete_test.py" test failed. It is an existing one with the error message: "Failed to start servers after format", which is not related to the updates made in https://github.com/daos-stack/hdf5-vol-daos/pull/16.

Adding reviewers.

2021-04-02 17:12 UTC, mchaarawi requested changes
i don't see where you are running the VOL tests.
all HW tests are skipped!

2021-04-02 17:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-03 00:33 UTC, cibervicho commented
All volunit tests passed in HW small:

[2021-04-03T00:05:19.736Z] Running: avocado run --ignore-missing-references on --html-job-result on --tap-job-result off --filter-by-tags=volunit --mux-yaml /tmp/tmp8mcnj_yl/daos_vol-daos_vol.yaml -- ./daos_vol/daos_vol.py
[2021-04-03T00:05:20.002Z] JOB ID     : 21539490d695b1705b70c5270d7fab1afdb5270b
[2021-04-03T00:05:20.002Z] JOB LOG    : /var/tmp/ftest/avocado/job-results/job-2021-04-03T00.05-2153949/job.log
[2021-04-03T00:07:41.822Z]  (01/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test1-dfuse-hosts-pool-servers-7775:  PASS (132.41 s)
[2021-04-03T00:07:56.719Z]  (02/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test2-dfuse-hosts-pool-servers-9eb1:  PASS (23.41 s)
[2021-04-03T00:08:28.961Z]  (03/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test3-dfuse-hosts-pool-servers-d2b5:  PASS (28.90 s)
[2021-04-03T00:11:05.497Z]  (04/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test4-dfuse-hosts-pool-servers-3612:  PASS (153.60 s)
[2021-04-03T00:11:52.174Z]  (05/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test5-dfuse-hosts-pool-servers-1e1f:  PASS (48.82 s)
[2021-04-03T00:12:02.165Z]  (06/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test6-dfuse-hosts-pool-servers-8e93:  PASS (13.52 s)
[2021-04-03T00:12:20.251Z]  (07/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test7-dfuse-hosts-pool-servers-a4a1:  PASS (16.49 s)
[2021-04-03T00:12:32.465Z]  (08/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test8-dfuse-hosts-pool-servers-3438:  PASS (12.90 s)
[2021-04-03T00:14:39.079Z]  (09/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test9-dfuse-hosts-pool-servers-153f:  PASS (114.18 s)
[2021-04-03T00:15:25.788Z]  (10/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test1-dfuse-hosts-pool-servers-7775:  PASS (56.15 s)
[2021-04-03T00:15:47.796Z]  (11/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test2-dfuse-hosts-pool-servers-9eb1:  PASS (23.50 s)
[2021-04-03T00:16:19.883Z]  (12/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test3-dfuse-hosts-pool-servers-d2b5:  PASS (29.46 s)
[2021-04-03T00:19:11.406Z]  (13/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test4-dfuse-hosts-pool-servers-3612:  PASS (168.71 s)
[2021-04-03T00:19:58.120Z]  (14/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test5-dfuse-hosts-pool-servers-1e1f:  PASS (48.90 s)
[2021-04-03T00:20:08.095Z]  (15/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test6-dfuse-hosts-pool-servers-8e93:  PASS (13.87 s)
[2021-04-03T00:20:26.190Z]  (16/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test7-dfuse-hosts-pool-servers-a4a1:  PASS (16.44 s)
[2021-04-03T00:20:38.444Z]  (17/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test8-dfuse-hosts-pool-servers-3438:  PASS (13.19 s)
[2021-04-03T00:22:45.017Z]  (18/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test9-dfuse-hosts-pool-servers-153f:  PASS (114.24 s)
[2021-04-03T00:22:45.017Z] RESULTS    : PASS 18 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
[2021-04-03T00:22:45.017Z] JOB TIME   : 1031.87 s

2021-04-05 17:30 UTC, cibervicho commented
All tests passed but the following:

+ Functional_Hardware_Large / FTEST_container.SnapshotAggregation.1-./container/snapshot_aggregation.py:SnapshotAggregation.test_snapshot_aggregation
	Reported in: https://jira.hpdd.intel.com/browse/DAOS-7179

+ Functional_Hardware_Large / FTEST_daos_test.DaosCoreTestDfs.1-./daos_test/daos_core_test_dfs.py:DaosCoreTestDfs.test_daos_dfs_unit

+ Functional_Hardware_Large / FTEST_pool.PoolCreateTests.1-./pool/create_capacity_test.py:PoolCreateTests.test_create_pool_quantity

+ Functional_Hardware_Medium / FTEST_daos_test.DaosCoreTest.09-./daos_test/daos_core_test.py:DaosCoreTest.test_daos_io

+ Functional_Hardware_Medium / FTEST_daos_test.DaosCoreTest.11-./daos_test/daos_core_test.py:DaosCoreTest.test_daos_array

+ Functional_Hardware_Medium / FTEST_daos_test.DaosCoreTest.16-./daos_test/daos_core_test.py:DaosCoreTest.test_daos_rebuild_simple

From what I can see these are not new failures and are not caused by this PR.

2021-04-05 17:33 UTC, brianjmurrell commented
> All tests passed but the following:
> 
> * Functional_Hardware_Large / FTEST_container.SnapshotAggregation.1-./container/snapshot_aggregation.py:SnapshotAggregation.test_snapshot_aggregation
>   Reported in: https://jira.hpdd.intel.com/browse/DAOS-7179

This is now being skipped in CI.  A re-run of testing (no merge necessary) should not hit this.

> * Functional_Hardware_Large / FTEST_daos_test.DaosCoreTestDfs.1-./daos_test/daos_core_test_dfs.py:DaosCoreTestDfs.test_daos_dfs_unit
> * Functional_Hardware_Large / FTEST_pool.PoolCreateTests.1-./pool/create_capacity_test.py:PoolCreateTests.test_create_pool_quantity
> * Functional_Hardware_Medium / FTEST_daos_test.DaosCoreTest.09-./daos_test/daos_core_test.py:DaosCoreTest.test_daos_io
> * Functional_Hardware_Medium / FTEST_daos_test.DaosCoreTest.11-./daos_test/daos_core_test.py:DaosCoreTest.test_daos_array
> * Functional_Hardware_Medium / FTEST_daos_test.DaosCoreTest.16-./daos_test/daos_core_test.py:DaosCoreTest.test_daos_rebuild_simple
> 
> From what I can see these are not new failures and are not caused by this PR.

So they have tickets?  If not, you should open tickets and document them with the issues above.

2021-04-05 17:35 UTC, brianjmurrell reviewed
None of these removals are in the libdaos.so client library, correct?  If so, LGTM, but I will let others with more knowledge of this code _Approve_.

2021-04-05 17:42 UTC, mchaarawi requested changes
I still see these functions used in pydaos:
client/pydaos/raw/daos_api.py
so they should be removed from there..

also gatekeepers will require an API major version bump and it's not done here.

2021-04-05 17:43 UTC, berserk-fury submitted a review, later dismissed
All daos-vol tests passed

https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5295/4/artifact/Functional_Hardware_Small/daos_vol/daos_vol.py/job.log

2021-04-05 18:15 UTC, jolivier23 commented
> I still see these functions used in pydaos:
> client/pydaos/raw/daos_api.py
> so they should be removed from there..
> 
> also gatekeepers will require an API major version bump and it's not done here.

A major API version bump will be a pain as it will require downstream components to rebuild.   Can we just mark these as deprecated instead to avoid this?   Then when we want to deliberately change the major version, we can do a wholesale removal of anything that fits the description.

See daos_obj.h for an example using __attribute__ ((deprecated))

2021-04-05 18:26 UTC, mchaarawi commented
> > I still see these functions used in pydaos:
> > client/pydaos/raw/daos_api.py
> > so they should be removed from there..
> > also gatekeepers will require an API major version bump and it's not done here.
> 
> A major API version bump will be a pain as it will require downstream components to rebuild. Can we just mark these as deprecated instead to avoid this? Then when we want to deliberately change the major version, we can do a wholesale removal of anything that fits the description.
> 
> See daos_obj.h for an example using **attribute** ((deprecated))

my usage of deprecated for an API is when we provide an alternative API to do a similar functionality to replace the current API.
In this case, my understanding was to totally remove those management APIs as this was never supposed to be exposed to users in the first place. so im not sure deprecated is sufficient here.
I will leave this for some body from the control plane team to comment on though as this is not an area of the code im involved in. (@mjmac @johannlombardi )

2021-04-05 20:47 UTC, jolivier23 commented
> > > I still see these functions used in pydaos:
> > > client/pydaos/raw/daos_api.py
> > > so they should be removed from there..
> > > also gatekeepers will require an API major version bump and it's not done here.
> > 
> > 
> > A major API version bump will be a pain as it will require downstream components to rebuild. Can we just mark these as deprecated instead to avoid this? Then when we want to deliberately change the major version, we can do a wholesale removal of anything that fits the description.
> > See daos_obj.h for an example using **attribute** ((deprecated))
> 
> my usage of deprecated for an API is when we provide an alternative API to do a similar functionality to replace the current API. which is exactly what i did for the oid generate API in daos_obj.h
> In this case, my understanding was to totally remove those management APIs as this was never supposed to be exposed to users in the first place. so im not sure deprecated is sufficient here.
> I will leave this for some body from the control plane team to comment on though as this is not an area of the code im involved in. (@mjmac @johannlombardi )

If nobody external uses them, I think we could justify removal without bumping the major version

2021-04-05 22:19 UTC, mjmac commented
> I will leave this for some body from the control plane team to comment on though as this is not an area of the code im involved in. (@mjmac @johannlombardi )

The control plane doesn't use the client API, so no concerns about this removal from our side.

2021-04-06 15:21 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-06 15:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-06 15:34 UTC, jolivier23 approved these changes

2021-04-06 15:34 UTC, jolivier23 commented on src/include/daos_mgmt.h
should we do whatever core rebuild tests do here rather than removing it entirely? @wangdi1 ?

2021-04-07 17:40 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-07 22:53 UTC, cibervicho commented
CI checks passed. https://build.hpdd.intel.com/blue/rest/organizations/jenkins/pipelines/daos-stack/pipelines/daos/branches/PR-5295/runs/8/nodes/1136/log/?start=0

[2021-04-07T22:28:37.869Z] Running: avocado run --ignore-missing-references on --html-job-result on --tap-job-result off --filter-by-tags=volunit,hw,small --mux-yaml /tmp/tmpdl2cblrm/daos_vol-daos_vol.yaml -- ./daos_vol/daos_vol.py
[2021-04-07T22:28:38.436Z] JOB ID     : d0fad0ac28469663678f707ef13fa3283b7ff1f8
[2021-04-07T22:28:38.436Z] JOB LOG    : /var/tmp/ftest/avocado/job-results/job-2021-04-07T22.28-d0fad0a/job.log
[2021-04-07T22:31:15.289Z]  (01/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test1-dfuse-hosts-pool-servers-31c6:  PASS (149.45 s)
[2021-04-07T22:31:37.245Z]  (02/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test2-dfuse-hosts-pool-servers-8ac6:  PASS (25.59 s)
[2021-04-07T22:32:09.330Z]  (03/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test3-dfuse-hosts-pool-servers-72ed:  PASS (31.09 s)
[2021-04-07T22:35:01.125Z]  (04/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test4-dfuse-hosts-pool-servers-231e:  PASS (161.99 s)
[2021-04-07T22:35:47.849Z]  (05/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test5-dfuse-hosts-pool-servers-96cd:  PASS (51.78 s)
[2021-04-07T22:35:55.983Z]  (06/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test6-dfuse-hosts-pool-servers-2a15:  PASS (15.15 s)
[2021-04-07T22:36:14.088Z]  (07/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test7-dfuse-hosts-pool-servers-8a2e:  PASS (17.88 s)
[2021-04-07T22:36:32.262Z]  (08/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test8-dfuse-hosts-pool-servers-d677:  PASS (15.17 s)
[2021-04-07T22:38:38.751Z]  (09/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_mpich;container-test9-dfuse-hosts-pool-servers-0cab:  PASS (115.54 s)
[2021-04-07T22:39:25.504Z]  (10/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test1-dfuse-hosts-pool-servers-31c6:  PASS (60.03 s)
[2021-04-07T22:39:52.331Z]  (11/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test2-dfuse-hosts-pool-servers-8ac6:  PASS (24.97 s)
[2021-04-07T22:40:24.488Z]  (12/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test3-dfuse-hosts-pool-servers-72ed:  PASS (31.56 s)
[2021-04-07T22:43:31.015Z]  (13/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test4-dfuse-hosts-pool-servers-231e:  PASS (179.58 s)
[2021-04-07T22:44:17.719Z]  (14/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test5-dfuse-hosts-pool-servers-96cd:  PASS (52.08 s)
[2021-04-07T22:44:32.673Z]  (15/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test6-dfuse-hosts-pool-servers-2a15:  PASS (15.31 s)
[2021-04-07T22:44:50.822Z]  (16/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test7-dfuse-hosts-pool-servers-8a2e:  PASS (17.59 s)
[2021-04-07T22:45:05.707Z]  (17/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test8-dfuse-hosts-pool-servers-d677:  PASS (14.93 s)
[2021-04-07T22:47:12.240Z]  (18/18) ./daos_vol/daos_vol.py:DaosVol.test_daos_vol_openmpi;container-test9-dfuse-hosts-pool-servers-0cab:  PASS (115.47 s)
[2021-04-07T22:47:12.240Z] RESULTS    : PASS 18 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

2021-04-07 23:04 UTC, berserk-fury submitted a review, later dismissed

2021-04-07 23:11 UTC, cibervicho commented
Skipped the build in Ubuntu because it can't deal with the PR-repos pragmas.

2021-04-07 23:19 UTC, cibervicho commented
Just a head's up, PR https://github.com/daos-stack/hdf5-vol-daos/pull/16 must land with this one.

2021-04-08 04:36 UTC, sylviachanoiyee commented
Could you kick off a build without skipping tests?

2021-04-08 13:50 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-08 13:55 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/9/execution/node/383/log

2021-04-08 13:58 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/9/execution/node/293/log

2021-04-08 14:11 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/9/execution/node/380/log

2021-04-08 14:20 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-08 14:24 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/10/execution/node/347/log

2021-04-08 14:28 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/10/execution/node/341/log

2021-04-08 14:41 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/10/execution/node/344/log

2021-04-08 16:06 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-08 16:21 UTC, cibervicho commented
> Could you kick off a build without skipping tests?

@sylviachanoiyee I just pushed another run without the "Test-tag" pragma, but I still need to include the "Skip-build-ubuntu20-rpm: true" pragma since the Ubuntu build step can't deal with the "PR-repos" pragma yet.

2021-04-08 16:52 UTC, brianjmurrell commented
> > Could you kick off a build without skipping tests?
> 
> @sylviachanoiyee I just pushed another run without the "Test-tag" pragma, but I still need to include the "Skip-build-ubuntu20-rpm: true" pragma since the Ubuntu build step can't deal with the "PR-repos" pragma yet.

Have you done a current-master regression test (running current master with no changes and just with a `PR-repos:` commit pragma) of hdf5-vol-daos@PR-16 yet?  That's really the first step.  Once that is done, then we can be confident landing that PR and then when this PR has proven the changes it needs, the hdf5-vol-daos PR can land and then this one doesn't need the `PR-repos:` any more.

This really should all be automated in the pipeline for building packages, yes, but it just has not had priority yet.

2021-04-08 17:06 UTC, cibervicho commented
> > > Could you kick off a build without skipping tests?
> > 
> > 
> > @sylviachanoiyee I just pushed another run without the "Test-tag" pragma, but I still need to include the "Skip-build-ubuntu20-rpm: true" pragma since the Ubuntu build step can't deal with the "PR-repos" pragma yet.
> 
> Have you done a current-master regression test (running current master with no changes and just with a `PR-repos:` commit pragma) of hdf5-vol-daos@PR-16 yet? That's really the first step. Once that is done, then we can be confident landing that PR and then when this PR has proven the changes it needs, the hdf5-vol-daos PR can land and then this one doesn't need the `PR-repos:` any more.
> 
> This really should all be automated in the pipeline for building packages, yes, but it just has not had priority yet.

Yes, hdf5-vol-daos@PR-16 has passed (https://github.com/daos-stack/hdf5-vol-daos/pull/16)

2021-04-08 17:09 UTC, brianjmurrell commented
> Yes, hdf5-vol-daos@PR-16 has passed ([daos-stack/hdf5-vol-daos#16](https://github.com/daos-stack/hdf5-vol-daos/pull/16))

That's not what I was asking.  Has that PR been run against pristine master to prove it does not cause any regressions when we land it?

2021-04-08 17:51 UTC, cibervicho commented
> > Yes, hdf5-vol-daos@PR-16 has passed ([daos-stack/hdf5-vol-daos#16](https://github.com/daos-stack/hdf5-vol-daos/pull/16))
> 
> That's not what I was asking. Has that PR been run against pristine master to prove it does not cause any regressions when we land it?

Working on that:  https://github.com/daos-stack/daos/pull/5376

2021-04-10 01:05 UTC, cibervicho commented
This PR seem to be aborted.

2021-04-10 01:23 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-13 09:31 UTC, johannlombardi commented
We will also need to remove the RPC definition and handlers in https://github.com/daos-stack/daos/blob/master/src/pool/rpc.h#L35

2021-04-17 01:16 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-17 03:27 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/13/execution/node/308/log

2021-04-19 14:23 UTC, jbrosenz commented
> We will also need to remove the RPC definition and handlers in https://github.com/daos-stack/daos/blob/master/src/pool/rpc.h#L35

I performed this exercise and created a draft PR to show what it looked like.  It looks like the RPC definitions and handlers should stay as-is, because they are being used.  @liw reviewed the draft and can comment further if necessary.

2021-04-20 01:25 UTC, liw commented
> > We will also need to remove the RPC definition and handlers in https://github.com/daos-stack/daos/blob/master/src/pool/rpc.h#L35
> 
> I performed this exercise and created a draft PR to show what it looked like. It looks like the RPC definitions and handlers should stay as-is, because they are being used. @liw reviewed the draft and can comment further if necessary.

Yes. The RPC operation are used by dRPC and other places. They can't be removed.

2021-04-24 00:52 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-28 15:57 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2190/1000)

[src/client/pydaos/raw/daos_api.py:1309](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L1309):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:22](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L22):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:23](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L23):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:24](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L24):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:83](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L83):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:106](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L106):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:142](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L142):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:190](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L190):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:224](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L224):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:484](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L484):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:818](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L818):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1349](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L1349):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1256](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L1256):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1386](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L1386):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1423](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L1423):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1453](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L1453):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1477](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L1477):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1758](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L1758):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:2170](https://github.com/daos-stack/daos/blob/0692d5b4b53eb2866de2a2448feabdc0bceba627/src/client/pydaos/raw/daos_api.py#L2170):
(pylint-protected-access) Access to a protected member _getframe of a client class

2021-04-30 13:18 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2190/1000)

[src/client/pydaos/raw/daos_api.py:1309](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L1309):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:22](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L22):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:23](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L23):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:24](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L24):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:83](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L83):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:106](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L106):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:142](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L142):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:190](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L190):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:224](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L224):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:484](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L484):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:818](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L818):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1349](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L1349):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1256](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L1256):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1386](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L1386):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1423](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L1423):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1453](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L1453):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1477](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L1477):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1758](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L1758):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:2170](https://github.com/daos-stack/daos/blob/991450a8cf6e007fa3c4a0b8200bc43f1db8ded0/src/client/pydaos/raw/daos_api.py#L2170):
(pylint-protected-access) Access to a protected member _getframe of a client class

2021-04-30 13:18 UTC, jbrosenz commented
Merged master and added the pragmas:
Skip-build-ubuntu20-rpm: true
PR-repos: hdf5-vol-daos@PR-16

2021-04-30 17:41 UTC, daosbuild1 commented
Test stage NLT completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/16/execution/node/885/log

2021-05-01 21:16 UTC, johannlombardi commented
It fails NLT ...

2021-05-03 15:15 UTC, jbrosenz commented
The NLT error looks like it is not related.  Ashley believes it is unrelated to this PR.  I merged master and am letting CI give it another run to see if it changes.

2021-05-03 15:16 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2190/1000)

[src/client/pydaos/raw/daos_api.py:1309](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L1309):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:22](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L22):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:23](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L23):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:24](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L24):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:83](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L83):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:106](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L106):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:142](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L142):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:190](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L190):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:224](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L224):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:484](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L484):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:818](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L818):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1349](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L1349):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1256](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L1256):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1386](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L1386):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1423](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L1423):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1453](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L1453):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1477](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L1477):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1758](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L1758):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:2170](https://github.com/daos-stack/daos/blob/4bbda365185e978d58e0f376085c9787a70d60ba/src/client/pydaos/raw/daos_api.py#L2170):
(pylint-protected-access) Access to a protected member _getframe of a client class

2021-05-03 22:52 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5295/17/display/redirect

2021-05-04 13:28 UTC, jbrosenz commented
Hiccup on CI.  I've merged master for a re-run.

2021-05-04 13:29 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2190/1000)

[src/client/pydaos/raw/daos_api.py:1309](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L1309):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:22](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L22):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:23](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L23):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:24](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L24):
(pylint-relative-beyond-top-level) Attempted relative import beyond top-level package

[src/client/pydaos/raw/daos_api.py:83](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L83):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:106](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L106):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:142](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L142):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:190](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L190):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:224](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L224):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:484](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L484):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:818](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L818):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1349](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L1349):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1256](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L1256):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1386](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L1386):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1423](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L1423):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1453](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L1453):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1477](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L1477):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1758](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L1758):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:2170](https://github.com/daos-stack/daos/blob/a3871fc4e8e4bc9c3da469551fc7cdd188c71306/src/client/pydaos/raw/daos_api.py#L2170):
(pylint-protected-access) Access to a protected member _getframe of a client class

2021-05-28 19:57 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2157/1000)

[src/client/pydaos/raw/daos_api.py:1283](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L1283):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:83](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L83):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:106](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L106):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:142](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L142):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:190](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L190):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:458](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L458):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:792](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L792):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1323](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L1323):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1230](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L1230):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1360](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L1360):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1397](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L1397):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1427](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L1427):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1451](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L1451):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1732](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L1732):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:2144](https://github.com/daos-stack/daos/blob/a3c84d42a0e833657a951d58b882164821f6d3fd/src/client/pydaos/raw/daos_api.py#L2144):
(pylint-protected-access) Access to a protected member _getframe of a client class

2021-05-28 20:03 UTC, daosbuild1 commented
Test stage Build on CentOS 7 debug completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/19/execution/node/429/log

2021-05-28 20:03 UTC, daosbuild1 commented
Test stage Build on CentOS 7 release completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/19/execution/node/431/log

2021-05-28 20:03 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/19/execution/node/384/log

2021-05-28 20:05 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/19/execution/node/387/log

2021-05-28 20:05 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/19/execution/node/306/log

2021-05-28 20:06 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/19/execution/node/361/log

2021-05-28 20:08 UTC, daosbuild1 commented
Test stage Build on Leap 15 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/19/execution/node/433/log

2021-05-28 20:19 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/19/execution/node/399/log

2021-05-28 20:34 UTC, johannlombardi commented
@jbrosenz it sounds like the automatic merge failed. Could you please refresh the patch?

2021-06-01 14:57 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2157/1000)

[src/client/pydaos/raw/daos_api.py:1283](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1283):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:83](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L83):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:106](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L106):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:142](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L142):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:190](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L190):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:458](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L458):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:792](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L792):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1323](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1323):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1230](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1230):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1360](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1360):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1397](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1397):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1427](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1427):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1451](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1451):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1732](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1732):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:2144](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L2144):
(pylint-protected-access) Access to a protected member _getframe of a client class

2021-06-01 16:34 UTC, daosbuild1 commented
Test stage NLT completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5295/20/execution/node/834/log

2021-06-03 17:16 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/client/pydaos/raw/daos_api.py:1](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1):
(pylint-too-many-lines) Too many lines in module (2157/1000)

[src/client/pydaos/raw/daos_api.py:1283](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1283):
(lint) This should ideally fail.

[src/client/pydaos/raw/daos_api.py:83](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L83):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:106](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L106):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:142](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L142):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:190](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L190):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:458](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L458):
(pylint-raise-missing-from) Consider explicitly re-raising using the 'from' keyword

[src/client/pydaos/raw/daos_api.py:792](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L792):
(pylint-unnecessary-pass) Unnecessary pass statement

[src/client/pydaos/raw/daos_api.py:1323](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1323):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1230](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1230):
(pylint-too-many-branches) Too many branches (27/25)

[src/client/pydaos/raw/daos_api.py:1360](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1360):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1397](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1397):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1427](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1427):
(pylint-no-else-raise) Unnecessary "else" after "raise"

[src/client/pydaos/raw/daos_api.py:1451](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1451):
(pylint-no-else-return) Unnecessary "else" after "return"

[src/client/pydaos/raw/daos_api.py:1732](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L1732):
(pylint-unused-argument) Unused argument 'context'

[src/client/pydaos/raw/daos_api.py:2144](https://github.com/daos-stack/daos/blob/09b30b229d73db682fb80b65940bddee772e7a1c/src/client/pydaos/raw/daos_api.py#L2144):
(pylint-protected-access) Access to a protected member _getframe of a client class

2021-06-06 07:53 UTC, johannlombardi approved these changes

2021-06-06 07:56 UTC, merged