Revert "DAOS-6495 test: Enable python bandit checking by default"
daos-stack/daos pull request #5490
Opened 2021-04-17 07:26 UTC by johannlombardi

Reverts daos-stack/daos#4964

2021-04-17 07:28 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-17 07:31 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5490/1/execution/node/284/log

2021-04-17 07:33 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5490/1/execution/node/362/log

2021-04-17 07:38 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5490/1/execution/node/365/log

2021-04-17 13:46 UTC, jolivier23 requested changes
Just want to make a comment to make sure we consider whether to revert this or not.

If you look at results for the master branch run after it was landed

https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/4353/

You can see the 187 failures but the build is still marked "green".   So these failures are essentially like checkpatch in that they are not fatal to the build.  They are annoying though but I think the idea here is to prevent new ones from coming in so we can look at and address the existing ones.  The patch will allow us to do that.

It does, however, make it a little harder to figure out what actual runtime tests failed.

2021-04-19 08:28 UTC, ashleypittman commented
It looks like the issue with this PR is that when it's run on master there are lots of historic builds in the tree which probably just shouldn't be there, with pylint/checkpatch we avoid this by ignoring the rpm build directories.

2021-04-23 14:07 UTC, ashleypittman commented
Fixed in https://github.com/daos-stack/daos/pull/5523

2021-04-23 14:07 UTC, closed without merging