DAOS-5465 csum: Corrupt BIO Address through VOS
daos-stack/daos pull request #5501
Opened 2021-04-19 21:24 UTC by ryon-jensen

Add the ability to set a bio address as corrupted using the VOS
iter API. This will be necessary for the checksum scrubber
to be able to mark data as corrupted when silent data
corruption is detected.

- Use extra padding in the bio_addr_t structure for flags and add a
  corrupted flag to indicate that data is corrupted.
- Add corrupted field to necessary structs in VOS to facilitate
  the setting/getting of the corrupted status of the data.
- Add vos_iter_corrupt api for setting the current record
  as corrupted.

Signed-off-by: Ryon Jensen <ryon.jensen@intel.com>

2021-04-19 21:26 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5501/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-04-19 21:26 UTC, daosbuild1 commented on src/vos/tests/vts_checksum.c
> +	param.ip_hdl = k.container_hdl;
(style)  Missing a blank line after declarations

2021-04-19 21:26 UTC, daosbuild1 commented on src/vos/tests/vts_checksum.c
> +	rc = vos_iterate(&param, VOS_ITER_OBJ, true, &anchor,
(style)  Missing a blank line after declarations

2021-04-19 21:26 UTC, daosbuild1 commented on src/vos/tests/vts_checksum.c
> +	param.ip_hdl = k.container_hdl;
```suggestion
	vos_iter_param_t param = {0};

```

2021-04-19 21:26 UTC, daosbuild1 commented on src/vos/tests/vts_checksum.c
> +	rc = vos_iterate(&param, VOS_ITER_OBJ, true, &anchor,
```suggestion
	struct vos_iter_anchors anchor = {0};

```

2021-04-19 21:26 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5501/1/execution/node/79/log

2021-04-19 21:30 UTC, ryon-jensen commented
This is a different approach to PR5444

2021-04-19 21:35 UTC, daosbuild1 commented
Test stage Build on CentOS 7 debug completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5501/2/execution/node/438/log

2021-04-19 21:35 UTC, daosbuild1 commented
Test stage Build on CentOS 7 release completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5501/2/execution/node/442/log

2021-04-19 21:36 UTC, daosbuild1 commented
Test stage Build on Ubuntu 20.04 with Clang completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5501/2/execution/node/436/log

2021-04-19 21:37 UTC, daosbuild1 commented
Test stage Build on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5501/2/execution/node/466/log

2021-04-19 21:37 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5501/2/execution/node/346/log

2021-04-19 21:37 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5501/2/execution/node/378/log

2021-04-19 21:38 UTC, daosbuild1 commented
Test stage Build on Leap 15 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5501/2/execution/node/464/log

2021-04-19 21:47 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5501/2/execution/node/431/log

2021-04-19 21:53 UTC, daosbuild1 commented
Test stage Build on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5501/2/execution/node/441/log

2021-04-19 21:56 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-19 22:38 UTC, jolivier23 submitted a review, later dismissed

2021-04-19 22:39 UTC, jolivier23 commented on src/include/daos_srv/bio.h
> +	uint16_t	ba_flags;
This should probably go in a separate change if we do it.  One that we might want to push to 1.2 along with space reservation for a btree in the pool

2021-04-19 22:56 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5501/3/execution/node/782/log

2021-04-20 02:15 UTC, ryon-jensen commented on src/include/daos_srv/bio.h
> +	uint16_t	ba_flags;
Makes sense. I can split it in to a different PR and create a separate ticket for it if it indeed needs to land to 1.2. I'm not in the meetings where 1.2 stuff is discussed, so let me know what's decided.

2021-04-20 02:16 UTC, ryon-jensen commented on src/include/daos_srv/vos.h
> +vos_iter_corrupt(daos_handle_t ih);
Ya, I agree. vos_iter_corrupt is too specialized. :)

2021-04-20 03:11 UTC, NiuYawei requested changes

2021-04-20 03:11 UTC, NiuYawei commented on src/vos/evt_iter.c
> +	BIO_ADDR_SET_CORRUPTED(&desc->dc_ex_addr);
I'm wondering why don't make it into a transaction to ensure the persistency (like what you did for dbtree_iter_corrupt()).

2021-04-20 03:11 UTC, NiuYawei commented on src/vos/vos_tree.c
> +	BIO_ADDR_SET_CORRUPTED(&irec->ir_ex_addr);
You did a in-place update (within PMDK transaction) without making snapshot by umem_tx_add().

2021-04-20 15:45 UTC, ryon-jensen commented on src/include/daos_srv/bio.h
> +	uint16_t	ba_flags;
I created PR #5510 for the bio_addr_t changes.

2021-04-20 16:31 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-20 16:32 UTC, ryon-jensen commented
Thanks @NiuYawei for your feedback. I'm not as familiar with the umem transaction stuff. Would you take a look at my updates in response to your feedback? There's still more updates that I need to make, but I want to make sure I've got the umem stuff right.

2021-04-21 01:10 UTC, NiuYawei approved these changes

2021-04-21 01:10 UTC, NiuYawei commented on src/vos/evt_iter.c
> +	rc = umem_tx_add(&tcx->tc_umm, trace->tr_node, sizeof(*desc));
I think we don't have to making snapshot for the whole desc,  adding 'dc_tx_addr' should be sufficient.

2021-04-21 01:10 UTC, NiuYawei commented on src/vos/vos_tree.c
> +	rc = umem_tx_add(&tins->ti_umm, rec->rec_off, sizeof(*irec));
Not a big deal, adding 'ir_ex_addr' only?

2021-04-23 16:19 UTC, Nasf-Fan commented on src/vos/evt_iter.c
> +	BIO_ADDR_SET_CORRUPTED(&desc->dc_ex_addr);
Do that when "if (rc == 0)".

2021-04-23 18:08 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-26 18:43 UTC, closed without merging