DAOS-7276 control: disable forwarding to syslog
daos-stack/daos pull request #5508
Opened 2021-04-20 15:30 UTC by tanabarr

Set daos_server service output to syslog to priority level debug to
avoid automatic forwarding of info level entries to syslog

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

2021-04-20 15:32 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-20 15:44 UTC, brianjmurrell requested changes
This doesn't feel like a/the correct fix for the problem.  Is this actually a case of https://bugzilla.redhat.com/show_bug.cgi?id=1855064?

Or is this a case of needing to specify `ForwardToSyslog=no` in `/etc/systemd/journald.conf`?

2021-04-21 08:57 UTC, tanabarr commented
> This doesn't feel like a/the correct fix for the problem. Is this actually a case of https://bugzilla.redhat.com/show_bug.cgi?id=1855064?
> 
> Or is this a case of needing to specify `ForwardToSyslog=no` in `/etc/systemd/journald.conf`?

We have already had a fair amount of off-line dialogue about this, this change is a step forward as standard out/err from the daos_server process shouldn't be classified as syslog priority INFO, which it currently is. This change will correct the syslog priority for output from the service, avoiding forwarding for the specific service whilst not affecting forwarding for other services on the system.

2021-04-21 14:05 UTC, brianjmurrell commented
> We have already had a fair amount of off-line dialogue about this,

Yes.  I wasn't convinced that the correct problem was being fixed during that conversation either.

> this change is a step forward as standard out/err from the daos_server process shouldn't be classified as syslog priority INFO,

Shouldn't be sent to syslog at all, or just messages at INFO level?  My understanding was that you were trying to completely disable syslog forwarding of all DAOS messages.

> which it currently is. This change will correct the syslog priority for output from the service, avoiding forwarding for the specific service

But only for messages of INFO or lower.  If the user enables debug such that DEBUG level messages are generated, those will go to syslog, won't they?  Is that really what we want, or are we trying to stop all DAOS messages, at any level, from going to syslog?

Quite honestly, all of this seems site-specific.  What one sysadmin wants will surely be different from what another wants.  AFAIU the default behaviour of systemd is to log a process's stdout/stderr to the journal.  Whether the journal's content also goes to syslog also again seems site specific.  I do wonder if we should just be embracing the principle of least surprise and just doing what all other systemd units do, so that we don't surprise the admin with outlier behaviour.

Another thing to consider perhaps is our stdout too chatty by default?

2021-04-21 20:11 UTC, tanabarr commented
> Shouldn't be sent to syslog at all, or just messages at INFO level? My understanding was that you were trying to completely disable syslog forwarding of all DAOS messages.
 
shouldn't be sent at all, but the fact is it is being pulled from the journal when systemd classifies it as INFO priority

> But only for messages of INFO or lower. If the user enables debug such that DEBUG level messages are generated, those will go to syslog, won't they? Is that really what we want, or are we trying to stop all DAOS messages, at any level, from going to syslog?

no, with these changes all DAOS output will be classified as DEBUG priority regardless of any DAOS generated prefix, external syslog managers e.g. rsyslog/imjournal, logstash, systemd will only forward INFO and higher

> Quite honestly, all of this seems site-specific. What one sysadmin wants will surely be different from what another wants. AFAIU the default behaviour of systemd is to log a process's stdout/stderr to the journal. Whether the journal's content also goes to syslog also again seems site specific. I do wonder if we should just be embracing the principle of least surprise and just doing what all other systemd units do, so that we don't surprise the admin with outlier behaviour.

this isn't outlier behaviour, IMO  this is a sensible step to improve the signal-to-noise ratio by leveraging our ability to write directly to syslog at custom priority levels from inside the control plane at the same time as providing detailed developer level logging to the journal

> Another thing to consider perhaps is our stdout too chatty by default?

yes it probably is

2021-04-22 18:02 UTC, mjmac reviewed
So if I understand correctly, the intent of this PR is to only allow RAS events to be logged from daos_server to syslog. All other output from daos_server will wind up in journalctl or a logfile if daos_control_log was set in the server config.

Isn't there a possibility that important context for the RAS events might be lost in this case? I'm thinking about the use case of a cluster with centralized logging and analysis (e.g. splunk). These systems won't know anything about our logfiles, and I don't know if they integrate with the systemd journal or just rely on stuff being forwarded to syslog.

2021-04-22 19:30 UTC, tanabarr commented
> So if I understand correctly, the intent of this PR is to only allow RAS events to be logged from daos_server to syslog. All other output from daos_server will wind up in journalctl or a logfile if daos_control_log was set in the server config.
> 
> Isn't there a possibility that important context for the RAS events might be lost in this case? I'm thinking about the use case of a cluster with centralized logging and analysis (e.g. splunk). These systems won't know anything about our logfiles, and I don't know if they integrate with the systemd journal or just rely on stuff being forwarded to syslog.

We can obviously continue to send log output to syslog if we want but I was under the impression from both you and @johannlombardi  that we wanted to restrict syslog output to RAS events only. I assumed that context for the events would be gathered from other sources e.g. journal or log files.

2021-04-23 08:46 UTC, tanabarr commented
@mjmac the other purpose of this ticket is to bring the syslog output of source builds and RPM installations into parity, source built server binary will not output to syslog by default.

2021-04-24 00:17 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-29 18:39 UTC, closed without merging