DAOS-623 vos: Fix consistency statements in README
daos-stack/daos pull request #5540
Opened 2021-04-22 06:36 UTC by liw

Thanks to Duan Shibo <duanshibo.d@gmail.com> on the daos mailing list,
an inaccuracy about the external consistency statement is found. This
patch fixes the comment to reflect the current implementation.

Doc-only: true
Signed-off-by: Li Wei <wei.g.li@intel.com>

2021-04-23 06:19 UTC, Nasf-Fan approved these changes

2021-04-26 14:06 UTC, jolivier23 requested changes

2021-04-26 14:06 UTC, jolivier23 commented on src/vos/README.md
> +conflicting transactions commit before it openes, as long as the
s/openes/opens ?

2021-04-27 01:42 UTC, liw commented on src/vos/README.md
> +conflicting transactions commit before it openes, as long as the
Errh... Will fix.

2021-04-27 06:37 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-04-27 14:22 UTC, jolivier23 approved these changes

2021-04-27 14:23 UTC, merged