DAOS-2617 documentation: update release notes and API
daos-stack/daos pull request #5623
Opened 2021-05-01 01:05 UTC by cdurf1

Skip-build: true
Skip-test: true

Signed-off-by: craig <craig.durfey@intel.com>

2021-05-01 01:07 UTC, cdurf1 commented
Only Release notes require review. The other files are for the API

2021-05-01 21:09 UTC, johannlombardi requested changes
all the code under doc/html should not go in the repository.

2021-05-02 21:02 UTC, brianjmurrell commented on doc/release/release_notes_v1_2.md
> +-  End-to-end Data Integrity
Extra space here:
```suggestion
- End-to-end Data Integrity
```

2021-05-02 21:02 UTC, brianjmurrell commented on doc/release/release_notes_v1_2.md
> +-  HDF5 with Async
Ditto.

```suggestion
- HDF5 with Async
```

2021-05-02 21:04 UTC, brianjmurrell commented on doc/release/release_notes_v1_2.md
> +is currently the only supported Linux distribution. An exhaustive list of
We are not supporting Leap/SLES 15 yet, officially?

2021-05-02 22:15 UTC, brianjmurrell commented on doc/release/release_notes_v1_2.md
> +- Testing has been performed on CentOS 7.9, OpenSuse 15.2,with CentOS  being used in the majority of the test cycles. Smaller scale testing has been done on OpenSuse 15.2, and no testing performed on
```suggestion
- Testing has been performed on CentOS 7.9, OpenSuse 15.2, with CentOS  being used in the majority of the test cycles. Smaller scale testing has been done on OpenSuse 15.2, and no testing performed on Ubuntu and MOFED 5.1x
```

2021-05-03 11:37 UTC, brianjmurrell commented on doc/release/release_notes_v1_2.md
> +space even there is plenty of free space in SSD
This seems to be a repeat of lines 298-326.

2021-05-03 13:01 UTC, closed without merging

2021-05-03 13:01 UTC, cdurf1 commented
Closing this request to delete html files

2021-05-03 19:18 UTC, skirvan44 commented on doc/release/release_notes_v1_2.md
> + - Reed-Solomon based EC support for I/O. DAOS has two value types: array value for large streaming I/O; single value for Key-value store. DAOS EC supports both array value and single value. An array
This feature also provides a set of predefined EC object classes as its user interface.  Perhaps instead:

The EC feature is activated by utilizing one of the predefined EC object classes.

2021-05-03 19:18 UTC, skirvan44 commented on doc/release/release_notes_v1_2.md
> +In DAOS, the excluded targets can be reintegrated back into the pool by dmg pool command, though the pool should not be connected (no I/O) during reintegration, otherwise application failure or even
Could we be explicit about the meaning of target here?

2021-05-03 19:18 UTC, skirvan44 commented on doc/release/release_notes_v1_2.md
> +supported as preview features and will be fully supported in the next release.
Is this left over from 1.0?  I believe we are claiming support for replication & self healing

2021-05-03 19:18 UTC, skirvan44 commented on doc/release/release_notes_v1_2.md
> +The aggregation service is only activated after the system has idled for more
ditto here, left over from 1.0?