DAOS-7455 daos: fix destination container creation
daos-stack/daos pull request #5674
Opened 2021-05-07 20:08 UTC by dsikich

When passing a generated cont UUID to filesystem copy
dfs_cont_create was failing. The cont_type was being
set incorrectly when passed to DFS through the container
properties. Also, since uns_resolve_path has been extended
to handle daos://$pool as a destination the cont_clone_hdlr
was updated. The created container UUID is now also being
printed to stdout.

Signed-off-by: Danielle Sikich <danielle.sikich@intel.com>

2021-05-07 20:10 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5674/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-05-07 20:10 UTC, daosbuild1 commented on src/utils/daos_hdlr.c
> +	 	/* This will be extended to get all props
(style)  code indent should use tabs where possible
(style)  please, no space before tabs

2021-05-07 20:10 UTC, daosbuild1 commented on src/utils/daos_hdlr.c
> +				fprintf(stderr, "Failed to allocate prop (%d)", rc);
(style)  line over 80 characters

2021-05-07 20:10 UTC, daosbuild1 commented on src/utils/daos_hdlr.c
> +
(style)  trailing whitespace

2021-05-07 20:10 UTC, daosbuild1 commented on src/utils/daos_hdlr.c
> +
(style)  trailing whitespace

2021-05-07 20:10 UTC, daosbuild1 commented on src/utils/daos_hdlr.c
> +		 * for object level copies */
(style)  Block comments use a trailing */ on a separate line

2021-05-07 20:10 UTC, daosbuild1 commented on src/utils/daos_hdlr.c
> +
(style)  trailing whitespace

2021-05-07 20:10 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5674/1/execution/node/85/log

2021-05-07 20:17 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-05-07 20:34 UTC, daltonbohning reviewed
@dsikich I'd recommend adding this pragma to your commit message to run the functional tests as a sanity check:

Features: fs_copy cont_clone

2021-05-07 20:38 UTC, dsikich commented
> @dsikich I'd recommend adding this pragma to your commit message to run the functional tests as a sanity check:
> 
> Features: fs_copy cont_clone

@daltonbohning thanks, added it!

2021-05-07 20:40 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-05-07 20:43 UTC, daltonbohning requested changes

2021-05-07 20:43 UTC, daltonbohning commented on src/utils/daos_hdlr.c
> +				D_GOTO(out, rc);
@dsikich Just noticed... daos_prop_alloc doesn't return an rc
```suggestion
			props = daos_prop_alloc(2);
			if (props == NULL) {
				fprintf(stderr, "Failed to allocate prop\n");
				D_GOTO(out, rc = -DER_NOMEM);
```

2021-05-07 20:47 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-05-07 20:47 UTC, daltonbohning approved these changes
Assuming the tests pass, LGTM.

2021-05-07 22:55 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-05-07 23:02 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-05-10 14:16 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-05-10 23:41 UTC, daosbuild1 commented
Test stage Functional on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5674/11/display/redirect

2021-05-10 23:54 UTC, mchaarawi approved these changes
looks fine to me, although i would really prefer to add some tests for any additional supported features in the daos tool to make sure it work and no regression gets introduced, if for example we change something in the duns.

2021-05-10 23:55 UTC, daosbuild1 commented
Test stage Functional on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5674/11/display/redirect

2021-05-11 23:15 UTC, dsikich commented
> looks fine to me, although i would really prefer to add some tests for any additional supported features in the daos tool to make sure it work and no regression gets introduced, if for example we change something in the duns.

@mchaarawi Thanks, there are some functional tests now for fs_copy and cont_clone that were run with Features: fs_copy cont_clone for this PR. There could be more though since there are so many different tools and options for each now. It is getting hard to keep track of and keep them all in sync between the daos tools and mpifileutils.

2021-05-11 23:30 UTC, dsikich commented
> > > looks fine to me, although i would really prefer to add some tests for any additional supported features in the daos tool to make sure it work and no regression gets introduced, if for example we change something in the duns.
> > 
> > 
> > @mchaarawi Thanks, there are some functional tests now for fs_copy and cont_clone that were run with Features: fs_copy cont_clone for this PR. There could be more though since there are so many different tools and options for each now. It is getting hard to keep track of and keep them all in sync between the daos tools and mpifileutils.
> 
> well my comment is referring directly to this PR that is fixing this case:
> "When passing a generated cont UUID to filesystem copy dfs_cont_create was failing."
> i don't see a test added for the daos tool, so if this is supposed to be fixing something, it would be good to a test so we don't see a regression.
> 
> same thing for:
> handle daos://$pool as a destination



> > > looks fine to me, although i would really prefer to add some tests for any additional supported features in the daos tool to make sure it work and no regression gets introduced, if for example we change something in the duns.
> > 
> > 
> > @mchaarawi Thanks, there are some functional tests now for fs_copy and cont_clone that were run with Features: fs_copy cont_clone for this PR. There could be more though since there are so many different tools and options for each now. It is getting hard to keep track of and keep them all in sync between the daos tools and mpifileutils.
> 
> well my comment is referring directly to this PR that is fixing this case:
> "When passing a generated cont UUID to filesystem copy dfs_cont_create was failing."
> i don't see a test added for the daos tool, so if this is supposed to be fixing something, it would be good to a test so we don't see a regression.
> 
> same thing for:
> handle daos://$pool as a destination

@mchaarawi Ok, yeah I agree. Would you prefer I add it to this PR?

2021-05-12 15:13 UTC, mchaarawi commented
> @mchaarawi Ok, yeah I agree. Would you prefer I add it to this PR?

oh no, that's fine. we can do it in a future PR. i was just saying since im making some changes to the UNS as you can see and it would be good to know that i don't break stuff by running unit tests in CI.

2021-05-12 15:29 UTC, dsikich commented
> > @mchaarawi Ok, yeah I agree. Would you prefer I add it to this PR?
> 
> oh no, that's fine. we can do it in a future PR. i was just saying since im making some changes to the UNS as you can see and it would be good to know that i don't break stuff by running unit tests in CI.

@mchaarawi ok, just wanted to make sure. I am going to look into it this week.

2021-05-17 23:52 UTC, merged