DAOS-5986 test: Implemented config_generate_run.py
daos-stack/daos pull request #5685
Opened 2021-05-10 18:39 UTC by shimizukko

Run dmg config generate and run daos_server with generated config file.

Quick-build: true
Skip-unit-tests: true
Test-tag: config_generate_run
Signed-off-by: Makito Kano <makito.kano@intel.com>

2021-05-10 18:41 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5685/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-05-10 18:47 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5685/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-05-10 18:47 UTC, daosbuild1 commented on src/tests/ftest/control/config_generate_run.py
> +            self.log.debug("## engine {}".format(i))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-05-10 18:47 UTC, daosbuild1 commented on src/tests/ftest/control/config_generate_run.py
> +            self.log.debug("## scm_mount = {}".format(engine["scm_mount"]))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-05-10 18:47 UTC, daosbuild1 commented on src/tests/ftest/control/config_generate_run.py
> +            self.log.debug("## scm_class = {}".format(engine["scm_class"]))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-05-10 18:47 UTC, daosbuild1 commented on src/tests/ftest/control/config_generate_run.py
> +            self.log.debug("## scm_list = {}".format(engine["scm_list"]))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-05-10 19:01 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5685/3/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-05-10 19:01 UTC, daosbuild1 commented on src/tests/ftest/control/config_generate_run.py
> +            self.log.debug("## scm_mount = {}".format(engine["scm_mount"]))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-05-10 19:01 UTC, daosbuild1 commented on src/tests/ftest/control/config_generate_run.py
> +            self.log.debug("## scm_list = {}".format(engine["scm_list"]))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-05-10 19:01 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/3/execution/node/102/log

2021-05-10 19:07 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/3/execution/node/309/log

2021-05-10 19:09 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/3/execution/node/314/log

2021-05-10 19:09 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/3/execution/node/295/log

2021-05-10 19:37 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/3/execution/node/319/log

2021-05-12 17:25 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5685/4/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-05-12 17:25 UTC, daosbuild1 commented on src/tests/ftest/control/config_generate_run.py
> +            self.log.debug("## engine {}".format(i))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-05-12 17:25 UTC, daosbuild1 commented on src/tests/ftest/control/config_generate_run.py
> +            self.log.debug("## scm_mount = {}".format(engine["scm_mount"]))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-05-12 17:25 UTC, daosbuild1 commented on src/tests/ftest/control/config_generate_run.py
> +            self.log.debug("## scm_class = {}".format(engine["scm_class"]))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-05-12 17:25 UTC, daosbuild1 commented on src/tests/ftest/control/config_generate_run.py
> +            self.log.debug("## scm_list = {}".format(engine["scm_list"]))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-05-12 17:25 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/4/execution/node/94/log

2021-05-12 17:34 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/4/execution/node/284/log

2021-05-12 17:36 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/4/execution/node/318/log

2021-05-12 17:36 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/4/execution/node/297/log

2021-05-12 18:05 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/4/execution/node/300/log

2021-05-14 11:09 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5685/5/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-05-14 11:09 UTC, daosbuild1 commented on src/tests/ftest/control/config_generate_run.py
> +            self.log.debug("## engine {}".format(i))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-05-14 11:09 UTC, daosbuild1 commented on src/tests/ftest/control/config_generate_run.py
> +            self.log.debug("## scm_mount = {}".format(engine["scm_mount"]))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-05-14 11:09 UTC, daosbuild1 commented on src/tests/ftest/control/config_generate_run.py
> +            self.log.debug("## scm_class = {}".format(engine["scm_class"]))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-05-14 11:09 UTC, daosbuild1 commented on src/tests/ftest/control/config_generate_run.py
> +            self.log.debug("## scm_list = {}".format(engine["scm_list"]))
(pylint-logging-format-interpolation) Use lazy % formatting in logging functions

2021-05-14 11:10 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/5/execution/node/98/log

2021-05-14 11:15 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/5/execution/node/309/log

2021-05-14 11:17 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/5/execution/node/315/log

2021-05-14 11:17 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/5/execution/node/312/log

2021-05-14 11:45 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/5/execution/node/318/log

2021-06-12 18:13 UTC, daosbuild1 commented
Test stage Functional on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/7/execution/node/709/log

2021-06-14 19:08 UTC, phender requested changes

2021-06-15 15:43 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/9/execution/node/252/log

2021-06-15 15:49 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/9/execution/node/242/log

2021-06-15 15:51 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/9/execution/node/241/log

2021-06-15 15:54 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5685/9/execution/node/249/log

2021-06-16 21:00 UTC, dinghwah approved these changes
LGTM.

2021-06-17 16:08 UTC, phender approved these changes

2021-06-17 20:23 UTC, merged