DAOS-623 test: Add fault injection check for NVMe tests
daos-stack/daos pull request #5697
Opened 2021-05-13 19:27 UTC by jolivier23

Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>

2021-05-13 19:29 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-05-13 19:35 UTC, ravalsam requested changes
There are other Two test cases where we remove the NVMe disk so also need to add in those function mention below.

nvme_test_verify_device_stats()
nvme_test_get_blobstore_state()

2021-05-14 12:24 UTC, jolivier23 commented
> There are other Two test cases where we remove the NVMe disk so also need to add in those function mention below.
> 
> 
> 
> nvme_test_verify_device_stats()
> 
> nvme_test_get_blobstore_state()

I couldn't find any fault injection calls in the other tests.  It looks like they are using dmg?

2021-05-14 16:30 UTC, ravalsam commented
> > There are other Two test cases where we remove the NVMe disk so also need to add in those function mention below.
> > nvme_test_verify_device_stats()
> > nvme_test_get_blobstore_state()
> 
> I couldn't find any fault injection calls in the other tests. It looks like they are using dmg?

Yes, it's using DMG, I see what you mean by fault injection in this case now.

2021-05-14 16:30 UTC, ravalsam approved these changes

2021-05-17 08:36 UTC, NiuYawei approved these changes

2021-05-17 13:18 UTC, merged