DAOS-7488 documentation: document usage of daos autotest in daos admi…
daos-stack/daos pull request #5735
Opened 2021-05-18 13:55 UTC by cdurf1

DAOS-7488 documentation: document daos autotest in daos admin guide

Skip-build: true
Skip-test: true

Signed-off-by: craig <craig.durfey@intel.com>

2021-05-18 14:00 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5735/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-05-18 14:00 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5735/1/execution/node/115/log

2021-05-18 14:52 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5735/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-05-18 14:52 UTC, daosbuild1 commented on doc/admin/deployment.md
> +
(style)  trailing whitespace

2021-05-18 14:52 UTC, daosbuild1 commented on doc/admin/deployment.md
> +
(style)  trailing whitespace

2021-05-18 14:52 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5735/2/execution/node/98/log

2021-05-19 14:04 UTC, johannlombardi requested changes
Looks good. Just a few changes.

2021-05-19 14:04 UTC, johannlombardi commented on doc/admin/deployment.md
> +on storage target'
should probably be moved to !!! note

2021-05-19 14:04 UTC, johannlombardi commented on doc/admin/deployment.md
> +
Please fix

2021-05-19 14:04 UTC, johannlombardi commented on doc/admin/deployment.md
> +
Please fix.

2021-05-19 14:04 UTC, johannlombardi commented on doc/admin/deployment.md
>  ### Launch the client application
Sounds like we don't really need this sub-section any longer given that the text is shorter.

2021-05-19 15:02 UTC, omar-ocampo commented
Looks good to me

2021-05-19 15:03 UTC, omar-ocampo approved these changes

2021-05-19 21:55 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5735/3/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-05-19 21:55 UTC, daosbuild1 commented on doc/admin/deployment.md
> +
(style)  trailing whitespace

2021-05-19 21:55 UTC, daosbuild1 commented on doc/admin/deployment.md
> +
(style)  trailing whitespace

2021-05-19 21:55 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5735/3/execution/node/102/log

2021-09-27 16:45 UTC, closed without merging