Include DAOS-4419 change in soak
daos-stack/daos pull request #5751
Opened 2021-05-20 09:46 UTC by mjean308

Quick-Functional: true
Skip-func-hw-test-small: true
Skip-func-hw-test-medium: true
Skip-func-test-vm: true
Test-tag-hw-large: soak_smoke

Signed-off-by: Maureen Jean <maureen.jean@intel.com>

2021-05-20 09:48 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_utils.py:1](https://github.com/daos-stack/daos/blob/20ab8b0722501b8a9b9d08412e4a995f13d098a4/src/tests/ftest/soak/soak_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1006/1000)

2021-05-20 22:53 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_utils.py:1](https://github.com/daos-stack/daos/blob/ec9013dc0cf3e877d54dc7867e907d969f7ac61a/src/tests/ftest/soak/soak_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1012/1000)

2021-05-21 10:21 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_utils.py:1](https://github.com/daos-stack/daos/blob/3962f6368d23ec66c4007aab9af6470f9d71157a/src/tests/ftest/soak/soak_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1004/1000)

2021-05-21 13:46 UTC, phender requested changes

2021-05-21 13:46 UTC, phender commented on src/tests/ftest/soak/soak_utils.py
> +        "sleep 20",
Was this intended?

2021-05-21 13:51 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_utils.py:1](https://github.com/daos-stack/daos/blob/f02f1d1119c9c1b50a4efcad33c23ed71c801ae2/src/tests/ftest/soak/soak_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1004/1000)

2021-06-01 17:40 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_utils.py:1](https://github.com/daos-stack/daos/blob/bcd27826d2293ab1e9e7fcdf340cfb12036c7e8a/src/tests/ftest/soak/soak_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1004/1000)

2021-06-01 18:26 UTC, shimizukko submitted a review, later dismissed

2021-06-01 18:28 UTC, dinghwah submitted a review, later dismissed
LGTM

2021-06-03 13:21 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_utils.py:1](https://github.com/daos-stack/daos/blob/87205b2f8b8a3208e0633e1e344f7020042a0acd/src/tests/ftest/soak/soak_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1004/1000)

2021-06-07 19:06 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_utils.py:1](https://github.com/daos-stack/daos/blob/64e11c49e3b3ee60770444de3a707000a7566b46/src/tests/ftest/soak/soak_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1004/1000)

2021-06-08 18:05 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/soak/soak_test_base.py:23](https://github.com/daos-stack/daos/blob/0d069072e0da34fc6526b8f79c573684e658df72/src/tests/ftest/soak/soak_test_base.py#L23):
(pylint-reimported) Reimport 'cleanup_dfuse' (imported line 23)
(pylint-unused-import) Unused create_racer_cmdline imported from soak_utils

[src/tests/ftest/soak/soak_test_base.py:301](https://github.com/daos-stack/daos/blob/0d069072e0da34fc6526b8f79c573684e658df72/src/tests/ftest/soak/soak_test_base.py#L301):
(pylint-no-member) Instance of 'SoakTestBase' has no 'job' member

[src/tests/ftest/soak/soak_utils.py:1](https://github.com/daos-stack/daos/blob/0d069072e0da34fc6526b8f79c573684e658df72/src/tests/ftest/soak/soak_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1015/1000)

2021-06-08 18:37 UTC, shimizukko approved these changes

2021-06-08 21:46 UTC, dinghwah approved these changes
LGTM.

2021-06-09 12:41 UTC, mjean308 commented
Single test failure is a soak failure due to known fio dfuse issue - DAOS-7778

2021-06-09 13:37 UTC, merged

2021-06-10 06:19 UTC, johannlombardi commented
@sylviachanoiyee @mjean308 please note that the commit message of this PR is not compliant to our standard.