CART-89 refactor: Refactor code for multi-provider support
daos-stack/daos pull request #5785
Opened 2021-05-25 00:16 UTC by frostedcmos

- Refactor code for multiprovider support
- Internal structures split between global shared data and per-provider
  data.
- Provider identifier moved from crt_context_t to hg_context_t
- For now default provider is used in few places, where provider
  cannot be easily derived
- Additional helper functions added to return and set per-provider
  data.

Signed-off-by: Alexander Oganezov <alexander.a.oganezov@intel.com>

2021-05-25 00:18 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5785/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-05-25 00:18 UTC, daosbuild1 commented on src/cart/crt_ctl.c
> +	d_list_t 			*ctx_list;
(style)  please, no space before tabs

2021-05-25 00:18 UTC, daosbuild1 commented on src/cart/crt_hg.c
> +	struct crt_prov_gdata 	*prov_data;
(style)  please, no space before tabs

2021-05-25 00:18 UTC, daosbuild1 commented on src/cart/crt_init.c
> +					d_getenv_bool("CRT_CTX_SHARE_ADDR", &share_addr);
(style)  line over 80 characters

2021-05-25 00:18 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5785/1/execution/node/117/log

2021-05-25 00:24 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-05-25 01:09 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5785/2/execution/node/699/log

2021-05-25 01:12 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5785/2/execution/node/713/log

2021-05-25 03:38 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5785/3/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-05-25 03:38 UTC, daosbuild1 commented on src/cart/crt_init.c
> +				crt_gdata.cg_init_prov = crt_na_dict[plugin_idx].nad_type;
(style)  line over 80 characters

2021-05-25 03:38 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5785/3/execution/node/117/log

2021-05-25 03:41 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5785/4/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-05-25 03:41 UTC, daosbuild1 commented on src/cart/crt_init.c
> +				crt_gdata.cg_init_prov =
(style)  trailing whitespace

2021-05-25 03:41 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5785/4/execution/node/90/log

2021-05-25 04:11 UTC, daosbuild1 commented
Test stage NLT completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5785/4/display/redirect

2021-05-25 04:12 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-05-25 14:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-05-25 20:42 UTC, jolivier23 requested changes
This is probably one that needs daily or full regression testing.

CART-89?   There is really no proper ticket for this?

2021-05-26 20:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-05-27 01:39 UTC, jolivier23 approved these changes

2021-05-27 17:17 UTC, jgmoore-or approved these changes

2021-05-27 19:57 UTC, merged