DAOS-7174 pool: coverity fixes
daos-stack/daos pull request #5817
Opened 2021-05-27 18:24 UTC by kccain

CID 331793 - unchecked return of uuid_parse()
CID 331792 - unchecked return of cmd_push_arg()

Signed-off-by: Kenneth Cain <kenneth.c.cain@intel.com>

2021-05-27 18:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-02 13:58 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-02 18:00 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-03 15:23 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-04 01:46 UTC, liw requested changes

2021-06-04 01:46 UTC, liw commented on src/engine/drpc_client.c
> +		D_GOTO(out_resp, rc = -DER_INVAL);
Generally, if a function like ds_pool_find_bylabel returns an error, its caller is not expected to look at pool_uuid and *svc_ranks. So we should free ranks before returning the -DER_INVAL. E.g., something like

    rc = uuid_parse(...);
    if (rc != 0) {
        ...
        D_FREE(*svc_ranks);
        D_GOTO(...);
    }

Additionally, is -DER_INVAL really appropriate? The caller hasn't specified any invalid argument in this case; it's the control plane supplying an invalid response...

2021-06-04 01:49 UTC, liw commented on src/engine/drpc_client.c
> +		D_GOTO(out_resp, rc = -DER_INVAL);
Or better only assign ranks to *svc_ranks after frsp->uuid has been successfully parsed.

2021-06-04 02:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-04 02:26 UTC, liw approved these changes
Thanks.

2021-06-08 18:54 UTC, mjmac commented on src/engine/drpc_client.c
> +		D_GOTO(out_resp, rc = -DER_IO);
minor nit: Is -DER_IO the right error here? Seems like maybe -DER_INVAL might be better?

2021-06-08 18:55 UTC, mjmac approved these changes
Generally LGTM, nothing to block on. Wondering about the error choice.

2021-06-08 18:55 UTC, mjmac commented on src/engine/drpc_client.c
> +		D_GOTO(out_resp, rc = -DER_IO);
Oh, hah. I see the @liw requested a change from -DER_INVAL.

2021-06-08 18:56 UTC, merged