Daos 6418 test
daos-stack/daos pull request #5855
Opened 2021-06-02 16:07 UTC by dinghwah

DAOS-6418-test: create and verify feature tags & pragmas
#       modified:   ../container/snapshot_aggregation.py
#       modified:   fio_small.py
#       modified:   io_aggregation.py
#       modified:   parallel_io.py
Signed-off-by: Ding Ho <ding-hwa.ho@intel.com>

2021-06-02 16:09 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-02 18:05 UTC, shimizukko approved these changes

2021-06-03 14:01 UTC, phender requested changes

2021-06-03 15:18 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-03 17:07 UTC, daosbuild1 commented
Test stage Functional on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5855/2/execution/node/1100/log

2021-06-08 16:07 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-08 18:08 UTC, daosbuild1 commented
Test stage Functional on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5855/3/execution/node/1120/log

2021-06-08 18:35 UTC, shimizukko approved these changes

2021-06-08 18:56 UTC, phender approved these changes

2021-06-08 19:53 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-09 02:17 UTC, daosbuild1 commented
Test stage Functional on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5855/4/execution/node/1140/log

2021-06-09 13:09 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-10 15:51 UTC, dinghwah commented
there are 2 errors from the pr-head are due to DAOS-7852, which are irrelated to this commit.

2021-06-10 19:03 UTC, merged