DAOS-623 build: Enable exclusion of psm3 build
daos-stack/daos pull request #5878
Opened 2021-06-04 05:30 UTC by rogue-developer

By default, libfabric tries to build psm2 and psm3 providers. Turns out these
builds fails on Fedora. Since disable of psm2 provider is already recommended
for Fedora. This patch adds the required code to disable psm3 provider as well.
In other words, this patch adds psm3 to EXCLUDE= option.

We can now build DAOS on Fedora by using this command:

$ scons --build-deps=yes --config=force BUILD_TYPE=release \
 EXCLUDE=psm2,psm3 install

          ¯\_(ツ)_/¯

Signed-off-by: Galen Erso <rogue.developer@outlook.com>

2021-06-04 09:53 UTC, tanabarr commented on site_scons/components/__init__.py
> +                          exclude(reqs, 'psm3',
nit: unnecessary line break?

2021-06-04 13:20 UTC, rogue-developer commented on site_scons/components/__init__.py
> +                          exclude(reqs, 'psm3',
Done

2021-06-04 16:40 UTC, frostedcmos reviewed
as mentioned on the community slack channel, this change also requires correspondning changes to ofi rpm package builds.

on the same note, once we update to the latest OFI we will be utilizing new feature recently added to it, that would disable every provider by default other than the ones we explicitly enable

2021-06-04 16:47 UTC, ashleypittman requested changes
We should do this more simply by just always passing the --disable-psm3 flag.

2021-06-09 09:44 UTC, ashleypittman commented
I've got a simpler version of this already included in https://github.com/daos-stack/daos/pull/5909 which is pending review.

2021-06-09 22:32 UTC, rogue-developer commented
> I've got a simpler version of this already included in #5909 which is pending review.

Since psm2 is going to be removed in #5909 I think that you should explicitly disable psm2 by adding `--disable-psm2` flag. Just like the other providers already disabled.

2021-06-11 04:39 UTC, rogue-developer commented
I created #5927 that address this functionality

2021-06-11 04:39 UTC, closed without merging