DAOS-7732 dfuse: Provide a fuse logging callback.
daos-stack/daos pull request #5888
Opened 2021-06-07 08:40 UTC by ashleypittman

When available provide a fuse logging callback to capture
fuse logging in the daos log.

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

2021-06-07 08:42 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5888/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-06-07 08:42 UTC, daosbuild1 commented on src/client/dfuse/dfuse_core.c
> +}
(style)  void function return statements are not generally useful

2021-06-07 08:42 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/1/execution/node/100/log

2021-06-07 08:46 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-07 08:52 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/2/execution/node/355/log

2021-06-07 08:52 UTC, daosbuild1 commented
Test stage Build on CentOS 7 debug completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/2/execution/node/434/log

2021-06-07 08:53 UTC, daosbuild1 commented
Test stage Build on CentOS 7 release completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/2/execution/node/409/log

2021-06-07 08:54 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/2/execution/node/378/log

2021-06-07 08:54 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/2/execution/node/379/log

2021-06-07 08:57 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/2/execution/node/335/log

2021-06-07 08:58 UTC, daosbuild1 commented
Test stage Build on Leap 15 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/2/execution/node/433/log

2021-06-07 09:10 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/2/execution/node/411/log

2021-06-07 11:56 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-14 20:52 UTC, jolivier23 requested changes

2021-06-14 20:52 UTC, jolivier23 commented on src/client/dfuse/SConscript
> +        cenv.AppendUnique(CPPDEFINES=['-DHAVE_FUSE_LOG=1'])
Didn't realize you could do this without defining the 0 case but my local test doesn't issue a warning.   Maybe there was some compiler in my past that complained about an undefined macro....or maybe I'm just dreaming.

2021-06-14 20:52 UTC, jolivier23 commented on src/client/dfuse/dfuse_core.c
> +		d_level = DLOG_DBG;
I think you just want DB_IO here.   DLOG_DBG is a bit mask that covers all debug bits so this is equivalent to something like

0xff | 0x1 where DLOG_DBG is 0xff and DB_IO is 0x1 (not actual values).

2021-06-14 20:52 UTC, jolivier23 commented on src/client/dfuse/dfuse_core.c
> +	mask = d_log_check(d_level | DB_IO | DD_FAC(fuse));
maybe it doesn't matter much but you lose some efficiency of macros here.  The D_ macro creates a single variable that it checks (and caches the result) so you essentially bypass subsequent calls to d_log_check.

I think maybe what you want here is something like this:

int *flag = &DD_FLAG(DLOG_EMIT, D_LOGFAC);

with the switch also grabbing the right variable.

Then it's a matter of mimicking _D_DEBUG macro...so something like

if (__builtin_expect(*flag, 0)) {
     if (*flag == DLOG_UNINIT) {
          _D_LOG_CHECK(*flag, *flag | D_LOGFAC, ##__VA_ARGS__);
          break;
     }
_D_LOG_NOCHECK(*flag, ##__VA_ARGS__);

So maybe we need another macro here that takes a variable as an argument...and modify the existing calls to _D_DEBUG to call it with DD_FLAG result as an argument

2021-09-16 08:20 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-01-14 09:44 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-01-14 11:21 UTC, daosbuild1 commented
Test stage Functional on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5888/5/display/redirect

2022-06-16 20:31 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5888/6/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-07-15 17:00 UTC, jolivier23 requested changes

2022-07-15 17:00 UTC, jolivier23 commented on src/client/dfuse/dfuse_core.c
> +		d_level = DLOG_DBG;
Put DB_IO here and remove the DB_IO below.

DLOG_DBG is 0x00ffff00 so it sets all debug streams (controlled by DD_MASK)

DLOG_IO is only one of those bits which allows one to turn it off even if capturing other debug.

2022-10-11 09:44 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5888/7/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-10-11 09:44 UTC, daosbuild1 commented on src/include/daos/debug.h
> +#define DAOS_FOREACH_LOG_FAC(ACTION, arg)                                                          \
(style)  Macros with complex values should be enclosed in parentheses

2022-10-11 09:44 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/7/execution/node/145/log

2022-10-11 09:45 UTC, daosbuild1 commented
Test stage Build on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/7/execution/node/372/log

2022-10-11 09:48 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/7/execution/node/342/log

2022-10-11 09:50 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/7/execution/node/330/log

2022-10-11 09:53 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/7/execution/node/325/log

2022-11-10 16:23 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5888/8/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-11-10 16:23 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/8/execution/node/145/log

2022-11-10 16:25 UTC, daosbuild1 commented
Test stage Build on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/8/execution/node/357/log

2022-11-10 16:33 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/8/execution/node/317/log

2022-11-10 16:35 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5888/9/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-11-10 16:35 UTC, daosbuild1 commented on src/include/daos/debug.h
> +#define DAOS_FOREACH_LOG_FAC(ACTION, arg)                                                          \
(style)  Macros with complex values should be enclosed in parentheses

2022-11-10 16:35 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/9/execution/node/146/log

2022-11-12 03:44 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/9/execution/node/1002/log

2022-11-23 13:58 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5888/10/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-11-23 13:58 UTC, daosbuild1 commented on src/include/daos/debug.h
> +#define DAOS_FOREACH_LOG_FAC(ACTION, arg)                                                          \
(style)  Macros with complex values should be enclosed in parentheses

2022-11-23 13:58 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/10/execution/node/145/log

2022-11-24 00:13 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5888/10/execution/node/1083/log

2023-06-30 13:52 UTC, ashleypittman commented
It is a draft.

2023-10-10 07:47 UTC, closed without merging