DAOS-7875 control: Set nr_hugepages for auto generate config file
daos-stack/daos pull request #5977
Opened 2021-06-16 19:24 UTC by sydneyvanda

Provide a reasonable nr_hugepages to the config for the auto generate
function. This will take into consideration the system hugepage size,
the max number of targets configured over all the engines, and the
minimum 1GB DMA buffer upper limit necessary for average I/O workload.

Signed-off-by: Sydney Vanda <sydney.m.vanda@intel.com>

2021-06-16 19:27 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-16 20:09 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5977/1/execution/node/727/log

2021-06-16 22:05 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-17 15:34 UTC, tanabarr approved these changes
looks good, 2 requests:
- add some unit tests
- use the existing helper functions for getting huge page info

2021-06-17 15:34 UTC, tanabarr commented on src/control/lib/control/auto.go
> +func getHugePageSize() (int, error) {
please use the helper in src/control/server/hugepages.go and move it out into the common package, just to reduce duplication, thanks

2021-06-17 15:35 UTC, tanabarr requested changes
requesting changes...

2021-06-17 18:14 UTC, shimizukko approved these changes

2021-06-17 21:35 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-17 22:17 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5977/3/execution/node/738/log

2021-06-18 20:09 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-18 20:52 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5977/4/execution/node/765/log

2021-06-18 21:39 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-19 13:00 UTC, shimizukko approved these changes

2021-06-21 08:58 UTC, tanabarr approved these changes

2021-06-21 19:37 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-22 20:43 UTC, merged