DAOS-6711 doc: ras event structure and ids
daos-stack/daos pull request #5992
Opened 2021-06-17 20:05 UTC by tanabarr

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

2021-06-17 20:07 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5992/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-06-17 20:07 UTC, daosbuild1 commented on src/control/events/README.md
> +Events raised in the control plane or received over dRPC
(style)  trailing whitespace

2021-06-17 20:07 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-5992/1/execution/node/87/log

2021-06-17 20:40 UTC, cdurf1 requested changes
Approved, pending the 'message' spelling in RAS Events table

2021-06-17 21:50 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-17 22:12 UTC, cdurf1 approved these changes

2021-06-18 11:44 UTC, johannlombardi approved these changes

2021-06-18 11:44 UTC, merged