DAOS-5363-test_io: Triage and investigate 16 functional tests failed on secure-mode
daos-stack/daos pull request #6016
Opened 2021-06-21 20:55 UTC by dinghwah

DAOS-5363-test_io: Triage and investigate 16 functional tests failed on secure-mode

     modified:   ../io/fio_small.yaml
     modified:   ../io/hdf5.yaml

Test-tag: fiosmall, hdf5
Signed-off-by: Ding Ho <ding-hwa.ho@intel.com>

2021-06-21 20:57 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-06-23 14:24 UTC, dinghwah commented on src/tests/ftest/io/fio_small.yaml
> -    allow_insecure: True
Test with secure mode was failed before.
So I keep the "transport_config: 
                         allow_insecure: False "
instead of delete it.

2021-06-23 14:52 UTC, shimizukko approved these changes

2021-07-06 19:35 UTC, phender requested changes
This PR did not run fio_small.py - it runs in HW Medium.  You're pragma should be `Test-tag: fiosmall hdf5` (w/o the comma).

2021-07-06 19:41 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-06 21:57 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-07 11:09 UTC, shimizukko approved these changes

2021-07-07 14:58 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6016/3/display/redirect

2021-07-07 15:31 UTC, dinghwah commented
4 failures from daos_vol.py test are not related to this commit.

2021-07-08 13:50 UTC, phender requested changes
All the HW Medium io/fio_small.py tests were skipped (https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6016/3/artifact/Functional%20Hardware%20Medium/io/fio_small.py/results.html).  They are skipped due to this `/scratch/CI-skip-list-master` entry:
```
[['DAOS-4419', 'test_method_name', 'test_fio_small']]
```
The best way to bypass this skip w/o affecting other tickets is to start your commit message with "DAOS-4419".

2022-02-14 16:30 UTC, closed without merging