DAOS-7317 Test: Adding IOR Hard test for EC Object types.
daos-stack/daos pull request #6131
Opened 2021-07-07 21:00 UTC by ravalsam

Quick-build: true
Test-tag: ior_hard

Signed-off-by: Samir Raval <samir.raval@intel.com>

2021-07-09 23:03 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6131/6/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-09 23:03 UTC, daosbuild1 commented on src/tests/ftest/util/ior_utils.py
> +        #   -O=0            stoneWallingWearOutIterations -- stop after
(style)  DOS line endings

2021-07-09 23:03 UTC, daosbuild1 commented on src/tests/ftest/ior/ior_hard.py
> +class IorHard(IorTestBase):
(pylint-too-many-ancestors) Too many ancestors (9/7)

2021-07-09 23:03 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6131/6/execution/node/100/log

2021-07-09 23:10 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-12 18:21 UTC, mchaarawi reviewed
unless im looking at the wrong place, i don't see the results for this test.
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6131/8/artifact/Functional%20Hardware%20Large/

2021-07-12 18:42 UTC, ravalsam commented
> unless im looking at the wrong place, i don't see the results for this test.
> https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6131/8/artifact/Functional%20Hardware%20Large/

Sorry forgot to paste the result link. The test initially ran with ior_hard tag and later it was running with default Ci tags(Which does not has IOR Hard to be run as part of Ci).
Previous run result can be found from https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6131/5/artifact/Functional%20Hardware%20Large/ior/ior_hard.py/

2021-07-12 18:46 UTC, saurabhtandan commented on src/tests/ftest/ior/ior_hard.yaml
> +      scm_class: dcpm
We don't want to use nvme for this test?

2021-07-12 18:51 UTC, saurabhtandan approved these changes
LGTM

2021-07-12 19:04 UTC, mchaarawi requested changes
for the read phase you are NOT supposed to pass these:
-D 300
-O stoneWallingWearOut=1

should also set
 --dfs.chunk_size=470080
not 1m to match what we actually do for io-500; unless there is a reason you are setting it to 1m.

2021-07-12 19:22 UTC, ravalsam commented
> for the read phase you are NOT supposed to pass these:
> -D 300
> -O stoneWallingWearOut=1

I really thought it's the same. Let me remove it.

> should also set
> --dfs.chunk_size=470080
> not 1m to match what we actually do for io-500; unless there is a reason you are setting it to 1m.

Not really let me change and rerun it again

2021-07-12 20:49 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-12 21:32 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6131/9/display/redirect

2021-07-12 21:34 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6131/9/display/redirect

2021-07-12 21:52 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6131/10/execution/node/249/log

2021-07-12 21:57 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6131/10/execution/node/252/log

2021-07-12 21:57 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6131/10/execution/node/246/log

2021-07-12 21:59 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6131/10/execution/node/243/log

2021-07-13 04:57 UTC, ravalsam commented
> > for the read phase you are NOT supposed to pass these:
> > -D 300
> > -O stoneWallingWearOut=1
> 
> I really thought it's the same. Let me remove it.
> 
> > should also set
> > --dfs.chunk_size=470080
> > not 1m to match what we actually do for io-500; unless there is a reason you are setting it to 1m.
> 
> Not really let me change and rerun it again

Updated the code and CI result can be found from https://build.hpdd.intel.com/job/daos-stack/job/daos/view/change-requests/job/PR-6131/11/artifact/Functional%20Hardware%20Large/ior/ior_hard.py/

2021-07-13 04:57 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-13 18:09 UTC, mchaarawi approved these changes

2021-07-13 18:25 UTC, saurabhtandan approved these changes
LGTM

2021-07-13 19:32 UTC, merged