DAOS-7966 abt: Add debugging options for Arbobots.
daos-stack/daos pull request #6153
Opened 2021-07-09 11:04 UTC by ashleypittman

If TARGET_TYPE is debug then turn on argobots debugging.
Fix use of ABT_self_get_type() to avoid hitting asserts
in debuging versions.

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

2021-07-09 11:06 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-09 15:54 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-12 21:12 UTC, jolivier23 requested changes
Looks like there is a conflict.  Otherwise, looks fine.

2021-07-12 21:15 UTC, bfaccini approved these changes

2021-07-12 21:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-12 21:29 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6153/3/execution/node/311/log

2021-07-12 21:33 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6153/3/execution/node/371/log

2021-07-12 21:34 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6153/3/execution/node/343/log

2021-07-12 21:37 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6153/3/execution/node/366/log

2021-07-12 21:54 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6153/3/display/redirect

2021-07-12 21:57 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6153/3/display/redirect

2021-07-13 07:16 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-13 22:09 UTC, jolivier23 approved these changes

2021-07-14 20:19 UTC, sylviachanoiyee approved these changes

2021-07-14 20:19 UTC, merged