DAOS-8072 obj: more debug info when fill record during enumerate
daos-stack/daos pull request #6213
Opened 2021-07-17 16:18 UTC by Nasf-Fan

Check more information when fill_rec() hits buffer overflow.

Signed-off-by: Fan Yong <fan.yong@intel.com>

2021-07-17 16:20 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-18 10:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-19 15:36 UTC, jolivier23 approved these changes

2021-07-20 07:19 UTC, liuxuezhao approved these changes

2021-07-20 18:38 UTC, jolivier23 requested changes
Has a merge conflict now

2021-07-21 01:17 UTC, Nasf-Fan commented
Related fixed has been done via the patch https://github.com/daos-stack/daos/pull/6157 by side-effect.

2021-07-21 01:17 UTC, closed without merging