DAOS-8055 utils: Separate daos_perf and vos_perf
daos-stack/daos pull request #6223
Opened 2021-07-19 14:27 UTC by NiuYawei

To get rid of server module dependency from daos_perf, the original
daos_perf is split into two binaries:

- daos_perf : for original 'daos' and 'echo' modes only.
- vos_perf  : for original 'vos' mode.

dts lib is also modified to get rid of dependency on vos, and
daos_racer is now independent of vos as well.

Signed-off-by: Niu Yawei <yawei.niu@intel.com>

2021-07-19 14:30 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-19 14:30 UTC, daosbuild1 commented on src/tests/daos_perf.c
> +	printf("daos_perf -- performance benchmark tool for DAOS\n\n\
(style)  Avoid line continuations in quoted strings

2021-07-19 14:30 UTC, daosbuild1 commented on src/tests/daos_perf.c
> +			     sizeof(perf_daos_opts)/sizeof(perf_daos_opts[0]),
(style)  Prefer ARRAY_SIZE(perf_daos_opts)

2021-07-19 14:30 UTC, daosbuild1 commented on src/tests/perf_common.c
> +daos_size_t	ts_nvme_size = 0;		/* default pool NVMe size */
(style)  do not initialise globals to 0

2021-07-19 14:30 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-07-19 14:30 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +	printf("vos_perf -- performance benchmark tool for VOS\n\n\
(style)  Avoid line continuations in quoted strings

2021-07-19 14:30 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-19 14:30 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +			     sizeof(perf_vos_opts)/sizeof(perf_vos_opts[0]),
(style)  Prefer ARRAY_SIZE(perf_vos_opts)

2021-07-19 14:30 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/1/execution/node/100/log

2021-07-19 14:36 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/1/execution/node/358/log

2021-07-19 14:38 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/1/execution/node/313/log

2021-07-19 14:38 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/1/execution/node/316/log

2021-07-19 14:41 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/1/execution/node/361/log

2021-07-19 15:12 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/1/execution/node/795/log

2021-07-19 15:16 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/1/execution/node/792/log

2021-07-20 03:22 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-20 03:22 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-20 03:22 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-07-20 03:22 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-20 03:22 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/2/execution/node/91/log

2021-07-20 03:29 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/2/execution/node/358/log

2021-07-20 03:30 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/2/execution/node/334/log

2021-07-20 03:31 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/2/execution/node/333/log

2021-07-20 03:33 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/2/execution/node/376/log

2021-07-20 14:18 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/3/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-20 14:18 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-20 14:18 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-07-20 14:18 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-20 14:18 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/3/execution/node/100/log

2021-07-20 14:24 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/3/execution/node/358/log

2021-07-20 14:26 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/3/execution/node/330/log

2021-07-20 14:26 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/3/execution/node/331/log

2021-07-20 14:29 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/3/execution/node/361/log

2021-07-21 03:20 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/4/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-21 03:20 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-21 03:20 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-07-21 03:20 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-21 03:20 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/4/execution/node/87/log

2021-07-21 03:27 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/4/execution/node/357/log

2021-07-21 03:28 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/4/execution/node/316/log

2021-07-21 03:29 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/4/execution/node/320/log

2021-07-21 03:32 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/4/execution/node/379/log

2021-07-21 04:07 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/4/execution/node/756/log

2021-07-21 04:11 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/4/execution/node/759/log

2021-07-21 09:04 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/5/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-21 09:04 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-21 09:04 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-07-21 09:04 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-21 09:04 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/5/execution/node/100/log

2021-07-21 09:11 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/5/execution/node/361/log

2021-07-21 09:12 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/5/execution/node/355/log

2021-07-21 09:12 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/5/execution/node/339/log

2021-07-21 09:15 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/5/execution/node/358/log

2021-07-21 09:47 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/5/execution/node/781/log

2021-07-21 09:51 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/5/execution/node/795/log

2021-07-22 07:17 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/6/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-22 07:17 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-22 07:17 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-07-22 07:17 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-22 07:17 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/6/execution/node/100/log

2021-07-22 07:23 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/6/execution/node/355/log

2021-07-22 07:24 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/6/execution/node/318/log

2021-07-22 07:25 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/6/execution/node/358/log

2021-07-22 07:28 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/6/execution/node/361/log

2021-07-23 04:22 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/7/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-23 04:22 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-23 04:22 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-07-23 04:22 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-23 04:22 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/7/execution/node/100/log

2021-07-23 04:29 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/7/execution/node/358/log

2021-07-23 04:30 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/7/execution/node/321/log

2021-07-23 04:31 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/7/execution/node/325/log

2021-07-23 04:34 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/7/execution/node/388/log

2021-07-23 07:57 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/8/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-23 07:57 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-23 07:57 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-07-23 07:57 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-23 07:57 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/8/execution/node/103/log

2021-07-23 08:03 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/8/execution/node/385/log

2021-07-23 08:04 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/8/execution/node/342/log

2021-07-23 08:05 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/8/execution/node/341/log

2021-07-23 08:08 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/8/execution/node/388/log

2021-07-23 10:14 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/9/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-23 10:14 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-23 10:14 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-07-23 10:14 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-23 10:14 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/9/execution/node/99/log

2021-07-23 10:21 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/9/execution/node/369/log

2021-07-23 10:22 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/9/execution/node/325/log

2021-07-23 10:23 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/9/execution/node/326/log

2021-07-23 10:25 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/9/execution/node/372/log

2021-07-26 03:01 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/10/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-26 03:01 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-26 03:01 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-07-26 03:01 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-26 03:01 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/10/execution/node/119/log

2021-07-26 03:09 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/10/execution/node/311/log

2021-07-26 03:10 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/10/execution/node/315/log

2021-07-26 03:10 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/10/execution/node/342/log

2021-07-26 03:11 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/10/execution/node/388/log

2021-07-26 03:52 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/10/execution/node/809/log

2021-07-26 03:55 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/10/execution/node/806/log

2021-07-26 04:28 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/11/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-26 04:28 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-26 04:28 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-07-26 04:28 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-26 04:28 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/11/execution/node/100/log

2021-07-26 04:35 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/11/execution/node/325/log

2021-07-26 04:36 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/11/execution/node/362/log

2021-07-26 04:36 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/11/execution/node/324/log

2021-07-26 04:38 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/11/execution/node/367/log

2021-07-26 05:11 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/11/execution/node/759/log

2021-07-26 05:14 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/11/execution/node/745/log

2021-07-26 07:56 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/12/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-26 07:56 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-26 07:56 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-07-26 07:56 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-26 07:56 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/12/execution/node/100/log

2021-07-26 08:03 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/12/execution/node/388/log

2021-07-26 08:04 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/12/execution/node/337/log

2021-07-26 08:05 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/12/execution/node/338/log

2021-07-26 08:07 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/12/execution/node/385/log

2021-07-26 14:25 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/13/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-26 14:25 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-26 14:25 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/13/execution/node/100/log

2021-07-26 14:32 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/13/execution/node/358/log

2021-07-26 14:33 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/13/execution/node/342/log

2021-07-26 14:34 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/13/execution/node/333/log

2021-07-26 14:37 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/13/execution/node/376/log

2021-07-27 02:08 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/14/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-27 02:08 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-27 02:08 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-07-27 02:08 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-07-27 02:08 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/14/execution/node/98/log

2021-07-27 02:08 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/14/execution/node/318/log

2021-07-27 02:15 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/14/execution/node/319/log

2021-07-27 02:16 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/14/execution/node/358/log

2021-07-27 02:17 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/14/execution/node/372/log

2021-07-27 02:50 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/14/execution/node/795/log

2021-07-27 02:53 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/14/execution/node/792/log

2021-08-02 10:15 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/15/execution/node/87/log

2021-08-03 03:10 UTC, NiuYawei commented
CentOS 8 build failed for "fatal: unable to access 'http://github.com/willemt/CLinkedListQueue/': Failed to connect to github.com port 80: Connection timed out"

2021-08-04 03:11 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/16/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-08-04 03:11 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-08-04 03:11 UTC, daosbuild1 commented on src/tests/perf_common.c
> +typedef char	key_str_t[DTS_KEY_LEN];
(style)  do not add new typedefs

2021-08-04 03:11 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-08-04 03:11 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +
(style)  trailing whitespace

2021-08-04 03:11 UTC, daosbuild1 commented on src/tests/vos_perf.c
> + 			break;
(style)  code indent should use tabs where possible
(style)  please, no space before tabs

2021-08-04 03:11 UTC, daosbuild1 commented on src/tests/vos_perf.c
> + 			break;
(style)  code indent should use tabs where possible
(style)  please, no space before tabs

2021-08-04 03:11 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-08-04 03:11 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/16/execution/node/100/log

2021-08-04 03:26 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/17/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-08-04 03:26 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-08-04 03:26 UTC, daosbuild1 commented on src/tests/perf_common.c
> +typedef char	key_str_t[DTS_KEY_LEN];
(style)  do not add new typedefs

2021-08-04 03:26 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-08-04 03:26 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +
(style)  trailing whitespace

2021-08-04 03:26 UTC, daosbuild1 commented on src/tests/vos_perf.c
> + 			break;
(style)  code indent should use tabs where possible
(style)  please, no space before tabs

2021-08-04 03:26 UTC, daosbuild1 commented on src/tests/vos_perf.c
> + 			break;
(style)  code indent should use tabs where possible
(style)  please, no space before tabs

2021-08-04 03:26 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-08-04 03:26 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/17/execution/node/101/log

2021-08-05 06:31 UTC, wangdi1 submitted a review, later dismissed

2021-08-05 09:40 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/18/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-08-05 09:40 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-08-05 09:40 UTC, daosbuild1 commented on src/tests/perf_common.c
> +typedef char	key_str_t[DTS_KEY_LEN];
(style)  do not add new typedefs

2021-08-05 09:40 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-08-05 09:40 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +
(style)  trailing whitespace

2021-08-05 09:40 UTC, daosbuild1 commented on src/tests/vos_perf.c
> + 			break;
(style)  code indent should use tabs where possible
(style)  please, no space before tabs

2021-08-05 09:40 UTC, daosbuild1 commented on src/tests/vos_perf.c
> + 			break;
(style)  code indent should use tabs where possible
(style)  please, no space before tabs

2021-08-05 09:40 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-08-05 09:40 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/18/execution/node/100/log

2021-08-06 02:35 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/19/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-08-06 02:35 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-08-06 02:35 UTC, daosbuild1 commented on src/tests/perf_common.c
> +typedef char	key_str_t[DTS_KEY_LEN];
(style)  do not add new typedefs

2021-08-06 02:35 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-08-06 02:35 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +
(style)  trailing whitespace

2021-08-06 02:35 UTC, daosbuild1 commented on src/tests/vos_perf.c
> + 			break;
(style)  code indent should use tabs where possible
(style)  please, no space before tabs

2021-08-06 02:35 UTC, daosbuild1 commented on src/tests/vos_perf.c
> + 			break;
(style)  code indent should use tabs where possible
(style)  please, no space before tabs

2021-08-06 02:35 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-08-06 02:35 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/19/execution/node/91/log

2021-08-06 13:19 UTC, jolivier23 approved these changes
You've lost a race again on spec.   But otherwise, looks good to me

2021-08-06 13:19 UTC, jolivier23 commented on debian/changelog
> +daos (1.3.104-3) unstable; urgency=medium
I think it's fine to have a different release number for debian

2021-08-09 02:31 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/20/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-08-09 02:31 UTC, daosbuild1 commented on src/tests/obj_ctl.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-08-09 02:31 UTC, daosbuild1 commented on src/tests/perf_common.c
> +typedef char	key_str_t[DTS_KEY_LEN];
(style)  do not add new typedefs

2021-08-09 02:31 UTC, daosbuild1 commented on src/tests/perf_common.c
> +"	Pool SCM partition size, which can have M(megatbytes) or \n"
(style)  unnecessary whitespace before a quoted newline

2021-08-09 02:31 UTC, daosbuild1 commented on src/tests/vos_perf.c
> +extern struct io_engine vos_engine;
(style)  externs should be avoided in .c files

2021-08-09 02:31 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/20/execution/node/119/log

2021-08-09 16:52 UTC, jolivier23 approved these changes

2021-08-10 01:35 UTC, wangdi1 submitted a review, later dismissed

2021-08-10 20:26 UTC, jolivier23 requested changes
I just tried this locally and noticed that readelf -d daos_perf shows a dependence on libdaos_common_pmem.so.   I uploaded #6427 which creates a separate client/server list so vos_perf depends on libdaos_common_pmem.so but  daos_perf only depends on libdaos_common.so

2021-08-18 15:32 UTC, jolivier23 approved these changes

2021-08-18 15:32 UTC, jolivier23 commented
I took the liberty of merging those changes to move this along while you're out.

2021-08-18 15:41 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/21/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-08-18 15:41 UTC, daosbuild1 commented on src/tests/perf_common.c
> +typedef char	key_str_t[DTS_KEY_LEN];
(style)  do not add new typedefs

2021-08-18 15:41 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/21/execution/node/100/log

2021-08-18 20:40 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/21/display/redirect

2021-08-18 20:41 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/21/display/redirect

2021-08-20 03:26 UTC, jolivier23 commented
Johann did some documentation updates for daos_perf -t VOS so that will need to be updated

2021-08-23 01:59 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6223/22/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-08-23 01:59 UTC, daosbuild1 commented on src/tests/perf_common.c
> +typedef char	key_str_t[DTS_KEY_LEN];
(style)  do not add new typedefs

2021-08-23 01:59 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6223/22/execution/node/100/log

2021-08-24 15:01 UTC, NiuYawei commented
ping reviewers, could you review this?

2021-08-24 20:48 UTC, jolivier23 approved these changes

2021-08-24 21:01 UTC, wangdi1 approved these changes

2021-08-24 22:48 UTC, merged