DAOS-7174 cont: take uuid as output param in cont_create
daos-stack/daos pull request #6242
Opened 2021-07-20 21:39 UTC by johannlombardi

Change daos_cont_create() to take a uuid as output parameter.
The UUID cannot be provided by the user any longer and will
be returned to the caller.

Backward API compatibility is supported via a macro that use
the old behavior when a uuid_t is passed instead of a uuid_t *.

Backward ABI compatibility is supported by keeping around
the daos_cont_create symbols, but not advertising them via
the header files (the macro overrides it).

Rename daos_cont_create_by_label() to daos_cont_create_with_label()
to align with new function naming.

Signed-off-by: Johann Lombardi <johann.lombardi@intel.com>

2021-07-20 21:41 UTC, johannlombardi commented
Alternative simpler proposal. Just a quick sketch patch that likely does not compile yet just to share the idea. Anyway, i am really off now and leave it to you guys :)

2021-07-20 21:42 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6242/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-20 21:42 UTC, daosbuild1 commented on src/include/daos_cont.h
> +		if (__builtin_types_compatible_p(typeof(co),		\
(style)  that open brace { should be on the previous line

2021-07-20 21:42 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6242/1/execution/node/119/log

2021-07-20 21:44 UTC, daosbuild1 commented
Test stage Build on CentOS 7 debug completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6242/1/execution/node/410/log

2021-07-20 21:44 UTC, daosbuild1 commented
Test stage Build on CentOS 7 release completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6242/1/execution/node/422/log

2021-07-20 21:44 UTC, daosbuild1 commented
Test stage Build on Leap 15 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6242/1/execution/node/434/log

2021-07-20 21:45 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6242/1/execution/node/315/log

2021-07-20 21:47 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6242/1/execution/node/310/log

2021-07-20 21:48 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6242/1/execution/node/376/log

2021-07-20 21:50 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6242/1/execution/node/379/log

2021-07-20 22:00 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6242/1/execution/node/411/log

2021-07-22 22:06 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6242/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-22 22:06 UTC, daosbuild1 commented on src/include/daos_cont.h
> +		if (__builtin_types_compatible_p(typeof(co),		\
(style)  that open brace { should be on the previous line

2021-07-22 22:06 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6242/2/execution/node/100/log

2021-07-22 22:11 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-23 00:28 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-23 20:46 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-23 23:21 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-26 15:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-26 15:36 UTC, daosbuild1 commented
Test stage Build on Leap 15 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6242/7/execution/node/407/log

2021-07-26 16:51 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6242/8/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-07-26 16:51 UTC, daosbuild1 commented on src/client/api/container.c
> +
(style)  trailing whitespace

2021-07-26 16:51 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6242/8/execution/node/100/log

2021-07-26 16:54 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-27 12:59 UTC, mchaarawi commented
OK i think this is in good shape now to do reviews. Johann started this, but i updated it so i shouldn't review this myself.

2021-07-27 14:34 UTC, jolivier23 requested changes

2021-07-27 14:34 UTC, jolivier23 commented on src/include/daos_cont.h
> +{
Please add a case for daos_cont_create to src/client/api/compile_check.c just to ensure it works for c++ now and into the future.

2021-07-27 16:04 UTC, kccain requested changes

2021-07-27 19:39 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-27 19:54 UTC, mchaarawi commented on src/client/dfs/dfs.c
> +	if (uuid_is_set)
good point

2021-07-27 19:54 UTC, mchaarawi commented on src/client/api/container.c
> +		D_ERROR("daos_cont_create UUID: label=%s failed, "
fixed

2021-07-27 19:54 UTC, mchaarawi commented on src/client/dfs/dfs.c
> + * daos_cont.h header file.
fixed

2021-07-28 17:59 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-07-29 01:37 UTC, kccain approved these changes

2021-07-30 14:09 UTC, jolivier23 approved these changes

2021-07-30 14:11 UTC, merged