DAOS-8123 test: Implemented positional parameter support and fixed qu…
daos-stack/daos pull request #6252
Opened 2021-07-21 19:19 UTC by shimizukko

…ery_attribute.py

Implemented positional parameter support for daos command.

Fixed and refactored query_attribute.py

Support JSON in daos command. Moved _get_json_result into command_utils.py so
we can maintain it in one place.

Skip-unit-tests: true
Test-tag: pr pool_query_attr
Signed-off-by: Makito Kano <makito.kano@intel.com>

2021-07-21 19:24 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6252/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:20](https://github.com/daos-stack/daos/blob/d28002fd02a1b5d292783cbee2f9b1bb74e1b4a4/src/tests/ftest/util/command_utils.py#L20):
(pylint-unused-import) Unused ObjectWithParameters imported from command_utils_base
(pylint-unused-import) Unused YamlParameters imported from command_utils_base

[src/tests/ftest/util/dmg_utils.py:370](https://github.com/daos-stack/daos/blob/d28002fd02a1b5d292783cbee2f9b1bb74e1b4a4/src/tests/ftest/util/dmg_utils.py#L370):
(pylint-too-many-arguments) Too many arguments (11/10)

2021-07-21 19:24 UTC, daosbuild1 commented on src/tests/ftest/pool/query_attribute.py
> +                "Actual = {}".format(expected_uuid, actual_uuid)
(pylint-too-many-format-args) Too many arguments for format string

2021-07-21 19:24 UTC, daosbuild1 commented on src/tests/ftest/pool/query_attribute.py
> +                "Actual = {}".format(expected_attrs, actual_attrs)
(pylint-too-many-format-args) Too many arguments for format string

2021-07-21 19:24 UTC, daosbuild1 commented on src/tests/ftest/pool/query_attribute.py
> +                    "Actual = {}".format(sample_vals[i], actual_val)
(pylint-too-many-format-args) Too many arguments for format string

2021-07-21 19:24 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils.py
> +                 with_json=False):
(pylint-unused-argument) Unused argument 'with_json'

2021-07-21 19:24 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils.py
> +        if self.json is None:
(pylint-no-member) Instance of 'CommandWithSubCommand' has no 'json' member

2021-07-21 19:24 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils.py
> +        prev_json_val = self.json.value
(pylint-no-member) Instance of 'CommandWithSubCommand' has no 'json' member

2021-07-21 19:24 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils.py
> +        self.json.update(True)
(pylint-no-member) Instance of 'CommandWithSubCommand' has no 'json' member

2021-07-21 19:24 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils.py
> +            self.json.update(prev_json_val)
(pylint-no-member) Instance of 'CommandWithSubCommand' has no 'json' member

2021-07-21 19:24 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils_base.py
> +class PositionalParameter(BasicParameter):
(pylint-missing-class-docstring) Missing class docstring

2021-07-21 19:24 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils_base.py
> +    def position(self):
(pylint-missing-function-docstring) Missing function or method docstring

2021-07-21 19:24 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils_base.py
> +class CommandWithPositionalParameters(CommandWithParameters):
(pylint-missing-class-docstring) Missing class docstring

2021-07-21 19:24 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6252/1/execution/node/119/log

2021-07-21 19:36 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6252/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:20](https://github.com/daos-stack/daos/blob/daeea263332f56dd74c07deae79ad2107efc6f79/src/tests/ftest/util/command_utils.py#L20):
(pylint-unused-import) Unused ObjectWithParameters imported from command_utils_base
(pylint-unused-import) Unused YamlParameters imported from command_utils_base

[src/tests/ftest/util/dmg_utils.py:370](https://github.com/daos-stack/daos/blob/daeea263332f56dd74c07deae79ad2107efc6f79/src/tests/ftest/util/dmg_utils.py#L370):
(pylint-too-many-arguments) Too many arguments (11/10)

2021-07-21 19:36 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils.py
> +                 with_json=False):
(pylint-unused-argument) Unused argument 'with_json'

2021-07-21 19:36 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils.py
> +        if self.json is None:
(pylint-no-member) Instance of 'CommandWithSubCommand' has no 'json' member

2021-07-21 19:36 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils.py
> +        prev_json_val = self.json.value
(pylint-no-member) Instance of 'CommandWithSubCommand' has no 'json' member

2021-07-21 19:36 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils.py
> +        self.json.update(True)
(pylint-no-member) Instance of 'CommandWithSubCommand' has no 'json' member

2021-07-21 19:36 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils.py
> +            self.json.update(prev_json_val)
(pylint-no-member) Instance of 'CommandWithSubCommand' has no 'json' member

2021-07-21 19:36 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils_base.py
> +    def position(self):
(pylint-missing-function-docstring) Missing function or method docstring

2021-07-21 19:36 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6252/2/execution/node/101/log

2021-07-21 19:43 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6252/3/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:20](https://github.com/daos-stack/daos/blob/bb16d7070e3710639ee8306399f8d0506cf51f93/src/tests/ftest/util/command_utils.py#L20):
(pylint-unused-import) Unused ObjectWithParameters imported from command_utils_base
(pylint-unused-import) Unused YamlParameters imported from command_utils_base

[src/tests/ftest/util/dmg_utils.py:370](https://github.com/daos-stack/daos/blob/bb16d7070e3710639ee8306399f8d0506cf51f93/src/tests/ftest/util/dmg_utils.py#L370):
(pylint-too-many-arguments) Too many arguments (11/10)

2021-07-21 19:43 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils.py
> +                 with_json=False):
(pylint-unused-argument) Unused argument 'with_json'

2021-07-21 19:43 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils.py
> +        if self.json is None:
(pylint-no-member) Instance of 'CommandWithSubCommand' has no 'json' member

2021-07-21 19:43 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils.py
> +        prev_json_val = self.json.value
(pylint-no-member) Instance of 'CommandWithSubCommand' has no 'json' member

2021-07-21 19:43 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils.py
> +        self.json.update(True)
(pylint-no-member) Instance of 'CommandWithSubCommand' has no 'json' member

2021-07-21 19:43 UTC, daosbuild1 commented on src/tests/ftest/util/command_utils.py
> +            self.json.update(prev_json_val)
(pylint-no-member) Instance of 'CommandWithSubCommand' has no 'json' member

2021-07-21 19:43 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6252/3/execution/node/120/log

2021-07-22 16:29 UTC, phender requested changes

2021-07-22 16:29 UTC, phender commented on src/tests/ftest/util/command_utils.py
> +    def __init__(self, namespace, command, path="", subprocess=False,
We don't need the `with_json=False` optional argument if the `DaosCommandBase` class is going to define `self.json = FormattedParameter("-j", False)`:
```suggestion
    def __init__(self, namespace, command, path="", subprocess=False):
```

There is some additional code needed at the end of the `__init__` method that will use this argument:
```
        self.json = None
```

2021-07-22 18:08 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/command_utils.py:20](https://github.com/daos-stack/daos/blob/f4376e0278e2e883e4c4b167e04cca67e8d057b7/src/tests/ftest/util/command_utils.py#L20):
(pylint-unused-import) Unused ObjectWithParameters imported from command_utils_base
(pylint-unused-import) Unused YamlParameters imported from command_utils_base

[src/tests/ftest/util/dmg_utils.py:370](https://github.com/daos-stack/daos/blob/f4376e0278e2e883e4c4b167e04cca67e8d057b7/src/tests/ftest/util/dmg_utils.py#L370):
(pylint-too-many-arguments) Too many arguments (11/10)

2021-07-22 19:12 UTC, phender approved these changes

2021-07-23 12:44 UTC, dinghwah approved these changes
LGTM.

2021-07-26 19:07 UTC, sylviachanoiyee commented
Unit tests are skipped but all changes under ftests.

2021-07-26 19:07 UTC, merged