Update dfuse_bash_cmd.py
daos-stack/daos pull request #6268
Opened 2021-07-23 15:20 UTC by kalfizah

Add echo/cat test for DAOS-7860. On Leap15 with pmem and verbs provider, if DAOS have Memory Registration Problem will not pass this test. Shouldn't be any problem for Centos and tmpfs.

2021-07-23 18:06 UTC, saurabhtandan commented on src/tests/ftest/io/dfuse_bash_cmd.py
> -        """Jira ID: DAOS-3508.
No need to change or add jira ticket. Jira ID simply reflects for the first time the test was added. Modifying it every time with the ticket for which change was made will eventually make it look too clumsy and idea of an ID will no longer suffice.

2021-07-23 18:15 UTC, saurabhtandan commented on src/tests/ftest/io/dfuse_bash_cmd.py
> +                            "echo 12345 > {0}/test; cat {0}/test".format(mount_dir)]
Minor: Will be nice to have one command each line to be consistant with the test structure. So something like this:
`"echo 12345 > {}/test".format(mount_dir),`
`"cat {}/test".format(mount_dir)]`

2021-07-23 18:22 UTC, saurabhtandan requested changes
Looking at your commit message it seems like you don't have the correct commit pragmas in order to run the test you made changes in. This test is a weekly test and won't run as part of your PR automatically. You will need to add a few pragmas to your last commit message before pushing. As you are just making changes to single test file, you can simply run only this test and saving time in CI by adding these two lines in your last commit message.

`Quick-Functional: true`
`Test-tag: bashcmd`

If you want more info on commit pragmas you can refer to this link: https://wiki.hpdd.intel.com/display/CI/Commit+Pragmas

2023-10-24 19:18 UTC, daltonbohning commented
Upstream ticket has been closed: https://daosio.atlassian.net/browse/DAOS-7860
Closing this stale PR

2023-10-24 19:18 UTC, closed without merging