DAOS-8173 test: Use positional parameter for daos container command a…
daos-stack/daos pull request #6337
Opened 2021-08-01 17:49 UTC by shimizukko

…nd fixed tests

Use CommandWithPositionalParameters in daos command.
Use PositionalParameter for self.pool since most of the daos container
subcommands have pool as positional parameter.
Reordered the parameters and the methods to match that of the help.

Renamed pool_list_cont to container_list and use JSON. Fixed the tests to
incorporate this change.

Skip-unit-test: true
Test-tag: pr dmg_pool_evict list_containers
Signed-off-by: Makito Kano <makito.kano@intel.com>

2021-08-01 17:51 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-01 17:54 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-01 17:57 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-01 18:48 UTC, daosbuild1 commented
Test stage Functional on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6337/3/display/redirect

2021-08-02 15:52 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-02 16:26 UTC, daosbuild1 commented
Test stage Scan CentOS 7 RPMs completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6337/5/display/redirect

2021-08-02 18:45 UTC, phender requested changes

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/container/list_containers.py
> +        actual_uuids = [uuid_label["UUID"] for uuid_label in data["response"]]
Until we start creating containers with labels should we be verifying the rest of the `daos container list` command, e.g. `data["Label"] == "container_label_not_set"`

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
> +        class CloneSubCommand(CommonContainerSubCommand):
```suggestion
        class CloneSubCommand(CommandWithParameters):
```

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
>                  self.path = FormattedParameter("--path={}")
```suggestion
                self.sys_name = FormattedParameter("--sys-name={}")
                self.path = FormattedParameter("--path={}")
                self.pool = PositionalParameter(1)
                self.cont = PositionalParameter(2)
```

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
> +                self.cont = PositionalParameter(2)
```suggestion
```

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
> +        class CreateSnapSubCommand(CommonContainerSubCommand):
```suggestion

                #    -c, --cont=<UUID>
                #            container UUID (optional)
                self.cont = FormattedParameter("--cont={}")

        class CreateSnapSubCommand(CommonContainerSubCommand):
```

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
> +                super().__init__("del-attrs")
```suggestion
                super().__init__("del-attr")
```

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
> +                self.attr = FormattedParameter("--attr={}")
```suggestion
                self.attr = PositionalParameter(3)
```

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
> +                self.cont = PositionalParameter(2)
```suggestion
```

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
> +                self.snap = FormattedParameter("--snap={}")
```suggestion
```

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
> +        class GetAttrSubCommand(CommonContainerSubCommand):
```suggestion
                #     -f, --force
                #             overwrite existing outfile
                self.force = FormattedParameter("--force", False)

        class GetAttrSubCommand(CommonContainerSubCommand):
```

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
> +                self.attr = FormattedParameter("--attr={}")
```suggestion
                self.attr = PositionalParameter(3)
```

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
> +                self.prop = FormattedParameter("--prop={}")
```suggestion
                self.prop = FormattedParameter("--properties={}")
```

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
> +                self.sys_name = FormattedParameter("--sys-name={}")
```suggestion
                self.sys_name = FormattedParameter("--sys-name={}")
                self.pool = PositionalParameter(1)
```

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
> +        class ListSubCommand(CommonContainerSubCommand):
```suggestion
        class ListSubCommand(CommandWithPositionalParameters):
```

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
> +        class ListObjectsSubCommand(CommonContainerSubCommand):
```suggestion
                self.verbose = FormattedParameter("--verbose", False)

        class ListObjectsSubCommand(CommonContainerSubCommand):
```

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
> +                super().__init__("list-objects")
```suggestion
                super().__init__("list-objects")
                self.epc = FormattedParameter("--epc={}")
```

2021-08-02 18:45 UTC, phender commented on src/tests/ftest/util/daos_utils_base.py
> +                self.value = FormattedParameter("--value={}")
```suggestion
                self.attr = PositionalParameter(3)
                self.value = PositionalParameter(4)
```

2021-08-02 19:59 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6337/6/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-08-02 19:59 UTC, daosbuild1 commented on src/tests/ftest/util/daos_utils_base.py
> +                super().__init__("clone")
(pylint-no-value-for-parameter) No value for argument 'command' in method call

2021-08-02 19:59 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6337/6/execution/node/99/log

2021-08-02 20:30 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-02 21:12 UTC, daosbuild1 commented
Test stage Test CentOS 7 RPMs completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6337/7/display/redirect

2021-08-03 16:48 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-04 17:42 UTC, phender approved these changes

2021-08-04 18:31 UTC, dinghwah approved these changes
LGTM.

2021-08-04 18:32 UTC, shimizukko commented
Known failures that aren't relevant to my change:
* ior/ior_small.py - DAOS-8233
* pool/create_capacity_test.py - DAOS-8229

2021-08-05 03:32 UTC, merged