DAOS-8213 test: Improve TestPool if label/UUID condition using identi…
daos-stack/daos pull request #6338
Opened 2021-08-01 18:43 UTC by shimizukko

…fier

Also removed exclude API call.

Skip-unit-tests: true
Test-tag: pr
Signed-off-by: Makito Kano <makito.kano@intel.com>

2021-08-01 18:45 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/test_utils_pool.py:215](https://github.com/daos-stack/daos/blob/7ad976701982d37b79ad0776972ba796cd58b1eb/src/tests/ftest/util/test_utils_pool.py#L215):
(pylint-unnecessary-comprehension) Unnecessary use of a comprehension

[src/tests/ftest/util/test_utils_pool.py:628](https://github.com/daos-stack/daos/blob/7ad976701982d37b79ad0776972ba796cd58b1eb/src/tests/ftest/util/test_utils_pool.py#L628):
(pylint-no-else-raise) Unnecessary "elif" after "raise"

[src/tests/ftest/util/test_utils_pool.py:614](https://github.com/daos-stack/daos/blob/7ad976701982d37b79ad0776972ba796cd58b1eb/src/tests/ftest/util/test_utils_pool.py#L614):
(pylint-unused-argument) Unused argument 'daos_log'

2021-08-01 18:50 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/test_utils_pool.py:215](https://github.com/daos-stack/daos/blob/3cf714d81009c23d08cfc693b4429169f55a7f62/src/tests/ftest/util/test_utils_pool.py#L215):
(pylint-unnecessary-comprehension) Unnecessary use of a comprehension

2021-08-01 18:56 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/test_utils_pool.py:215](https://github.com/daos-stack/daos/blob/4347fe7c5e29642e86e0c1e6d9d7334fd0e695b5/src/tests/ftest/util/test_utils_pool.py#L215):
(pylint-unnecessary-comprehension) Unnecessary use of a comprehension

2021-08-02 20:00 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/test_utils_pool.py:215](https://github.com/daos-stack/daos/blob/da199ff692cbe5adf00f3e7d7d7d1863d57934da/src/tests/ftest/util/test_utils_pool.py#L215):
(pylint-unnecessary-comprehension) Unnecessary use of a comprehension

2021-08-02 20:54 UTC, daosbuild1 commented
Test stage Functional on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6338/4/display/redirect

2021-08-03 19:18 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6338/5/display/redirect

2021-08-03 19:24 UTC, daosbuild1 commented
Test stage Functional Hardware Small completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6338/5/display/redirect

2021-08-03 19:30 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6338/5/display/redirect

2021-08-04 11:48 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/test_utils_pool.py:215](https://github.com/daos-stack/daos/blob/2d2aec629ad74ffa3acb1f5ed96f55606157d914/src/tests/ftest/util/test_utils_pool.py#L215):
(pylint-unnecessary-comprehension) Unnecessary use of a comprehension

2021-08-04 17:09 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/test_utils_pool.py:215](https://github.com/daos-stack/daos/blob/0e0301f77eb7e1870f6eaeb5948f6ecdb9ed9dc2/src/tests/ftest/util/test_utils_pool.py#L215):
(pylint-unnecessary-comprehension) Unnecessary use of a comprehension

2021-08-04 19:36 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/test_utils_pool.py:238](https://github.com/daos-stack/daos/blob/afff89bc47d0b7ff357bbed42214d0e12678a90e/src/tests/ftest/util/test_utils_pool.py#L238):
(pylint-unnecessary-comprehension) Unnecessary use of a comprehension

2021-08-04 23:28 UTC, daosbuild1 commented
Test stage Functional on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6338/8/execution/node/953/log

2021-08-05 15:46 UTC, phender approved these changes

2021-08-05 15:53 UTC, phender requested changes
`self.identifier` should be used in https://github.com/daos-stack/daos/blob/afff89bc47d0b7ff357bbed42214d0e12678a90e/src/tests/ftest/util/test_utils_pool.py#L838-L842

2021-08-05 16:18 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/test_utils_pool.py:237](https://github.com/daos-stack/daos/blob/21a1b2f10736221cedcaa8c4790e9349366d5c3b/src/tests/ftest/util/test_utils_pool.py#L237):
(pylint-unnecessary-comprehension) Unnecessary use of a comprehension

2021-08-05 16:43 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6338/10/execution/node/371/log

2021-08-05 16:44 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6338/10/execution/node/380/log

2021-08-05 17:06 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6338/10/execution/node/377/log

2021-08-06 17:38 UTC, phender approved these changes

2021-08-06 18:30 UTC, shimizukko commented
Test failures that are not related to this change.

- pool/connect_test.py - DAOS-8257
- server/daos_server_restart.py - DAOS-8257
- daos_test/daos_core_test.py - DAOS-8259
- osa/osa_offline_reintegration.py - DAOS-8231

2021-08-06 19:02 UTC, dinghwah approved these changes
lgtm

2021-08-09 20:28 UTC, merged