DAOS-8184 test: Use UUID to call some dmg pool commands
daos-stack/daos pull request #6351
Opened 2021-08-03 12:26 UTC by shimizukko

Add some UUID test coverage for dmg pool commands.
Updated the tests to use TestPool instead of directly calling dmg.

Skip-unit-tests: true
Test-tag: snapshot_aggregation test_pool_svc bad_evict pool_evict_basic
Signed-off-by: Makito Kano <makito.kano@intel.com>

2021-08-03 12:28 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6351/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/pool/bad_evict.py:7](https://github.com/daos-stack/daos/blob/b967e95ae934017d7e481badd8b28e2a1b826da9/src/tests/ftest/pool/bad_evict.py#L7):
(pylint-unused-import) Unused import traceback

[src/tests/ftest/pool/bad_evict.py:11](https://github.com/daos-stack/daos/blob/b967e95ae934017d7e481badd8b28e2a1b826da9/src/tests/ftest/pool/bad_evict.py#L11):
(pylint-unused-import) Unused CommandFailure imported from command_utils

[src/tests/ftest/pool/evict_test.py:11](https://github.com/daos-stack/daos/blob/b967e95ae934017d7e481badd8b28e2a1b826da9/src/tests/ftest/pool/evict_test.py#L11):
(pylint-unused-import) Unused CommandFailure imported from command_utils_base

2021-08-03 12:28 UTC, daosbuild1 commented on src/tests/ftest/pool/bad_evict.py
> +            for item in range(0, len(saveduuid)):
(pylint-consider-using-enumerate) Consider using enumerate instead of iterating with range and len

2021-08-03 12:28 UTC, daosbuild1 commented on src/tests/ftest/pool/bad_evict.py
> +            for item in range(0, len(saveduuid)):
(pylint-consider-using-enumerate) Consider using enumerate instead of iterating with range and len

2021-08-03 12:28 UTC, daosbuild1 commented on src/tests/ftest/pool/evict_test.py
> +        if pool.dmg.result.exit_status != 0:
(pylint-no-member) Instance of 'list' has no 'dmg' member

2021-08-03 12:28 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6351/1/execution/node/100/log

2021-08-03 12:55 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/pool/bad_evict.py:7](https://github.com/daos-stack/daos/blob/deb1dec03c0d163c08a9636a76e5728ffdc8366b/src/tests/ftest/pool/bad_evict.py#L7):
(pylint-unused-import) Unused import traceback

[src/tests/ftest/pool/bad_evict.py:11](https://github.com/daos-stack/daos/blob/deb1dec03c0d163c08a9636a76e5728ffdc8366b/src/tests/ftest/pool/bad_evict.py#L11):
(pylint-unused-import) Unused CommandFailure imported from command_utils

[src/tests/ftest/pool/evict_test.py:11](https://github.com/daos-stack/daos/blob/deb1dec03c0d163c08a9636a76e5728ffdc8366b/src/tests/ftest/pool/evict_test.py#L11):
(pylint-unused-import) Unused CommandFailure imported from command_utils_base

2021-08-03 12:59 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-03 18:21 UTC, phender requested changes

2021-08-03 18:21 UTC, phender commented on src/tests/ftest/pool/bad_evict.py
> +        self.pool.use_label = True
```suggestion
        # trash the UUID value in various ways
        if excludeuuid is None:
            saveduuid = (ctypes.c_ubyte * 16)(0)
            for index, _ in enumerate(saveduuid):
                saveduuid[index] = self.pool.pool.uuid[index]
            self.pool.pool.uuid[0:] = \
                [0 for item in range(0, len(self.pool.pool.uuid))]
        elif excludeuuid == 'JUNK':
            saveduuid = (ctypes.c_ubyte * 16)(0)
            for index, _ in enumerate(saveduuid):
                saveduuid[index] = self.pool.pool.uuid[index]
            self.pool.pool.uuid[4] = 244

        self.pool.uuid = self.pool.pool.get_uuid_str()

        try:
            # Make dmg call and poolevict() not fail.
            self.pool.dmg.exit_status_exception = False
            self.pool.use_label = False
            self.pool.evict()
        finally:
            self.pool.use_label = True
            self.pool.dmg.exit_status_exception = True
```

2021-08-04 11:55 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-04 17:47 UTC, phender approved these changes

2021-08-04 18:32 UTC, dinghwah approved these changes
LGTM.

2021-08-05 01:15 UTC, sylviachanoiyee commented
all changes under ftests/pool

2021-08-05 01:16 UTC, merged