DAOS-8008 engine: quiet dpdk logging
daos-stack/daos pull request #6419
Opened 2021-08-10 12:03 UTC by tanabarr

Add SPDK patch (source and RPM builds updated) to allow multiple cli
args to be passed to DPDK when initialized by SPDK.

Reinstate DPDK log mask setting to reduce output to ERROR and higher
(default is NOTICE).

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

2021-08-10 12:05 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-10 12:06 UTC, tanabarr commented
https://github.com/daos-stack/spdk/pull/24 updates the SPDK in-house packaging with the relevant patch.

2021-08-10 12:20 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6419/1/execution/node/409/log

2021-08-10 14:12 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6419/2/execution/node/316/log

2021-08-10 15:17 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-10 17:35 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6419/4/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-08-10 17:35 UTC, daosbuild1 commented on src/bio/bio_xstream.c
> +	opts.env_context = "--log-level=lib.eal:4 --log-level=lib.user1:4" + \
(style)  Avoid unnecessary line continuations

2021-08-10 17:35 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6419/4/execution/node/100/log

2021-08-10 17:37 UTC, jolivier23 requested changes

2021-08-10 17:37 UTC, jolivier23 commented on site_scons/components/__init__.py
> +                commands=['git config user.email "daos@daos.groups.io"',
does this change local settings?  Why do we need to add git config here anyway?

We already have a built-in mechanism for applying a patch if it's helpful

In build.config
[patch_versions]
spdk=https://path/to/patch

2021-08-10 17:41 UTC, daosbuild1 commented
Test stage Build on CentOS 7 debug completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6419/4/execution/node/411/log

2021-08-10 17:42 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6419/4/execution/node/394/log

2021-08-10 17:42 UTC, daosbuild1 commented
Test stage Build on CentOS 7 release completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6419/4/execution/node/446/log

2021-08-10 17:43 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6419/4/execution/node/400/log

2021-08-10 17:43 UTC, daosbuild1 commented
Test stage Build on Leap 15 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6419/4/execution/node/435/log

2021-08-10 17:43 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6419/4/execution/node/381/log

2021-08-10 17:47 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6419/4/execution/node/397/log

2021-08-10 17:56 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6419/4/execution/node/423/log

2021-08-10 21:50 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-10 22:05 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6419/5/execution/node/409/log

2021-08-11 08:45 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-12 11:15 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-12 16:37 UTC, jolivier23 approved these changes

2021-08-12 16:39 UTC, tanabarr commented
SnapshotAggregation known failure in CI:
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-6419/8/tests/

2021-08-12 19:43 UTC, johannlombardi approved these changes

2021-08-12 19:44 UTC, merged