DAOS-7758 test: set rf to be 1 for offline drain test
daos-stack/daos pull request #6455
Opened 2021-08-13 14:52 UTC by wangshilong

Creating objects with oclass RP_2G1 implies rf:1, which
was expected failure if container was created with rf:2.

Test-tag-hw-medium: pr,hw,medium,ib2,offline_drain
Signed-off-by: Wang Shilong <shilong.wang@intel.com>

2021-08-13 14:54 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-17 00:51 UTC, rpadma2 requested changes
Present run didn't run all the offline drain test case. The issue is with oclass test case (different object class testing).

Please run the testing using the following tag (at the commit message):
Test-tag-hw-medium: pr,hw,medium,ib2 offline_drain

Here is the present issue under oclass test case:
IOR uses the RP_3G6 (for which the script will calculate the appropriate rf value which is 2).
MDtest unfortunately doesn't use the same object class. It uses RP_2G1 and it causing problems. 
We have to make sure IOR and MDtest uses same object class during the testing.

2021-08-17 01:14 UTC, rpadma2 commented
Looks like the problem is under this method under util/osa_utils.py
===========================================

    def run_mdtest_thread(self, oclass="RP_2G1"):
        """Start mdtest thread and wait until thread completes.
        Args:
            oclass (str): IOR object class, container class.
        """
        # Create container only
        self.mdtest_cmd.dfs_destroy = False
        if self.container is None:
            self.add_container(self.pool, create=False)
            self.mdtest_cmd.dfs_oclass.update(oclass)
            self.set_cont_class_properties(self.mdtest_cmd.dfs_oclass)
            if self.test_with_checksum is False:
                tmp = self.get_object_replica_value(self.mdtest_cmd.dfs_oclass)
                rf_value = "rf:{}".format(tmp - 1)
                self.update_cont_properties(rf_value)
            self.container.create()

The object class is set only when the self.container is None... It doesn't handle if the container is already created. The container is already created during the IOR run. The mdtest is run on the same container where IOR was run. 
I think the changes needed maybe like this:
        if self.container is None:
            self.add_container(self.pool, create=False)
            self.mdtest_cmd.dfs_oclass.update(oclass)
            self.set_cont_class_properties(self.mdtest_cmd.dfs_oclass)
            if self.test_with_checksum is False:
                tmp = self.get_object_replica_value(self.mdtest_cmd.dfs_oclass)
                rf_value = "rf:{}".format(tmp - 1)
                self.update_cont_properties(rf_value)
            self.container.create()
        else:
            self.mdtest_cmd.dfs_oclass.update(oclass)
            self.set_cont_class_properties(self.mdtest_cmd.dfs_oclass)
            if self.test_with_checksum is False:
                tmp = self.get_object_replica_value(self.mdtest_cmd.dfs_oclass)
                rf_value = "rf:{}".format(tmp - 1)
                self.update_cont_properties(rf_value)

2021-08-18 02:22 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/osa_utils.py:22](https://github.com/daos-stack/daos/blob/d013710442f3ef045efcd9364c4604e13ae757a9/src/tests/ftest/util/osa_utils.py#L22):
(pylint-too-many-public-methods) Too many public methods (24/20)

2021-08-18 13:48 UTC, rpadma2 approved these changes
LGTM.

2021-08-18 16:45 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6455/2/display/redirect

2021-08-19 05:00 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/osa_utils.py:22](https://github.com/daos-stack/daos/blob/d013710442f3ef045efcd9364c4604e13ae757a9/src/tests/ftest/util/osa_utils.py#L22):
(pylint-too-many-public-methods) Too many public methods (24/20)

2021-08-19 08:40 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/osa_utils.py:22](https://github.com/daos-stack/daos/blob/d013710442f3ef045efcd9364c4604e13ae757a9/src/tests/ftest/util/osa_utils.py#L22):
(pylint-too-many-public-methods) Too many public methods (24/20)

2021-08-19 15:08 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/osa_utils.py:22](https://github.com/daos-stack/daos/blob/d013710442f3ef045efcd9364c4604e13ae757a9/src/tests/ftest/util/osa_utils.py#L22):
(pylint-too-many-public-methods) Too many public methods (24/20)

2021-08-20 01:37 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/osa_utils.py:22](https://github.com/daos-stack/daos/blob/e08b37e72af3e158810264dc642c28580b43443a/src/tests/ftest/util/osa_utils.py#L22):
(pylint-too-many-public-methods) Too many public methods (24/20)

2021-08-24 16:00 UTC, saurabhtandan reviewed
Also, reading the title of PR it seems like we simply want to achieve rf:1 for offline drain test. So my question is, why can't we simply use the test yaml file to do that instead of extracting the object class then assigning it to a `tmp` and then calculating rf factor?
If I am not understanding something right, feel free to explain.

2021-09-01 16:44 UTC, saurabhtandan approved these changes
LGTM

2021-09-07 14:24 UTC, rpadma2 commented
Hmm... The test changes does what is expected. Both IOR and MDTest now uses the same class..
But, I don't understand how functional tests is showing all tests passed when the one of the tests actually failed. Looks like rebuild was stuck busy... Also, pool destroy failed and test "ERROR"ed out.
2021-09-02 05:51:54,597 stacktrace       L0047 ERROR|   File "/usr/lib64/python3.6/subprocess.py", line 1424, in _try_wait
2021-09-02 05:51:54,597 stacktrace       L0047 ERROR|     (pid, sts) = os.waitpid(self.pid, wait_flags)
2021-09-02 05:51:54,597 stacktrace       L0047 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/runner.py", line 312, in sigterm_handler
2021-09-02 05:51:54,597 stacktrace       L0047 ERROR|     raise RuntimeError("Test interrupted by SIGTERM")
2021-09-02 05:51:54,597 stacktrace       L0047 ERROR| RuntimeError: Test interrupted by SIGTERM
2021-09-02 05:51:54,597 stacktrace       L0048 ERROR| 
2021-09-02 05:51:54,597 test             L0876 DEBUG| Local variables:
2021-09-02 05:51:54,599 test             L0879 DEBUG|  -> oclass <class 'str'>: RP_2G8
2021-09-02 05:51:54,599 test             L0879 DEBUG|  -> self <class 'osa_offline_drain.OSAOfflineDrain'>: 4-./osa/osa_offline_drain.py:OSAOfflineDrain.test_osa_offline_drain_oclass;aggregation-single-checksum-container-single-hosts-clientslots-iorflags-client_processes-32K-pool-rebuild-1KB-0-1-server_manager-setup-snapshot-test_obj_class-test_ranks-01a9
2021-09-02 05:51:54,599 test             L0338 INFO | ==================================================

https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6455/11/artifact/Functional%20Hardware%20Medium/osa/osa_offline_drain.py/job.log/*view*/

2021-09-07 16:34 UTC, saurabhtandan approved these changes
LGTM

2021-09-09 00:13 UTC, wangshilong commented
@rpadma2 I agreed, but i think that should not block this test improvement PR? we could open seperated ticket with that issue?

2021-09-09 00:37 UTC, rpadma2 commented
> @rpadma2 I agreed, but i think that should not block this test improvement PR? we could open seperated ticket with that issue?

Sure, I agree. But, please create a bug ticket with the information. Someone can taka look at the issue later.

2021-09-09 00:54 UTC, rpadma2 approved these changes
LGTM.

2021-09-09 09:20 UTC, merged