DAOS-7174 doc: document daos_perf and fix a few nits
daos-stack/daos pull request #6501
Opened 2021-08-18 12:35 UTC by johannlombardi

Fix a few intending issues (e.g. in property tables and dfuse modes).
Add an example for daos_perf.
Add an example for IL monitoring.

doc-only: true

Signed-off-by: Johann Lombardi <johann.lombardi@intel.com>

2021-08-18 12:37 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-18 12:42 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-18 15:45 UTC, cdurf1 commented on doc/user/workflow.md
>      The command is executed in a development environment,
An open line is rqd here to render the Note

2021-08-18 15:45 UTC, cdurf1 commented on doc/user/workflow.md
>      Smaller pools may show DER_NOSPACE(-1007): 'No space
And a line here.

2021-08-18 15:55 UTC, cdurf1 approved these changes

2021-08-18 16:08 UTC, jolivier23 requested changes
Looks fine but I wonder if we should just move this to #6223 

So +1 but with request changes so you at least read this comment before landing

2021-08-18 17:50 UTC, daosbuild1 commented
Test stage Functional on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6501/2/display/redirect

2021-08-19 07:11 UTC, johannlombardi commented
@jolivier23 got it.

2021-08-19 07:55 UTC, merged