DAOS-8445 tests: run daos_racer with multiple client ranks
daos-stack/daos pull request #6588
Opened 2021-08-31 09:05 UTC by Nasf-Fan

That will help to generate more race conditions.

Signed-off-by: Fan Yong <fan.yong@intel.com>

2021-08-31 09:07 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-08-31 16:20 UTC, phender submitted a review, later dismissed

2021-08-31 17:21 UTC, saurabhtandan requested changes
This change alone will not enable daos_racer to be run on multiple clients. 
`2021-08-31 12:38:53,346 parameters       L0146 DEBUG| PARAMS (key=runtime, path=/run/daos_racer/*, default=60) => 600
2021-08-31 12:38:53,347 daos_racer_utils L0107 INFO | Running export D_LOG_FILE=/var/tmp/daos_testing/daos_racer_daos.log;export OMPI_MCA_btl_openib_warn_default_gid_prefix=0;export OMPI_MCA_btl=tcp,self;export OMPI_MCA_oob=tcp;export OMPI_MCA_pml=ob1;export D_LOG_MASK=ERR; /usr/bin/daos_racer -n /etc/daos/daos_control.yml -t 600 on wolf-116 with a 900s timeout
2021-08-31 12:48:57,248 general_utils    L0409 INFO | Command: export D_LOG_FILE=/var/tmp/daos_testing/daos_racer_daos.log;export OMPI_MCA_btl_openib_warn_default_gid_prefix=0;export OMPI_MCA_btl=tcp,self;export OMPI_MCA_oob=tcp;export OMPI_MCA_pml=ob1;export D_LOG_MASK=ERR; /usr/bin/daos_racer -n /etc/daos/daos_control.yml -t 600
2021-08-31 12:48:57,248 general_utils    L0410 INFO | Results:
2021-08-31 12:48:57,248 general_utils    L0414 INFO |   wolf-116: exit_status=0, interrupted=False:
2021-08-31 12:48:57,248 general_utils    L0416 INFO |     racer start with 1 threads duration 600 secs
2021-08-31 12:48:57,248 general_utils    L0416 INFO |     	pool size     : SCM: 2048 MB, NVMe: 8192 MB
2021-08-31 12:48:57,248 general_utils    L0416 INFO |     Verifying consistency after racer...
2021-08-31 12:48:57,249 general_utils    L0416 INFO |     Verified consistency after racer.
2021-08-31 12:48:57,249 daos_racer_utils L0119 INFO | Test passed!`

In the daos_racer.py and daos_racer_simple.py files you might want to make the following change as well.
`- daos_racer = DaosRacerCommand(self.bin, self.hostlist_clients[0], dmg)`
`+ daos_racer = DaosRacerCommand(self.bin, self.hostlist_clients, dmg)`

2021-08-31 23:11 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-09-01 16:11 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6588/3/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-09-01 16:11 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6588/3/execution/node/119/log

2021-09-01 16:24 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6588/3/execution/node/383/log

2021-09-08 14:04 UTC, sylviachanoiyee commented
Looks like the build failed and test are not run, @Nasf-Fan , can you retrigger?

2021-09-26 02:36 UTC, Nasf-Fan commented
Replaced by the patch https://github.com/daos-stack/daos/pull/6804

2021-09-26 02:36 UTC, closed without merging