Daos 8017 test: Weekly test: rebuild cascading_failures test failed RC: -2031 on Writing object after 2 ranks rebuild completed
daos-stack/daos pull request #6662
Opened 2021-09-09 19:34 UTC by dinghwah

Update with container RF in test.yaml

Test-tag: pr cascading
Signed-off-by: Ding Ho ding-hwa.ho@intel.com

2021-09-09 19:37 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-09-10 11:03 UTC, shimizukko approved these changes

2021-09-13 22:07 UTC, phender approved these changes

2021-09-13 23:41 UTC, omar-ocampo submitted a review, later dismissed
LGTM

2021-09-14 02:02 UTC, sylviachanoiyee requested changes
Why is rf set to 1, and not 2 or more?
From the discussion in DAOS-8017, the suggestion was to set 
#RF >= #exluded_ranks
There are 3 tests in this file, killing 2 ranks simultaneously, sequentially, and in cascading fashion. So shouldn't rf be at least 2?
FYI, the sequential failed in weekly build #203 and simultaneous failed in weekly #204.

==> Please see the update, also includes all 3 rebuild tests.

2021-09-14 03:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-09-14 13:37 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6662/3/display/redirect

2021-09-14 13:47 UTC, shimizukko approved these changes

2021-09-15 01:22 UTC, sylviachanoiyee commented
@dinghwah , I think we need to enable Leap15 testing in this PR. The failures I see in weekly are Leap15, not CentOS7. 
At this point, we don't really know if the PR fixes the issue. Thanks.

2021-09-15 19:27 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-09-16 14:10 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-09-20 14:21 UTC, omar-ocampo approved these changes

2021-09-20 18:54 UTC, sylviachanoiyee approved these changes

2021-09-20 18:57 UTC, merged