DAOS-7174 utils: remove reference to psm2 yaml file
daos-stack/daos pull request #6777
Opened 2021-09-21 20:05 UTC by johannlombardi

Replace reference to the psm2 server config file with verbs.

Signed-off-by: Johann Lombardi <johann.lombardi@intel.com>

2021-09-21 20:19 UTC, jolivier23 approved these changes

2021-09-21 20:55 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6777/1/execution/node/678/log

2021-09-21 21:36 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-09-21 22:25 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-6777/2/execution/node/693/log

2021-09-21 23:35 UTC, kjacque approved these changes

2021-09-21 23:39 UTC, kjacque requested changes
Whoops, it looks like the updated tests didn't actually pass. In TestServerConfig_Constructed you need to change the `WithCrtCtxShareAddr(...)` line to have a 0 instead of a 1.

2021-09-22 05:31 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-09-22 06:32 UTC, merged