DAOS-8968 mercury: Update to v2.1.0rc3
daos-stack/daos pull request #7316
Opened 2021-11-11 16:12 UTC by frostedcmos

- Update mercury to v2.1.0rc3
- Apply patch for daos-8968

PR-repos: mercury@PR-68

Signed-off-by: Alexander Oganezov <alexander.a.oganezov@intel.com>

2021-11-11 16:14 UTC, frostedcmos commented
Corresponding mercury build https://github.com/daos-stack/mercury/pull/68

2021-11-11 16:15 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-11-11 16:25 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7316/1/execution/node/392/log

2021-11-11 16:25 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7316/1/execution/node/377/log

2021-11-11 16:32 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7316/1/execution/node/380/log

2021-11-11 16:33 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7316/1/execution/node/325/log

2021-11-11 16:35 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7316/1/execution/node/330/log

2021-11-11 18:35 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-11-11 18:53 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7316/2/execution/node/379/log

2021-11-11 19:01 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7316/2/execution/node/325/log

2021-11-16 17:50 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-11-16 19:45 UTC, brianjmurrell approved these changes

2021-11-17 18:23 UTC, jolivier23 submitted a review, later dismissed

2021-11-19 03:51 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-11-19 03:57 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7316/4/execution/node/323/log

2021-11-19 03:58 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7316/4/execution/node/326/log

2021-11-19 04:01 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7316/4/execution/node/320/log

2021-11-19 04:03 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-11-19 19:14 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-11-26 16:49 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-11-26 16:59 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7316/7/execution/node/337/log

2021-11-26 17:00 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7316/7/execution/node/342/log

2021-11-26 17:01 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7316/7/execution/node/317/log

2021-11-26 17:10 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7316/7/execution/node/345/log

2021-11-26 17:13 UTC, brianjmurrell requested changes
Just -1 to prevent premature accidental landing before https://github.com/daos-stack/mercury/pull/68 lands.

2021-11-26 17:13 UTC, brianjmurrell commented on utils/rpms/daos.spec
> +%global mercury_version 2.1.0~rc4-1%{?dist}
https://github.com/daos-stack/mercury/pull/68 needs to land, build and publish before this can land.

2021-11-26 17:15 UTC, brianjmurrell submitted a review, later dismissed

2021-11-30 03:33 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-11-30 22:13 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-12-01 18:43 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-12-02 22:38 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-12-03 18:11 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-12-03 19:11 UTC, johannlombardi approved these changes

2021-12-03 19:11 UTC, jolivier23 approved these changes

2021-12-03 19:14 UTC, merged