DAOS-9172 Test: Remove daos_server prepare storage command from Avcoado setup.
daos-stack/daos pull request #7527
Opened 2021-12-01 20:10 UTC by ravalsam

No need to call storage prepare as it's being done internally when daos_server starts.

Test-tag: pr daily_regression

Signed-off-by: Samir Raval <samir.raval@intel.com>

2021-12-01 20:12 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/server_utils.py:1](https://github.com/daos-stack/daos/blob/4773c0df24383f8c0621c2c6b009bd7c4cf8e488/src/tests/ftest/util/server_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1065/1000)

[src/tests/ftest/util/server_utils.py:174](https://github.com/daos-stack/daos/blob/4773c0df24383f8c0621c2c6b009bd7c4cf8e488/src/tests/ftest/util/server_utils.py#L174):
(pylint-unused-argument) Unused argument 'storage'

[src/tests/ftest/util/server_utils.py:615](https://github.com/daos-stack/daos/blob/4773c0df24383f8c0621c2c6b009bd7c4cf8e488/src/tests/ftest/util/server_utils.py#L615):
(pylint-consider-using-set-comprehension) Consider using a set comprehension
(pylint-consider-using-dict-items) Consider iterating with .items()

2021-12-01 20:36 UTC, phender requested changes
Just some minor related changes needed.  It may also make sense to manually run the `network/cart_self_test.py` to see if it is adversely effected by the change.

2021-12-01 20:36 UTC, phender commented on src/tests/ftest/util/server_utils.py
> -        if storage:
We should also make these corresponding edits in https://github.com/daos-stack/daos/blob/4773c0df24383f8c0621c2c6b009bd7c4cf8e488/src/tests/ftest/util/server_utils.py#L174-L180:
```
    def prepare(self):
        """Prepare to start daos_server."""
```

And in https://github.com/daos-stack/daos/blob/master/src/tests/ftest/control/daos_admin_privileged.py#L55:
```
        self.server_managers[0].prepare()
```

2021-12-01 20:36 UTC, phender commented on src/tests/ftest/util/server_utils.py
> -                        {"plm_rsh_args": "-l root"}, "orterun.mca", True)
If the `network/cart_self_test.py` test fails - one of the few tests that still use `orterun` to launch the server - then we may need to reinstate this code.  If that does end up being the case, I'd suggest something like this: 
```
        if self.manager.job.using_nvme or self.manager.job.using_dcpm:
            if hasattr(self.manager, "mca"):
                self.manager.mca.update({"plm_rsh_args": "-l root"}, "orterun.mca", True)
```

2021-12-01 21:47 UTC, tanabarr approved these changes

2021-12-03 16:56 UTC, ravalsam commented
Closing this as more testing and changes might be needed.

2021-12-03 16:56 UTC, closed without merging