DAOS-7526 test: Adding io & system admin test
daos-stack/daos pull request #7543
Opened 2021-12-02 15:22 UTC by saurabhtandan

Adding io & basic system admin test to the deployment
directory to check happy path io tests and system admin
activities.

Test-tag: pr iosysadmin

Signed-off-by: Saurabh Tandan <saurabh.tandan@intel.com>

2021-12-02 15:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-12-06 02:03 UTC, shimizukko submitted a review, later dismissed

2021-12-06 17:28 UTC, phender requested changes

2021-12-06 17:28 UTC, phender commented on src/tests/ftest/deployment/io_sys_admin.py
> +                                         new_test_user, new_test_group)
For 3 containers per pool:
```suggestion
            for cont_idx in range(1, 4):
                self.add_container_qty(1, self.pool[-1], namespace="/run/container_{}/".format(cont_idx))
                daos.container_set_owner(self.pool[-1].uuid, self.container[-1].uuid,
                                         new_test_user, new_test_group)
```

2021-12-06 19:50 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7543/2/execution/node/248/log

2021-12-06 19:56 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7543/2/execution/node/230/log

2021-12-07 17:13 UTC, saurabhtandan commented on src/tests/ftest/deployment/io_sys_admin.py
> +        return free_space
Done

2021-12-07 17:14 UTC, saurabhtandan commented on src/tests/ftest/deployment/io_sys_admin.py
> +#        hdf5_plugin_path = self.params.get("plugin_path", '/run/hdf5_vol/*')
Done

2021-12-07 17:15 UTC, saurabhtandan commented on src/tests/ftest/deployment/io_sys_admin.py
> +        # wirte large data sets
Done

2021-12-07 17:15 UTC, saurabhtandan commented on src/tests/ftest/deployment/io_sys_admin.py
> +                                         new_test_user, new_test_group)
Done

2021-12-07 17:17 UTC, saurabhtandan commented
The PR was run with 'pr' tag earlier
And the last run was run for just the 'iosysadmin' tag which is expected to fail with known issue of DAOS-9218

2021-12-08 17:20 UTC, ravalsam approved these changes

2021-12-08 17:29 UTC, phender approved these changes

2021-12-08 17:29 UTC, phender commented on src/tests/ftest/util/file_count_test_base.py
> +
The pydocstyle recommendation is single-spacing between methods inside a class and double-spacing between classes or standalone methods in a file.
```suggestion
```

2021-12-09 01:16 UTC, shimizukko approved these changes

2021-12-09 15:18 UTC, merged