DAOS-7509 documentation: Update DAOS HW documentation
daos-stack/daos pull request #7693
Opened 2021-12-16 19:57 UTC by cdurf1

Skip-build: true
Skip-test: true

Signed-off-by: craig <craig.durfey@intel.com>

2021-12-16 19:59 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-12-17 22:24 UTC, Michael-Hennecke commented on docs/admin/hardware.md
> +x86\_64 are applicable for ARM builds as well. DAOS and its dependencies
the DAOS client is not regularly tested on ARM64 ... please keep the original text.

2021-12-17 22:25 UTC, Michael-Hennecke commented on docs/admin/hardware.md
> +=====================
please keep original MD heading markup using #, ##, etc.

2021-12-17 22:25 UTC, Michael-Hennecke commented on docs/admin/hardware.md
> +deployed in two different ways:
figure dropped, so delete the reference to it?

2021-12-17 22:27 UTC, Michael-Hennecke commented on docs/admin/hardware.md
> +network cards.
please keep the original text - "rails" have a special meaning that usually does not apply here, and it *is* the engine and not the server that is meant here.

2021-12-17 22:29 UTC, Michael-Hennecke commented on docs/admin/hardware.md
> +height="3.1944444444444446in"}
remove image resizing tags?

2021-12-17 22:29 UTC, Michael-Hennecke commented on docs/admin/hardware.md
> +height="5.791666666666667in"}
remove image resizing tags?

2021-12-17 22:31 UTC, Michael-Hennecke commented on docs/admin/hardware.md
> +
use in-place markdown HREFs [text](link) instead of footnotes?

2021-12-17 22:32 UTC, Michael-Hennecke requested changes
see inline comments...

2021-12-20 21:01 UTC, kprantis commented
Any update on addressing the above review feedback?

2021-12-20 21:14 UTC, cdurf1 commented
@kprantis  - I'll have it in by EOD

2021-12-20 21:45 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-7693/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-12-20 21:45 UTC, daosbuild1 commented on docs/admin/hardware.md
> +ARM testing is not part of the current DAOS CI pipeline and is thus not
(style)  trailing whitespace

2021-12-20 21:45 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7693/2/execution/node/112/log

2021-12-20 21:58 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-7693/3/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2021-12-20 21:58 UTC, daosbuild1 commented on docs/admin/hardware.md
> +[SPDK](https://pmem.io/pmdk/), [PMDK](https://spdk.io/), and
(style)  trailing whitespace

2021-12-20 21:58 UTC, daosbuild1 commented on docs/admin/hardware.md
> +ARM testing is not part of the current DAOS CI pipeline and is thus not
(style)  trailing whitespace

2021-12-20 21:58 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7693/3/execution/node/113/log

2021-12-20 22:04 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-12-20 22:17 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7693/4/execution/node/378/log

2021-12-20 22:19 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7693/4/execution/node/350/log

2021-12-21 14:51 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-12-21 15:01 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7693/5/execution/node/363/log

2021-12-21 15:02 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7693/5/execution/node/359/log

2021-12-21 15:10 UTC, Michael-Hennecke commented on docs/admin/hardware.md
> +network cards.
still referring to "rails".... which isn't how most DAOS systems are deployed: most DAOS systems have their multiple network interfaces connected to the same "rail", not to multiple "rails". so the original text that simply says "multiple network interfaces" is the more general and more appropriate description.

2021-12-21 15:12 UTC, Michael-Hennecke approved these changes

2021-12-22 08:33 UTC, johannlombardi approved these changes

2021-12-22 08:34 UTC, merged

2021-12-22 08:34 UTC, johannlombardi commented
Please back port to release/2.0.