DAOS-9210 doc: clarify IOR usage in QSG/testing
daos-stack/daos pull request #7714
Opened 2021-12-17 22:05 UTC by Michael-Hennecke

Clarify IOR usage, including the use of API=DFS

Signed-off-by: Michael Hennecke <michael.hennecke@intel.com>

2021-12-17 22:07 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-12-18 04:08 UTC, Kmannth requested changes

2021-12-18 04:08 UTC, Kmannth commented on docs/testing/ior.md
> +$ mpirun -hostfile /path/to/hostfile_clients -np 30 <your_dir>/bin/ior -a POSIX -b 5G -t 1M -v -W -w -r -R -i 1 -o /tmp/daos_dfuse/testfile
This is still Posix. Either load the interception library or move to the to the DFS version please as the comment suggests. 

I don't think we want to promote standard Posix usage in the manual.   There are plenty of other guides that teach people how to do this.

2021-12-18 04:08 UTC, Kmannth commented on docs/testing/ior.md
> +$ mpirun -hostfile /path/to/hostfile_clients -np 10 <your_dir>/bin/mdtest -a POSIX -z 0 -F -C -i 1 -n 3334 -e 4096 -d /tmp/daos_dfuse/ -w 4096
Still -a Posix.  Please update for better performance. 

Please help new to mdtest users understand what -a -z -F -C -i -n -e -D -W all mean.

2021-12-19 16:39 UTC, johannlombardi approved these changes

2021-12-19 16:40 UTC, johannlombardi commented
Please address the changes suggested by @Kmannth in a new PR.

2021-12-19 16:40 UTC, merged