DAOS-9354 control: use min hugepages for scan
daos-stack/daos pull request #7771
Opened 2021-12-27 05:18 UTC by wangshilong

A small amount of huge pages is needed to do storage
scan for SPDK device probing.

Test-tag: control_start nvme_scan
Signed-off-by: Wang Shilong <shilong.wang@intel.com>

2021-12-27 07:36 UTC, johannlombardi submitted a review, later dismissed

2021-12-27 13:36 UTC, tanabarr requested changes
looks good other than the suggested change for the corner case

2021-12-27 13:36 UTC, tanabarr commented on src/control/server/server_utils.go
> +		prepReq.HugePageCount = srv.cfg.NrHugepages * len(srv.cfg.Engines)
```suggestion
		if len(srv.cfg.Engines) == 0 {
		        prepReq.HugePageCount = srv.cfg.NrHugepages
		} else {
		        prepReq.HugePageCount = srv.cfg.NrHugepages * len(srv.cfg.Engines)
		}
```
To cover the case where nr_hugepages has been set in the config file but no engines have been defined.

2021-12-28 01:37 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2021-12-28 07:58 UTC, johannlombardi approved these changes

2021-12-28 07:59 UTC, merged