DAOS-9667 test: update large dm tests to use tmpfs
daos-stack/daos pull request #7917
Opened 2022-01-18 22:09 UTC by daltonbohning

- Update large datamover tests to use tmpfs on a single client
  instead of shared NFS, since NFS is too slow.
- General test cleanup

Test-tag: dm_large_dir dm_large_file
Skip-unit-tests: true

Signed-off-by: Dalton Bohning <dalton.bohning@intel.com>

2022-01-18 22:11 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-01-19 16:03 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/data_mover_test_base.py:1](https://github.com/daos-stack/daos/blob/9dde7dbef7cbf77a63a5198a4487c95ea7790749/src/tests/ftest/util/data_mover_test_base.py#L1):
(pylint-too-many-lines) Too many lines in module (1300/1000)

[src/tests/ftest/util/data_mover_test_base.py:24](https://github.com/daos-stack/daos/blob/9dde7dbef7cbf77a63a5198a4487c95ea7790749/src/tests/ftest/util/data_mover_test_base.py#L24):
(pylint-too-many-public-methods) Too many public methods (21/20)

2022-01-20 06:51 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-7917/2/display/redirect

2022-01-20 16:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/data_mover_test_base.py:1](https://github.com/daos-stack/daos/blob/d0e69f5ea08ef8a52948e4a25a8ce3fa2e6812f7/src/tests/ftest/util/data_mover_test_base.py#L1):
(pylint-too-many-lines) Too many lines in module (1300/1000)

[src/tests/ftest/util/data_mover_test_base.py:24](https://github.com/daos-stack/daos/blob/d0e69f5ea08ef8a52948e4a25a8ce3fa2e6812f7/src/tests/ftest/util/data_mover_test_base.py#L24):
(pylint-too-many-public-methods) Too many public methods (21/20)

2022-01-20 22:21 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/data_mover_test_base.py:1](https://github.com/daos-stack/daos/blob/4ff813dc4196227567f7d5fa053f9bbd370d473d/src/tests/ftest/util/data_mover_test_base.py#L1):
(pylint-too-many-lines) Too many lines in module (1300/1000)

[src/tests/ftest/util/data_mover_test_base.py:24](https://github.com/daos-stack/daos/blob/4ff813dc4196227567f7d5fa053f9bbd370d473d/src/tests/ftest/util/data_mover_test_base.py#L24):
(pylint-too-many-public-methods) Too many public methods (21/20)

2022-01-21 16:50 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/data_mover_test_base.py:1](https://github.com/daos-stack/daos/blob/3905cdeca7001cbe2b56befe5fd949cbf0c70489/src/tests/ftest/util/data_mover_test_base.py#L1):
(pylint-too-many-lines) Too many lines in module (1300/1000)

[src/tests/ftest/util/data_mover_test_base.py:24](https://github.com/daos-stack/daos/blob/3905cdeca7001cbe2b56befe5fd949cbf0c70489/src/tests/ftest/util/data_mover_test_base.py#L24):
(pylint-too-many-public-methods) Too many public methods (21/20)

2022-01-24 17:51 UTC, shimizukko approved these changes

2022-01-27 15:57 UTC, saurabhtandan submitted a review, later dismissed
LGTM

2022-01-27 16:36 UTC, phender requested changes

2022-01-27 16:36 UTC, phender commented on src/tests/ftest/datamover/large_file.py
> +            pool, self.container[0])
Did this get missed?
```suggestion
            pool, cont1])
```

2022-01-27 17:31 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/data_mover_test_base.py:1](https://github.com/daos-stack/daos/blob/9d80cb5f689c017cc0efe1f68eb77ae4c031642c/src/tests/ftest/util/data_mover_test_base.py#L1):
(pylint-too-many-lines) Too many lines in module (1300/1000)

[src/tests/ftest/util/data_mover_test_base.py:24](https://github.com/daos-stack/daos/blob/9d80cb5f689c017cc0efe1f68eb77ae4c031642c/src/tests/ftest/util/data_mover_test_base.py#L24):
(pylint-too-many-public-methods) Too many public methods (21/20)

2022-01-27 17:33 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/data_mover_test_base.py:1](https://github.com/daos-stack/daos/blob/bbcdc91016d8c0ce8eeca78883c05673c84714f2/src/tests/ftest/util/data_mover_test_base.py#L1):
(pylint-too-many-lines) Too many lines in module (1300/1000)

[src/tests/ftest/util/data_mover_test_base.py:24](https://github.com/daos-stack/daos/blob/bbcdc91016d8c0ce8eeca78883c05673c84714f2/src/tests/ftest/util/data_mover_test_base.py#L24):
(pylint-too-many-public-methods) Too many public methods (21/20)

2022-01-27 18:42 UTC, phender approved these changes

2022-01-27 22:56 UTC, saurabhtandan approved these changes
LGTM

2022-01-28 10:02 UTC, shimizukko approved these changes

2022-01-28 22:15 UTC, merged