DAOS-9651 vos: Add VOS aggregation metrics
daos-stack/daos pull request #7925
Opened 2022-01-19 08:31 UTC by NiuYawei

Added per pool VOS aggregation metrics.

Signed-off-by: Niu Yawei <yawei.niu@intel.com>

2022-01-19 08:33 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-01-19 08:40 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7925/1/execution/node/370/log

2022-01-19 08:40 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7925/1/execution/node/329/log

2022-01-19 08:40 UTC, daosbuild1 commented
Test stage Build on Leap 15 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7925/1/execution/node/383/log

2022-01-19 08:42 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7925/1/execution/node/357/log

2022-01-19 08:42 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7925/1/execution/node/366/log

2022-01-19 08:56 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-7925/1/execution/node/394/log

2022-01-19 09:43 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-01-19 19:58 UTC, jolivier23 approved these changes

2022-01-20 05:35 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-7925/2/display/redirect

2022-01-20 05:36 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-7925/2/display/redirect

2022-01-21 02:01 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-01-24 05:38 UTC, Nasf-Fan approved these changes

2022-01-24 05:38 UTC, Nasf-Fan commented on src/vos/vos_internal.h
> + *			(1: entry is removed; 2: entry is invisible)
Better to define some MACRO for the return values.

2022-01-25 15:50 UTC, johannlombardi commented
IIRC, some other files must be edited when adding new metrics. @kjacque any thoughts?

2022-01-25 19:15 UTC, kjacque requested changes
It is also necessary to update `src/tests/ftest/util/telemetry_utils.py` with the new metrics. It would be wise to run with test-tag "telemetry" if you haven't already.

It looks like a number of the telemetry tests are already run with PRs. Unless they are being skipped, it's surprising to me that you wouldn't encounter failures with these changes. Have you verified your new metrics via both dmg telemetry metric list and daos_metrics?

2022-01-26 03:12 UTC, NiuYawei commented
> It is also necessary to update `src/tests/ftest/util/telemetry_utils.py` with the new metrics. It would be wise to run with test-tag "telemetry" if you haven't already.
> 
> It looks like a number of the telemetry tests are already run with PRs. Unless they are being skipped, it's surprising to me that you wouldn't encounter failures with these changes. Have you verified your new metrics via both dmg telemetry metric list and daos_metrics?

I think the 'src/tests/ftest/util/telemetry_utils.py' only needs be modified when you adding a new system-wide metric (like when I was adding metrics for scheduler, I added scheduler metrics in this file), for per-pool metrics, I think this file doesn't need be touched. (Of course, I think the test could be improved to verify per-pool metrics as well, but that should be done in a separate patch)

Sure, I verified both 'daos_metrics' and 'dmg telemetry metrics list/query'.

2022-01-26 21:38 UTC, kjacque commented
> I think the 'src/tests/ftest/util/telemetry_utils.py' only needs be modified when you adding a new system-wide metric (like when I was adding metrics for scheduler, I added scheduler metrics in this file), for per-pool metrics, I think this file doesn't need be touched. (Of course, I think the test could be improved to verify per-pool metrics as well, but that should be done in a separate patch)

You're right, seems like the metrics list test isn't getting the per-pool metrics. My bad. I think this is fine, then, as long as the metrics themselves look good coming out of dmg.

2022-01-26 21:38 UTC, kjacque approved these changes

2022-01-29 08:30 UTC, merged