DAOS-9310-test_2.0: BasicTxTest.test_tx_basics - pool connect timeout
daos-stack/daos pull request #7932
Opened 2022-01-19 17:32 UTC by dinghwah

Description: Cherrypick from master branch, increase timeout.

Test-tag: basictx
Skip-unit-tests: true
Skip-func-test-leap15: false
Skip-func-test-el7: false
Skip-func-test-el8: false
Test-repeat: 5
Signed-off-by: Ding Ho ding-hwa.ho@intel.com

2022-01-19 17:35 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-01-19 20:01 UTC, shimizukko approved these changes

2022-01-21 19:52 UTC, phender approved these changes

2022-01-30 22:17 UTC, sylviachanoiyee commented
@phender , please check if it is ok to land to 2.0 now or if we should wait till 2.0.1 is released. Something to bring up in rmg.

2022-02-04 22:36 UTC, phender requested changes
Due to an invalid commit message format, the https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-7932/1/testReport/FTEST_dtx/ skipped all 15 runs of test_tx_basics.  This PR needs to be re-run with a fixed commit message.

2022-02-04 22:45 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-06-02 15:51 UTC, phender commented
@dinghwah this PR needs to be run with a new commit message that includes the ticket number to ensure the skipped test_tx_basics test is run:
```
DAOS-9310 test: Updated commit message to run skipped tests

Test-tag: basictx
Skip-unit-tests: true
Skip-func-test-leap15: false
Skip-func-test-el7: false
Skip-func-test-el8: false
Test-repeat: 5

Signed-off-by: Ding Ho ding-hwa.ho@intel.com
```

2022-06-02 16:43 UTC, closed without merging