DAOS-9690 test: Add support to use label in tests for daos container …
daos-stack/daos pull request #7958
Opened 2022-01-21 20:47 UTC by shimizukko

…create/destroy

The goal is to convert the tests to use label to create and destroy
container. This makes it a complex PR, so I broke it down to 3 parts.
This is the first part that does the following:

1. Move LabelGenerator from test_utils_pool.py to test_utils_base.py
because both TestPool and TestContainer use it.
2. Add self.label in daos_utils_base.py -> class CreateSubCommand
to add --label support.
3. Add label parameter in daos_utils.py -> container_create() and
pass it in to _get_json_result()

Skip-unit-tests: true
Test-tag: pr
Signed-off-by: Makito Kano <makito.kano@intel.com>

2022-01-21 20:49 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/test_utils_pool.py:22](https://github.com/daos-stack/daos/blob/44e1175b00baf433b82059a1e8f7133057c51c6d/src/tests/ftest/util/test_utils_pool.py#L22):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

[src/tests/ftest/util/test_utils_pool.py:136](https://github.com/daos-stack/daos/blob/44e1175b00baf433b82059a1e8f7133057c51c6d/src/tests/ftest/util/test_utils_pool.py#L136):
(pylint-undefined-variable) Undefined variable 'LabelGenerator'

2022-01-21 20:58 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/test_utils_pool.py:22](https://github.com/daos-stack/daos/blob/01acd71610858369d1b957473f376ba5598d1ba1/src/tests/ftest/util/test_utils_pool.py#L22):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-01-24 17:15 UTC, daltonbohning approved these changes

2022-01-24 17:15 UTC, daltonbohning commented on src/tests/ftest/util/test_utils_base.py
> +    """Generates label used for pool."""
Minor
```suggestion
    """Generates labels used for pools and containers."""
```

2022-01-24 17:55 UTC, shimizukko commented on src/tests/ftest/util/test_utils_base.py
> +    """Generates label used for pool."""
Thanks. I'll fix it in the upcoming PR.

2022-01-27 16:29 UTC, phender requested changes
The `LabelGenerator` class is imported by 9 other non-skipped tests that were not run as part of this PR:

- nvme/pool_exclude.py:NvmePoolExclude.test_nvme_pool_excluded (weekly)
- osa/offline_extend.py:OSAOfflineExtend.test_osa_offline_extend (daily)
- osa/offline_extend.py:OSAOfflineExtend.test_osa_offline_extend_without_checksum (weekly)
- osa/offline_extend.py:OSAOfflineExtend.test_osa_offline_extend_multiple_pools (weekly)
- osa/offline_extend.py:OSAOfflineExtend.test_osa_offline_extend_after_snapshot (daily)
- osa/offline_parallel_test.py:OSAOfflineParallelTest.test_osa_offline_parallel_test (daily)
-osa/offline_parallel_test.py:OSAOfflineParallelTest.test_osa_offline_parallel_test_without_csum (weekly)
- osa/offline_parallel_test.py:OSAOfflineParallelTest.test_osa_offline_parallel_test_rank_boot (weekly)
- osa/offline_parallel_test.py:OSAOfflineParallelTest.test_osa_offline_parallel_test_oclass (weekly)

The import statement used by these tests may need to updated:
```
from test_utils_pool import TestPool, LabelGenerator
```
But at the very least these tests should be run as part of the PR to ensure that changes have no ill effects.

Note: the osa/online_reintegration.py test also uses this import, but all tests are currently skipped.

2022-01-27 17:22 UTC, daltonbohning commented
@phender python actually allows you to import from a file that imports from a file. So `from test_utils_pool import LabelGenerator` is valid, because `test_utils_pool` imports `LabelGenerator`. Otherwise, it seems the `LabelGenerator` class was just copy-pasted, with no real changes.
That being said, looking at this again... I do think it would be cleaner and safer to update these imports and run the tests just in case.

2022-02-04 11:51 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/test_utils_pool.py:22](https://github.com/daos-stack/daos/blob/29a0f0329de9a9fde6d607cdce47899167665c83/src/tests/ftest/util/test_utils_pool.py#L22):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-02-04 11:59 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/test_utils_pool.py:22](https://github.com/daos-stack/daos/blob/73b9613b1744dcf2b68e3129ecda343017580e30/src/tests/ftest/util/test_utils_pool.py#L22):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-02-06 13:10 UTC, shimizukko commented
@phender Thanks. I updated the import statements and ran those tests that directly import `LabelGenerator`.

2022-02-07 16:09 UTC, daltonbohning approved these changes

2022-02-08 21:46 UTC, phender approved these changes

2022-02-08 21:50 UTC, merged