DAOS-8526 test: Remove openmpi from test.py
daos-stack/daos pull request #8060
Opened 2022-02-02 22:29 UTC by mjean308

remove the avocado dependency on openmpi in TestWithoutServers

Signed-off-by: Maureen Jean <maureen.jean@intel.com>

2022-02-02 22:32 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8060/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:518](https://github.com/daos-stack/daos/blob/bf0420aad354f18b36f7caeb877b50724a69033b/src/tests/ftest/cart/util/cart_utils.py#L518):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/apricot/apricot/test.py:35](https://github.com/daos-stack/daos/blob/bf0420aad354f18b36f7caeb877b50724a69033b/src/tests/ftest/util/apricot/apricot/test.py#L35):
(pylint-unused-import) Unused load_mpi imported from env_modules

[src/tests/ftest/util/apricot/apricot/test.py:36](https://github.com/daos-stack/daos/blob/bf0420aad354f18b36f7caeb877b50724a69033b/src/tests/ftest/util/apricot/apricot/test.py#L36):
(pylint-unused-import) Unused find_executable imported from distutils.spawn

2022-02-02 22:32 UTC, daosbuild1 commented on src/tests/ftest/cart/util/cart_utils.py
> +from job_manage_utils import Orterun
(pylint-import-error) Unable to import 'job_manage_utils'

2022-02-02 22:32 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/1/execution/node/111/log

2022-02-03 00:10 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:518](https://github.com/daos-stack/daos/blob/d901fe9ddcc5944f85e7176d337782248731b2c7/src/tests/ftest/cart/util/cart_utils.py#L518):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/apricot/apricot/test.py:35](https://github.com/daos-stack/daos/blob/d901fe9ddcc5944f85e7176d337782248731b2c7/src/tests/ftest/util/apricot/apricot/test.py#L35):
(pylint-unused-import) Unused load_mpi imported from env_modules

[src/tests/ftest/util/apricot/apricot/test.py:36](https://github.com/daos-stack/daos/blob/d901fe9ddcc5944f85e7176d337782248731b2c7/src/tests/ftest/util/apricot/apricot/test.py#L36):
(pylint-unused-import) Unused find_executable imported from distutils.spawn

2022-02-03 14:21 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:520](https://github.com/daos-stack/daos/blob/c91902b1976f3d0b38b9118d019c90bf9d6ac405/src/tests/ftest/cart/util/cart_utils.py#L520):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/apricot/apricot/test.py:35](https://github.com/daos-stack/daos/blob/c91902b1976f3d0b38b9118d019c90bf9d6ac405/src/tests/ftest/util/apricot/apricot/test.py#L35):
(pylint-unused-import) Unused load_mpi imported from env_modules

[src/tests/ftest/util/apricot/apricot/test.py:36](https://github.com/daos-stack/daos/blob/c91902b1976f3d0b38b9118d019c90bf9d6ac405/src/tests/ftest/util/apricot/apricot/test.py#L36):
(pylint-unused-import) Unused find_executable imported from distutils.spawn

2022-02-03 16:29 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:514](https://github.com/daos-stack/daos/blob/ed8532a4f2ab29b3da26a0b168e8dc2cc5cc9773/src/tests/ftest/cart/util/cart_utils.py#L514):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/apricot/apricot/test.py:35](https://github.com/daos-stack/daos/blob/ed8532a4f2ab29b3da26a0b168e8dc2cc5cc9773/src/tests/ftest/util/apricot/apricot/test.py#L35):
(pylint-unused-import) Unused load_mpi imported from env_modules

[src/tests/ftest/util/apricot/apricot/test.py:36](https://github.com/daos-stack/daos/blob/ed8532a4f2ab29b3da26a0b168e8dc2cc5cc9773/src/tests/ftest/util/apricot/apricot/test.py#L36):
(pylint-unused-import) Unused find_executable imported from distutils.spawn

[src/tests/ftest/util/test_utils_pool.py:22](https://github.com/daos-stack/daos/blob/ed8532a4f2ab29b3da26a0b168e8dc2cc5cc9773/src/tests/ftest/util/test_utils_pool.py#L22):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

[src/tests/ftest/util/test_utils_pool.py:16](https://github.com/daos-stack/daos/blob/ed8532a4f2ab29b3da26a0b168e8dc2cc5cc9773/src/tests/ftest/util/test_utils_pool.py#L16):
(pylint-unused-import) Unused run_command imported from general_utils

[src/tests/ftest/util/test_utils_pool.py:17](https://github.com/daos-stack/daos/blob/ed8532a4f2ab29b3da26a0b168e8dc2cc5cc9773/src/tests/ftest/util/test_utils_pool.py#L17):
(pylint-unused-import) Unused load_mpi imported from env_modules

2022-02-03 17:38 UTC, daosbuild1 commented
Test stage Test CentOS 8.3.2011 RPMs completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/4/execution/node/1169/log

2022-02-03 17:39 UTC, daosbuild1 commented
Test stage Test CentOS 7 RPMs completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/4/execution/node/1188/log

2022-02-04 17:57 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/9e005f5bc7c0966c6597bd159b72f771139e0b6e/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/apricot/apricot/test.py:35](https://github.com/daos-stack/daos/blob/9e005f5bc7c0966c6597bd159b72f771139e0b6e/src/tests/ftest/util/apricot/apricot/test.py#L35):
(pylint-unused-import) Unused load_mpi imported from env_modules

[src/tests/ftest/util/apricot/apricot/test.py:36](https://github.com/daos-stack/daos/blob/9e005f5bc7c0966c6597bd159b72f771139e0b6e/src/tests/ftest/util/apricot/apricot/test.py#L36):
(pylint-unused-import) Unused find_executable imported from distutils.spawn

[src/tests/ftest/util/test_utils_pool.py:22](https://github.com/daos-stack/daos/blob/9e005f5bc7c0966c6597bd159b72f771139e0b6e/src/tests/ftest/util/test_utils_pool.py#L22):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

[src/tests/ftest/util/test_utils_pool.py:16](https://github.com/daos-stack/daos/blob/9e005f5bc7c0966c6597bd159b72f771139e0b6e/src/tests/ftest/util/test_utils_pool.py#L16):
(pylint-unused-import) Unused run_command imported from general_utils

[src/tests/ftest/util/test_utils_pool.py:17](https://github.com/daos-stack/daos/blob/9e005f5bc7c0966c6597bd159b72f771139e0b6e/src/tests/ftest/util/test_utils_pool.py#L17):
(pylint-unused-import) Unused load_mpi imported from env_modules

2022-02-05 14:56 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/aaece767a0d5dc62cfeee890f3b7caf9d94fd8e3/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/apricot/apricot/test.py:35](https://github.com/daos-stack/daos/blob/aaece767a0d5dc62cfeee890f3b7caf9d94fd8e3/src/tests/ftest/util/apricot/apricot/test.py#L35):
(pylint-unused-import) Unused load_mpi imported from env_modules

[src/tests/ftest/util/apricot/apricot/test.py:36](https://github.com/daos-stack/daos/blob/aaece767a0d5dc62cfeee890f3b7caf9d94fd8e3/src/tests/ftest/util/apricot/apricot/test.py#L36):
(pylint-unused-import) Unused find_executable imported from distutils.spawn

[src/tests/ftest/util/test_utils_pool.py:22](https://github.com/daos-stack/daos/blob/aaece767a0d5dc62cfeee890f3b7caf9d94fd8e3/src/tests/ftest/util/test_utils_pool.py#L22):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

[src/tests/ftest/util/test_utils_pool.py:16](https://github.com/daos-stack/daos/blob/aaece767a0d5dc62cfeee890f3b7caf9d94fd8e3/src/tests/ftest/util/test_utils_pool.py#L16):
(pylint-unused-import) Unused run_command imported from general_utils

[src/tests/ftest/util/test_utils_pool.py:17](https://github.com/daos-stack/daos/blob/aaece767a0d5dc62cfeee890f3b7caf9d94fd8e3/src/tests/ftest/util/test_utils_pool.py#L17):
(pylint-unused-import) Unused load_mpi imported from env_modules

2022-02-07 17:29 UTC, shimizukko submitted a review, later dismissed

2022-02-09 17:56 UTC, saurabhtandan approved these changes
LGTM

2022-02-09 18:57 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/0da631392acb4a62d01f8f570b6dc5ed7adb9c57/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/apricot/apricot/test.py:35](https://github.com/daos-stack/daos/blob/0da631392acb4a62d01f8f570b6dc5ed7adb9c57/src/tests/ftest/util/apricot/apricot/test.py#L35):
(pylint-unused-import) Unused load_mpi imported from env_modules

[src/tests/ftest/util/apricot/apricot/test.py:36](https://github.com/daos-stack/daos/blob/0da631392acb4a62d01f8f570b6dc5ed7adb9c57/src/tests/ftest/util/apricot/apricot/test.py#L36):
(pylint-unused-import) Unused find_executable imported from distutils.spawn

[src/tests/ftest/util/test_utils_pool.py:22](https://github.com/daos-stack/daos/blob/0da631392acb4a62d01f8f570b6dc5ed7adb9c57/src/tests/ftest/util/test_utils_pool.py#L22):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

[src/tests/ftest/util/test_utils_pool.py:16](https://github.com/daos-stack/daos/blob/0da631392acb4a62d01f8f570b6dc5ed7adb9c57/src/tests/ftest/util/test_utils_pool.py#L16):
(pylint-unused-import) Unused run_command imported from general_utils

[src/tests/ftest/util/test_utils_pool.py:17](https://github.com/daos-stack/daos/blob/0da631392acb4a62d01f8f570b6dc5ed7adb9c57/src/tests/ftest/util/test_utils_pool.py#L17):
(pylint-unused-import) Unused load_mpi imported from env_modules

2022-02-10 19:50 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/27d33273822941632ab16b3a72492dc0760a0e19/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/apricot/apricot/test.py:35](https://github.com/daos-stack/daos/blob/27d33273822941632ab16b3a72492dc0760a0e19/src/tests/ftest/util/apricot/apricot/test.py#L35):
(pylint-unused-import) Unused load_mpi imported from env_modules

[src/tests/ftest/util/apricot/apricot/test.py:36](https://github.com/daos-stack/daos/blob/27d33273822941632ab16b3a72492dc0760a0e19/src/tests/ftest/util/apricot/apricot/test.py#L36):
(pylint-unused-import) Unused find_executable imported from distutils.spawn

[src/tests/ftest/util/test_utils_pool.py:22](https://github.com/daos-stack/daos/blob/27d33273822941632ab16b3a72492dc0760a0e19/src/tests/ftest/util/test_utils_pool.py#L22):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

[src/tests/ftest/util/test_utils_pool.py:16](https://github.com/daos-stack/daos/blob/27d33273822941632ab16b3a72492dc0760a0e19/src/tests/ftest/util/test_utils_pool.py#L16):
(pylint-unused-import) Unused run_command imported from general_utils

[src/tests/ftest/util/test_utils_pool.py:17](https://github.com/daos-stack/daos/blob/27d33273822941632ab16b3a72492dc0760a0e19/src/tests/ftest/util/test_utils_pool.py#L17):
(pylint-unused-import) Unused load_mpi imported from env_modules

2022-02-11 14:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/a7fbaf86b63d271c55adb81b5d68d28e966760f7/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/apricot/apricot/test.py:35](https://github.com/daos-stack/daos/blob/a7fbaf86b63d271c55adb81b5d68d28e966760f7/src/tests/ftest/util/apricot/apricot/test.py#L35):
(pylint-unused-import) Unused load_mpi imported from env_modules

[src/tests/ftest/util/apricot/apricot/test.py:36](https://github.com/daos-stack/daos/blob/a7fbaf86b63d271c55adb81b5d68d28e966760f7/src/tests/ftest/util/apricot/apricot/test.py#L36):
(pylint-unused-import) Unused find_executable imported from distutils.spawn

[src/tests/ftest/util/test_utils_pool.py:22](https://github.com/daos-stack/daos/blob/a7fbaf86b63d271c55adb81b5d68d28e966760f7/src/tests/ftest/util/test_utils_pool.py#L22):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

[src/tests/ftest/util/test_utils_pool.py:16](https://github.com/daos-stack/daos/blob/a7fbaf86b63d271c55adb81b5d68d28e966760f7/src/tests/ftest/util/test_utils_pool.py#L16):
(pylint-unused-import) Unused run_command imported from general_utils

[src/tests/ftest/util/test_utils_pool.py:17](https://github.com/daos-stack/daos/blob/a7fbaf86b63d271c55adb81b5d68d28e966760f7/src/tests/ftest/util/test_utils_pool.py#L17):
(pylint-unused-import) Unused load_mpi imported from env_modules

2022-02-16 14:05 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/6d92c1c838108be024d5ff8c6ac64624a74a4ea0/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/apricot/apricot/test.py:35](https://github.com/daos-stack/daos/blob/6d92c1c838108be024d5ff8c6ac64624a74a4ea0/src/tests/ftest/util/apricot/apricot/test.py#L35):
(pylint-unused-import) Unused load_mpi imported from env_modules

[src/tests/ftest/util/apricot/apricot/test.py:36](https://github.com/daos-stack/daos/blob/6d92c1c838108be024d5ff8c6ac64624a74a4ea0/src/tests/ftest/util/apricot/apricot/test.py#L36):
(pylint-unused-import) Unused find_executable imported from distutils.spawn

[src/tests/ftest/util/test_utils_pool.py:22](https://github.com/daos-stack/daos/blob/6d92c1c838108be024d5ff8c6ac64624a74a4ea0/src/tests/ftest/util/test_utils_pool.py#L22):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

[src/tests/ftest/util/test_utils_pool.py:16](https://github.com/daos-stack/daos/blob/6d92c1c838108be024d5ff8c6ac64624a74a4ea0/src/tests/ftest/util/test_utils_pool.py#L16):
(pylint-unused-import) Unused run_command imported from general_utils

[src/tests/ftest/util/test_utils_pool.py:17](https://github.com/daos-stack/daos/blob/6d92c1c838108be024d5ff8c6ac64624a74a4ea0/src/tests/ftest/util/test_utils_pool.py#L17):
(pylint-unused-import) Unused load_mpi imported from env_modules

2022-02-16 19:10 UTC, daosbuild1 commented
Test stage Functional on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8060/12/display/redirect

2022-02-16 19:15 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8060/13/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/62f10c0e035ad69c0e8c4da545b88edaa7bcaf9d/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/62f10c0e035ad69c0e8c4da545b88edaa7bcaf9d/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/62f10c0e035ad69c0e8c4da545b88edaa7bcaf9d/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/62f10c0e035ad69c0e8c4da545b88edaa7bcaf9d/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/62f10c0e035ad69c0e8c4da545b88edaa7bcaf9d/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/62f10c0e035ad69c0e8c4da545b88edaa7bcaf9d/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-02-16 19:15 UTC, daosbuild1 commented on src/tests/ftest/util/general_utils.py
> +    return (int(result.exit_status) == 0)
(pylint-superfluous-parens) Unnecessary parens after 'return' keyword

2022-02-16 19:15 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/13/execution/node/132/log

2022-02-17 01:20 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/33ee96370a56b19062a2cfecea8d51ccafba1d6a/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/launch.py:47](https://github.com/daos-stack/daos/blob/33ee96370a56b19062a2cfecea8d51ccafba1d6a/src/tests/ftest/launch.py#L47):
(pylint-useless-object-inheritance) Class 'TemporaryDirectory' inherits from object, can be safely removed from bases in python3

[src/tests/ftest/launch.py:93](https://github.com/daos-stack/daos/blob/33ee96370a56b19062a2cfecea8d51ccafba1d6a/src/tests/ftest/launch.py#L93):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/33ee96370a56b19062a2cfecea8d51ccafba1d6a/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-02-17 01:24 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/5632d9cbee6f1fcba109e9810e74820eeb79a5ff/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/launch.py:47](https://github.com/daos-stack/daos/blob/5632d9cbee6f1fcba109e9810e74820eeb79a5ff/src/tests/ftest/launch.py#L47):
(pylint-useless-object-inheritance) Class 'TemporaryDirectory' inherits from object, can be safely removed from bases in python3

[src/tests/ftest/launch.py:93](https://github.com/daos-stack/daos/blob/5632d9cbee6f1fcba109e9810e74820eeb79a5ff/src/tests/ftest/launch.py#L93):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/5632d9cbee6f1fcba109e9810e74820eeb79a5ff/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-02-17 17:55 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/6e32bef68075d87464b45cd815763350956e2a42/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/launch.py:47](https://github.com/daos-stack/daos/blob/6e32bef68075d87464b45cd815763350956e2a42/src/tests/ftest/launch.py#L47):
(pylint-useless-object-inheritance) Class 'TemporaryDirectory' inherits from object, can be safely removed from bases in python3

[src/tests/ftest/launch.py:93](https://github.com/daos-stack/daos/blob/6e32bef68075d87464b45cd815763350956e2a42/src/tests/ftest/launch.py#L93):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/6e32bef68075d87464b45cd815763350956e2a42/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-02-20 13:44 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/b042e2b4faef4df4e46d83869209c56b6d4f5305/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/launch.py:47](https://github.com/daos-stack/daos/blob/b042e2b4faef4df4e46d83869209c56b6d4f5305/src/tests/ftest/launch.py#L47):
(pylint-useless-object-inheritance) Class 'TemporaryDirectory' inherits from object, can be safely removed from bases in python3

[src/tests/ftest/launch.py:93](https://github.com/daos-stack/daos/blob/b042e2b4faef4df4e46d83869209c56b6d4f5305/src/tests/ftest/launch.py#L93):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/b042e2b4faef4df4e46d83869209c56b6d4f5305/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-02-20 13:46 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/17/execution/node/344/log

2022-02-20 13:54 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/17/execution/node/403/log

2022-02-20 13:55 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/17/execution/node/358/log

2022-02-20 13:55 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/17/execution/node/349/log

2022-02-23 22:31 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/19/execution/node/326/log

2022-02-23 22:43 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/19/execution/node/369/log

2022-02-23 22:46 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/19/execution/node/357/log

2022-02-23 22:49 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/19/execution/node/350/log

2022-02-24 01:15 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/cfe908d5156fcda522c105037292ddb64771e148/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/launch.py:47](https://github.com/daos-stack/daos/blob/cfe908d5156fcda522c105037292ddb64771e148/src/tests/ftest/launch.py#L47):
(pylint-useless-object-inheritance) Class 'TemporaryDirectory' inherits from object, can be safely removed from bases in python3

[src/tests/ftest/launch.py:93](https://github.com/daos-stack/daos/blob/cfe908d5156fcda522c105037292ddb64771e148/src/tests/ftest/launch.py#L93):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/cfe908d5156fcda522c105037292ddb64771e148/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:320](https://github.com/daos-stack/daos/blob/cfe908d5156fcda522c105037292ddb64771e148/src/tests/ftest/util/ior_test_base.py#L320):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/cfe908d5156fcda522c105037292ddb64771e148/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-02-27 15:53 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/e24ff86b0b405bfb33fb04b1fe8777391e843962/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/launch.py:47](https://github.com/daos-stack/daos/blob/e24ff86b0b405bfb33fb04b1fe8777391e843962/src/tests/ftest/launch.py#L47):
(pylint-useless-object-inheritance) Class 'TemporaryDirectory' inherits from object, can be safely removed from bases in python3

[src/tests/ftest/launch.py:93](https://github.com/daos-stack/daos/blob/e24ff86b0b405bfb33fb04b1fe8777391e843962/src/tests/ftest/launch.py#L93):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/e24ff86b0b405bfb33fb04b1fe8777391e843962/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:320](https://github.com/daos-stack/daos/blob/e24ff86b0b405bfb33fb04b1fe8777391e843962/src/tests/ftest/util/ior_test_base.py#L320):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/e24ff86b0b405bfb33fb04b1fe8777391e843962/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-02-28 22:10 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/c1df949cac6e9993a075433ad31c47b6117fcad6/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/launch.py:47](https://github.com/daos-stack/daos/blob/c1df949cac6e9993a075433ad31c47b6117fcad6/src/tests/ftest/launch.py#L47):
(pylint-useless-object-inheritance) Class 'TemporaryDirectory' inherits from object, can be safely removed from bases in python3

[src/tests/ftest/launch.py:93](https://github.com/daos-stack/daos/blob/c1df949cac6e9993a075433ad31c47b6117fcad6/src/tests/ftest/launch.py#L93):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/c1df949cac6e9993a075433ad31c47b6117fcad6/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:320](https://github.com/daos-stack/daos/blob/c1df949cac6e9993a075433ad31c47b6117fcad6/src/tests/ftest/util/ior_test_base.py#L320):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/c1df949cac6e9993a075433ad31c47b6117fcad6/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-01 23:23 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8060/25/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/ior_test_base.py:311](https://github.com/daos-stack/daos/blob/a96a56e0f09ba6391177426295aa10c306a79f39/src/tests/ftest/util/ior_test_base.py#L311):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/a96a56e0f09ba6391177426295aa10c306a79f39/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/a96a56e0f09ba6391177426295aa10c306a79f39/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/a96a56e0f09ba6391177426295aa10c306a79f39/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/a96a56e0f09ba6391177426295aa10c306a79f39/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/a96a56e0f09ba6391177426295aa10c306a79f39/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/a96a56e0f09ba6391177426295aa10c306a79f39/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/macsio_test_base.py:45](https://github.com/daos-stack/daos/blob/a96a56e0f09ba6391177426295aa10c306a79f39/src/tests/ftest/util/macsio_test_base.py#L45):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/a96a56e0f09ba6391177426295aa10c306a79f39/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-01 23:23 UTC, daosbuild1 commented on src/tests/ftest/util/ior_test_base.py
> +
(style)  trailing whitespace
(pylint-trailing-whitespace) Trailing whitespace

2022-03-01 23:23 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/25/execution/node/98/log

2022-03-01 23:33 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:519](https://github.com/daos-stack/daos/blob/c7c02bfa3aa1e345363d6d30ab8da3e97d543a61/src/tests/ftest/cart/util/cart_utils.py#L519):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/c7c02bfa3aa1e345363d6d30ab8da3e97d543a61/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/c7c02bfa3aa1e345363d6d30ab8da3e97d543a61/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/c7c02bfa3aa1e345363d6d30ab8da3e97d543a61/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/c7c02bfa3aa1e345363d6d30ab8da3e97d543a61/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/c7c02bfa3aa1e345363d6d30ab8da3e97d543a61/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:311](https://github.com/daos-stack/daos/blob/c7c02bfa3aa1e345363d6d30ab8da3e97d543a61/src/tests/ftest/util/ior_test_base.py#L311):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/macsio_test_base.py:45](https://github.com/daos-stack/daos/blob/c7c02bfa3aa1e345363d6d30ab8da3e97d543a61/src/tests/ftest/util/macsio_test_base.py#L45):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/c7c02bfa3aa1e345363d6d30ab8da3e97d543a61/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-03 06:23 UTC, daosbuild1 commented
Test stage Functional Hardware Small completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/27/execution/node/1192/log

2022-03-03 19:43 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:520](https://github.com/daos-stack/daos/blob/99e99b1b0127b6c5654ad3b20aaa82e91abe0596/src/tests/ftest/cart/util/cart_utils.py#L520):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/99e99b1b0127b6c5654ad3b20aaa82e91abe0596/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/99e99b1b0127b6c5654ad3b20aaa82e91abe0596/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/99e99b1b0127b6c5654ad3b20aaa82e91abe0596/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/99e99b1b0127b6c5654ad3b20aaa82e91abe0596/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/99e99b1b0127b6c5654ad3b20aaa82e91abe0596/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:311](https://github.com/daos-stack/daos/blob/99e99b1b0127b6c5654ad3b20aaa82e91abe0596/src/tests/ftest/util/ior_test_base.py#L311):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/macsio_test_base.py:45](https://github.com/daos-stack/daos/blob/99e99b1b0127b6c5654ad3b20aaa82e91abe0596/src/tests/ftest/util/macsio_test_base.py#L45):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/99e99b1b0127b6c5654ad3b20aaa82e91abe0596/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-04 14:16 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:520](https://github.com/daos-stack/daos/blob/d1ce82d0bcd7922ce0f6fcb0f7ca5a6da1fe4ea6/src/tests/ftest/cart/util/cart_utils.py#L520):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/d1ce82d0bcd7922ce0f6fcb0f7ca5a6da1fe4ea6/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/d1ce82d0bcd7922ce0f6fcb0f7ca5a6da1fe4ea6/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/d1ce82d0bcd7922ce0f6fcb0f7ca5a6da1fe4ea6/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/d1ce82d0bcd7922ce0f6fcb0f7ca5a6da1fe4ea6/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/d1ce82d0bcd7922ce0f6fcb0f7ca5a6da1fe4ea6/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:311](https://github.com/daos-stack/daos/blob/d1ce82d0bcd7922ce0f6fcb0f7ca5a6da1fe4ea6/src/tests/ftest/util/ior_test_base.py#L311):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/macsio_test_base.py:45](https://github.com/daos-stack/daos/blob/d1ce82d0bcd7922ce0f6fcb0f7ca5a6da1fe4ea6/src/tests/ftest/util/macsio_test_base.py#L45):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/d1ce82d0bcd7922ce0f6fcb0f7ca5a6da1fe4ea6/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-06 18:20 UTC, daosbuild1 commented
Test stage Functional Hardware Small completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/29/execution/node/1192/log

2022-03-07 04:15 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/29/execution/node/1294/log

2022-03-07 17:41 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:520](https://github.com/daos-stack/daos/blob/b0f1d614e5a962db76cd420e6c71d25b6ef04053/src/tests/ftest/cart/util/cart_utils.py#L520):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/b0f1d614e5a962db76cd420e6c71d25b6ef04053/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/b0f1d614e5a962db76cd420e6c71d25b6ef04053/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/b0f1d614e5a962db76cd420e6c71d25b6ef04053/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/b0f1d614e5a962db76cd420e6c71d25b6ef04053/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/b0f1d614e5a962db76cd420e6c71d25b6ef04053/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:311](https://github.com/daos-stack/daos/blob/b0f1d614e5a962db76cd420e6c71d25b6ef04053/src/tests/ftest/util/ior_test_base.py#L311):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/macsio_test_base.py:45](https://github.com/daos-stack/daos/blob/b0f1d614e5a962db76cd420e6c71d25b6ef04053/src/tests/ftest/util/macsio_test_base.py#L45):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/b0f1d614e5a962db76cd420e6c71d25b6ef04053/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-09 18:39 UTC, shimizukko submitted a review, later dismissed

2022-03-09 20:19 UTC, phender requested changes
In addition the following tests should be run to verify code changes:
- src/tests/ftest/daos_perf/large.py
- src/tests/ftest/daos_perf/small.py
- src/tests/ftest/daos_racer/parallel.py
- src/tests/ftest/daos_vol/bigio.py
- src/tests/ftest/nvme/enospace.py
- src/tests/ftest/nvme/fragmentation.py
- src/tests/ftest/nvme/pool_capacity.py
- src/tests/ftest/server/metadata.py

2022-03-09 20:19 UTC, phender commented on src/tests/ftest/util/job_manager_utils.py
> +        self.path = path
This is already defined as `self._path` in `CommandWithParameters.__init__()`.  Please remove.
```suggestion
```

2022-03-09 20:19 UTC, phender commented on src/tests/ftest/util/job_manager_utils.py
> +        return os.path.join(os.path.split(self.path)[0], 'lib')
```suggestion
        return os.path.join(os.path.split(self._path)[0], 'lib')
```

2022-03-09 20:19 UTC, phender commented on src/tests/ftest/util/job_manager_utils.py
> +        if not self.path:
```suggestion
        if not self._path:
```

2022-03-09 20:19 UTC, phender commented on src/tests/ftest/util/job_manager_utils.py
> +            raise CommandFailure("MPI path is not defined")
Given the different paths we have in play here, might I suggest a slightly more clear error message:
```suggestion
            raise CommandFailure("Unable to obtain MPI library path: Full path for {} undefined!".format(self.command))
```

2022-03-09 20:19 UTC, phender commented on src/tests/ftest/util/job_manager_utils.py
> +        Returns: path to mpi lib
```suggestion
        Returns:
            str: mpi library path

```

2022-03-09 20:19 UTC, phender commented on src/tests/ftest/util/job_manager_utils.py
> +    def get_lib_path(self):
Should this be moved to the common `JobManager` class? Or maybe a `class MpiJobManager(JobManager):` class that then `Mpirun` and `Orterun` inherit?

2022-03-09 20:19 UTC, phender commented on src/tests/ftest/util/job_manager_utils.py
> +    def get_lib_path(self):
Same edits from `Orterun.get_lib_path()` would apply here unless its made common.

2022-03-09 22:39 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8060/32/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:520](https://github.com/daos-stack/daos/blob/b87cc9f82b947dde011080bb41350d7edba83576/src/tests/ftest/cart/util/cart_utils.py#L520):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/b87cc9f82b947dde011080bb41350d7edba83576/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/b87cc9f82b947dde011080bb41350d7edba83576/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/b87cc9f82b947dde011080bb41350d7edba83576/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/b87cc9f82b947dde011080bb41350d7edba83576/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/b87cc9f82b947dde011080bb41350d7edba83576/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:315](https://github.com/daos-stack/daos/blob/b87cc9f82b947dde011080bb41350d7edba83576/src/tests/ftest/util/ior_test_base.py#L315):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/job_manager_utils.py:380](https://github.com/daos-stack/daos/blob/b87cc9f82b947dde011080bb41350d7edba83576/src/tests/ftest/util/job_manager_utils.py#L380):
(pylint-undefined-variable) Undefined variable 'load_mpi'

[src/tests/ftest/util/macsio_test_base.py:45](https://github.com/daos-stack/daos/blob/b87cc9f82b947dde011080bb41350d7edba83576/src/tests/ftest/util/macsio_test_base.py#L45):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/b87cc9f82b947dde011080bb41350d7edba83576/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-09 22:39 UTC, daosbuild1 commented on src/tests/ftest/util/job_manager_utils.py
> +        if not load_mpi(mpi_type):
(pylint-undefined-variable) Undefined variable 'load_mpi'

2022-03-09 22:39 UTC, daosbuild1 commented on src/tests/ftest/util/job_manager_utils.py
> +        if not load_mpi(mpi_type):
(pylint-undefined-variable) Undefined variable 'load_mpi'

2022-03-09 22:39 UTC, daosbuild1 commented on src/tests/ftest/util/job_manager_utils.py
> +        if not load_mpi(self.mpi_type):
(pylint-undefined-variable) Undefined variable 'load_mpi'

2022-03-09 22:39 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/32/execution/node/112/log

2022-03-10 00:16 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:520](https://github.com/daos-stack/daos/blob/9f412c8a1696731514a5a8284cc4b8c5b4f918bf/src/tests/ftest/cart/util/cart_utils.py#L520):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/9f412c8a1696731514a5a8284cc4b8c5b4f918bf/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/9f412c8a1696731514a5a8284cc4b8c5b4f918bf/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/9f412c8a1696731514a5a8284cc4b8c5b4f918bf/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/9f412c8a1696731514a5a8284cc4b8c5b4f918bf/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/9f412c8a1696731514a5a8284cc4b8c5b4f918bf/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:315](https://github.com/daos-stack/daos/blob/9f412c8a1696731514a5a8284cc4b8c5b4f918bf/src/tests/ftest/util/ior_test_base.py#L315):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/macsio_test_base.py:45](https://github.com/daos-stack/daos/blob/9f412c8a1696731514a5a8284cc4b8c5b4f918bf/src/tests/ftest/util/macsio_test_base.py#L45):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/9f412c8a1696731514a5a8284cc4b8c5b4f918bf/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-10 14:21 UTC, shimizukko approved these changes

2022-03-10 21:31 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8060/34/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:520](https://github.com/daos-stack/daos/blob/fffc8724ca420972fce2db696c7affb2c1087280/src/tests/ftest/cart/util/cart_utils.py#L520):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/fffc8724ca420972fce2db696c7affb2c1087280/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/fffc8724ca420972fce2db696c7affb2c1087280/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/fffc8724ca420972fce2db696c7affb2c1087280/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/fffc8724ca420972fce2db696c7affb2c1087280/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/fffc8724ca420972fce2db696c7affb2c1087280/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:315](https://github.com/daos-stack/daos/blob/fffc8724ca420972fce2db696c7affb2c1087280/src/tests/ftest/util/ior_test_base.py#L315):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/macsio_test_base.py:45](https://github.com/daos-stack/daos/blob/fffc8724ca420972fce2db696c7affb2c1087280/src/tests/ftest/util/macsio_test_base.py#L45):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/mpio_test_base.py:9](https://github.com/daos-stack/daos/blob/fffc8724ca420972fce2db696c7affb2c1087280/src/tests/ftest/util/mpio_test_base.py#L9):
(pylint-unused-import) Unused import os

[src/tests/ftest/util/mpio_utils.py:72](https://github.com/daos-stack/daos/blob/fffc8724ca420972fce2db696c7affb2c1087280/src/tests/ftest/util/mpio_utils.py#L72):
(pylint-use-a-generator) Use a generator instead 'all(os.path.join(exe) for exe in executables[test_name])'

[src/tests/ftest/util/mpio_utils.py:19](https://github.com/daos-stack/daos/blob/fffc8724ca420972fce2db696c7affb2c1087280/src/tests/ftest/util/mpio_utils.py#L19):
(pylint-too-few-public-methods) Too few public methods (1/2)

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/fffc8724ca420972fce2db696c7affb2c1087280/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-10 21:31 UTC, daosbuild1 commented on src/tests/ftest/util/mpio_utils.py
> +                self.fail(
(pylint-no-member) Instance of 'MpioUtils' has no 'fail' member

2022-03-10 21:31 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/34/execution/node/113/log

2022-03-10 21:44 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8060/35/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:520](https://github.com/daos-stack/daos/blob/f73ce8863032c5f141d8dcc5a2424e85ff4c6166/src/tests/ftest/cart/util/cart_utils.py#L520):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/f73ce8863032c5f141d8dcc5a2424e85ff4c6166/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/apricot/apricot/test.py:24](https://github.com/daos-stack/daos/blob/f73ce8863032c5f141d8dcc5a2424e85ff4c6166/src/tests/ftest/util/apricot/apricot/test.py#L24):
(pylint-unused-import) Unused find_executable imported from distutils.spawn

[src/tests/ftest/util/apricot/apricot/test.py:26](https://github.com/daos-stack/daos/blob/f73ce8863032c5f141d8dcc5a2424e85ff4c6166/src/tests/ftest/util/apricot/apricot/test.py#L26):
(pylint-unused-import) Unused load_mpi imported from env_modules

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/f73ce8863032c5f141d8dcc5a2424e85ff4c6166/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/f73ce8863032c5f141d8dcc5a2424e85ff4c6166/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/f73ce8863032c5f141d8dcc5a2424e85ff4c6166/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/f73ce8863032c5f141d8dcc5a2424e85ff4c6166/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:315](https://github.com/daos-stack/daos/blob/f73ce8863032c5f141d8dcc5a2424e85ff4c6166/src/tests/ftest/util/ior_test_base.py#L315):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/macsio_test_base.py:45](https://github.com/daos-stack/daos/blob/f73ce8863032c5f141d8dcc5a2424e85ff4c6166/src/tests/ftest/util/macsio_test_base.py#L45):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/mpio_test_base.py:9](https://github.com/daos-stack/daos/blob/f73ce8863032c5f141d8dcc5a2424e85ff4c6166/src/tests/ftest/util/mpio_test_base.py#L9):
(pylint-unused-import) Unused import os

[src/tests/ftest/util/mpio_utils.py:72](https://github.com/daos-stack/daos/blob/f73ce8863032c5f141d8dcc5a2424e85ff4c6166/src/tests/ftest/util/mpio_utils.py#L72):
(pylint-use-a-generator) Use a generator instead 'all(os.path.join(exe) for exe in executables[test_name])'

[src/tests/ftest/util/mpio_utils.py:19](https://github.com/daos-stack/daos/blob/f73ce8863032c5f141d8dcc5a2424e85ff4c6166/src/tests/ftest/util/mpio_utils.py#L19):
(pylint-too-few-public-methods) Too few public methods (1/2)

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/f73ce8863032c5f141d8dcc5a2424e85ff4c6166/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-10 21:44 UTC, daosbuild1 commented on src/tests/ftest/util/mpio_utils.py
> +    def run_mpiio_tests(self, hostlist, pool_uuid, test_repo,
(pylint-no-self-use) Method could be a function

2022-03-10 21:45 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/35/execution/node/113/log

2022-03-11 00:09 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8060/36/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:520](https://github.com/daos-stack/daos/blob/8a2f520bf6e03eb9eb9a2d21a1718f6578e5dea9/src/tests/ftest/cart/util/cart_utils.py#L520):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/8a2f520bf6e03eb9eb9a2d21a1718f6578e5dea9/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/apricot/apricot/test.py:24](https://github.com/daos-stack/daos/blob/8a2f520bf6e03eb9eb9a2d21a1718f6578e5dea9/src/tests/ftest/util/apricot/apricot/test.py#L24):
(pylint-unused-import) Unused find_executable imported from distutils.spawn

[src/tests/ftest/util/apricot/apricot/test.py:26](https://github.com/daos-stack/daos/blob/8a2f520bf6e03eb9eb9a2d21a1718f6578e5dea9/src/tests/ftest/util/apricot/apricot/test.py#L26):
(pylint-unused-import) Unused load_mpi imported from env_modules

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/8a2f520bf6e03eb9eb9a2d21a1718f6578e5dea9/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/8a2f520bf6e03eb9eb9a2d21a1718f6578e5dea9/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/8a2f520bf6e03eb9eb9a2d21a1718f6578e5dea9/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/8a2f520bf6e03eb9eb9a2d21a1718f6578e5dea9/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:315](https://github.com/daos-stack/daos/blob/8a2f520bf6e03eb9eb9a2d21a1718f6578e5dea9/src/tests/ftest/util/ior_test_base.py#L315):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/macsio_test_base.py:45](https://github.com/daos-stack/daos/blob/8a2f520bf6e03eb9eb9a2d21a1718f6578e5dea9/src/tests/ftest/util/macsio_test_base.py#L45):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/8a2f520bf6e03eb9eb9a2d21a1718f6578e5dea9/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-11 00:09 UTC, daosbuild1 commented on src/tests/ftest/mpiio/llnl_mpi4py.py
> +        manager = get_job_manager(self, mpi_type="mpich")
(pylint-undefined-variable) Undefined variable 'get_job_manager'

2022-03-11 00:09 UTC, daosbuild1 commented on src/tests/ftest/mpiio/llnl_mpi4py.py
> +        self.run_test(manager, test_repo, "llnl")
(pylint-too-many-function-args) Too many positional arguments for method call

2022-03-11 00:09 UTC, daosbuild1 commented on src/tests/ftest/util/mpiio_test_base.py
> +            self.fail("Unknown mpiio test name: %s", test_name)
(pylint-too-many-function-args) Too many positional arguments for method call

2022-03-11 00:09 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/36/execution/node/98/log

2022-03-11 00:20 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8060/37/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:520](https://github.com/daos-stack/daos/blob/2cd0af5c174c9c33b7125735d632ff4f0d5fa0c2/src/tests/ftest/cart/util/cart_utils.py#L520):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/2cd0af5c174c9c33b7125735d632ff4f0d5fa0c2/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/2cd0af5c174c9c33b7125735d632ff4f0d5fa0c2/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/2cd0af5c174c9c33b7125735d632ff4f0d5fa0c2/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/2cd0af5c174c9c33b7125735d632ff4f0d5fa0c2/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/2cd0af5c174c9c33b7125735d632ff4f0d5fa0c2/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:315](https://github.com/daos-stack/daos/blob/2cd0af5c174c9c33b7125735d632ff4f0d5fa0c2/src/tests/ftest/util/ior_test_base.py#L315):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/macsio_test_base.py:45](https://github.com/daos-stack/daos/blob/2cd0af5c174c9c33b7125735d632ff4f0d5fa0c2/src/tests/ftest/util/macsio_test_base.py#L45):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/2cd0af5c174c9c33b7125735d632ff4f0d5fa0c2/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-11 00:20 UTC, daosbuild1 commented on src/tests/ftest/util/mpiio_test_base.py
> +            self.fail("Unknown mpiio test name: %s", test_name)
(pylint-too-many-function-args) Too many positional arguments for method call

2022-03-11 00:20 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/37/execution/node/113/log

2022-03-11 00:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:520](https://github.com/daos-stack/daos/blob/4eeb4e290e9e2eef9094b0acadc8805c7d67ada2/src/tests/ftest/cart/util/cart_utils.py#L520):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/4eeb4e290e9e2eef9094b0acadc8805c7d67ada2/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/4eeb4e290e9e2eef9094b0acadc8805c7d67ada2/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/4eeb4e290e9e2eef9094b0acadc8805c7d67ada2/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/4eeb4e290e9e2eef9094b0acadc8805c7d67ada2/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/4eeb4e290e9e2eef9094b0acadc8805c7d67ada2/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:315](https://github.com/daos-stack/daos/blob/4eeb4e290e9e2eef9094b0acadc8805c7d67ada2/src/tests/ftest/util/ior_test_base.py#L315):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/macsio_test_base.py:45](https://github.com/daos-stack/daos/blob/4eeb4e290e9e2eef9094b0acadc8805c7d67ada2/src/tests/ftest/util/macsio_test_base.py#L45):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/4eeb4e290e9e2eef9094b0acadc8805c7d67ada2/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-11 00:45 UTC, phender submitted a review, later dismissed

2022-03-11 10:31 UTC, shimizukko submitted a review, later dismissed

2022-03-11 18:49 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:520](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/cart/util/cart_utils.py#L520):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/io/macsio_test.py:81](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/io/macsio_test.py#L81):
(pylint-no-member) Instance of 'list' has no 'working_dir' member

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:227](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/util/ior_test_base.py#L227):
(pylint-no-member) Instance of 'list' has no 'process' member

[src/tests/ftest/util/ior_test_base.py:325](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/util/ior_test_base.py#L325):
(pylint-no-member) Instance of 'list' has no 'stop' member

[src/tests/ftest/util/ior_test_base.py:315](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/util/ior_test_base.py#L315):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/macsio_test_base.py:79](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/util/macsio_test_base.py#L79):
(pylint-no-member) Instance of 'list' has no 'assign_hosts' member

[src/tests/ftest/util/macsio_test_base.py:81](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/util/macsio_test_base.py#L81):
(pylint-no-member) Instance of 'list' has no 'assign_processes' member

[src/tests/ftest/util/macsio_test_base.py:82](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/util/macsio_test_base.py#L82):
(pylint-no-member) Instance of 'list' has no 'assign_environment' member

[src/tests/ftest/util/macsio_test_base.py:86](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/util/macsio_test_base.py#L86):
(pylint-no-member) Instance of 'list' has no 'run' member

[src/tests/ftest/util/macsio_test_base.py:45](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/util/macsio_test_base.py#L45):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:21](https://github.com/daos-stack/daos/blob/1f9dfc77b16558e14d741bd5af5d5d72b8446607/src/tests/ftest/util/test_utils_pool.py#L21):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-11 19:27 UTC, shimizukko approved these changes

2022-03-11 20:50 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8060/40/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:520](https://github.com/daos-stack/daos/blob/4b95860e7374517f4f2f7246a4c2bfa3a4814ada/src/tests/ftest/cart/util/cart_utils.py#L520):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/4b95860e7374517f4f2f7246a4c2bfa3a4814ada/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/apricot/apricot/test.py:22](https://github.com/daos-stack/daos/blob/4b95860e7374517f4f2f7246a4c2bfa3a4814ada/src/tests/ftest/util/apricot/apricot/test.py#L22):
(pylint-unused-import) Unused MPILoadError imported from exception_utils

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/4b95860e7374517f4f2f7246a4c2bfa3a4814ada/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/4b95860e7374517f4f2f7246a4c2bfa3a4814ada/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/4b95860e7374517f4f2f7246a4c2bfa3a4814ada/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/4b95860e7374517f4f2f7246a4c2bfa3a4814ada/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:315](https://github.com/daos-stack/daos/blob/4b95860e7374517f4f2f7246a4c2bfa3a4814ada/src/tests/ftest/util/ior_test_base.py#L315):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/macsio_test_base.py:45](https://github.com/daos-stack/daos/blob/4b95860e7374517f4f2f7246a4c2bfa3a4814ada/src/tests/ftest/util/macsio_test_base.py#L45):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:22](https://github.com/daos-stack/daos/blob/4b95860e7374517f4f2f7246a4c2bfa3a4814ada/src/tests/ftest/util/test_utils_pool.py#L22):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-11 20:50 UTC, daosbuild1 commented on src/tests/ftest/util/job_manager_utils.py
> +    def __init__(self, job, subprocess=False, mpi_type="openmpi"):
(pylint-unused-argument) Unused argument 'mpi_type'

2022-03-11 20:50 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8060/40/execution/node/113/log

2022-03-11 21:12 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/cart/util/cart_utils.py:520](https://github.com/daos-stack/daos/blob/660262d5999d0871800d8d82f457000fb77c6c43/src/tests/ftest/cart/util/cart_utils.py#L520):
(pylint-consider-using-with) Consider using 'with' for resource-allocating operations

[src/tests/ftest/nvme/fragmentation.py:104](https://github.com/daos-stack/daos/blob/660262d5999d0871800d8d82f457000fb77c6c43/src/tests/ftest/nvme/fragmentation.py#L104):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/660262d5999d0871800d8d82f457000fb77c6c43/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/660262d5999d0871800d8d82f457000fb77c6c43/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/660262d5999d0871800d8d82f457000fb77c6c43/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/660262d5999d0871800d8d82f457000fb77c6c43/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/ior_test_base.py:315](https://github.com/daos-stack/daos/blob/660262d5999d0871800d8d82f457000fb77c6c43/src/tests/ftest/util/ior_test_base.py#L315):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/macsio_test_base.py:45](https://github.com/daos-stack/daos/blob/660262d5999d0871800d8d82f457000fb77c6c43/src/tests/ftest/util/macsio_test_base.py#L45):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/test_utils_pool.py:22](https://github.com/daos-stack/daos/blob/660262d5999d0871800d8d82f457000fb77c6c43/src/tests/ftest/util/test_utils_pool.py#L22):
(pylint-too-many-instance-attributes) Too many instance attributes (32/30)

2022-03-11 22:36 UTC, phender approved these changes

2022-03-13 10:03 UTC, shimizukko approved these changes

2022-03-14 13:30 UTC, mjean308 commented
5 failures in PR
Centos8: svc/PoolSVC - pool query timeout after rebuild - DAOS-8495
HW small: bigio - hang - known issue  DAOS-6654
HW medium: osa/offline drain snapshot:  network issue
general_utils.DaosTestError: Timeout detected running 'clush -S -v -w wolf-122,wolf-123,wolf-124 /usr/bin/mkdir -p /var/tmp/daos_testing/test_osa_offline_drain_after_snapsot' with a 10s timeout
HW large: soak smoke:    Failed in TearDown: network issue
Timeout detected running 'scp wolf-142:/var/tmp/daos_testing/daos*.log.*   timeout 120secs
HW large: server/metadata.py - DAOS-9078

2022-03-14 18:58 UTC, merged