DAOS-9822: track accurate mtime with dfs_stat
daos-stack/daos pull request #8081
Opened 2022-02-04 16:42 UTC by mchaarawi

- Add RPC stack to return max_epoch with key query
- Update key query to optionally return the max_epoch
- Add new Array api (daos_array_stat) that queries the array size and max epoch
- Add CART API to convert epoch to timespec
- Update DFS to use the array stat API instead of array get_size on dfs_stat

Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>

2022-02-04 16:45 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8081/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-02-04 16:45 UTC, daosbuild1 commented on src/include/daos_array.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-04 16:45 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-04 16:45 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/1/execution/node/112/log

2022-02-08 20:39 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8081/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-02-08 20:39 UTC, daosbuild1 commented on src/include/daos_array.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-08 20:39 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-08 20:39 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/2/execution/node/117/log

2022-02-08 22:35 UTC, daosbuild1 commented
Test stage Test CentOS 7 RPMs completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/2/execution/node/1216/log

2022-02-08 22:35 UTC, daosbuild1 commented
Test stage Test CentOS 8.3.2011 RPMs completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/2/execution/node/1207/log

2022-02-14 21:48 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8081/4/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-02-14 21:48 UTC, daosbuild1 commented on src/include/daos_array.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-14 21:48 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-14 21:48 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/4/execution/node/97/log

2022-02-14 23:28 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8081/5/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-02-14 23:28 UTC, daosbuild1 commented on src/include/daos_array.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-14 23:28 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-14 23:28 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/5/execution/node/115/log

2022-02-15 21:25 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8081/6/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-02-15 21:25 UTC, daosbuild1 commented on src/include/daos_array.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-15 21:25 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-15 21:25 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/6/execution/node/113/log

2022-02-15 21:29 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/6/execution/node/360/log

2022-02-15 21:34 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/6/execution/node/319/log

2022-02-15 21:39 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/6/execution/node/359/log

2022-02-15 21:41 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/6/execution/node/371/log

2022-02-15 22:08 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8081/7/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-02-15 22:08 UTC, daosbuild1 commented on src/include/daos_array.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-15 22:08 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-15 22:08 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/7/execution/node/112/log

2022-02-15 22:14 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/7/execution/node/300/log

2022-02-15 22:33 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/7/execution/node/370/log

2022-02-15 23:06 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/7/execution/node/364/log

2022-02-15 23:30 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/7/execution/node/367/log

2022-02-24 20:58 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8081/8/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-02-24 20:58 UTC, daosbuild1 commented on src/include/daos_array.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-24 20:58 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-24 20:58 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define OBJ_PROTO_CLI_RPC_LIST(ver)					\
(style)  Macros with complex values should be enclosed in parentheses

2022-02-24 20:58 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_0	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-02-24 20:58 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_1	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-02-24 20:58 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/8/execution/node/112/log

2022-02-24 21:06 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8081/9/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-02-24 21:06 UTC, daosbuild1 commented on src/include/daos_array.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-24 21:06 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-24 21:06 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define OBJ_PROTO_CLI_RPC_LIST(ver)					\
(style)  Macros with complex values should be enclosed in parentheses

2022-02-24 21:06 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_0	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-02-24 21:06 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_1	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-02-24 21:06 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/9/execution/node/132/log

2022-02-24 21:14 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8081/10/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-02-24 21:14 UTC, daosbuild1 commented on src/include/daos_array.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-24 21:14 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-24 21:14 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define OBJ_PROTO_CLI_RPC_LIST(ver)					\
(style)  Macros with complex values should be enclosed in parentheses

2022-02-24 21:14 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_0	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-02-24 21:14 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_1	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-02-24 21:14 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/10/execution/node/132/log

2022-02-28 20:54 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8081/13/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-02-28 20:54 UTC, daosbuild1 commented on src/include/daos_array.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-28 20:54 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2022-02-28 20:54 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define OBJ_PROTO_CLI_RPC_LIST(ver)					\
(style)  Macros with complex values should be enclosed in parentheses

2022-02-28 20:54 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_0	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-02-28 20:54 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_1	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-02-28 20:54 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/13/execution/node/112/log

2022-03-01 15:48 UTC, Michael-Hennecke requested changes
doxygen issues in daos_task.h - can those be fixed?

2022-03-01 15:51 UTC, mchaarawi commented
> doxygen issues in daos_task.h - can those be fixed?

again those are not part of this PR. we should really create a ticket and address doxygen issues in a separate PR that can be ported to 2.0.x

2022-03-01 22:02 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8081/14/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-03-01 22:02 UTC, daosbuild1 commented on src/include/daos_array.h
> +typedef struct {
(style)  do not add new typedefs

2022-03-01 22:02 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2022-03-01 22:02 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define OBJ_PROTO_CLI_RPC_LIST(ver)					\
(style)  Macros with complex values should be enclosed in parentheses

2022-03-01 22:02 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_0	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-03-01 22:02 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_1	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-03-01 22:02 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/14/execution/node/112/log

2022-03-01 23:38 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8081/15/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-03-01 23:38 UTC, daosbuild1 commented on src/include/daos_array.h
> +typedef struct {
(style)  do not add new typedefs

2022-03-01 23:38 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2022-03-01 23:38 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define OBJ_PROTO_CLI_RPC_LIST(ver)					\
(style)  Macros with complex values should be enclosed in parentheses

2022-03-01 23:38 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_0	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-03-01 23:38 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_1	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-03-01 23:38 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/15/execution/node/111/log

2022-03-03 00:14 UTC, jolivier23 approved these changes

2022-03-07 19:20 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8081/18/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-03-07 19:20 UTC, daosbuild1 commented on src/include/daos_array.h
> +typedef struct {
(style)  do not add new typedefs

2022-03-07 19:20 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2022-03-07 19:20 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define OBJ_PROTO_CLI_RPC_LIST(ver)					\
(style)  Macros with complex values should be enclosed in parentheses

2022-03-07 19:20 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_0	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-03-07 19:20 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_1	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-03-07 19:20 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/18/execution/node/121/log

2022-03-17 19:00 UTC, kprantis commented
The two failures in testing are known issues? You are requesting force landing?

2022-03-21 21:36 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8081/19/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-03-21 21:36 UTC, daosbuild1 commented on src/include/daos_array.h
> +typedef struct {
(style)  do not add new typedefs

2022-03-21 21:36 UTC, daosbuild1 commented on src/include/daos_task.h
> +typedef struct {
(style)  do not add new typedefs

2022-03-21 21:36 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define OBJ_PROTO_CLI_RPC_LIST(ver)					\
(style)  Macros with complex values should be enclosed in parentheses

2022-03-21 21:36 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_0	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-03-21 21:36 UTC, daosbuild1 commented on src/object/obj_rpc.h
> +#define DAOS_OSEQ_OBJ_QUERY_KEY_1	/* output fields */	 \
(style)  Macros with complex values should be enclosed in parentheses

2022-03-21 21:36 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8081/19/execution/node/112/log

2022-03-25 09:54 UTC, merged