DAOS-9644 control: add telemetry_port to server YML (#8098)
daos-stack/daos pull request #8102
Opened 2022-02-07 15:36 UTC by Michael-Hennecke

add telemetry_port to the daos_server.yml sample files
update telemetry documentation in administration.md

Doc-only: true
Signed-off-by: Michael Hennecke <michael.hennecke@intel.com>

2022-02-07 18:50 UTC, kjacque approved these changes
Nice update.

2022-02-07 19:29 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-02-07 21:15 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8102/2/execution/node/741/log

2022-02-09 07:16 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-02-09 17:13 UTC, kjacque approved these changes

2022-02-15 23:40 UTC, jolivier23 requested changes
Looks like there is a conflict on this one

2022-02-15 23:40 UTC, jolivier23 commented
Also, can you add a reference to the landed master commit/PR

2022-02-16 10:50 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-02-16 10:52 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8102/4/execution/node/366/log

2022-02-16 10:59 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8102/4/execution/node/326/log

2022-02-16 11:00 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8102/4/execution/node/351/log

2022-02-16 11:02 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8102/4/execution/node/369/log

2022-02-16 11:54 UTC, daosbuild1 commented
Test stage NLT completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8102/4/execution/node/747/log

2022-02-22 07:24 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8102/6/execution/node/253/log

2022-02-22 07:31 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8102/6/execution/node/231/log

2022-02-22 07:34 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8102/6/execution/node/278/log

2022-02-22 07:34 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8102/6/execution/node/242/log

2022-02-22 07:50 UTC, daosbuild1 commented
Test stage NLT completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8102/5/execution/node/276/log

2022-02-22 08:30 UTC, daosbuild1 commented
Test stage NLT completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8102/6/execution/node/643/log

2022-02-23 10:27 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-02-23 13:02 UTC, merged