DAOS-9748 doc: document FI_OFI_RXM_USE_SRX in daos_server.yml
daos-stack/daos pull request #8116
Opened 2022-02-08 07:42 UTC by wangshilong

It is reported that daos engine could not start with
Intel Corporation Ethernet Controller E810-C for QSFP.

Problem is daos engines enabled SRX by default, while some
network card could not support it well, setting FI_OFI_RXM_USE_SRX
to 0 could walkaround issue.

Doc-only: true
Signed-off-by: Wang Shilong <shilong.wang@intel.com>

2022-02-08 07:45 UTC, wangshilong commented
I did not find a good place to update information like this, maybe there should be a place like: "known hardware issue with DAOS"

2022-02-16 13:42 UTC, wiliamhuang approved these changes

2022-02-18 12:14 UTC, Michael-Hennecke requested changes

2022-02-18 12:14 UTC, Michael-Hennecke commented on utils/config/daos_server.yml
> +#                               shared receive context, eg intel E810-C.
you need a 2nd comment character here or unmarshalling will cause a test fail...
did not --> does not

2022-02-22 08:18 UTC, Michael-Hennecke approved these changes

2022-02-22 13:22 UTC, wiliamhuang approved these changes

2022-02-23 13:14 UTC, johannlombardi approved these changes

2022-02-23 13:15 UTC, merged

2022-02-23 13:47 UTC, mjmac commented
Worth noting that the global config option `disable_srx: true` achieves the same goal. https://github.com/daos-stack/daos/blob/master/utils/config/daos_server.yml#L97

The documentation on that option could probably be better, though. I tried to find a definition for SRX and exactly what it was for, but google failed me.