DAOS-9313 test: more log for osa_offline_reintegration_with_rf
daos-stack/daos pull request #8135
Opened 2022-02-09 12:20 UTC by Nasf-Fan

Enable "io,trace" in the DD_MASK.

Signed-off-by: Fan Yong <fan.yong@intel.com>

2022-02-09 12:23 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-02-11 16:16 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-02-15 07:08 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-02-16 02:35 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-02-18 14:09 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-02-20 02:04 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-02-20 02:05 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8135/7/execution/node/363/log

2022-02-20 02:12 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8135/7/execution/node/336/log

2022-02-20 02:15 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8135/7/execution/node/367/log

2022-02-20 02:16 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8135/7/execution/node/370/log

2022-02-22 07:52 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-02-24 08:51 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-02-28 02:36 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-02-28 15:04 UTC, Nasf-Fan commented
We hope to reproduce the issue, then restart the test.

2022-02-28 15:07 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-03-03 17:44 UTC, Nasf-Fan commented
Set 12 failed on osa_offline_reintegration again, but this time, it is caused by DAOS-9975. Then have to restart the test for further try.

2022-03-03 17:48 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-03-17 06:15 UTC, Nasf-Fan commented on src/tests/ftest/osa/offline_reintegration.yaml
> +        - DD_MASK=mgmt,md,rebuild,io,trace
I repeated the test many times with the patch, nerve reproduce the issue, then I have to consider to land it to master, once we fix related issue, this patch can be rollback together the fixes.

2022-03-27 08:06 UTC, Nasf-Fan commented
We need to land this patch to collective more logs.

2022-03-28 19:14 UTC, jolivier23 commented
> We need to land this patch to collect more logs.

how often does the issue happen?   Could we set the commit pragma to run the test(s) in question 100 times or some such and go from there?   Or is it so rare that it needs to be landed?

2022-03-28 19:17 UTC, jolivier23 requested changes
Adding  a review to remove from inbox while question answered.

2022-04-13 02:43 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-04-27 03:23 UTC, Nasf-Fan commented
> I think what you would want is something like
> Test-tag: [identifying tag for the failing test(s)]
> Test-repeat: 100

Here is some commit parameters for the PR:

Test-tag-hw-medium: osa_offline_reintegration
Test-repeat: 30

But osa_offline_reintegration did not run in CI test. Is there any wrong?
@brianjmurrell , thanks!

2022-04-27 11:42 UTC, brianjmurrell commented
> Here is some commit parameters for the PR:
> 
> Test-tag-hw-medium: osa_offline_reintegration
> Test-repeat: 30
> 
> But osa_offline_reintegration did not run in CI test. Is there any wrong? @brianjmurrell , thanks!

Could be [DAOS-10029](https://daosio.atlassian.net/browse/DAOS-10029).  @phender Thoughts?

2022-04-27 12:58 UTC, phender commented
> > Here is some commit parameters for the PR:
> > Test-tag-hw-medium: osa_offline_reintegration
> > Test-repeat: 30
> > But osa_offline_reintegration did not run in CI test. Is there any wrong? @brianjmurrell , thanks!
> 
> Could be [DAOS-10029](https://daosio.atlassian.net/browse/DAOS-10029). @phender Thoughts?
> 
> As an aside @phender, because the pragma used was `Test-tag-hw-medium` and not `Test-tag` would that mean that all test stages (i.e. VMs, hardware small and large) would have run all of their tests 30x, unnecessarily tying up (hardware) clusters for an extended amount of time? If so, should we perhaps only allow `Test-repeat` to be used with `Test-tag` and not any of the `Test-tag-<stage>` pragmas? At least then, the user gets an error message up front instead of unintentionally tying up valuable hardware resources for long periods of time. Or the framework could just internally drop any `-<stage>` from `Test-tag-<stage>` to effect what the user most likely actually wanted.

The first problem is `osa_offline_reintegration` is not a test tag.  The [`osa/offline_reintegration.py:OSAOfflineReintegration.test_osa_offline_reintegration_with_rf`](https://github.com/daos-stack/daos/blob/master/src/tests/ftest/osa/offline_reintegration.py#L289-L293) test uses these test tags:
```
        :avocado: tags=all,daily_regression
        :avocado: tags=hw,medium,ib2
        :avocado: tags=osa,checksum
        :avocado: tags=offline_reintegration_full,mpich
        :avocado: tags=offline_reintegration_with_rf
```
The `offline_reintegration_with_rf` tag is unique and the one I'd suggest to use.  Then you'll run into DAOS-10029 because this test uses python3-specific code, so you'll need to use an additional test tag (one for a test is currently skipped) to get past the `list_tests.py` check that verifies if the stage has any tests to run.  In this case I'd suggest using `online_parallel`.

So to run just the `osa/offline_reintegration.py:OSAOfflineReintegration.test_osa_offline_reintegration_with_rf` test use either:
```
Test-tag: offline_reintegration_with_rf online_parallel
```
or:
```
Test-tag-hw-medium: offline_reintegration_with_rf online_parallel
```

The second - and major - issue is the pragmas being used are incomplete to achieve the desired goal of running one test multiple times.  The problem with:
```
Test-tag-hw-medium: offline_reintegration_with_rf online_parallel
Test-repeat: 30
```
Is that it only reduces the tests run in the HW Medium stage and will still run the other functional test stages with the `pr` tag (the default) so all the tests in `Functional on EL 8`, `Functional on HW Small`, and `Functional on HW Large` are run 30 times - not good for CI at all.

We can limit the test repetition by either explicitly targeting the stage:
```
Test-repeat-hw-medium: 30
``` 
or eliminating any tests from being run on the other functional test stages indirectly with:
```
Test-tag: offline_reintegration_with_rf online_parallel
```
or directly with:
```
Skip-unit-tests: true
Skip-func-test-vm: true
Skip-func-hw-test-small: true
Skip-func-hw-test-large: true
Test-tag-hw-medium: offline_reintegration_with_rf online_parallel
```

So putting it all together these are the tags that should be used for this PR:
```
Test-tag: offline_reintegration_with_rf online_parallel
Test-repeat-hw-medium: 30
```

2022-04-28 07:31 UTC, Nasf-Fan commented
Thanks @brianjmurrell @phender !
Let me try again with the new parameters.

2022-04-28 07:32 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-04-29 00:59 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-18 15:50 UTC, Nasf-Fan commented
> So putting it all together these are the pragmas that should be used for this PR:

> Test-tag: offline_reintegration_with_rf online_parallel
> Test-repeat-hw-medium: 30

The PR has been refreshed for more than two weeks, but the expected test seemed still not run. @brianjmurrell

2022-05-18 18:46 UTC, daltonbohning commented
> > So putting it all together these are the pragmas that should be used for this PR:
> 
> > Test-tag: offline_reintegration_with_rf online_parallel
> > Test-repeat-hw-medium: 30
> 
> The PR has been refreshed for more than two weeks, but the expected test seemed still not run. @brianjmurrell

The test was in the skiplist:
`[['DAOS-10435', 'test_method_name', 'test_osa_offline_reintegration_with_rf']]|0ccff36`
And commit `0ccff36` was merged after this PR's base. So I think it should work if you merge master and re-run

2022-06-06 08:10 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2023-03-20 00:24 UTC, Nasf-Fan commented
Not need it any longer.

2023-03-20 00:24 UTC, closed without merging