Update general_utils.py
daos-stack/daos pull request #8281
Opened 2022-02-22 22:41 UTC by kalfizah

DAOS-9929 test: Test updated for 9929, increase clush timeout.

2022-02-22 22:44 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/74ab586b6575e1f8f4025e1652e636a4fc61141e/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/74ab586b6575e1f8f4025e1652e636a4fc61141e/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/74ab586b6575e1f8f4025e1652e636a4fc61141e/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/74ab586b6575e1f8f4025e1652e636a4fc61141e/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-02-23 17:33 UTC, saurabhtandan requested changes
Looking at your last commit pushed, it seems like the tag for concerned test was not included in the commit message. Hence rebuild/basic.py test will not be run as part of the PR.
You will need to re-push the PR with following pragma in the commit message
`Test-tag: rebuild_tests`

My suggestion will be, let the current PR run in Jenkins and let it finish, so you have a successful PR run once. And then re-push with the pragma as mentioned above. That will run only the rebuild/basic.py test for you and save CI time.

2022-02-23 17:33 UTC, saurabhtandan commented on src/tests/ftest/util/general_utils.py
>      """Create the specified directory on the specified hosts.
Minor: timeout description should be updated as well below to reflect 15 seconds now instead of 10 seconds.

2022-02-23 17:33 UTC, saurabhtandan commented on src/tests/ftest/util/general_utils.py
>      """Create the specified directory on the specified hosts.
Same as above.

2022-02-23 18:26 UTC, kalfizah commented on src/tests/ftest/util/general_utils.py
>      """Create the specified directory on the specified hosts.
Done. Thanks.

2022-02-23 18:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/general_utils.py:158](https://github.com/daos-stack/daos/blob/5104fcd9d34515a5fa7fc3b32615f19576b66d61/src/tests/ftest/util/general_utils.py#L158):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:200](https://github.com/daos-stack/daos/blob/5104fcd9d34515a5fa7fc3b32615f19576b66d61/src/tests/ftest/util/general_utils.py#L200):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:382](https://github.com/daos-stack/daos/blob/5104fcd9d34515a5fa7fc3b32615f19576b66d61/src/tests/ftest/util/general_utils.py#L382):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:392](https://github.com/daos-stack/daos/blob/5104fcd9d34515a5fa7fc3b32615f19576b66d61/src/tests/ftest/util/general_utils.py#L392):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-02-25 10:03 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8281/2/execution/node/1537/log

2022-03-02 00:40 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-03-02 14:10 UTC, mchaarawi reviewed
im not sure what this PR is about. all i see in the changes is my PR that was landed, but no change to timeout or anything like that.

2022-03-14 17:58 UTC, phender commented
@kalfizah can you fix this, please?  Your original file changes to general_utils.py have been lost.

2022-03-14 18:49 UTC, closed without merging

2022-03-14 18:51 UTC, kalfizah commented
This one is broken, I've created a new one, https://github.com/daos-stack/daos/pull/8356.