DAOS-9972 test: Workaround for SPDK scan failing when VMD is enabled
daos-stack/daos pull request #8300
Opened 2022-02-24 12:36 UTC by tanabarr

Verify issue on wolf-[53,126-129].

Workaround the test failures by failing fast on first scan failure,
subsequent scans after daos_server process restart will succeed
and tests will pass.

Changes:
- remove unnecessary storage prepare calls in test setup
- fail daos_server setup on any spdk scan errors

Quick-functional: true
Parallel-build: true
Skip-unit-tests: true
Skip-func-test-vm: true
Skip-func-hw-test-small: true
Skip-func-hw-test-large: true
Test-tag-hw-medium: test_daos_degraded_mode
Test-repeat: 2

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

2022-02-24 21:21 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/server_utils.py:1](https://github.com/daos-stack/daos/blob/c6cecb95a3c3218966b2864178bbe6a985ab4d3a/src/tests/ftest/util/server_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1099/1000)

2022-02-24 21:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/server_utils.py:1](https://github.com/daos-stack/daos/blob/c6cecb95a3c3218966b2864178bbe6a985ab4d3a/src/tests/ftest/util/server_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1099/1000)

2022-02-24 23:03 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8300/4/execution/node/723/log

2022-02-24 23:21 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/server_utils.py:1](https://github.com/daos-stack/daos/blob/ab482f2b11e8ba9ec23362616927f20d9cb9d4a0/src/tests/ftest/util/server_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1099/1000)

2022-02-25 09:41 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/server_utils.py:1](https://github.com/daos-stack/daos/blob/df66682d175f5f93337515e299ab8874b9ffc90b/src/tests/ftest/util/server_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1099/1000)

2022-02-25 09:44 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/server_utils.py:1](https://github.com/daos-stack/daos/blob/df66682d175f5f93337515e299ab8874b9ffc90b/src/tests/ftest/util/server_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1099/1000)

2022-02-25 14:09 UTC, phender requested changes
I think the changes to server_utils.py look good, but warrant more extensive testing.  I would expand the test coverage using the following pragmas:
```
Quick-build: true 
Test-tag: pr daily_regression
Allow-unstable-test: true
Skip-fault-injection-test: true
```

2022-02-28 10:58 UTC, tanabarr commented
replaced by the following PRs:
- https://github.com/daos-stack/daos/pull/8288
- https://github.com/daos-stack/daos/pull/8334
- https://github.com/daos-stack/daos/pull/8335

2022-02-28 10:58 UTC, closed without merging