DAOS-10147 EC: clear EC stripe list if EC aggregation is aborted
daos-stack/daos pull request #8486
Opened 2022-03-17 16:40 UTC by wangdi1

clear EC stripe list if EC aggregation is aborted, since post_cb
might be skipped.

Signed-off-by: Di Wang <di.wang@intel.com>

2022-03-17 16:43 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-03-17 19:56 UTC, jolivier23 requested changes

2022-03-17 19:56 UTC, jolivier23 commented on src/object/srv_ec_aggregate.c
> +			agg_process_curr_stripe(ih, agg_param, entry, agg_entry, acts);
I am not sure this is safe to do after re-probe.   Is there not an alternative where we simply clean-up what we've allocated?   Or is it too late at this point.    I believe the nested iterator will do a dbtree_iter_fetch on the entry in question and I'm not sure it's valid.  If more I/O happened, the tree pointers may have moved.  The alternative is to add a callback for "exit" but that probably isn't the right answer for 2.0.

2022-03-17 21:17 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-03-17 21:24 UTC, jolivier23 approved these changes

2022-03-18 01:00 UTC, NiuYawei requested changes

2022-03-18 01:00 UTC, NiuYawei commented on src/object/srv_ec_aggregate.c
> +		agg_clear_extents(agg_entry);
Shouldn't such cleanup function called in cont_ec_aggregate_cb()? what if vos_iterate() abort on other errors (error not returned by pre callback)?

2022-03-18 01:45 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-03-18 01:46 UTC, NiuYawei approved these changes

2022-03-18 01:47 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8486/3/execution/node/359/log

2022-03-18 01:53 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8486/3/execution/node/318/log

2022-03-18 01:57 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8486/3/execution/node/370/log

2022-03-18 01:57 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8486/3/execution/node/353/log

2022-03-18 07:14 UTC, johannlombardi commented
This needs to run with the test tag suggested by Phil:
Test-tag: largefilecount

2022-03-18 07:14 UTC, johannlombardi commented
This needs to run with the test tag suggested by Phil:
Test-tag: largefilecount

2022-03-18 08:54 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8486/5/execution/node/251/log

2022-03-18 09:00 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8486/5/execution/node/231/log

2022-03-18 09:04 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8486/5/execution/node/254/log

2022-03-18 09:10 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8486/5/execution/node/312/log

2022-03-18 15:19 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-03-18 15:21 UTC, jgmoore-or approved these changes

2022-03-18 17:32 UTC, johannlombardi approved these changes

2022-03-19 08:28 UTC, merged