DAOS-10259 build: Add SPDK patch to fix bug with VMD init on specific…
daos-stack/daos pull request #8676
Opened 2022-04-11 19:24 UTC by tanabarr

… drives

Patches added in source build for the following SPDK fix:
    https://review.spdk.io/gerrit/c/spdk/spdk/+/12208

Solves DAOS-10259 where SPDK is failing in spdk_vmd_init() when
scanning from the control plane on start-up.

PR-repos: spdk@PR-46
Skip-build-ubuntu20-rpm: true

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

2022-04-11 19:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-04-13 16:45 UTC, brianjmurrell requested changes

2022-04-13 16:45 UTC, brianjmurrell commented on Jenkinsfile
> +@Library(value="pipeline-lib@skip_optane_2") _
You need to back this out before you can land.

2022-04-14 13:14 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-04-14 13:17 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8676/2/execution/node/351/log

2022-04-14 13:17 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8676/2/execution/node/354/log

2022-04-14 13:18 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8676/2/execution/node/348/log

2022-04-15 10:13 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-04-15 13:35 UTC, daosbuild1 commented
Test stage Functional Hardware Small completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8676/3/execution/node/1381/log

2022-04-16 11:59 UTC, brianjmurrell approved these changes

2022-04-21 11:54 UTC, mjmac approved these changes

2022-04-21 11:55 UTC, merged