DAOS-623 build: Use pip to install deps on Ubuntu.
daos-stack/daos pull request #8816
Opened 2022-04-25 16:42 UTC by ashleypittman

Install python dependencies rather than OS ones so we get to
control the versions used.

This allows daos to build in Docker under 22.04 as it avoids
the the meson/spdk build issue.

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

2022-04-25 16:44 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-04-25 17:07 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-04-25 18:11 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-04-25 18:42 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-04-26 09:11 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-04-26 10:58 UTC, ashleypittman commented
This brings Ubuntu dockerfile inline with Rocky 8 and allows daos to be compiled on Ubuntu 22:04 although it does not change what CI/GHA uses.

2022-04-26 16:59 UTC, jolivier23 submitted a review, later dismissed

2022-04-27 08:53 UTC, johannlombardi requested changes
Well, the way i see this patch is that it actually uses a different way to install meson for Ubuntu compared to other distributions. We should either use pip everywhere and add it to the documentation as well or use the distrib packages and fix the issue in SPDK. I am not keen on having a different path just for Ubuntu.

2022-04-27 10:31 UTC, ashleypittman commented
> Well, the way i see this patch is that it actually uses a different way to install meson for Ubuntu compared to other distributions. We should either use pip everywhere and add it to the documentation as well or use the distrib packages and fix the issue in SPDK. I am not keen on having a different path just for Ubuntu.

That's not quite the case.  We've long used pip in individual dockerfiles, mostly either for packages not in the distro like pyelftools or more recently scons to avoid the EL8 bug.  Recently I've been trying to use virtual environments and ensure that our tools can work with them, https://github.com/daos-stack/daos/pull/8590 was a recent change the the build to allow their use and migrate the EL8 dockerfile so this PR really brings Ubuntu in-line with Rocky.  I guess I should have updated the documentation at the same time, and migrate leap over as part of this PR?

2022-04-27 13:04 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-04-27 13:18 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-04-27 13:33 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/8/execution/node/359/log

2022-04-27 13:44 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-04-27 13:57 UTC, daosbuild1 commented
Test stage Build on Leap 15 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/9/execution/node/451/log

2022-04-27 13:57 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/9/execution/node/381/log

2022-04-27 13:59 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/9/execution/node/554/log

2022-04-28 16:22 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-04-28 16:24 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/11/execution/node/415/log

2022-04-28 16:31 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/11/execution/node/340/log

2022-04-28 16:33 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/11/execution/node/407/log

2022-04-28 16:34 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/11/execution/node/364/log

2022-04-28 16:37 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/11/execution/node/380/log

2022-05-05 10:10 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-05 10:24 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/12/execution/node/537/log

2022-05-05 11:03 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-05 11:30 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/13/execution/node/526/log

2022-05-05 11:36 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-05 12:03 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/14/execution/node/526/log

2022-05-05 12:19 UTC, johannlombardi approved these changes

2022-05-05 12:39 UTC, ashleypittman commented
I'm still trying to get this to work in CI as it appears Jenkins does not honour PATH settings from the dockerfile, and it should probably have https://github.com/daos-stack/daos/pull/8796 rolled into it which is removing some regressions from the artifactory change.

2022-05-05 14:03 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-05 14:05 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/16/execution/node/424/log

2022-05-05 14:14 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/16/execution/node/389/log

2022-05-05 14:14 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/16/execution/node/404/log

2022-05-05 16:16 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-05 17:10 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8816/17/execution/node/798/log

2022-05-05 19:15 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-06 08:18 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-06 08:21 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-06 09:30 UTC, johannlombardi approved these changes

2022-05-06 11:55 UTC, brianjmurrell submitted a review, later dismissed
Expanding the risk profile of using unsigned code pulled frequently and randomly from pypi doesn't seem like a good idea to me.  Certainly when there are packages for those modules available from distros which are maintained by the distros.

Indeed, I would have raised this concern on #8590 had I seen it before it landed.

2022-05-06 12:47 UTC, ashleypittman commented on utils/scripts/install-centos7.sh
> -    python36-scons \
This is for build, not deployment, and we're aiming to increase the coverage and flexibility of what we can test.  This PR also adds the BASE_DISTRO arg that already exists in el8 and puts it in leap and ubuntu so as a separate activity outside of CI so far I'm been using these changes to verify that we can run with alternative distributions and keep up-to-date with upstream.

Certainly for Ubuntu the distro packages are not capable of building daos without using pypi.  The same is true for scons on el8 where this change is already applied and centos 7 which on current master is already calling pip without referencing the requirments.txt file.

I believe the Ubuntu 22.04 update is blocked on this (i.e. it won't proceed without it) and these changes should also assist in the Leap 15.4 update, at least in terms of the Github actions configuration.

2022-05-08 23:07 UTC, brianjmurrell commented on utils/scripts/install-centos7.sh
> -    python36-scons \
> Certainly for Ubuntu the distro packages are not capable of building daos without using pypi.

Yes, it's understood that some (hopefully minimal (as can be)) use of pypi might be necessary as we just don't have the bandwidth to roll the required RPMs.  But I would argue that there should at least be tickets for that minimal set of pypi modules that we do use as our ideal working scenario is to use RPMs, presumably maintained by a human and validated  -- whether those are from upstream or by ourselves.  If there are no tickets, the work will never get prioritized and scheduled.

> The same is true for scons on el8

Not true: https://github.com/daos-stack/scons/tree/master

> I believe the Ubuntu 22.04 update is blocked on this (i.e. it won't proceed without it) and these changes should also assist in the Leap 15.4 update, at least in terms of the Github actions configuration.

Why would this assist on Leap 15.4?  One would presume that python module RPMs would be the most up-to-date there.

2022-05-11 23:20 UTC, jolivier23 approved these changes

2022-05-13 09:43 UTC, johannlombardi commented
IIRC, this is only for building in docker and for folks who want to do local build, right? This has no impact on how we generate our RPMs. Correct? It sounds like reducing the number of RPM packages to be installed (usually a request to your sysadmin) is a good idea for this path. @brianjmurrell, do you disagree?

2022-05-13 09:43 UTC, johannlombardi approved these changes

2022-05-14 09:07 UTC, johannlombardi commented
Ping.

2022-05-16 13:29 UTC, brianjmurrell commented
> IIRC, this is only for building in docker and for folks who want to do local build, right?

Right.  But we are effectively providing to people a way of building that ls "less secure".

> This has no impact on how we generate our RPMs. Correct?

Correct.

> It sounds like reducing the number of RPM packages to be installed (usually a request to your sysadmin) is a good idea for this path. @brianjmurrell, do you disagree?

I would agree if we could find a way that was safer than pulling source code from a completely unauthenticated (i.e. not even cryptographically authenticated) and actively hacked (i.e. typo-squatting in the absolute least) source.

But given that the exposure would just be local I can disagree and commit here.

2022-05-20 18:27 UTC, merged