DAOS-9789 test: Run job_tests and agent_tests via run_tests.sh
daos-stack/daos pull request #8871
Opened 2022-04-29 15:43 UTC by dpquigl

job and agent unit tests were being run via the ftest suite instead of the unit
test stage. This removes the functional tests which run the agent_test and
job_test unit test binaries and instead runs them via run_tests.sh which is
used in the unit test stage.

Signed-off-by: David Quigley <david.quigley@intel.com>

2022-04-29 15:45 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-04-29 16:08 UTC, daltonbohning requested changes
Nice! But we also need to remove the `unittest` entry from scons, since the directory no longer exists:
https://github.com/daos-stack/daos/blob/5f0cdfe5063f264f8a8410e252c07a6fd25ebda1/src/tests/ftest/SConscript#L18

2022-04-29 16:50 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8871/1/execution/node/795/log

2022-04-29 16:59 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8871/1/execution/node/798/log

2022-05-02 17:58 UTC, dpquigl commented
@daltonbohning Removed the directory from the SConsctruct file and pushed the change.

2022-05-02 18:00 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-03 02:18 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-03 03:34 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8871/3/execution/node/807/log

2022-05-03 03:47 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8871/3/execution/node/821/log

2022-05-03 14:16 UTC, daltonbohning reviewed
Changes LGTM, but it these tests are failing as unit tests

2022-05-03 16:05 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-04 16:48 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-04 18:17 UTC, daosbuild1 commented
Test stage Unit Test with memcheck completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8871/5/execution/node/816/log

2022-05-05 02:43 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-05 21:45 UTC, daltonbohning approved these changes

2022-05-06 17:33 UTC, dinghwah approved these changes

2022-05-09 15:47 UTC, merged