DAOS-10458 build: Move dmg into daos-admin RPM
daos-stack/daos pull request #8925
Opened 2022-05-04 21:42 UTC by mjmac

Create a new admin-only RPM to allow installation
independently of client/server dependencies.

Signed-off-by: Michael MacDonald <mjmac.macdonald@intel.com>

2022-05-04 21:45 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-04 22:34 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8925/1/execution/node/798/log

2022-05-05 13:27 UTC, brianjmurrell requested changes
As you can see by the test failures, you are going to have to arrange for the daos-admin package to be installed on test nodes during test.  Perhaps it needs to be a dependency of a daos*tests* RPM?

2022-05-05 13:30 UTC, mjmac commented
> As you can see by the test failures, you are going to have to arrange for the daos-admin package to be installed on test nodes during test. Perhaps it needs to be a dependency of a daos_tests_ RPM?

Hmm, yeah. I was trying to work out where that goop lived in advance but didn't find it so I pushed this to see where it would fail. Probably does make sense to just add it as an install dep to those RPMs though.

2022-05-05 14:20 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-05 20:05 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-08 15:32 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-09 16:13 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-09 20:55 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-10 12:22 UTC, brianjmurrell submitted a review, later dismissed

2022-05-27 20:10 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-06-02 13:02 UTC, Michael-Hennecke approved these changes

2022-06-02 13:22 UTC, mjmac commented
@brianjmurrell: Ping... Please re-review. No significant changes since last time, just refreshing after losing the changelog race.

2022-06-02 15:50 UTC, merged