DAOS-9888 obj: add support of EC conditional fetch
daos-stack/daos pull request #8959
Opened 2022-05-09 08:22 UTC by liuxuezhao

Add support of EC conditional fetch -
create local TX for conditional fetch,
split to multiple sub-tasks for cond_akey fetch with multiple akeys

Add related UT cases.

A few bug fixes -
skip fetch/update in akey_fetch()/akey_update() for NULL recxs which is
possible when fetch multiple IODs and recxs only valid on partial shard.
fix a bug in shard_auxi_task_cb() that may use incorrect task pointer.

Signed-off-by: Xuezhao Liu <xuezhao.liu@intel.com>

2022-05-09 08:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-10 08:48 UTC, Nasf-Fan requested changes
If the original EC conditional fetch request contains multiple akeys, and if no parity shards are available, then it will be split into N sub-fetch, and each sub-fetch will be sent to all data shards, right? If yes, that will be N * D RPCs, right?

On the other hand, CI test hit segment fault, that seems related with your patch although I did not find where the trouble line is.

2022-05-10 08:48 UTC, Nasf-Fan commented on src/object/cli_obj.c
> +		rc = dc_tx_local_open(obj_auxi->obj->cob_coh, DAOS_EPOCH_MAX, 0, &obj_auxi->th);
I think we need to use "0" epoch instead of DAOS_EPOCH_MAX, otherwise, the DTX logic will regard as the epoch chosen.

2022-05-10 09:17 UTC, liuxuezhao commented
> If the original EC conditional fetch request contains multiple akeys, and if no parity shards are available, then it will be split into N sub-fetch, and each sub-fetch will be sent to all data shards, right? If yes, that will be N * D RPCs, right?

Yes, but the "no parity shard available" is cornel case.
For the task split for multiple akeys, I am afraid we have no choice unless changing fetch RPC definition, that will cause inter-operability problem.
Because for one akey, any shard return 0 (exist) it means the akey exist, but for multiple akey case any akey non-exist the fetch request will return non-exist.  It looks impossible to check/set the final rc is mix the akeys in one fetch request.
For example cond_akey fetch with akey0 and akey1, on EC 2P1 obj. akey 0 only exist on shard0, and akey 1 only exist on shard1. That cond_akey fetch should return 0, because both akey exist on one shard. But if mix the two akey fetches on one request, both shard 0 and shard 1 will return NON-EXIST for that fetch request and client obj can-only return NON-EXIST.

> On the other hand, CI test hit segment fault, that seems related with your patch although I did not find where the trouble line is.

Yes there are some test failures I'll figure it out.

2022-05-10 09:31 UTC, liuxuezhao commented on src/object/cli_obj.c
> -		obj_auxi->is_ec_obj = 1;
did not removed, just moved to obj_task_init_common().
original code set it here will cause some cases lost setting the flag.

2022-05-10 09:31 UTC, liuxuezhao commented on src/object/cli_obj.c
> +		 * map_ver not changed.
in that case server will reply DER_STALE and client will refresh layout.

2022-05-10 09:31 UTC, liuxuezhao commented on src/object/cli_obj.c
> +			tse_task_complete(check_task, rc);
here the original task already completed and in executing completion CB, if obj_ec_check_exist failed this func will not reinit it and it just keep as completed as before and set the RC.

2022-05-10 09:31 UTC, liuxuezhao commented on src/object/cli_obj.c
> +		if (bit_map == NIL_BITMAP && !is_ec_check_exist) {
for EC check existence, either the two cases you mentioned can come here. whether or not some parity is available is checked inside obj_ec_check_exist_tgts_get()

2022-05-10 09:31 UTC, liuxuezhao commented on src/object/cli_obj.c
> +		D_ASSERT(rc <= 0 || rc == 1);
OK, fine.

2022-05-10 09:32 UTC, liuxuezhao commented on src/object/cli_obj.c
> +		rc = dc_tx_local_open(obj_auxi->obj->cob_coh, DAOS_EPOCH_MAX, 0, &obj_auxi->th);
> I think we need to use "0" epoch instead of DAOS_EPOCH_MAX, otherwise, the DTX logic will regard as the epoch chosen.

ok, thanks.

2022-05-10 09:36 UTC, liuxuezhao commented on src/object/cli_obj.c
> +		rc = dc_tx_local_open(obj_auxi->obj->cob_coh, DAOS_EPOCH_MAX, 0, &obj_auxi->th);
> We need the local TX for conditional fetch only when we have to degrade mode fetch from all data shards.

For multi-akeys case will split to multiple tasks share the same th, so seems not related with check existence form data shards or parity shard? (all the tasks need based on same epoch).

2022-05-11 03:26 UTC, Nasf-Fan commented on src/object/cli_obj.c
> +		rc = dc_tx_local_open(obj_auxi->obj->cob_coh, DAOS_EPOCH_MAX, 0, &obj_auxi->th);
That depends on the semantics we want to offer. If the conditional fetch request is within a user TX, then all the sub requests, in spite of for single akey or multiple akeys, will use the same epoch. But if it is not in user TX context, then it is not guaranteed that the existence for different akeys need to be for the same epoch. That is similar as the case that if the application reads across multiple dkeys, then the final obtained data may have multiple epochs view.

2022-05-11 03:58 UTC, liuxuezhao commented on src/object/cli_obj.c
> +		rc = dc_tx_local_open(obj_auxi->obj->cob_coh, DAOS_EPOCH_MAX, 0, &obj_auxi->th);
agreed. But for the case that only with one akey but cond_fetch need to send to multiple data shards, that should based on same epoch right? So to simplify the processing, maybe fine that always based on one epoch?

2022-05-11 05:53 UTC, Nasf-Fan commented on src/object/cli_obj.c
> +		rc = dc_tx_local_open(obj_auxi->obj->cob_coh, DAOS_EPOCH_MAX, 0, &obj_auxi->th);
Yes, for single akey based conditional fetch under degraded mode, the multiple RPCs need to have the same epoch.

My original suggestion was that if some parity shard is available for conditional fetch, then we do NOT need to split the fetch request into multiple sub-requests in spite of how many akeys, instead, we can directly send one conditional fetch request to the parity shard, right? Then do not need the local TX.

2022-05-11 12:00 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-12 01:19 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-15 09:15 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-17 15:15 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-17 16:57 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8959/6/display/redirect

2022-05-18 02:59 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-18 04:22 UTC, daosbuild1 commented
Test stage Unit Test completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8959/7/execution/node/847/log

2022-05-18 14:30 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-06-02 05:39 UTC, Nasf-Fan approved these changes

2022-06-02 05:49 UTC, Nasf-Fan requested changes
Please adjust the patch to match the master version.

2022-06-02 06:37 UTC, liuxuezhao commented
> Please adjust the patch to match the master version.

sure, the master branch patch probably wait di's another big patch land first, there are lots of conflict.

2022-06-05 04:56 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-06-06 03:07 UTC, liuxuezhao commented
> Please adjust the patch to match the master version.

done, thx.

2022-06-07 02:35 UTC, Nasf-Fan approved these changes

2022-06-14 18:52 UTC, merged