DAOS-10567 daos: fail if all replicas tried
daos-stack/daos pull request #8994
Opened 2022-05-11 08:52 UTC by wangshilong

If one pool is not up because of disk incompatible reasons,
pool query will return DER_NOTLEADER and retry forever.

'dmg pool list' will hang because of above reason, improve
the case by breaking loop if all replicas have been tried.

Signed-off-by: Wang Shilong <shilong.wang@intel.com>

2022-05-11 08:54 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-11 09:00 UTC, wangshilong commented on src/common/rsvc.c
> +	} else if (client->sc_tried >= client->sc_ranks->rl_nr) {
Maybe it could use the sc_next >= rl_nr to check if all replicas has been tried since now sc_next always started from 0?
to avoid extra var here.

2022-05-11 09:30 UTC, daosbuild1 commented
Test stage NLT completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-8994/1/execution/node/770/log

2022-05-11 14:29 UTC, wangshilong commented
> So what is the behavior with this patch in the ticket? Will it skip the incompatible pool or fail pool list altogether? The latter is probably an improvement but it seems we would want to list all of the pools we can.

From i i tried, it will list successful pool anyway. and output errors for those incompatible pools.

2022-05-11 14:29 UTC, jolivier23 submitted a review, later dismissed
I looked at the ticket and answered my question.  I do wonder if we can't have some special handling for DER_DF_INCOMPT to avoid confusing error messages but so long as old_pool is readable in 2.0, this is a big improvement.

2022-05-12 04:01 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-12 06:20 UTC, liw requested changes
Only trying the replicas once has a problem. We expect the PS leader election to take 7 to 14 s in most cases. If all replicas are tried within this 7-to-14-s period, we will return the error, breaking the fault tolerance of the PS replication.

Another problem is that an rsvc_client does not always represent a single operation. In the typical libdaos use cases, an rsvc_client object is initialized for each pool handle, and is used by all subsequent operations that use this pool handle. With this patch, an rsvc_client object will, however, become "stuck" after trying all replicas once without finding a leader.

We could introduce a timeout that fires if a bit over 14 s has passed and all replicas have been tried. Because rsvc_client is shared by multiple operations, how to implement such a timeout may need some thinking.

For the pool list operation, I think if we query the pools one by one, this timeout solution may still be not enough. Maybe the MS needs to maintain info/status of the pools, such as, "pool X has suffered from a timeout before and is likely not available", or "pool Y is incompatible" (if we maintain the layout version on the MS). On top of that, a further optimization might be to query the pools in parallel.

2022-05-12 06:20 UTC, liw commented on src/common/rsvc.c
> +		   client->sc_next >= client->sc_ranks->rl_nr) {
Hmm, does this patch work? It looks like sc_next is always < client->sc_ranks->rl_nr due to the "%" operation.

2022-05-13 07:10 UTC, closed without merging