DAOS-10051 engine: wait RPC replies to quit ULTs properly (#8841)
daos-stack/daos pull request #8999
Opened 2022-05-11 14:41 UTC by wangshilong

After xstream breaking progress loop, there will be no chance
to run rpc timeout checking for this transport context, if one
ult(eg dtx) is sending RPC to a died remote server, ULT will be
blocked forever in wait_all_exited().

Fix this problem by running cart progress in wait_all_exited()
which will run timeout check and abort RPC properly.

Test-tag: pr cascading rebuild_container_rf rebuild_cont_create cont_rf_oclass_enforcement rebuild,multitarget rebuild,delete_objects rebuildreadarray
Signed-off-by: Wang Shilong <shilong.wang@intel.com>

2022-05-11 14:44 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-11 15:41 UTC, daltonbohning approved these changes

2022-05-12 00:54 UTC, NiuYawei approved these changes

2022-05-12 02:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-16 21:15 UTC, phender requested changes
@wangshilong this PR needs to verify that it fixes the tests currently skipped by the DOAS-10051 ticket:

test_simultaneous_failures
test_cascading_failures
test_rebuild_delete_objects
test_rebuild_delete_records
test_read_array_during_rebuild
test_rebuild_with_container_rf
test_rebuild_container_create

Since the last commit message did not start with "DAOS-10051 " these tests were skipped in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8999/2, e.g. https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8999/2/artifact/Functional%20on%20EL%208/rebuild/cascading_failures.py/results.html

2022-05-17 01:10 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/rebuild_test_base.py:92](https://github.com/daos-stack/daos/blob/c8547b5524e7035413e4d38555093c3f09699a5a/src/tests/ftest/util/rebuild_test_base.py#L92):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/util/rebuild_test_base.py:117](https://github.com/daos-stack/daos/blob/c8547b5524e7035413e4d38555093c3f09699a5a/src/tests/ftest/util/rebuild_test_base.py#L117):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/util/rebuild_test_base.py:126](https://github.com/daos-stack/daos/blob/c8547b5524e7035413e4d38555093c3f09699a5a/src/tests/ftest/util/rebuild_test_base.py#L126):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

2022-05-17 04:23 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8999/3/display/redirect

2022-05-19 16:53 UTC, daltonbohning commented
Looks like this needs a merge with `release/2.2` to fix the EL8 failure

2022-05-20 02:12 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/rebuild_test_base.py:92](https://github.com/daos-stack/daos/blob/9bf408bd575483f50341bff46ec9c1b2e211c7ea/src/tests/ftest/util/rebuild_test_base.py#L92):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/util/rebuild_test_base.py:117](https://github.com/daos-stack/daos/blob/9bf408bd575483f50341bff46ec9c1b2e211c7ea/src/tests/ftest/util/rebuild_test_base.py#L117):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/util/rebuild_test_base.py:126](https://github.com/daos-stack/daos/blob/9bf408bd575483f50341bff46ec9c1b2e211c7ea/src/tests/ftest/util/rebuild_test_base.py#L126):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

2022-05-23 08:21 UTC, merged