DAOS-10579 tools: Ensure daos list-container JSON is lowercase
daos-stack/daos pull request #9019
Opened 2022-05-13 14:18 UTC by mjmac

The default behavior is to use CamelCase; just add json: tags
to the struct fields to make them snake_case.

Features: container

Signed-off-by: Michael MacDonald <mjmac.macdonald@intel.com>

2022-05-13 15:10 UTC, daltonbohning requested changes
Unfortunately, all of these tests are in `full_regression`, which are currently not included with `Features`. To get the intended behavior, you'll have to use:
```
Test-tag: pr container der_enospace dmg_pool_evict
```
We plan to include `full_rergression` in `Features` once pass/fail is more stable.

2022-05-13 15:21 UTC, daltonbohning commented
> Are you sure it works that way? I was under the impression that adding a label or labels to `Features: ` is just additive to the base `pr` label. @brianjmurrell, @phender: Would you please confirm either way?

Yes, here is the pipeline handling: https://github.com/daos-stack/pipeline-lib/blob/2ceb3be1d25ca075d1c7947d3159e42ec8c0d23b/vars/parseStageInfo.groovy#L228-L238

And some (maybe unclear/noisy?) documentation: https://daosio.atlassian.net/wiki/spaces/DAOS/pages/10984259629/Test+Tags#How-Do-I-Use-Test-Tags-in-a-PR?

2022-05-13 15:24 UTC, brianjmurrell commented
> Are you sure it works that way? I was under the impression that adding a label or labels to `Features: ` is just additive to the base `pr` label. @brianjmurrell, @phender: Would you please confirm either way?

Yes, `Features:` right now is just a union of whatever tags you request and `pr|daily_regression`.  That is because there are too many known failures on `weekly_regression` to make it useful to add those tests also.

The goal is (and has been, for probably on the order of years now) to eventually have `weekly_regression` running clean and being able to add it's tests to `Features:`.

2022-05-13 15:25 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/control/dmg_pool_evict.py:88](https://github.com/daos-stack/daos/blob/db53dc5d2bb82983cdfe47e8470dc9733f810c89/src/tests/ftest/control/dmg_pool_evict.py#L88):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:61](https://github.com/daos-stack/daos/blob/db53dc5d2bb82983cdfe47e8470dc9733f810c89/src/tests/ftest/nvme/enospace.py#L61):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:66](https://github.com/daos-stack/daos/blob/db53dc5d2bb82983cdfe47e8470dc9733f810c89/src/tests/ftest/nvme/enospace.py#L66):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:164](https://github.com/daos-stack/daos/blob/db53dc5d2bb82983cdfe47e8470dc9733f810c89/src/tests/ftest/nvme/enospace.py#L164):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:168](https://github.com/daos-stack/daos/blob/db53dc5d2bb82983cdfe47e8470dc9733f810c89/src/tests/ftest/nvme/enospace.py#L168):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:239](https://github.com/daos-stack/daos/blob/db53dc5d2bb82983cdfe47e8470dc9733f810c89/src/tests/ftest/nvme/enospace.py#L239):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:303](https://github.com/daos-stack/daos/blob/db53dc5d2bb82983cdfe47e8470dc9733f810c89/src/tests/ftest/nvme/enospace.py#L303):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:339](https://github.com/daos-stack/daos/blob/db53dc5d2bb82983cdfe47e8470dc9733f810c89/src/tests/ftest/nvme/enospace.py#L339):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:348](https://github.com/daos-stack/daos/blob/db53dc5d2bb82983cdfe47e8470dc9733f810c89/src/tests/ftest/nvme/enospace.py#L348):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:353](https://github.com/daos-stack/daos/blob/db53dc5d2bb82983cdfe47e8470dc9733f810c89/src/tests/ftest/nvme/enospace.py#L353):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:388](https://github.com/daos-stack/daos/blob/db53dc5d2bb82983cdfe47e8470dc9733f810c89/src/tests/ftest/nvme/enospace.py#L388):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:417](https://github.com/daos-stack/daos/blob/db53dc5d2bb82983cdfe47e8470dc9733f810c89/src/tests/ftest/nvme/enospace.py#L417):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

2022-05-16 19:10 UTC, mjmac commented
The last run hit failures in nvme/enospc.py (https://daosio.atlassian.net/browse/DAOS-10499, evidently). I looked through the failures and confirmed that they were not due to the updated tool output, so I've re-pushed one more time with a simple `Features: container` pragma to get a clean run.

2022-05-16 19:12 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/control/dmg_pool_evict.py:88](https://github.com/daos-stack/daos/blob/80b930f06dcdedc034f80e516193db117896a814/src/tests/ftest/control/dmg_pool_evict.py#L88):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:61](https://github.com/daos-stack/daos/blob/80b930f06dcdedc034f80e516193db117896a814/src/tests/ftest/nvme/enospace.py#L61):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:66](https://github.com/daos-stack/daos/blob/80b930f06dcdedc034f80e516193db117896a814/src/tests/ftest/nvme/enospace.py#L66):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:164](https://github.com/daos-stack/daos/blob/80b930f06dcdedc034f80e516193db117896a814/src/tests/ftest/nvme/enospace.py#L164):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:168](https://github.com/daos-stack/daos/blob/80b930f06dcdedc034f80e516193db117896a814/src/tests/ftest/nvme/enospace.py#L168):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:239](https://github.com/daos-stack/daos/blob/80b930f06dcdedc034f80e516193db117896a814/src/tests/ftest/nvme/enospace.py#L239):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:303](https://github.com/daos-stack/daos/blob/80b930f06dcdedc034f80e516193db117896a814/src/tests/ftest/nvme/enospace.py#L303):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:339](https://github.com/daos-stack/daos/blob/80b930f06dcdedc034f80e516193db117896a814/src/tests/ftest/nvme/enospace.py#L339):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:348](https://github.com/daos-stack/daos/blob/80b930f06dcdedc034f80e516193db117896a814/src/tests/ftest/nvme/enospace.py#L348):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:353](https://github.com/daos-stack/daos/blob/80b930f06dcdedc034f80e516193db117896a814/src/tests/ftest/nvme/enospace.py#L353):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:388](https://github.com/daos-stack/daos/blob/80b930f06dcdedc034f80e516193db117896a814/src/tests/ftest/nvme/enospace.py#L388):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:417](https://github.com/daos-stack/daos/blob/80b930f06dcdedc034f80e516193db117896a814/src/tests/ftest/nvme/enospace.py#L417):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

2022-05-17 02:27 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9019/3/display/redirect

2022-05-17 16:28 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/control/dmg_pool_evict.py:88](https://github.com/daos-stack/daos/blob/dd2eac3672f9ca847d188a55f1f3be85b474f5f2/src/tests/ftest/control/dmg_pool_evict.py#L88):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:61](https://github.com/daos-stack/daos/blob/dd2eac3672f9ca847d188a55f1f3be85b474f5f2/src/tests/ftest/nvme/enospace.py#L61):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:66](https://github.com/daos-stack/daos/blob/dd2eac3672f9ca847d188a55f1f3be85b474f5f2/src/tests/ftest/nvme/enospace.py#L66):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:164](https://github.com/daos-stack/daos/blob/dd2eac3672f9ca847d188a55f1f3be85b474f5f2/src/tests/ftest/nvme/enospace.py#L164):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:168](https://github.com/daos-stack/daos/blob/dd2eac3672f9ca847d188a55f1f3be85b474f5f2/src/tests/ftest/nvme/enospace.py#L168):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:239](https://github.com/daos-stack/daos/blob/dd2eac3672f9ca847d188a55f1f3be85b474f5f2/src/tests/ftest/nvme/enospace.py#L239):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:303](https://github.com/daos-stack/daos/blob/dd2eac3672f9ca847d188a55f1f3be85b474f5f2/src/tests/ftest/nvme/enospace.py#L303):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:339](https://github.com/daos-stack/daos/blob/dd2eac3672f9ca847d188a55f1f3be85b474f5f2/src/tests/ftest/nvme/enospace.py#L339):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:348](https://github.com/daos-stack/daos/blob/dd2eac3672f9ca847d188a55f1f3be85b474f5f2/src/tests/ftest/nvme/enospace.py#L348):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:353](https://github.com/daos-stack/daos/blob/dd2eac3672f9ca847d188a55f1f3be85b474f5f2/src/tests/ftest/nvme/enospace.py#L353):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:388](https://github.com/daos-stack/daos/blob/dd2eac3672f9ca847d188a55f1f3be85b474f5f2/src/tests/ftest/nvme/enospace.py#L388):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

[src/tests/ftest/nvme/enospace.py:417](https://github.com/daos-stack/daos/blob/dd2eac3672f9ca847d188a55f1f3be85b474f5f2/src/tests/ftest/nvme/enospace.py#L417):
(pylint-consider-using-f-string) Formatting a regular string which could be a f-string

2022-05-19 11:43 UTC, shimizukko approved these changes

2022-05-19 12:17 UTC, knard-intel reviewed
Just to be sure to have fully understand what have been done.
- In the first time, you have validated this patch with adapted pragama: Test-Tags running the updated tests.
- In the second time, you pushed a rebase of your branch with the Feature pragma to avoid false positive errors ?

Otherwise the patch is OK for me.

2022-05-19 13:07 UTC, mjmac commented
Yes, that's correct. The nvme/enospc.py test is apparently failing due to some incorrect assumptions or some other problem. My primary concern for this PR was to ensure that the change in JSON output was not the cause of the test failures, so I looked for tests that used the `list-container` output.

2022-05-19 13:30 UTC, knard-intel approved these changes
OK for me

2022-05-19 14:12 UTC, merged