DAOS-10595 build: Restrict SPDK version to less than 22
daos-stack/daos pull request #9057
Opened 2022-05-17 09:26 UTC by tanabarr

Restrict SPDK version on release/2.2 to avoid any interference when
upgrading to v22.01.1 on master branch.

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

2022-05-17 09:29 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-17 10:56 UTC, johannlombardi approved these changes

2022-05-17 11:05 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9057/1/display/redirect

2022-05-20 09:04 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-20 12:58 UTC, brianjmurrell requested changes
This range pinning really should be expressed in the `debian/control` also:

https://github.com/daos-stack/daos/blob/e69cb998e4034d5411163bf1cc0485b9e999f58b/debian/control#L29

```patch
-  libspdk-dev, 
+  libspdk-dev (>=21.07), libspdk-dev (<<22)
```

It's definitely an oversight that it was not added in 5260802 or any update subsequent to that.

2022-05-20 12:58 UTC, brianjmurrell commented on utils/rpms/daos.spec
> +BuildRequires: spdk-devel < 22
While we typically want each dependency on it's own line, a version range can be specified on a single line:

```suggestion
BuildRequires: spdk-devel >= 21.07, spdk-devel < 22
```

That makes it more difficult to miss that it's actually a range, not just a _greater than or equal to_.

2022-05-20 12:58 UTC, brianjmurrell commented on utils/rpms/daos.spec
> +Requires: spdk-tools < 22
```suggestion
Requires: spdk-tools >= 21.07, spdk-tools < 22
```

2022-05-20 13:40 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-20 13:41 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9057/6/execution/node/335/log

2022-05-20 13:46 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-20 14:29 UTC, brianjmurrell requested changes
Missing `debian/changes` update.

Please remember to let me resolve conversations that I start.  It helps me keep track the issues I raise in the many PRs that I am asked to review.

2022-05-20 14:29 UTC, brianjmurrell commented on debian/control
> +               dpdk-dev (<<21.11),
```suggestion
```

2022-05-20 15:32 UTC, daosbuild1 commented
Test stage Test EL 8.5 RPMs completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9057/7/display/redirect

2022-05-20 15:32 UTC, daosbuild1 commented
Test stage Test CentOS 7 RPMs completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9057/7/display/redirect

2022-05-20 15:34 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-20 15:41 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9057/8/execution/node/373/log

2022-05-20 15:47 UTC, daosbuild1 commented
Test stage Build RPM on EL 8.5 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9057/8/execution/node/399/log

2022-05-20 15:47 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9057/8/execution/node/393/log

2022-05-20 15:50 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9057/8/execution/node/396/log

2022-05-20 23:11 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9057/9/execution/node/285/log

2022-05-20 23:14 UTC, daosbuild1 commented
Test stage Build RPM on EL 8.5 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9057/9/execution/node/203/log

2022-05-20 23:16 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9057/9/execution/node/218/log

2022-05-20 23:19 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9057/9/execution/node/261/log

2022-05-21 10:02 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-24 14:49 UTC, brianjmurrell commented on debian/control
> +               dpdk-dev (<<21.11),
> done

Is it a GitHub anomaly or is this not actually removed as suggested?

2022-05-24 15:02 UTC, brianjmurrell requested changes
Per previous comments.

2022-05-24 15:43 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9057/12/execution/node/352/log

2022-05-24 15:48 UTC, daosbuild1 commented
Test stage Build RPM on EL 8.5 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9057/12/execution/node/362/log

2022-05-24 15:50 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9057/12/execution/node/398/log

2022-05-24 15:52 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9057/12/execution/node/365/log

2022-05-24 17:11 UTC, brianjmurrell commented
Looks like we don't have the equivillent of https://github.com/daos-stack/spdk/blob/fd3be59285e44b76d355e404162cfaf5088fe2c3/spdk.spec#L79 in https://github.com/daos-stack/spdk/blob/fd3be59285e44b76d355e404162cfaf5088fe2c3/debian/control#L24-L26 which is causing the most recent DEB build failure.

2022-05-24 21:00 UTC, tanabarr commented
> Looks like we don't have the equivillent of https://github.com/daos-stack/spdk/blob/fd3be59285e44b76d355e404162cfaf5088fe2c3/spdk.spec#L79 in https://github.com/daos-stack/spdk/blob/fd3be59285e44b76d355e404162cfaf5088fe2c3/debian/control#L24-L26 which is causing the most recent DEB build failure.

So this requires a bump to the release version of our SPDK v21.07 to fix, correct?

2022-05-25 20:27 UTC, brianjmurrell commented
> So this requires a bump to the release version of our SPDK v21.07 to fix, correct?

While my comment is technically correct, it doesn't seem reasonable to try to fix history at this point.  So while it would be most correct to update the spdk being used for _release/2.x_ branches, to have spdk-dev require dpdk-dev like the RPMs do, it's not practical, so let's just continue to have the `debian/control` have `dpdk-dev` in it's `Build-Depends:`.  Let's leave the `libisal-dev` in there as that is technically correct, but let's put back the `dpdk-dev (<<21.11)` for the `release/2.x` PRs.  Apologies for all of the confusion.  Just too much going on at once to keep it all straight unfortunately.

2022-05-25 21:38 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-26 11:00 UTC, brianjmurrell approved these changes

2022-05-27 14:15 UTC, mjmac approved these changes

2022-05-27 14:30 UTC, merged