Ec rotate online reintegration
daos-stack/daos pull request #9200
Opened 2022-05-29 05:27 UTC by wangdi1

patch to include all patches for EC rotation and online reintegration for testing purpose.

2022-05-29 05:30 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9200/1/execution/node/113/log

2022-06-01 05:18 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9200/2/execution/node/104/log

2022-06-02 04:26 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9200/4/execution/node/151/log

2022-06-02 04:33 UTC, daosbuild1 commented
Test stage Build on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9200/4/execution/node/435/log

2022-06-02 04:33 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9200/4/execution/node/369/log

2022-06-02 04:36 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9200/4/execution/node/412/log

2022-06-02 04:37 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9200/4/execution/node/415/log

2022-06-02 04:39 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9200/4/execution/node/409/log

2022-11-03 22:50 UTC, jolivier23 requested changes
patch has conflicts.  Please convert to draft PR if it's not for review as it's adding watchers automatically.

2022-11-03 22:55 UTC, wangdi1 commented
close this PR. the patch has been moved to other PR.

2022-11-03 22:55 UTC, closed without merging