DAOS-10621 test: Fix weekly-testing timed builds
daos-stack/daos pull request #9212
Opened 2022-05-31 20:13 UTC by phender

Moving to using CHANGE_TARGET resolves the issue of running with the
correct daos RPMs in a weekly-testing* branch PR, but this variable is
not set during timed weekly-testing* builds.  Use the BRANCH_NAME
variable if the CHANGE_TARGET variable is not set to allow
weekly-testing* timed builds to install the correct doas RPMs.

Skip-unit-tests: true
Test-tag: always_passes

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

2022-05-31 20:16 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-05-31 20:44 UTC, daltonbohning approved these changes

2022-06-01 12:32 UTC, brianjmurrell requested changes

2022-06-01 12:32 UTC, brianjmurrell commented on ci/provisioning/post_provision_config.sh
> +           CHANGE_TARGET=\"${CHANGE_TARGET:-$BRANCH_NAME}\"
Per the PR for the other branch, `$CHANGE_TARGET` should be considered immutable and you can do your this-or-that substitution where you need the either/or value.

2022-06-01 17:58 UTC, daltonbohning approved these changes

2022-06-02 15:17 UTC, brianjmurrell approved these changes

2022-06-02 19:02 UTC, merged