DAOS-10816 build: Update install_ubuntu.sh
daos-stack/daos pull request #9311
Opened 2022-06-09 20:28 UTC by kjacque

Added meson and pyelftools to the list of packages to be installed.
These two are required when building dependencies (--build-deps=yes)
for DAOS developers.

Signed-off-by: Kris Jacque <kristin.jacque@intel.com>

2022-06-09 20:29 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-06-09 20:33 UTC, ashleypittman requested changes
We install these packages through pip on all distros when using the dockerfiles, as shown in https://github.com/daos-stack/daos/blob/master/docs/admin/installation.md

The commands you want are these ones:
```sh
python3 -m pip venv venv
source venv/bin/activate
python3 -m pip install -r requirments.txt
```
Once you've done this once you just need the `source` command for new shells.

2022-06-09 23:51 UTC, kjacque commented
> We install these packages through pip on all distros when using the dockerfiles, as shown in https://github.com/daos-stack/daos/blob/master/docs/admin/installation.md
> 
> The commands you want are these ones:
> 
> ```shell
> python3 -m venv venv
> source venv/bin/activate
> python3 -m pip install -r requirements.txt
> ```
> 
> Once you've done this once you just need the `source` command for new shells.

Ah, understood. Any reason not to include the pip installs in the install-*.sh scripts?

2022-06-10 06:59 UTC, ashleypittman commented
> > We install these packages through pip on all distros when using the dockerfiles, as shown in https://github.com/daos-stack/daos/blob/master/docs/admin/installation.md
> > The commands you want are these ones:
> > ```shell
> > python3 -m venv venv
> > source venv/bin/activate
> > python3 -m pip install -r requirements.txt
> > ```
> > 
> > Once you've done this once you just need the `source` command for new shells.
> 
> Ah, understood. Any reason not to include the pip installs in the install-*.sh scripts?

Unfortunately yes, the install-*.sh scripts are run as root and the python/pip commands need to be run as the user.

2022-06-10 14:16 UTC, kjacque commented
> Unfortunately yes, the install-*.sh scripts are run as root and the python/pip commands need to be run as the user.

Got it. I wonder, would it be acceptable to add a script that calls the other script(s) with sudo and pip without? For ease of setting up a new environment.

2022-06-10 18:37 UTC, jolivier23 commented
> > Unfortunately yes, the install-*.sh scripts are run as root and the python/pip commands need to be run as the user.
> 
> Got it. I wonder, would it be acceptable to add a script that calls the other script(s) with sudo and pip without? For ease of setting up a new environment.
> 
> I'm thinking something that figures out the OS and calls the right install-*.sh script.

I think having an install script for user stuff would be good.

2022-06-10 18:59 UTC, jolivier23 reviewed
Adding a comment to clear the review.   Need to address Ashley's comment. I think a separate script would be nice.

2022-06-10 19:17 UTC, ashleypittman commented
> > Unfortunately yes, the install-*.sh scripts are run as root and the python/pip commands need to be run as the user.
> 
> Got it. I wonder, would it be acceptable to add a script that calls the other script(s) with sudo and pip without? For ease of setting up a new environment.
> 
> I'm thinking something that figures out the OS and calls the right install-*.sh script.

It's really just two commands, one to setup the virtual environment, "source" which is a bash function to load it and another command to install the code, so even if you did put it in a script it would reduce the number of commands you'd need to know from three to two.  The dockerfiles have to setup the environment via docker rather than sourcing the bash script so they wouldn't benefit from such a script anyway.

2022-06-10 22:08 UTC, kjacque commented
> It's really just two commands, one to setup the virtual environment, "source" which is a bash function to load it and another command to install the code, so even if you did put it in a script it would reduce the number of commands you'd need to know from three to two. The dockerfiles have to setup the environment via docker rather than sourcing the bash script so they wouldn't benefit from such a script anyway.

I'm thinking from the developer perspective, setting up a new dev/build environment. We do it so rarely it's just very easy to forget there's more to do than run the install script. Even if it's just a couple lines, it's still helpful for it to live outside a dockerfile, for the folks who are developing without docker. Otherwise we have to both remember it exists and hunt for it...

2022-06-10 22:52 UTC, kjacque commented
Put up a different proposal in #9330. I'll close this one as it's not the right way to solve this problem.

2022-06-10 22:52 UTC, closed without merging