DAOS-10525 rebuild: fix data shard rebuild epoch (#9382)
daos-stack/daos pull request #9405
Opened 2022-06-17 15:45 UTC by wangdi1

EC data shard rebuild epoch should be no higher than
the replicate data epoch on the parity shard, otherwise
parity shard might have lower epoch than its data shard,
which can cause data corruption for degraded fetch.

Add test case to verify it.

Signed-off-by: Di Wang <di.wang@intel.com>

2022-06-17 15:46 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-06-19 14:04 UTC, liuxuezhao approved these changes

2022-06-24 01:59 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-04 06:19 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-07 16:27 UTC, jolivier23 requested changes
This one has a conflict now.  

Please add release-2.2 and [un]clean-cherry-pick labels to the PR when you update.

2022-07-27 15:57 UTC, wangdi1 commented
this patch is not needed anymore

2022-07-27 15:57 UTC, closed without merging