DAOS-1452 test: ensure ULTs stacks are dumped when needed (#7768)
daos-stack/daos pull request #9468
Opened 2022-06-22 14:11 UTC by bfaccini

Address issues with dumping ULTs stacks upon failure/timeout
during CI tests. Add test case to verify this functionality.
Please note that those tests are not run for now since they
report legitimate errors.

Change-Id: Id48031bc7a262cb27aaaac8e4726d45265ad9c88
Test-tag: pr,test_daos_server_dump_basic
Signed-off-by: Bruno Faccini <bruno.faccini@intel.com>

2022-06-24 16:10 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9468/1/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/general_utils.py:162](https://github.com/daos-stack/daos/blob/299419d720748b8848826d67560dc4737aa34fa4/src/tests/ftest/util/general_utils.py#L162):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:267](https://github.com/daos-stack/daos/blob/299419d720748b8848826d67560dc4737aa34fa4/src/tests/ftest/util/general_utils.py#L267):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in function call

[src/tests/ftest/util/general_utils.py:204](https://github.com/daos-stack/daos/blob/299419d720748b8848826d67560dc4737aa34fa4/src/tests/ftest/util/general_utils.py#L204):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:462](https://github.com/daos-stack/daos/blob/299419d720748b8848826d67560dc4737aa34fa4/src/tests/ftest/util/general_utils.py#L462):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:472](https://github.com/daos-stack/daos/blob/299419d720748b8848826d67560dc4737aa34fa4/src/tests/ftest/util/general_utils.py#L472):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/server_utils.py:1](https://github.com/daos-stack/daos/blob/299419d720748b8848826d67560dc4737aa34fa4/src/tests/ftest/util/server_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1116/1000)

[src/tests/ftest/util/server_utils.py:73](https://github.com/daos-stack/daos/blob/299419d720748b8848826d67560dc4737aa34fa4/src/tests/ftest/util/server_utils.py#L73):
(pylint-too-many-arguments) Too many arguments (11/10)

[src/tests/ftest/util/server_utils.py:849](https://github.com/daos-stack/daos/blob/299419d720748b8848826d67560dc4737aa34fa4/src/tests/ftest/util/server_utils.py#L849):
(pylint-unspecified-encoding) Using open without explicitly specifying an encoding

2022-06-24 16:10 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9468/1/execution/node/115/log

2022-06-24 16:31 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9468/1/execution/node/333/log

2022-06-24 16:32 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9468/1/execution/node/411/log

2022-06-29 15:15 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9468/2/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/general_utils.py:162](https://github.com/daos-stack/daos/blob/263b7db42336f3a6e1c9e4dc79b81e804a752c6f/src/tests/ftest/util/general_utils.py#L162):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:267](https://github.com/daos-stack/daos/blob/263b7db42336f3a6e1c9e4dc79b81e804a752c6f/src/tests/ftest/util/general_utils.py#L267):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in function call

[src/tests/ftest/util/general_utils.py:204](https://github.com/daos-stack/daos/blob/263b7db42336f3a6e1c9e4dc79b81e804a752c6f/src/tests/ftest/util/general_utils.py#L204):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:462](https://github.com/daos-stack/daos/blob/263b7db42336f3a6e1c9e4dc79b81e804a752c6f/src/tests/ftest/util/general_utils.py#L462):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:472](https://github.com/daos-stack/daos/blob/263b7db42336f3a6e1c9e4dc79b81e804a752c6f/src/tests/ftest/util/general_utils.py#L472):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/server_utils.py:1](https://github.com/daos-stack/daos/blob/263b7db42336f3a6e1c9e4dc79b81e804a752c6f/src/tests/ftest/util/server_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1116/1000)

[src/tests/ftest/util/server_utils.py:73](https://github.com/daos-stack/daos/blob/263b7db42336f3a6e1c9e4dc79b81e804a752c6f/src/tests/ftest/util/server_utils.py#L73):
(pylint-too-many-arguments) Too many arguments (11/10)

[src/tests/ftest/util/server_utils.py:849](https://github.com/daos-stack/daos/blob/263b7db42336f3a6e1c9e4dc79b81e804a752c6f/src/tests/ftest/util/server_utils.py#L849):
(pylint-unspecified-encoding) Using open without explicitly specifying an encoding

2022-06-29 15:15 UTC, daosbuild1 commented on src/tests/ftest/server/daos_server_dump.py
> +        self._Test__status = 'PASS'
(pylint-attribute-defined-outside-init) Attribute '_Test__status' defined outside __init__

2022-06-29 15:15 UTC, daosbuild1 commented on src/tests/ftest/server/daos_server_dump.py
> +            self._Test__status = 'FAIL'
(pylint-attribute-defined-outside-init) Attribute '_Test__status' defined outside __init__

2022-06-29 15:15 UTC, daosbuild1 commented on src/tests/ftest/util/apricot/apricot/test.py
> +    dump_engines_stacks
(pylint-syntax-error) invalid syntax (<unknown>, line 31)

2022-06-29 15:15 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9468/2/execution/node/107/log

2022-06-29 15:28 UTC, daosbuild1 commented
Test stage Build RPM on CentOS 7 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9468/2/execution/node/366/log

2022-07-05 12:38 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9468/3/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/general_utils.py:162](https://github.com/daos-stack/daos/blob/e3f7d44221feaa870f6a5487a6be07c2b1524c08/src/tests/ftest/util/general_utils.py#L162):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:267](https://github.com/daos-stack/daos/blob/e3f7d44221feaa870f6a5487a6be07c2b1524c08/src/tests/ftest/util/general_utils.py#L267):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in function call

[src/tests/ftest/util/general_utils.py:204](https://github.com/daos-stack/daos/blob/e3f7d44221feaa870f6a5487a6be07c2b1524c08/src/tests/ftest/util/general_utils.py#L204):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:462](https://github.com/daos-stack/daos/blob/e3f7d44221feaa870f6a5487a6be07c2b1524c08/src/tests/ftest/util/general_utils.py#L462):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:472](https://github.com/daos-stack/daos/blob/e3f7d44221feaa870f6a5487a6be07c2b1524c08/src/tests/ftest/util/general_utils.py#L472):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/server_utils.py:1](https://github.com/daos-stack/daos/blob/e3f7d44221feaa870f6a5487a6be07c2b1524c08/src/tests/ftest/util/server_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1116/1000)

[src/tests/ftest/util/server_utils.py:73](https://github.com/daos-stack/daos/blob/e3f7d44221feaa870f6a5487a6be07c2b1524c08/src/tests/ftest/util/server_utils.py#L73):
(pylint-too-many-arguments) Too many arguments (11/10)

[src/tests/ftest/util/server_utils.py:849](https://github.com/daos-stack/daos/blob/e3f7d44221feaa870f6a5487a6be07c2b1524c08/src/tests/ftest/util/server_utils.py#L849):
(pylint-unspecified-encoding) Using open without explicitly specifying an encoding

2022-07-05 12:38 UTC, daosbuild1 commented on src/tests/ftest/server/daos_server_dump.py
> +        self._Test__status = 'PASS'
(pylint-attribute-defined-outside-init) Attribute '_Test__status' defined outside __init__

2022-07-05 12:38 UTC, daosbuild1 commented on src/tests/ftest/server/daos_server_dump.py
> +            self._Test__status = 'FAIL'
(pylint-attribute-defined-outside-init) Attribute '_Test__status' defined outside __init__

2022-07-05 12:38 UTC, daosbuild1 commented on src/tests/ftest/util/apricot/apricot/test.py
> +    dump_engines_stacks
(pylint-syntax-error) invalid syntax (<unknown>, line 31)

2022-07-05 12:38 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9468/3/execution/node/122/log

2022-07-05 12:46 UTC, daosbuild1 requested changes
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9468/4/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/apricot/apricot/test.py:145](https://github.com/daos-stack/daos/blob/a24ab5bdcb7b4e02b16938b3f5efc48f701a9c69/src/tests/ftest/util/apricot/apricot/test.py#L145):
(pylint-unspecified-encoding) Using open without explicitly specifying an encoding

[src/tests/ftest/util/apricot/apricot/test.py:167](https://github.com/daos-stack/daos/blob/a24ab5bdcb7b4e02b16938b3f5efc48f701a9c69/src/tests/ftest/util/apricot/apricot/test.py#L167):
(pylint-unspecified-encoding) Using open without explicitly specifying an encoding

[src/tests/ftest/util/apricot/apricot/test.py:185](https://github.com/daos-stack/daos/blob/a24ab5bdcb7b4e02b16938b3f5efc48f701a9c69/src/tests/ftest/util/apricot/apricot/test.py#L185):
(pylint-unspecified-encoding) Using open without explicitly specifying an encoding

[src/tests/ftest/util/apricot/apricot/test.py:198](https://github.com/daos-stack/daos/blob/a24ab5bdcb7b4e02b16938b3f5efc48f701a9c69/src/tests/ftest/util/apricot/apricot/test.py#L198):
(pylint-unspecified-encoding) Using open without explicitly specifying an encoding

[src/tests/ftest/util/apricot/apricot/test.py:218](https://github.com/daos-stack/daos/blob/a24ab5bdcb7b4e02b16938b3f5efc48f701a9c69/src/tests/ftest/util/apricot/apricot/test.py#L218):
(pylint-unspecified-encoding) Using open without explicitly specifying an encoding

[src/tests/ftest/util/apricot/apricot/test.py:616](https://github.com/daos-stack/daos/blob/a24ab5bdcb7b4e02b16938b3f5efc48f701a9c69/src/tests/ftest/util/apricot/apricot/test.py#L616):
(pylint-protected-access) Access to a protected member _check_info of a client class

[src/tests/ftest/util/general_utils.py:162](https://github.com/daos-stack/daos/blob/a24ab5bdcb7b4e02b16938b3f5efc48f701a9c69/src/tests/ftest/util/general_utils.py#L162):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:267](https://github.com/daos-stack/daos/blob/a24ab5bdcb7b4e02b16938b3f5efc48f701a9c69/src/tests/ftest/util/general_utils.py#L267):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in function call

[src/tests/ftest/util/general_utils.py:204](https://github.com/daos-stack/daos/blob/a24ab5bdcb7b4e02b16938b3f5efc48f701a9c69/src/tests/ftest/util/general_utils.py#L204):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:462](https://github.com/daos-stack/daos/blob/a24ab5bdcb7b4e02b16938b3f5efc48f701a9c69/src/tests/ftest/util/general_utils.py#L462):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:472](https://github.com/daos-stack/daos/blob/a24ab5bdcb7b4e02b16938b3f5efc48f701a9c69/src/tests/ftest/util/general_utils.py#L472):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/server_utils.py:1](https://github.com/daos-stack/daos/blob/a24ab5bdcb7b4e02b16938b3f5efc48f701a9c69/src/tests/ftest/util/server_utils.py#L1):
(pylint-too-many-lines) Too many lines in module (1116/1000)

[src/tests/ftest/util/server_utils.py:73](https://github.com/daos-stack/daos/blob/a24ab5bdcb7b4e02b16938b3f5efc48f701a9c69/src/tests/ftest/util/server_utils.py#L73):
(pylint-too-many-arguments) Too many arguments (11/10)

[src/tests/ftest/util/server_utils.py:849](https://github.com/daos-stack/daos/blob/a24ab5bdcb7b4e02b16938b3f5efc48f701a9c69/src/tests/ftest/util/server_utils.py#L849):
(pylint-unspecified-encoding) Using open without explicitly specifying an encoding

2022-07-05 12:46 UTC, daosbuild1 commented on src/tests/ftest/server/daos_server_dump.py
> +            self._Test__status = 'FAIL'
(pylint-attribute-defined-outside-init) Attribute '_Test__status' defined outside __init__

2022-07-05 12:46 UTC, daosbuild1 commented on src/tests/ftest/util/apricot/apricot/test.py
> +    def fail(self, message=None):
(pylint-arguments-renamed) Parameter 'msg' has been renamed to 'self' in overridden 'TestWithServers.fail' method

2022-07-05 12:46 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9468/4/execution/node/123/log

2022-07-08 07:37 UTC, bfaccini commented
@sylviachanoiyee and @phender , any chance you can review this ??

2022-07-08 19:52 UTC, jolivier23 requested changes
Some of these changes seem to be related to a bad merge or something.  Can you please check?

2022-07-09 13:13 UTC, bfaccini commented
> Some of these changes seem to be related to a bad merge or something. Can you please check?

Well, I did not look to the diff details, but yes you are right and I don't know what has happen... Should I close/remove this branch and create a new one @jolivier23 ??

2022-07-18 17:17 UTC, closed without merging