DAOS-10898 obj: remove incorrect assert in small_io test (#10898)
daos-stack/daos pull request #9486
Opened 2022-06-23 06:16 UTC by fengchunsong

daos_array_read with type=DAOS_OT_ARRAY, the array->byte_array is false,
then it don't invoke tse_task_register_cbs to register check_short_read_cb,
so iod.arr_nr_short_read isn't modified.

Signed-off-by: Chunsong Feng <fengchunsong@huawei.com>

2022-06-23 06:17 UTC, fengchunsong commented
@wangshilong @mchaarawi please help to review.

2022-06-23 08:18 UTC, wangshilong requested changes
Following fix looks better? we shall use DAOS_OT_ARRAY_BYTE to generate OID.

```
diff --git a/src/tests/suite/daos_array.c b/src/tests/suite/daos_array.c
index eddfdbe..cbcbed4 100644
--- a/src/tests/suite/daos_array.c
+++ b/src/tests/suite/daos_array.c
@@ -224,7 +224,7 @@ small_io(void **state)
        int             rc;

        par_barrier(PAR_COMM_WORLD);
-       oid = daos_test_oid_gen(arg->coh, OC_SX, type, 0, arg->myrank);
+       oid = daos_test_oid_gen(arg->coh, OC_SX, typeb, 0, arg->myrank);

        /** create the array */
        rc = daos_array_create(arg->coh, oid, DAOS_TX_NONE, 1, 1048576, &oh,
@@ -254,6 +254,7 @@ small_io(void **state)

        d_iov_set(&iov, rbuf, BUFLEN);
        sgl.sg_iovs = &iov;
+       iod.arr_nr_short_read = 1;
        rc = daos_array_read(oh, DAOS_TX_NONE, &iod, &sgl, NULL);
        assert_rc_equal(rc, 0);
        assert_int_equal(iod.arr_nr_short_read, 0);
```

2022-06-23 08:26 UTC, fengchunsong commented
> Following fix looks better? we shall use DAOS_OT_ARRAY_BYTE to generate OID.
> 
> ```
> diff --git a/src/tests/suite/daos_array.c b/src/tests/suite/daos_array.c
> index eddfdbe..cbcbed4 100644
> --- a/src/tests/suite/daos_array.c
> +++ b/src/tests/suite/daos_array.c
> @@ -224,7 +224,7 @@ small_io(void **state)
>         int             rc;
> 
>         par_barrier(PAR_COMM_WORLD);
> -       oid = daos_test_oid_gen(arg->coh, OC_SX, type, 0, arg->myrank);
> +       oid = daos_test_oid_gen(arg->coh, OC_SX, typeb, 0, arg->myrank);
> 
>         /** create the array */
>         rc = daos_array_create(arg->coh, oid, DAOS_TX_NONE, 1, 1048576, &oh,
> @@ -254,6 +254,7 @@ small_io(void **state)
> 
>         d_iov_set(&iov, rbuf, BUFLEN);
>         sgl.sg_iovs = &iov;
> +       iod.arr_nr_short_read = 1;
>         rc = daos_array_read(oh, DAOS_TX_NONE, &iod, &sgl, NULL);
>         assert_rc_equal(rc, 0);
>         assert_int_equal(iod.arr_nr_short_read, 0);
> ```
Yes, it's more better.

2022-06-23 08:36 UTC, wangshilong approved these changes

2022-06-24 16:37 UTC, mchaarawi commented
I pulled this PR into an internal one here and it passed:
https://github.com/daos-stack/daos/pull/9493
result:
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-9493/2/pipeline

2022-06-27 17:36 UTC, merged