DAOS-10887 test: Remove single service leader from yaml file
daos-stack/daos pull request #9528
Opened 2022-06-27 15:43 UTC by saurabhtandan

Remove single pool service leader from test yaml

Test-tag: widelystriped
Test-repeat: 5

Signed-off-by: Saurabh Tandan <saurabh.tandan@intel.com>

2022-06-28 17:33 UTC, daltonbohning requested changes
Just realized the test tag is wrong. It should be `rebuild_widely_striped`, as `widelystriped` does not exist
https://github.com/daos-stack/daos/blob/bafa50a19f4ea0d2be74df963c8dac61c41cf862/src/tests/ftest/rebuild/widely_striped.py#L48

2022-06-28 22:29 UTC, daltonbohning approved these changes

2022-06-29 11:37 UTC, shimizukko approved these changes

2022-07-05 20:16 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-08 13:58 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9528/4/execution/node/656/log

2022-07-08 19:49 UTC, jolivier23 reviewed
Add gatekeeper when ready to go

2022-07-15 03:04 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9528/5/execution/node/655/log

2022-07-18 16:26 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9528/6/execution/node/213/log

2022-07-18 16:28 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9528/6/execution/node/206/log

2022-07-18 16:30 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9528/6/execution/node/237/log

2022-07-23 11:31 UTC, shimizukko submitted a review, later dismissed

2022-07-25 14:45 UTC, daltonbohning approved these changes

2022-08-12 19:35 UTC, saurabhtandan commented
Closing this PR as it was taken care in the following PR
https://github.com/daos-stack/daos/pull/9827

2022-08-12 19:35 UTC, closed without merging