DAOS-10365 dfuse: Allow dfuse caching of attributes.
daos-stack/daos pull request #9565
Opened 2022-06-30 15:29 UTC by ashleypittman

2022-06-30 15:31 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-01 10:48 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-01 15:39 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-04 08:59 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-07 14:43 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-07 14:50 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-08 08:46 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-08 09:14 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-13 14:26 UTC, ashleypittman commented
This is failing in CI however I've verified what should be the same I/O pattern locally and it passes 20/20 times.  Still investigating.

2022-07-13 14:27 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-13 17:19 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9565/10/display/redirect

2022-07-14 07:26 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-14 07:32 UTC, daosbuild1 commented
Test stage Build DEB on Ubuntu 20.04 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9565/11/execution/node/335/log

2022-07-14 07:32 UTC, daosbuild1 commented
Test stage Build RPM on Leap 15 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9565/11/execution/node/338/log

2022-07-14 07:36 UTC, daosbuild1 commented
Test stage Build on Leap 15 with Intel-C and TARGET_PREFIX completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9565/11/execution/node/407/log

2022-07-14 07:36 UTC, daosbuild1 commented
Test stage Build RPM on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9565/11/execution/node/398/log

2022-07-14 08:46 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-14 16:59 UTC, daltonbohning approved these changes

2022-07-18 20:00 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-21 08:03 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-21 11:39 UTC, ashleypittman commented
This PR is also causing intermittent NLT failures with test_truncate_with_caching

2022-07-22 13:42 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-01 18:00 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-08 08:53 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-22 10:35 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-23 10:43 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-25 11:37 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-31 10:30 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-31 11:54 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-9565/23/testReport/(root)/

2022-08-31 18:50 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-01 00:30 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-9565/24/testReport/(root)/

2022-09-01 10:19 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-06 09:41 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-06 12:52 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-9565/26/testReport/(root)/

2022-09-06 15:27 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-06 16:23 UTC, daosbuild1 commented
Test stage NLT on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9565/27/execution/node/621/log

2022-09-07 07:30 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-07 09:34 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-07 09:38 UTC, ashleypittman commented on src/client/dfuse/dfuse.h
> +		dfuse_cache_set_time(desc);                                                        \
I think we should probably remove this.

2022-09-07 09:46 UTC, daosbuild1 commented
Test stage NLT on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9565/29/display/redirect

2022-09-07 09:47 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-07 10:50 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-9565/30/testReport/(root)/

2022-09-07 15:09 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-07 16:17 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-9565/31/testReport/(root)/

2022-09-07 22:28 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9565/32/execution/node/889/log

2022-09-08 12:38 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-08 16:31 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-9565/34/testReport/(root)/

2022-09-09 08:12 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-09 12:16 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-9565/35/testReport/(root)/

2022-09-09 15:01 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-10 07:47 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status UNSTABLE.  https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-9565/36/testReport/(root)/

2022-09-12 10:45 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-12 17:32 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-13 16:24 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-13 16:57 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-14 07:22 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-14 08:33 UTC, daosbuild1 commented
Test stage Unit Test on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9565/42/execution/node/618/log

2022-09-16 16:04 UTC, jolivier23 submitted a review, later dismissed

2022-09-16 16:14 UTC, daltonbohning submitted a review, later dismissed

2022-09-16 17:09 UTC, mchaarawi requested changes
i still have not had a chance to retry after the latest update, so hold on before landing

2022-09-20 17:53 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-20 20:05 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-20 21:37 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-21 11:25 UTC, ashleypittman commented
This has passed a key test in CI, please can I request re-review.

2022-09-21 12:41 UTC, mchaarawi approved these changes

2022-09-21 17:04 UTC, daltonbohning approved these changes

2022-09-21 17:24 UTC, merged