DAOS-11130 object: fix name match in daos_oclass_name2id()
daos-stack/daos pull request #9703
Opened 2022-07-14 15:19 UTC by wangshilong

If name is shorter than @oc_name, eg, RP_3G3 could match
RP_3G32, fix to require name length match as well.

Signed-off-by: Wang Shilong <shilong.wang@intel.com>
Required-githooks: true

2022-07-14 15:20 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-14 15:24 UTC, wangshilong commented on src/object/obj_class.c
>  	for (oc = &daos_obj_classes[0]; oc->oc_id != OC_UNKNOWN; oc++) {
@gnailzenh A further question is should we support more oclass name than defined?
Eg, if users pass RP_3G3, we should return id as: 3 << 24 | 3

And we need modify daos_oclass_id2name() to convert ID to oclass name(need be careful for overflow though)

2022-07-20 12:41 UTC, bfaccini submitted a review, later dismissed

2022-07-21 14:54 UTC, wiliamhuang submitted a review, later dismissed

2022-07-21 20:30 UTC, jolivier23 requested changes

2022-07-21 20:30 UTC, jolivier23 commented on src/object/obj_class.c
> +		    strncmp(oc->oc_name, name, strlen(name)) == 0)
do you really need strncmp if you just checked the string length?  I think coverity will probably complain about this.  Perhaps it should be strlen(oc->oc_name) == strnlen(name, SOME_MAX_STRLEN) && strcmp(....)

where SOME_MAX_STRLEN is bigger than any of the known names.

2022-07-28 02:05 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-07-28 02:27 UTC, wiliamhuang approved these changes

2022-07-29 19:37 UTC, jolivier23 approved these changes

2022-08-04 22:13 UTC, merged