DAOS-11160 - Fixing Misspelling of 'Sending' in test messages.
daos-stack/daos pull request #9933
Opened 2022-08-08 21:06 UTC by kalfizah

Signed-off-by: Kurniawan Alfizah <kurniawan.alfizah@intel.com>

2022-08-08 21:34 UTC, jamesanunez approved these changes

2022-08-08 21:40 UTC, phender approved these changes

2022-08-08 21:44 UTC, phender commented
@kalfizah the Jira Report GHA failed with "Errors are component not formatted correctly" because the title of the commit is missing a component, e.g "DAOS-11160 <component>: Fixing Misspelling of 'Sending' in test messages.".  In this case the component should be "test".

2022-08-08 21:48 UTC, phender requested changes
The code changes look fine.

The Jira Report GHA failed with "Errors are component not formatted correctly" because the title of the commit is missing a component, e.g `DAOS-11160 [component]: Fixing Misspelling of 'Sending' in test messages.`. In this case the component should be `test`.

The PR has also failed "Check PR" in https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-9933/1/pipeline. Please follow the instructions in the error message. Unfortunately this requires a new PR.

2022-08-16 17:45 UTC, kalfizah commented
Need to fix and create a new PR. So I close this one. Thanks.

2022-08-16 17:45 UTC, closed without merging