DAOS-11121 build: don't ship daos-mofed shim RPM
daos-stack/daos pull request #9934
Opened 2022-08-08 21:27 UTC by Michael-Hennecke

add daos-mofed* to .rpmignore

Signed-off-by: Michael Hennecke <michael.hennecke@intel.com>

2022-08-08 21:28 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-08 22:31 UTC, JohnMalmberg approved these changes

2022-08-08 22:35 UTC, JohnMalmberg requested changes
This is still going to pull in mercury-ucx*rpms on el-8 and leap15.

2022-08-09 08:03 UTC, Michael-Hennecke commented
> This is still going to pull in mercury-ucx*rpms on el-8 and leap15.

Yes, you reported that under a different ticket, DAOS-11121, and the PR for that is https://github.com/daos-stack/daos/pull/9691 ...

2022-08-09 09:13 UTC, merged