DAOS-9601 chk: container cleanup
daos-stack/daos pull request #9977
Opened 2022-08-14 15:02 UTC by Nasf-Fan

Destroy the orphan containers that have storage allocated on
the engine but do not exist in container service by default.

Signed-off-by: Fan Yong <fan.yong@intel.com>

2022-08-14 15:04 UTC, daosbuild1 requested changes

2022-08-14 15:04 UTC, daosbuild1 commented on src/container/srv_container.c
> +	D_DEBUG(DB_MD, DF_CONT" destory orphan container: "DF_RC"\n",
```suggestion
	D_DEBUG(DB_MD, DF_CONT" destroy orphan container: "DF_RC"\n",
```

2022-08-14 15:04 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9977/1/execution/node/145/log

2022-08-14 15:06 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-15 00:14 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-16 03:13 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-20 01:55 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-20 12:57 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-24 15:53 UTC, daosbuild1 submitted a review, later dismissed
Style warning(s) for job https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9977/7/
Please review https://wiki.hpdd.intel.com/display/DC/Coding+Rules

2022-08-24 15:53 UTC, daosbuild1 commented on src/chk/chk_internal.h
> +#define DAOS_ISEQ_CHK_CONT_LIST							\
(style)  Macros with complex values should be enclosed in parentheses

2022-08-24 15:53 UTC, daosbuild1 commented on src/chk/chk_internal.h
> +#define DAOS_OSEQ_CHK_CONT_LIST							\
(style)  Macros with complex values should be enclosed in parentheses

2022-08-24 15:53 UTC, daosbuild1 commented
Test stage checkpatch completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9977/7/execution/node/144/log

2022-08-24 16:05 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-24 16:17 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-26 03:11 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-26 09:04 UTC, liw requested changes

2022-08-26 15:28 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-08-26 18:48 UTC, daosbuild1 commented
Test stage Functional on EL 8 completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9977/16/execution/node/888/log

2022-08-26 19:00 UTC, daosbuild1 commented
Test stage Functional Hardware Medium completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9977/16/execution/node/1011/log

2022-08-26 19:19 UTC, daosbuild1 commented
Test stage Functional Hardware Large completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9977/16/execution/node/1131/log

2022-08-26 19:21 UTC, daosbuild1 commented
Test stage Functional Hardware Small completed with status FAILURE.  https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-9977/16/execution/node/1189/log

2022-08-29 00:33 UTC, liw approved these changes

2022-08-29 00:44 UTC, Nasf-Fan commented
Because of the issue of undefined variable "CommandWithPositionalParameters", I forked another PR#10129 to replace this one with different base.

2022-08-29 00:44 UTC, closed without merging