DAOS-11205 test: support access_points_suffix
daos-stack/daos pull request #9986
Opened 2022-08-15 23:13 UTC by daltonbohning

Test-tag: pr,-hw

Support specifying access_points_suffix in test config, which will be
appended to each hostname.

Required-githooks: true

Signed-off-by: Dalton Bohning <dalton.bohning@intel.com>

2022-08-16 16:47 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/apricot/apricot/test.py:1330](https://github.com/daos-stack/daos/blob/0e5e6ee68be137c04407d0080302ba21eccba976/src/tests/ftest/util/apricot/apricot/test.py#L1330):
(pylint-arguments-renamed) Parameter 'msg' has been renamed to 'self' in overridden 'TestWithServers.fail' method

[src/tests/ftest/util/apricot/apricot/test.py:1335](https://github.com/daos-stack/daos/blob/0e5e6ee68be137c04407d0080302ba21eccba976/src/tests/ftest/util/apricot/apricot/test.py#L1335):
(pylint-arguments-renamed) Parameter 'msg' has been renamed to 'self' in overridden 'TestWithServers.error' method

[src/tests/ftest/util/general_utils.py:161](https://github.com/daos-stack/daos/blob/0e5e6ee68be137c04407d0080302ba21eccba976/src/tests/ftest/util/general_utils.py#L161):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:266](https://github.com/daos-stack/daos/blob/0e5e6ee68be137c04407d0080302ba21eccba976/src/tests/ftest/util/general_utils.py#L266):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in function call

[src/tests/ftest/util/general_utils.py:203](https://github.com/daos-stack/daos/blob/0e5e6ee68be137c04407d0080302ba21eccba976/src/tests/ftest/util/general_utils.py#L203):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:480](https://github.com/daos-stack/daos/blob/0e5e6ee68be137c04407d0080302ba21eccba976/src/tests/ftest/util/general_utils.py#L480):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:490](https://github.com/daos-stack/daos/blob/0e5e6ee68be137c04407d0080302ba21eccba976/src/tests/ftest/util/general_utils.py#L490):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/server_utils.py:74](https://github.com/daos-stack/daos/blob/0e5e6ee68be137c04407d0080302ba21eccba976/src/tests/ftest/util/server_utils.py#L74):
(pylint-too-many-arguments) Too many arguments (12/10)

2022-08-16 17:11 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/apricot/apricot/test.py:1330](https://github.com/daos-stack/daos/blob/439d442259103958b36f3e9cfc5bceb2f5432cf2/src/tests/ftest/util/apricot/apricot/test.py#L1330):
(pylint-arguments-renamed) Parameter 'msg' has been renamed to 'self' in overridden 'TestWithServers.fail' method

[src/tests/ftest/util/apricot/apricot/test.py:1335](https://github.com/daos-stack/daos/blob/439d442259103958b36f3e9cfc5bceb2f5432cf2/src/tests/ftest/util/apricot/apricot/test.py#L1335):
(pylint-arguments-renamed) Parameter 'msg' has been renamed to 'self' in overridden 'TestWithServers.error' method

[src/tests/ftest/util/general_utils.py:161](https://github.com/daos-stack/daos/blob/439d442259103958b36f3e9cfc5bceb2f5432cf2/src/tests/ftest/util/general_utils.py#L161):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:266](https://github.com/daos-stack/daos/blob/439d442259103958b36f3e9cfc5bceb2f5432cf2/src/tests/ftest/util/general_utils.py#L266):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in function call

[src/tests/ftest/util/general_utils.py:203](https://github.com/daos-stack/daos/blob/439d442259103958b36f3e9cfc5bceb2f5432cf2/src/tests/ftest/util/general_utils.py#L203):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:480](https://github.com/daos-stack/daos/blob/439d442259103958b36f3e9cfc5bceb2f5432cf2/src/tests/ftest/util/general_utils.py#L480):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:490](https://github.com/daos-stack/daos/blob/439d442259103958b36f3e9cfc5bceb2f5432cf2/src/tests/ftest/util/general_utils.py#L490):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/server_utils.py:74](https://github.com/daos-stack/daos/blob/439d442259103958b36f3e9cfc5bceb2f5432cf2/src/tests/ftest/util/server_utils.py#L74):
(pylint-too-many-arguments) Too many arguments (12/10)

2022-08-17 14:58 UTC, daltonbohning commented
@phender The new harness test passed: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9986/3/artifact/Functional%20on%20EL%208/harness/config.py/

2022-08-17 15:01 UTC, daltonbohning commented on src/tests/ftest/harness/config.yaml
> +  test_clients: 1
Just realized my latest change of `test_servers: 2` didn't get pushed... I'll need to update that and re-test before landing

2022-08-19 14:58 UTC, phender submitted a review, later dismissed

2022-08-19 15:07 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/apricot/apricot/test.py:1330](https://github.com/daos-stack/daos/blob/14d4fd89a25369c8009470e93269b88e322ec24c/src/tests/ftest/util/apricot/apricot/test.py#L1330):
(pylint-arguments-renamed) Parameter 'msg' has been renamed to 'self' in overridden 'TestWithServers.fail' method

[src/tests/ftest/util/apricot/apricot/test.py:1335](https://github.com/daos-stack/daos/blob/14d4fd89a25369c8009470e93269b88e322ec24c/src/tests/ftest/util/apricot/apricot/test.py#L1335):
(pylint-arguments-renamed) Parameter 'msg' has been renamed to 'self' in overridden 'TestWithServers.error' method

[src/tests/ftest/util/general_utils.py:161](https://github.com/daos-stack/daos/blob/14d4fd89a25369c8009470e93269b88e322ec24c/src/tests/ftest/util/general_utils.py#L161):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:266](https://github.com/daos-stack/daos/blob/14d4fd89a25369c8009470e93269b88e322ec24c/src/tests/ftest/util/general_utils.py#L266):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in function call

[src/tests/ftest/util/general_utils.py:203](https://github.com/daos-stack/daos/blob/14d4fd89a25369c8009470e93269b88e322ec24c/src/tests/ftest/util/general_utils.py#L203):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:480](https://github.com/daos-stack/daos/blob/14d4fd89a25369c8009470e93269b88e322ec24c/src/tests/ftest/util/general_utils.py#L480):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:490](https://github.com/daos-stack/daos/blob/14d4fd89a25369c8009470e93269b88e322ec24c/src/tests/ftest/util/general_utils.py#L490):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/server_utils.py:74](https://github.com/daos-stack/daos/blob/14d4fd89a25369c8009470e93269b88e322ec24c/src/tests/ftest/util/server_utils.py#L74):
(pylint-too-many-arguments) Too many arguments (12/10)

2022-08-19 20:32 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/apricot/apricot/test.py:1330](https://github.com/daos-stack/daos/blob/5639ab657e5ae2ae04fa6218e864d0eb6b760cb6/src/tests/ftest/util/apricot/apricot/test.py#L1330):
(pylint-arguments-renamed) Parameter 'msg' has been renamed to 'self' in overridden 'TestWithServers.fail' method

[src/tests/ftest/util/apricot/apricot/test.py:1335](https://github.com/daos-stack/daos/blob/5639ab657e5ae2ae04fa6218e864d0eb6b760cb6/src/tests/ftest/util/apricot/apricot/test.py#L1335):
(pylint-arguments-renamed) Parameter 'msg' has been renamed to 'self' in overridden 'TestWithServers.error' method

[src/tests/ftest/util/general_utils.py:161](https://github.com/daos-stack/daos/blob/5639ab657e5ae2ae04fa6218e864d0eb6b760cb6/src/tests/ftest/util/general_utils.py#L161):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:266](https://github.com/daos-stack/daos/blob/5639ab657e5ae2ae04fa6218e864d0eb6b760cb6/src/tests/ftest/util/general_utils.py#L266):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in function call

[src/tests/ftest/util/general_utils.py:203](https://github.com/daos-stack/daos/blob/5639ab657e5ae2ae04fa6218e864d0eb6b760cb6/src/tests/ftest/util/general_utils.py#L203):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:480](https://github.com/daos-stack/daos/blob/5639ab657e5ae2ae04fa6218e864d0eb6b760cb6/src/tests/ftest/util/general_utils.py#L480):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:490](https://github.com/daos-stack/daos/blob/5639ab657e5ae2ae04fa6218e864d0eb6b760cb6/src/tests/ftest/util/general_utils.py#L490):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/server_utils.py:74](https://github.com/daos-stack/daos/blob/5639ab657e5ae2ae04fa6218e864d0eb6b760cb6/src/tests/ftest/util/server_utils.py#L74):
(pylint-too-many-arguments) Too many arguments (12/10)

2022-08-22 14:52 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/apricot/apricot/test.py:1330](https://github.com/daos-stack/daos/blob/892a6df7f420e0dd3eecd6bfa7a54c5fb24a5ed4/src/tests/ftest/util/apricot/apricot/test.py#L1330):
(pylint-arguments-renamed) Parameter 'msg' has been renamed to 'self' in overridden 'TestWithServers.fail' method

[src/tests/ftest/util/apricot/apricot/test.py:1335](https://github.com/daos-stack/daos/blob/892a6df7f420e0dd3eecd6bfa7a54c5fb24a5ed4/src/tests/ftest/util/apricot/apricot/test.py#L1335):
(pylint-arguments-renamed) Parameter 'msg' has been renamed to 'self' in overridden 'TestWithServers.error' method

[src/tests/ftest/util/general_utils.py:161](https://github.com/daos-stack/daos/blob/892a6df7f420e0dd3eecd6bfa7a54c5fb24a5ed4/src/tests/ftest/util/general_utils.py#L161):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:266](https://github.com/daos-stack/daos/blob/892a6df7f420e0dd3eecd6bfa7a54c5fb24a5ed4/src/tests/ftest/util/general_utils.py#L266):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in function call

[src/tests/ftest/util/general_utils.py:203](https://github.com/daos-stack/daos/blob/892a6df7f420e0dd3eecd6bfa7a54c5fb24a5ed4/src/tests/ftest/util/general_utils.py#L203):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:480](https://github.com/daos-stack/daos/blob/892a6df7f420e0dd3eecd6bfa7a54c5fb24a5ed4/src/tests/ftest/util/general_utils.py#L480):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:490](https://github.com/daos-stack/daos/blob/892a6df7f420e0dd3eecd6bfa7a54c5fb24a5ed4/src/tests/ftest/util/general_utils.py#L490):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/server_utils.py:74](https://github.com/daos-stack/daos/blob/892a6df7f420e0dd3eecd6bfa7a54c5fb24a5ed4/src/tests/ftest/util/server_utils.py#L74):
(pylint-too-many-arguments) Too many arguments (12/10)

2022-08-23 18:50 UTC, shimizukko approved these changes

2022-08-26 19:14 UTC, phender requested changes
One minor pylint fix

2022-08-26 19:14 UTC, phender commented on src/tests/ftest/util/server_utils.py
> +                 namespace="/run/server_manager/*", access_points_suffix=None):
```suggestion
                 namespace="/run/server_manager/*", access_points_suffix=None):
        # pylint: disable=too-many-arguments
```

2022-08-26 19:18 UTC, daltonbohning commented on src/tests/ftest/util/server_utils.py
> +                 namespace="/run/server_manager/*", access_points_suffix=None):
Done, thanks

2022-08-26 19:20 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/apricot/apricot/test.py:1330](https://github.com/daos-stack/daos/blob/1a04b7311e4a3f53066d968d7dce0b008029881f/src/tests/ftest/util/apricot/apricot/test.py#L1330):
(pylint-arguments-renamed) Parameter 'msg' has been renamed to 'self' in overridden 'TestWithServers.fail' method

[src/tests/ftest/util/apricot/apricot/test.py:1335](https://github.com/daos-stack/daos/blob/1a04b7311e4a3f53066d968d7dce0b008029881f/src/tests/ftest/util/apricot/apricot/test.py#L1335):
(pylint-arguments-renamed) Parameter 'msg' has been renamed to 'self' in overridden 'TestWithServers.error' method

[src/tests/ftest/util/general_utils.py:161](https://github.com/daos-stack/daos/blob/1a04b7311e4a3f53066d968d7dce0b008029881f/src/tests/ftest/util/general_utils.py#L161):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:266](https://github.com/daos-stack/daos/blob/1a04b7311e4a3f53066d968d7dce0b008029881f/src/tests/ftest/util/general_utils.py#L266):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in function call

[src/tests/ftest/util/general_utils.py:203](https://github.com/daos-stack/daos/blob/1a04b7311e4a3f53066d968d7dce0b008029881f/src/tests/ftest/util/general_utils.py#L203):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:480](https://github.com/daos-stack/daos/blob/1a04b7311e4a3f53066d968d7dce0b008029881f/src/tests/ftest/util/general_utils.py#L480):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:490](https://github.com/daos-stack/daos/blob/1a04b7311e4a3f53066d968d7dce0b008029881f/src/tests/ftest/util/general_utils.py#L490):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-08-30 23:08 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

FYI: Errors found in lines not modified in the patch:

[src/tests/ftest/util/apricot/apricot/test.py:1330](https://github.com/daos-stack/daos/blob/243495861ff0028e06a01e5f90bbd16d1bbf5e13/src/tests/ftest/util/apricot/apricot/test.py#L1330):
(pylint-arguments-renamed) Parameter 'msg' has been renamed to 'self' in overridden 'TestWithServers.fail' method

[src/tests/ftest/util/apricot/apricot/test.py:1335](https://github.com/daos-stack/daos/blob/243495861ff0028e06a01e5f90bbd16d1bbf5e13/src/tests/ftest/util/apricot/apricot/test.py#L1335):
(pylint-arguments-renamed) Parameter 'msg' has been renamed to 'self' in overridden 'TestWithServers.error' method

[src/tests/ftest/util/general_utils.py:161](https://github.com/daos-stack/daos/blob/243495861ff0028e06a01e5f90bbd16d1bbf5e13/src/tests/ftest/util/general_utils.py#L161):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:266](https://github.com/daos-stack/daos/blob/243495861ff0028e06a01e5f90bbd16d1bbf5e13/src/tests/ftest/util/general_utils.py#L266):
(pylint-unexpected-keyword-arg) Unexpected keyword argument 'allow_output_check' in function call

[src/tests/ftest/util/general_utils.py:203](https://github.com/daos-stack/daos/blob/243495861ff0028e06a01e5f90bbd16d1bbf5e13/src/tests/ftest/util/general_utils.py#L203):
(pylint-inconsistent-return-statements) Either all return statements in a function should return an expression, or none of them should.

[src/tests/ftest/util/general_utils.py:480](https://github.com/daos-stack/daos/blob/243495861ff0028e06a01e5f90bbd16d1bbf5e13/src/tests/ftest/util/general_utils.py#L480):
(pylint-consider-using-dict-items) Consider iterating with .items()

[src/tests/ftest/util/general_utils.py:490](https://github.com/daos-stack/daos/blob/243495861ff0028e06a01e5f90bbd16d1bbf5e13/src/tests/ftest/util/general_utils.py#L490):
(pylint-consider-using-dict-items) Consider iterating with .items()

2022-09-02 15:15 UTC, daosbuild1 reviewed
LGTM.  No errors found by checkpatch.

2022-09-03 10:51 UTC, shimizukko approved these changes

2022-09-07 20:59 UTC, phender approved these changes

2022-09-07 21:01 UTC, merged